Optionally allow user provisioning failures
openedx-unsupported/configuration pull request #3398
Opened 2016-09-28 15:52 UTC by haikuginger

When using the user management playbook in the context of an OpenEdX instance with persistent databases stored on another server, we discovered that we may run into errors when managing users if the user's email address has been changed since the initial provisioning. Since this is expected, we'd like to optionally set a variable while provisioning that determines whether we fail at provisioning if user account creation fails.

In other words, if we have a persistent database that has previously been fully provisioned, then a failure of the management command is likely due to an acceptable reason, and we can safely ignore it.

**Dependencies**: None

**Partner information**: 3rd party-hosted open edX instance

**Testing instructions**:

1. On a devstack, pull this version of configuration.
2. Run the following command:

    `ansible-playbook -i "localhost," manage_edxapp_users_and_groups.yml --extra-vars '{"django_users":[{"username":"staff","email":"fake-staff@example.com"}, {"username":"honor","email":"honor@example.com"}], "django_groups":[], "deployment_settings":"devstack"}' -c local`

3. Observe that the playbook fails (ends with the message: "FATAL: all hosts have already failed -- aborting").

4. Run the following command:

    `ansible-playbook -i "localhost," manage_edxapp_users_and_groups.yml --extra-vars '{"django_users":[{"username":"staff","email":"fake-staff@example.com"}, {"username":"honor","email":"honor@example.com"}], "django_groups":[], "deployment_settings":"devstack", "ignore_user_creation_errors":"yes", "ignore_user_creation_failures":true}' -c local`

5. Observe that there is an "...ignoring" note under the failed play, and that the final report does not show any failures.

**Author notes and concerns**:

1. The previous version of the playbook was statically tied to `settings=aws`. To make testing this change in a devstack feasible, it was necessary to add a variable to change that to have an arbitrary value (e.g., `settings=devstack` or `settings=openstack`).

2. While it would have been nice to simply set a variable in `ignore_errors` on a single play, this does not appear to be possible with the current version of Ansible. As a result, it was necessary to create an additional play with `ignore_errors: yes` and run that play conditionally on the variable passed in. 

**Reviewers**
- [ ] @pomegranited 
- [ ] edX reviewer[s] TBD

2016-09-28 15:52 UTC, edx-webhook commented
Thanks for the pull request, @haikuginger! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

To automatically create an OSPR issue for this pull request, just visit this link: https://openedx-webhooks.herokuapp.com/github/process_pr?number=3398&repo=edx%2Fconfiguration

2016-09-28 15:53 UTC, edx-webhook commented
Thanks for the pull request, @haikuginger! I've created [OSPR-1477](https://openedx.atlassian.net/browse/OSPR-1477) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

2016-09-29 03:14 UTC, pomegranited requested changes
@haikuginger Your change works as described, but I don't like the duplication of logic required to work around the `ignore_errors` variable bug in ansible.

Please see my alternative suggestion.  I'm open to debate on whether it's clarifies and de-risks the behaviour or not.

Also, there's an unnecessary `--extra-vars` variable defined in your PR description; please remove it:

`"ignore_user_creation_failures":true`

2016-09-29 03:14 UTC, pomegranited commented on playbooks/edx-east/manage_edxapp_users_and_groups.yml
> +      when: ignore_user_creation_errors | bool
I really don't like the duplication of logic here..  seems to be asking for trouble down the road.

I found an [alternative way of throwing conditional errors](http://docs.ansible.com/ansible/playbooks_loops.html#using-register-with-a-loop).  Do you think this way is less confusing?

```yaml

    - name: Manage users
      shell: >
        {{ python_path }} {{ manage_path }} lms --settings={{ deployment_settings|default('aws') }}
        manage_user {{ item.username | quote }} {{ item.email | quote }}
        {% if item.get('groups', []) | length %}--groups {{ item.groups | default([]) | map('quote') | join(' ') }}{% endif %}
        {% if item.get('remove') %}--remove{% endif %}
        {% if item.get('superuser') %}--superuser{% endif %}
        {% if item.get('staff') %}--staff{% endif %}
        {% if item.get('unusable_password') %}--unusable-password{% endif %}
        {% if item.get('initial_password_hash') %}--initial-password-hash {{ item.initial_password_hash | quote }}{% endif %}
      register: manage_users_result
      ignore_errors: True
      with_items: django_users

    - name: "Manage users fails on error unless {{ ignore_user_creation_errors }}"
      fail: item
      when:
      - item|failed
      - not ignore_user_creation_errors | bool
      with_items: manage_users_result.results
```

Would merit a nice comment explaining that the `ignore_errors` setting won't take a variable, and which ansible version fixes the issue.

2016-09-29 03:14 UTC, pomegranited commented on playbooks/edx-east/manage_edxapp_users_and_groups.yml
> +        {{ python_path }} {{ manage_path }} lms --settings={{ deployment_settings|default('aws') }}
Please:

* Add `deployment_settings` to the list of `vars` above.
* Reference the [existing `EDXAPP_SETTINGS` variable](https://github.com/edx/configuration/blob/master/playbooks/roles/edxapp/defaults/main.yml#L99), falling back to `aws` as default.
* Remove the default value from each usage in the tasks list.

```yaml
    vars:
      python_path: /edx/bin/python.edxapp
      manage_path: /edx/bin/manage.edxapp
      ignore_user_creation_errors: no
      deployment_settings: "{{ EDXAPP_SETTINGS | default('aws') }}"
...
      shell: >
          {{ python_path }} {{ manage_path }} lms --settings={{ deployment_settings }}
...
```

2016-09-29 03:14 UTC, pomegranited commented on playbooks/edx-east/manage_edxapp_users_and_groups.yml
> +        {{ python_path }} {{ manage_path }} lms --settings={{ deployment_settings|default('aws') }}
See above comment re `deployment_settings`, and remove default value.

2016-10-02 19:25 UTC, haikuginger commented on playbooks/edx-east/manage_edxapp_users_and_groups.yml
> +      when: ignore_user_creation_errors | bool
I like it. Reimplementing that way.

2016-10-02 19:27 UTC, haikuginger commented on playbooks/edx-east/manage_edxapp_users_and_groups.yml
> +        {{ python_path }} {{ manage_path }} lms --settings={{ deployment_settings|default('aws') }}
It's important to note that, rather than a role that's called as part of any standard EdX playbook, so while I'm happy to change to using that variable as opposed to an alternative, I'm not sure it actually increases ease-of-use on its own aside from being more "canonical".

2016-10-02 20:04 UTC, haikuginger commented
@pomegranited, most of those changes have been made. I've confirmed that this is not an issue as of Ansible 2.1.0, but have not investigated further on that front.

2016-10-03 09:54 UTC, pomegranited approved these changes

2016-10-03 09:57 UTC, pomegranited commented
Thanks for making those changes @haikuginger! :+1:

One minor thing left with the PR instructions - "notes and concerns" point #2 needs updating with the new workaround.

- [x] I tested this on my devstack, using the PR instructions.
- [x] I read through the code.
- [x] <strike>I checked for accessibility issues</strike> - accessibility is not affected.
- [x] Includes documentation - explains the bug in ansible it's working around.

2016-10-03 20:32 UTC, gsong commented
@haikuginger Did you already make the changes in the PR instructions per @pomegranited? If so, I'll move this one along the review track.

2016-10-03 21:10 UTC, haikuginger commented
@gsong, yes, this should be ready to go.

2016-10-18 14:16 UTC, gsong commented
@edx/devops Is this something for you to review in one of your sprints?

2016-10-18 18:54 UTC, maxrothman commented
@fredsmith let's try to get the corresponding OSPR ticket into a sprint.

2016-10-27 14:46 UTC, gsong commented
@maxrothman @fredsmith Any updates on <https://openedx.atlassian.net/browse/OSPR-1477>? Let @haikuginger or me know if there's anything that needs to be done.

2016-11-15 18:38 UTC, gsong commented
@edx/devops *bump*

2016-11-15 19:22 UTC, maxrothman commented
Out of curiosity, have you tested a combination of `register` and `failed_when` rather than `ignore_errors` and a separate task?

2016-11-17 03:06 UTC, haikuginger commented
@maxrothman, we discussed that option internally, and came to the conclusion that, because this is running a manage.py command, parsing the message and allowing the failure only for the specific relevant error messages would add unnecessary complexity.

2016-11-17 18:59 UTC, feanil commented
:+1:  looks good to me.  Go ahead an merge if it looks good to @maxrothman

2016-11-17 19:31 UTC, maxrothman commented
I'm 👍 , but I'm surprised you can't do the same `when` check you can't just move the `when` in the second task into a `failed_when` on the first.

2016-11-18 04:49 UTC, haikuginger commented
@maxrothman, I may have misunderstood your intent. I'll double-check that method before merging to be sure.

2016-11-23 15:27 UTC, feanil commented
@haikuginger any reason this hasn't merged yet?

2016-11-23 15:59 UTC, haikuginger commented
@feanil, sorry, it's been a busy week, and I haven't gotten around to doing the investigation into @maxrothman's question. I can squash and merge as-is if you'd like.

2016-11-23 17:02 UTC, feanil commented
@haikuginger up to you.  If you plan on making this better, then by all means take your time.  I just wanted to make sure it was still active.

2016-11-28 22:06 UTC, haikuginger commented
@maxrothman, I took a second look, and your suggestion paid off to the tune of several removed lines of code. I've tested this new version, and it works fine; if you and @feanil want to make another pass, that'd be great.

2016-11-28 22:36 UTC, maxrothman commented
Awesome! 👍

2016-11-29 14:42 UTC, feanil approved these changes
Nice!

2016-11-30 15:43 UTC, haikuginger commented
Squashed from 19a468b.

2016-11-30 15:53 UTC, merged