Adds bootstrap role, which installs python 2.7 using raw ansible
openedx-unsupported/configuration pull request #3606
Opened 2017-01-12 09:04 UTC by pomegranited

This PR adds a `bootstrap` role, which installs `python` using raw ansible commands.  This change is required because ansible currently cannot run on an unmodified xenial image.

The `bootstrap` role is run by `edx_sandbox.yml` and `edx-stateless.yml` as a separate, prefixed playbook, so that the main "Configure instance(s)" playbook can be left unmodified, with `gather_facts: yes'.

**Discussions**: ref: [edx-code post](https://groups.google.com/d/msg/openedx-ops/pIR1JFMxYSA/nDwygEpUDAAJ).

**Merge deadline**: ASAP - We'd like to start using this now to provision instances from OpenCraft IM using the ubuntu xenial cloud images.

**Testing instructions**:

1. Create a VM using an unmodified xenial cloud image, e.g. https://cloud-images.ubuntu.com/xenial/current/
1. Clone this repo and branch, create a virtualenv, and run:

    ```
    make requirements
    cd playbooks
    ansible-playbook -i "instance_ip," -u ubuntu -e @path/to/your/vars.yml edx_sandbox.yml
    ```
1. Ensure that the playbook runs to completion.

To test using an [OpenCraft IM](https://github.com/open-craft/opencraft) devstack:

1. Set `OPENSTACK_SANDBOX_BASE_IMAGE` to point to a xenial cloud image, e.g. `'{"name": "xenial-server-cloudimg-amd64-disk1-unmodified-20161214"}'` is available on OpenCraft's dev OVH instance.
1. Run `make shell`, and these commands:

    ```python
    from instance.factories import instance_factory
    instance = instance_factory(name="xenial-dev", sub_domain="xenial.dev.sandbox",
        configuration_version="jill/xenial-bootstrap",
        configuration_source_repo_url="https://github.com/open-craft/configuration.git",
        edx_platform_commit="open-release/ficus.master",
        edx_platform_repository_url="https://github.com/edx/edx-platform.git",
        openedx_release="open-release/ficus.master"
    )
    instance.spawn_appserver()
    ``` 
1. Check the output to verify that the `bootstrap` role runs, and the "Configure instance(s)" playbook runs at least the first few roles ok.
1. Ok to cancel at this point, and run:

    ```python
    instance.shut_down()`.
    ```

**Author notes and concerns**:

1. We are aware that edX currently run the [ansible-bootstrap script](https://github.com/edx/configuration/blob/master/util/install/ansible-bootstrap.sh) on their new `xenial` instances, which installs `python`, among other things.  This change brings that one critical step into an`edx:configuration` role.

**Reviewers**
- [ ] @bdero 

Configuration Pull Request
---

Make sure that the following steps are done before merging

  - [ ] @devops team member has commented with :+1:
  - [ ] are you adding any new default values that need to be overridden when this goes live?  
    - [ ] Open a ticket (DEVOPS) to make sure that they have been added to secure vars.
    - [ ] Add an entry to the CHANGELOG.

2017-01-12 09:05 UTC, edx-webhook commented
Thanks for the pull request, @pomegranited! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fconfiguration&number=3606"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-01-13 03:30 UTC, bdero commented
:+1:

- [x] I tested this: I launched in OpenedX instance against the xenial image with your branch and Ansible proceeded to execute other plays with tasks requiring the target to have python (non-raw tasks):
```
13/Jan/2017 03:23:59 |     INFO | process=2313  | instance.models.appserver | instance=120 (xenial-dev2),app_server=30 (AppServer 1) | PLAY [Bootstrap instance(s)] ***************************************************
13/Jan/2017 03:23:59 |     INFO | process=2313  | instance.models.appserver | instance=120 (xenial-dev2),app_server=30 (AppServer 1) | 
13/Jan/2017 03:24:09 |     INFO | process=2313  | instance.models.appserver | instance=120 (xenial-dev2),app_server=30 (AppServer 1) | TASK [bootstrap : Update apt-get] **********************************************
13/Jan/2017 03:24:09 |     INFO | process=2313  | instance.models.appserver | instance=120 (xenial-dev2),app_server=30 (AppServer 1) | changed: [............]
13/Jan/2017 03:24:17 |     INFO | process=2313  | instance.models.appserver | instance=120 (xenial-dev2),app_server=30 (AppServer 1) | 
13/Jan/2017 03:24:17 |     INFO | process=2313  | instance.models.appserver | instance=120 (xenial-dev2),app_server=30 (AppServer 1) | TASK [bootstrap : Install packages] ********************************************
13/Jan/2017 03:24:17 |     INFO | process=2313  | instance.models.appserver | instance=120 (xenial-dev2),app_server=30 (AppServer 1) | changed: [............] => (item=python-minimal)
13/Jan/2017 03:24:17 |     INFO | process=2313  | instance.models.appserver | instance=120 (xenial-dev2),app_server=30 (AppServer 1) | 
13/Jan/2017 03:24:17 |     INFO | process=2313  | instance.models.appserver | instance=120 (xenial-dev2),app_server=30 (AppServer 1) | PLAY [Configure instance(s)] ***************************************************
13/Jan/2017 03:24:17 |     INFO | process=2313  | instance.models.appserver | instance=120 (xenial-dev2),app_server=30 (AppServer 1) | 
13/Jan/2017 03:24:20 |     INFO | process=2313  | instance.models.appserver | instance=120 (xenial-dev2),app_server=30 (AppServer 1) | TASK [setup] *******************************************************************
13/Jan/2017 03:24:20 |     INFO | process=2313  | instance.models.appserver | instance=120 (xenial-dev2),app_server=30 (AppServer 1) | ok: [............]
13/Jan/2017 03:24:20 |     INFO | process=2313  | instance.models.appserver | instance=120 (xenial-dev2),app_server=30 (AppServer 1) | 
13/Jan/2017 03:24:22 |     INFO | process=2313  | instance.models.appserver | instance=120 (xenial-dev2),app_server=30 (AppServer 1) | TASK [swapfile : Write swapfile] ***********************************************
13/Jan/2017 03:24:22 |     INFO | process=2313  | instance.models.appserver | instance=120 (xenial-dev2),app_server=30 (AppServer 1) | changed: [............]

```
- [x] I read through the code
- [ ] ~~I checked for accessibility issues~~ N/A.
- [ ] ~~Includes documentation~~ Not necessary.

2017-01-13 03:47 UTC, edx-webhook commented
Thanks for the pull request, @pomegranited! I've created [OSPR-1647](https://openedx.atlassian.net/browse/OSPR-1647) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

2017-01-17 13:54 UTC, feanil commented
@edx/devops second opinion on this?  I think the approach is fine but I'd prefer to not call this role `bootstrap` unless it did the same things as bootstrap.sh.  This is mostly to avoid confusion.  A suggestion would be to call it the `python` role?  I'm open to other ideas as well.

2017-01-17 15:21 UTC, maxrothman commented
Why not simply execute `ansible-bootstrap.sh` using the [script module](http://docs.ansible.com/ansible/script_module.html)? Like the raw module, it doesn't require Python on the remote server.

2017-01-17 22:49 UTC, pomegranited commented
@feanil I'd be happy to rename the role to `python`.

@maxrothman We found that all we needed to get `edx_sandbox.yml` installed on an unmodified `xenial` image was python2.7, and we didn't need the rest of the things installed by the bootstrap script.

Specifically, I didn't encounter any issues with pip in 16.04, which [ansible-bootstrap.sh works around](https://github.com/edx/configuration/blob/master/util/install/ansible-bootstrap.sh#L128-L132), but maybe I just didn't encounter that use case?

And the other libraries, (e.g. [python-yaml build-essential git-core libmysqlclient-dev libffi-dev libssl-dev](https://github.com/edx/configuration/blob/master/util/install/ansible-bootstrap.sh#L123)) are installed as needed by other roles (e.g. [`edx_ansible`](https://github.com/edx/configuration/blob/b10da53da28358ee82f56307ec30eaf9c329e292/playbooks/roles/edx_ansible/defaults/main.yml#L24-L34), [`edxapp`](https://github.com/edx/configuration/blob/1e59c4a668e2f5899f95fcd637a6b810fbd05565/playbooks/roles/edxapp/defaults/main.yml#L1181), [`rbenv`](https://github.com/edx/configuration/blob/b10da53da28358ee82f56307ec30eaf9c329e292/playbooks/roles/rbenv/defaults/main.yml#L17)).

2017-01-18 15:17 UTC, nedbat commented
@pomegranited are you saying that ansible-bootstrap.sh does more than it needs to? It seems like with this change we'd have two different ways to accomplish the same thing.  Maybe we can converge on just one?

2017-01-19 19:53 UTC, nedbat commented
@pomegranited I think I was confusing the local machine (running Ansible) with the remote machine (being deployed).

2017-01-20 06:25 UTC, pomegranited commented
@nedbat Yep, I'm saying ansible-bootstrap.sh does more than we need it to, but our use case is very specific: edxapp servers, provisioned using edx_sandbox.yml.  

Not sure what your other comment means, though?  https://github.com/edx/configuration/pull/3606#issuecomment-273880293

2017-01-20 20:00 UTC, nedbat commented
@pomegranited sorry, my "two ways" comment was that it seemed like we had two different ways to get Python 2.7 installed.  But I was confusing the local (ansible-running) machine with the remote (being-configured) machine.  ansible-bootstrap.sh installs Python 2.7 for the local machine.  This change will ensure it is installed on the remote machine.  (unless I'm still missing a subtlety!)

2017-01-21 00:19 UTC, pomegranited commented
@nedbat Yep that's right.

2017-01-21 02:44 UTC, pomegranited commented
@feanil 5345863 renames the role to `python`, as requested.

@maxrothman What do you think?  Is it ok to be using this role instead of running ansible-bootstrap.sh ?

2017-01-24 19:33 UTC, maxrothman commented
Just to clarify, is this role intended to install python on the host on which `ansible-playbook ...` is run, or on the host that ansible sshes to?

2017-01-25 00:01 UTC, pomegranited commented
@maxrothman On the remote host, the one that ansible sshes to. 😄

2017-01-25 18:38 UTC, maxrothman commented
Now I'm confused about @nedbat's comment. Does this not do the same thing as `ansible-bootstrap.sh`?

2017-01-25 22:14 UTC, gsong requested changes

2017-01-25 22:14 UTC, gsong commented on playbooks/roles/python/tasks/main.yml
> +  raw: apt-get update -qq
Rather than using `raw`, can this be accomplished using `apt`?

2017-01-25 22:14 UTC, gsong commented on playbooks/edx_sandbox.yml
> +- name: Bootstrap instance(s)
Let’s remove this from the `edx_sandbox` playbook. One option would be to create another playbook for openstack install, which plays the `python` role and includes `edx_sandbox` playbook.

2017-01-25 22:14 UTC, gsong commented on playbooks/edx-stateless.yml
> +- name: Bootstrap instance(s)
@feanil I’m not sure how `edx-stateless` playbook is used. Is this appropriate here? Or should we potentially create an open-stack specific playbook which then includes the new role and the `edx-stateless` playbook?

2017-01-25 23:05 UTC, pomegranited commented
@maxrothman This change does only one of the things that ansible-bootstrap does: installs python2.7.  Ansible-bootstrap does far more than we need (please see [previous comment](https://github.com/edx/configuration/pull/3606#issuecomment-273325821)).

2017-01-25 23:06 UTC, pomegranited commented on playbooks/roles/python/tasks/main.yml
> +  raw: apt-get update -qq
Ansible requires that the target host have python2.7 installed before it can do anything with its standard modules, like `apt`.

So we have to run this step as a raw task

2017-01-25 23:07 UTC, pomegranited commented on playbooks/edx_sandbox.yml
> +- name: Bootstrap instance(s)
This isn't just openstack specific.  If you launch an AWS instance using an ubuntu xenial cloud image, you'll still need to install python2.7 before you can run any ansible commands on the new instance.

2017-01-25 23:23 UTC, maxrothman commented on playbooks/edx-stateless.yml
> +- name: Bootstrap instance(s)
`edx-stateless` is like a sandbox except with all of the stateful services (read: databases) removed. It's designed for people to take a first step in scaling out a deployment.

2017-01-26 14:37 UTC, gsong commented on playbooks/edx-stateless.yml
> +- name: Bootstrap instance(s)
@maxrothman Is this a playbook that we use within edX or it's more for the community?

2017-01-26 14:53 UTC, maxrothman commented on playbooks/edx-stateless.yml
> +- name: Bootstrap instance(s)
It's for the community.

2017-01-26 15:31 UTC, gsong commented
I did a quick diff between `python-minimal` and what we install with `ansible-bootstrap`. I think this overlap for now is fine. I'll also double check by running our own native install to make sure

2017-01-26 15:32 UTC, edx-webhook commented
Hello @pomegranited: We are unable to continue with review of your submission at this time. Please see the associated JIRA ticket for more explanation.

2017-01-26 15:46 UTC, gsong reviewed
I've tested successfully with `edx_sandbox` playbook.

2017-01-26 15:46 UTC, gsong approved these changes

2017-01-26 16:16 UTC, feanil approved these changes

2017-01-26 18:23 UTC, gsong commented
@pomegranited Feel free to merge any time you're ready. We'll take care of make sure it's on the ficus branch as well.

2017-01-26 23:11 UTC, pomegranited commented
Thanks so much @maxrothman , @feanil  @gsong !  This change makes our lives much easier.  Merging now.

2017-01-26 23:31 UTC, merged