Update credentials playbook
openedx-unsupported/configuration pull request #3608
Opened 2017-01-12 20:23 UTC by MatthewPiatetsky

@edx/ecommerce @clintonb 
Relevant DEVOPS Ticket: https://openedx.atlassian.net/browse/DEVOPS-5289
Relevant Credentials PR: https://github.com/edx/credentials/pull/147
Configuration Pull Request
---

Make sure that the following steps are done before merging

  - [ ] @devops team member has commented with :+1:
  - [ ] are you adding any new default values that need to be overridden when this goes live?  
    - [ ] Open a ticket (DEVOPS) to make sure that they have been added to secure vars.
    - [ ] Add an entry to the CHANGELOG.

2017-01-12 20:25 UTC, clintonb approved these changes

2017-01-12 20:26 UTC, clintonb commented on CHANGELOG.md
> +  - Added `EXTRA_APPS` to enable edX specific data in credentials
...to enable the inclusion of additional Django apps in the Credentials Service.

2017-01-12 20:52 UTC, rlucioni approved these changes

2017-01-17 14:40 UTC, feanil requested changes
Other than changelog, this looks good.

2017-01-17 14:40 UTC, feanil commented on CHANGELOG.md
> +
New changelog entries should go at the top.

2017-01-17 14:45 UTC, MatthewPiatetsky commented
@feanil 
did I fix it?  
Assuming I also need to wait for the devops ticket to be complete for this to be merged?

2017-01-17 15:12 UTC, feanil approved these changes

2017-01-17 15:13 UTC, feanil commented
@MatthewPiatetsky Since this has a default value(empty list) you don't need to wait on the secure config before merging this.  Though you will need to wait on that ticket before deploying this code to our production system.

2017-01-17 20:04 UTC, feanil commented on CHANGELOG.md
> +  - Added `EXTRA_APPS` to enable the inclusion of additional Django apps in the Credentials Service.
This should be `CREDENTIALS_EXTRA_APPS` which is the top level var that was added.

2017-01-19 16:34 UTC, merged