Don't enrol the staff user in the demo course if the staff user wasn't created.
openedx-unsupported/configuration pull request #3639
Opened 2017-01-27 13:43 UTC by smarnach

When `COMMON_CREATE_STAFF_USER` is set to false, the user won't be created, but the demo role will try to enrol the user anyway, resulting in an error.  This fix makes sure the staff user is only enroled if it was created.

This fix should also be cherry-picked on the Fixus release branch.

Configuration Pull Request
---

Make sure that the following steps are done before merging

  - [ ] @devops team member has commented with :+1:
  - [ ] are you adding any new default values that need to be overridden when this goes live?  
    - [ ] Open a ticket (DEVOPS) to make sure that they have been added to secure vars.
    - [ ] Add an entry to the CHANGELOG.

2017-01-27 13:43 UTC, edx-webhook commented
Thanks for the pull request, @smarnach! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=3639&repo=edx%2Fconfiguration"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-01-27 14:51 UTC, e0d commented on playbooks/roles/demo/tasks/deploy.yml
> +    - DEMO_CREATE_STAFF_USER or item.email != 'staff.example.com'
Do we need both DEMO_CREATE_STAFF_USER and COMMON_CREATE_STAFF_USER?

2017-01-27 15:14 UTC, smarnach commented on playbooks/roles/demo/tasks/deploy.yml
> +    - DEMO_CREATE_STAFF_USER or item.email != 'staff.example.com'
@e0d Sorry, `COMMON_CREATE_STAFF_USER` does not exist.  It was just a typo in the PR description.

2017-01-30 04:39 UTC, pomegranited requested changes

2017-01-30 04:39 UTC, pomegranited commented on playbooks/roles/demo/tasks/deploy.yml
> +    - DEMO_CREATE_STAFF_USER or item.email != 'staff.example.com'
Typo: you've got `staff.example.com`, but should be `staff@example.com`.

2017-01-30 04:39 UTC, pomegranited commented on playbooks/roles/demo/tasks/deploy.yml
> +    - DEMO_CREATE_STAFF_USER or item.email != 'staff.example.com'
I've never liked that `staff@example.com` is hard-coded into this playbook.  Can we have staff list like `demo_test_users`, e.g. `demo_staff_users` ?

I'm open to discussion whether this is out of scope for this change, but I've suggested it since we're adding a third occurrence of the string.

2017-01-30 19:45 UTC, pomegranited approved these changes
:+1:

- [x] I tested this by deploying a new edxapp server with `DEMO_CREATE_STAFF_USER: false`, and verifying that the staff user is not created, but the other default users are.
- [x] I read through the code
- [x] <strike>I checked for accessibility issues</strike>
- [x] <strike>Includes documentation</strike> - not required

2017-02-01 20:17 UTC, feanil commented
@smarnach perhaps the right way forward is to just have one list of demo users? This is getting quite messy.

2017-02-01 20:38 UTC, smarnach commented
@feanil Well, the code already was a bit messy.  I tried to clean it up while keeping backwards-compatibility.  If we use just a single list of users, the only way to achieve what `DEMO_CREATE_STAFF_USER: false` currently does is to copy the whole list of remaining users from the defaults file.  Another change in behaviour compared to the current situation is that the staff user would also get enrolled in the test courses, while currently only the `demo_test_users` get enrolled.  If you are fine with these backwards-incompatible changes, I'm happy to make the required changes.

2017-02-06 11:24 UTC, smarnach commented
@feanil Since this fixes a bug in Ficus, it would be nice if we could get this into the release.  I'm happy to change it in the way you requested if you are fine with the implications.

@nedbat Once this is merged, it would be great if this could be cherry-picked on the Ficus branch.

2017-02-06 16:36 UTC, feanil commented
I'm fine with leaving it as is, given backwards compatibility.  However, what was the reason for removing the course modes associated with the users?

2017-02-06 16:40 UTC, smarnach commented
@feanil The course modes aren't used anymore since [this commit](https://github.com/open-craft/configuration/commit/d238da6304c192924442e22cff23c6f8b15b75ed), so I didn't see a point in keeping them.  The `enroll_user_in_course` managment command now used to enroll users does not support to choose a mode.  It always enrols users in the default mode.

2017-02-06 19:13 UTC, feanil commented
Then I wonder if we should change the user-ids and e-mails as well.  Otherwise, people testing might make an assumption that the user is a certain kind of user.  We should have done it when it was no-longer relevant but we can do it now so it's clear in the future.

2017-02-07 18:14 UTC, smarnach commented
@feanil Renaming the users might make sense given that the current names are misleading.  However, these user accounts are documented in many places (e.g. [here](https://github.com/edx/edx-platform/wiki/Frequently-Asked-Questions#which-are-default-accounts-on-edx) and [here](https://github.com/edx/edx-documentation/blob/master/en_us/install_operations/source/installation/installation_options.rst#default-accounts)), and I suspect that there could be some automated tests that depend on the current names, so we might create more confusion than we clear up.

An alternative to changing the names would be to reintroduce a way of enrolling users in a specific course mode via the `enroll_user_in_course` management command.  I don't know how useful that would actually be in practice.

Our main goal with this PR was to fix a bug in the Ficus release.  Since we are already very close to the release, I'd like to keep the changes as small and as backwards-compatible as possible, so my preferred option would be to merge this PR as it is.

2017-02-08 11:23 UTC, edx-webhook commented
Thanks for the pull request, @smarnach! I've created [OSPR-1666](https://openedx.atlassian.net/browse/OSPR-1666) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

2017-02-08 15:32 UTC, feanil approved these changes

2017-02-08 15:35 UTC, feanil commented
@smarnach  makes sense, thanks for finding this debt, I'll put something on our backlog to clean it up. Hopefully before the next named release.

2017-02-08 19:28 UTC, merged

2017-02-08 19:31 UTC, smarnach commented
Thanks @feanil!

@nedbat Could you please consider cherry-picking this on the Ficus release branch?  It's a small bug fix for a bug only occurring when `DEMO_CREATE_STAFF_USER` is set to `False`, which probably very few people do.

2017-02-10 17:42 UTC, nedbat commented
I've cherry-picked this to Ficus.

2017-02-10 18:12 UTC, smarnach commented
Thanks, @nedbat!