Mroytman/update dockerfile
openedx-unsupported/configuration pull request #3690
Opened 2017-02-10 14:32 UTC by MichaelRoytman

Configuration Pull Request
---

Make sure that the following steps are done before merging

  - [ ] A devops team member has commented with :+1:
  - [ ] are you adding any new default values that need to be overridden when this goes live?
    - [ ] Open a ticket (DEVOPS) to make sure that they have been added to secure vars.
    - [ ] Add an entry to the CHANGELOG.

2017-02-10 14:33 UTC, MichaelRoytman commented on playbooks/roles/jenkins_master/tasks/main.yml
> +    - install"base
fix typo; install:base

2017-02-10 14:34 UTC, MichaelRoytman commented on playbooks/roles/jenkins_master/tasks/main.yml
>  # https://issues.jenkins-ci.org/browse/JENKINS-20407
tag?

2017-02-10 14:34 UTC, MichaelRoytman commented on playbooks/roles/jenkins_master/tasks/main.yml
>    lineinfile:
additional tags?

2017-02-10 18:07 UTC, fredsmith commented on playbooks/roles/jenkins_master/tasks/main.yml
>  # https://issues.jenkins-ci.org/browse/JENKINS-20407
install:system-requirements

2017-02-10 18:08 UTC, fredsmith commented on playbooks/roles/jenkins_master/tasks/main.yml
>    lineinfile:
install:app-configuration

2017-02-10 18:10 UTC, MichaelRoytman commented on playbooks/roles/jenkins_master/tasks/main.yml
>  - name: install Jenkins package
install:app-requirements

2017-02-14 21:59 UTC, feanil approved these changes
Wait to make sure @estute doesn't have issues but then I think this is good to merge.

2017-02-14 21:59 UTC, feanil commented on util/jenkins/jenkins.sh
> +#: "${JENKINS_HOME:="/var/jenkins_home"}"
Remove the commented code and provide a link to the location you lifted the rest of this from.

2017-02-14 21:59 UTC, feanil commented on playbooks/roles/jenkins_master/tasks/main.yml
> +- name: restart Jenkinks
@estute FYI, this removes this PR removes the jenkins start/restart handlers and opts to just restart jenkins everytime.  The reason is that handlers don't respect tags.  This means you can't build a jenkins docker container because it tries to start the service using systemd which is not running on the container.

2017-02-15 15:39 UTC, feanil commented on util/jenkins/jenkins.sh
> +Jenkins shell script lifted from https://github.com/jenkinsci/docker/blob/fd794015787ba07d84a7c8d4c625652e648408c5/jenkins.sh.
Don't forget to add a `#` at the beginning to make this a comment.

2017-02-15 15:41 UTC, MichaelRoytman commented
@estute Any concerns regarding these changes?

2017-02-17 21:21 UTC, jibsheet requested changes
Few small changes and then we can rebase/squash/remove my commit and merge.

2017-02-17 21:21 UTC, jibsheet commented on playbooks/roles/tools_jenkins/meta/main.yml
> +    jenkins_custom_plugins: []
Does this error because it's not defined, or are you just being complete?  (I haven't noticed the error)

2017-02-17 21:21 UTC, jibsheet commented on .travis.yml
> -  - MAKE_TARGET=test.syntax
We should rebase out my commit at the end - it's up as a PR at https://github.com/edx/configuration/pull/3707

2017-02-17 21:21 UTC, jibsheet commented on util/jenkins/jenkins.sh
> +#! /bin/bash -e
I believe we stopped using this, right?  If so, we can remove the file (and the .dockerignore line)

2017-02-21 18:11 UTC, MichaelRoytman commented on playbooks/roles/tools_jenkins/meta/main.yml
> +    jenkins_custom_plugins: []
It does cause an error when running the "TASK [jenkins_master : Compile custom plugins]" task. The plugins from jenkins_master were buggy, and @feanil suggested that we don't want to debug plugins that don't seem relevant.

Full text of error below:

`        "[INFO] Compiling 9 source files to /tmp/github-sqs-plugin/target/classes", 
        "[INFO] ------------------------------------------------------------------------", 
        "[INFO] BUILD FAILURE", 
        "[INFO] ------------------------------------------------------------------------", 
        "[INFO] Total time: 5:01.461s", 
        "[INFO] Finished at: Fri Feb 17 21:44:56 UTC 2017", 
        "[INFO] Final Memory: 18M/54M", 
        "[INFO] ------------------------------------------------------------------------", 
        "[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5:compile (default-compile) on project github-sqs-plugin: Fatal error compiling: tools.jar not found: /usr/lib/jvm/java-7-openjdk-amd64/jre/../lib/tools.jar -> [Help 1]", 
        "[ERROR] ", 
        "[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.", 
        "[ERROR] Re-run Maven using the -X switch to enable full debug logging.", 
        "[ERROR] ", 
        "[ERROR] For more information about the errors and possible solutions, please read the following articles:", 
        "[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException"
    ], 
    "warnings": []
}
	to retry, use: --limit @/edx/app/edx_ansible/edx_ansible/docker/plays/jenkins_tools.retry`

2017-02-21 18:51 UTC, MichaelRoytman commented on .travis.yml
> -  - MAKE_TARGET=test.syntax
Poof. It's gone.

2017-02-21 18:52 UTC, michaelroytman commented on util/jenkins/jenkins.sh
> +#! /bin/bash -e
All set.

2017-02-21 19:03 UTC, jibsheet approved these changes

2017-02-21 19:04 UTC, jibsheet commented
Let's squash and then we can merge (all the typo/fixup commits should disappear).  Let one of us know if you need interactive rebase help.

2017-02-21 20:45 UTC, jibsheet commented
ship it when CI passes

2017-02-21 22:04 UTC, merged