Add ES migration scripts
openedx-unsupported/configuration pull request #3700
Opened 2017-02-15 20:32 UTC by maxrothman

Configuration Pull Request
---

Make sure that the following steps are done before merging

  - [ ] A devops team member has commented with :+1:
  - [ ] are you adding any new default values that need to be overridden when this goes live?
    - [ ] Open a ticket (DEVOPS) to make sure that they have been added to secure vars.
    - [ ] Add an entry to the CHANGELOG.

2017-02-16 18:43 UTC, robrap commented on util/elasticsearch/verify-index-copy.py
> +Compare two Elasticsearch indices
Should this compare mappings as well?

2017-02-16 18:44 UTC, robrap commented on util/elasticsearch/incremental-reindex.sh
> +# Thin wrapper around rake search:catchup.
Maybe mentioned that this is specific to cs_comments_service.

2017-02-16 19:02 UTC, robrap requested changes

2017-02-16 19:02 UTC, robrap commented on util/elasticsearch/incremental-reindex.sh
> +#   ./incremental-reindex.sh content -1hour
How does `-1hour` work?  This gets translated into minutes?

2017-02-16 19:02 UTC, robrap commented on util/elasticsearch/incremental-reindex.sh
> +#   SLEEP_TIME  Number of seconds to sleep between re-indexing
Just a note that the WINDOW doesn't account for the SLEEP_TIME.  If you had it sleep for an hour with a window of 30 minutes, you'd miss documents.  Maybe add a comment, or add a dummy check that `SLEEP_TIME < WINDOW * 60`.

2017-02-16 19:02 UTC, robrap commented on util/elasticsearch/verify-index-copy.py
> +Compare two Elasticsearch indices
FYI: I'm not reviewing this because I think it is under development.  Let me know when it is ready.

2017-02-16 19:02 UTC, robrap commented on util/elasticsearch/incremental-reindex.sh
> +#!/usr/bin/env bash
Do we need an incremental script using logstash as well for teams?  Maybe that is part of a later story?

2017-02-16 19:16 UTC, maxrothman commented on util/elasticsearch/incremental-reindex.sh
> +#!/usr/bin/env bash
I have a strong hunch that we we can move the entire teams and notes indices in a small enough amount of time that we can do it during downtime (i.e. <5m), so such a script would not be necessary.

2017-02-16 21:10 UTC, robrap commented on util/elasticsearch/incremental-reindex.sh
> +#!/usr/bin/env bash
I'm not clear on what "during downtime" means?  But, what I think you are saying is that we can copy everything both before and after we are running just the updated instances.  Is that what you are saying?

2017-02-16 22:17 UTC, maxrothman commented on util/elasticsearch/incremental-reindex.sh
> +#!/usr/bin/env bash
My plan for those apps is the following:
* Remove instances from the loadbalancer
* move the index to the new cluster
* Add the instances to the loadbalancer

Since the index is moved completely during downtime, there's no need for a catchup script.

2017-02-16 22:22 UTC, robrap commented on util/elasticsearch/incremental-reindex.sh
> +#!/usr/bin/env bash
Do you mean search downtime or app downtime?  Are you saying we will have LMS downtime for this migration? I didn't think we would have downtime.

2017-02-16 22:23 UTC, maxrothman commented on util/elasticsearch/incremental-reindex.sh
> +#!/usr/bin/env bash
I was under the impression we could get downtime if we needed it. We could also just do search downtime if that's possible. As long as nothing can write to the index.

2017-02-23 14:51 UTC, feanil commented
I thought these scripts were going to go into the forums repo here(https://github.com/edx/cs_comments_service/tree/master/scripts/es) replacing the old stream2es scripts.

2017-02-23 16:05 UTC, maxrothman commented
That was the original plan, but since `copy-index.sh` will be used for all 3 apps and not just forums, it seemed to make more sense to put them in config in the same way we did for the mongo migration.

2017-02-23 16:07 UTC, feanil commented
Don't forget to PR a removal of the files in forums and to add a readme there to point to these scripts when they are finalized.

2017-02-23 16:25 UTC, maxrothman commented
Yep, already have the PR, waiting to merge it.

On Thu, Feb 23, 2017 at 11:07 AM, Feanil Patel <notifications@github.com>
wrote:

> Don't forget to PR a removal of the files in forums and to add a readme
> there to point to these scripts when they are finalized.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/edx/configuration/pull/3700#issuecomment-282036661>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ACfH7nCpPlb71SJI2rut3pR1Phr13Usjks5rfa63gaJpZM4MCNi6>
> .
>

2017-02-23 20:01 UTC, dianakhuang commented
@maxrothman I added a first round of the script. Haven't had a chance to test it on something like load-test yet, but I figured I'd let you take a look at it to make sure it looks the way you want.

2017-02-24 15:56 UTC, maxrothman reviewed
It seems like there's some confusion about the requirements. I'm looking the script to do a full scan OR a random check, configurable via an option, not one then the other.

It'd also be good to print the IDs and bodies of non-matching documents, rather than just the total.

2017-02-24 15:56 UTC, maxrothman commented on util/elasticsearch/verify-index-copy.py
> +def grouper(iterable, n, fillvalue=None):
fillvalue does not appear to be used.

2017-02-24 15:56 UTC, maxrothman commented on util/elasticsearch/verify-index-copy.py
> +        '-cp', '--check-percentage', dest='check_percentage', type=float, default=.1,
Nit: single-dash options should only be one letter long

2017-02-24 15:56 UTC, maxrothman commented on util/elasticsearch/verify-index-copy.py
> +        help='Percentage of matching docs between old and new indices req. for an OK (default: .9)'
FWIW we're not planning on using this option. We're just going to run at the error rate in the log.

2017-02-24 15:56 UTC, maxrothman commented on util/elasticsearch/verify-index-copy.py
> +            matching += 1 if elt['found'] else 0
It looks like this function is just checking whether the id is found, but doesn't compare the content of the documents.

2017-02-24 15:56 UTC, maxrothman commented on util/elasticsearch/verify-index-copy.py
> +        help='Number of documents to scan through in simple scan. (default: 100000)'
Is there a particular reason for this option? I don't really understand the use case

2017-02-24 15:56 UTC, maxrothman commented on util/elasticsearch/verify-index-copy.py
> +    ratio = float(matching) / current_checked
Nit: you can do the cast to float in the argument definition

2017-02-24 15:58 UTC, dianakhuang commented on util/elasticsearch/verify-index-copy.py
> +        help='Number of documents to scan through in simple scan. (default: 100000)'
If we're going to scan every document, why do we even need to do the random check?

2017-02-24 16:01 UTC, maxrothman commented on util/elasticsearch/verify-index-copy.py
> +        help='Number of documents to scan through in simple scan. (default: 100000)'
The random check trades confidence for speed. We'll run the random check before making the cluster live, then do the slow, full scan afterwards while the cluster is active.

TL/DR: we want to gain some confidence before go-live and more confidence later asynchronously.

2017-02-24 16:51 UTC, dianakhuang commented
@maxrothman I believe I have addressed your comments, so this should be ready for testing.

2017-02-24 18:31 UTC, robrap requested changes

2017-02-24 18:31 UTC, robrap commented on util/elasticsearch/verify-index-copy.py
> +        help='Percentage of randomly found docs to check between old and new indices (default: .1)'
I was imagining that we would need an argument for a timestamp and only compare documents updated before that timestamp.  @maxrothman: I think the detailed migration plan for forums would help clarify these requirements.

2017-02-24 18:31 UTC, robrap commented on util/elasticsearch/verify-index-copy.py
> +     In order to match the two indeces without having to deal with ordering issues,
typo: indeces

2017-02-24 18:31 UTC, robrap commented on util/elasticsearch/verify-index-copy.py
> +     we pull a set of dcouments from the old ES index, and then try to find matching
typo: dcouments

2017-02-24 18:31 UTC, robrap commented on util/elasticsearch/verify-index-copy.py
> +    search_result = es.mget(index=index, body=body)
Out of curiosity, are there parts of the document we are not comparing?  If there is, can you make that explicit in the comment so it is either documented or we can choose to compare.

2017-02-24 18:31 UTC, robrap commented on util/elasticsearch/verify-index-copy.py
> +Verifies that an index was correctly copied from one ES host to another.
As discussed, should compare mappings.

2017-02-24 18:44 UTC, maxrothman commented on util/elasticsearch/verify-index-copy.py
> +            )
Nit: prefix the logging lines with something easy to search, like I did on https://github.com/edx/configuration/pull/3700/files#diff-7a0dc9e15666855efef7dce951d51334R198

2017-02-24 18:46 UTC, dianakhuang commented on util/elasticsearch/verify-index-copy.py
> +    search_result = es.mget(index=index, body=body)
Yup, there is a bunch of metadata that we're not comparing here. I'll add a comment.

2017-02-24 18:46 UTC, maxrothman commented on util/elasticsearch/verify-index-copy.py
> +        help='Percentage of randomly found docs to check between old and new indices (default: .1)'
Unfortunately this is a bit of a chicken-and-egg thing: I can't finish making a detailed migration plan until I've iterated and tested one using this script. I also suspect this script will be iterated on as the plan development continues.

What would be the goal of the timestamp filtering?

2017-02-24 19:24 UTC, robrap commented on util/elasticsearch/verify-index-copy.py
> +        help='Percentage of randomly found docs to check between old and new indices (default: .1)'
I guess I don't see it that way, but we all work differently.  I would write my initial detailed plan and review it and then test and iterate.

A rough detailed plan would be:
- Create new ES cluster.
- Create new cs_comments_service instance (AMI earlier).
- Run bin/rake search:initialize on new ES cluster to create the alias and mappings.
- Run logstash copy from old ES to new ES at time=T.
- Validate documents using @dianakhuang script, comparing old ES to new ES for documents updated before T (or T-5 minutes).
- Make one post manually (for later validation).
- Switch auto-scaling group to new instances.
- Wait for draining of old instances.
- Run catchup from T - 1 hour.
- Double check that new manual post is searchable after catchup.

You can see in step above how I would use the timestamp, to avoid comparing to changes that continue after the copy.

2017-02-24 19:35 UTC, maxrothman commented on util/elasticsearch/verify-index-copy.py
> +        help='Percentage of randomly found docs to check between old and new indices (default: .1)'
Here was broadly what I was thinking:
* Create new ES cluster.
* Create new cs_comments_service instance (AMI earlier).
* Run bin/rake search:initialize on new ES cluster to create the alias and mappings.
* Run logstash copy from old ES to new ES at time=T.
* Run catchup for T - however long it took to run the copy
* Validate randomly sampled documents using script from old ES to new ES
* Make one post manually (for later validation).
* Switch auto-scaling group to new instances.
* Wait for draining of old instances.
* Run catchup from T - however long it's been since the last catchup.
* Double check that new manual post is searchable after catchup.

Since the time it takes to run the first catchup will be relatively small, I'm not worried about the few documents added in that amount of time, thus I don't think timestamp search is necessary. I'm not expecting 0 errors from the script, just close to 0.

2017-02-24 20:03 UTC, maxrothman commented on util/elasticsearch/verify-index-copy.py
> +def check_mappings(old_mapping, new_mapping):
FWIW Difflib might make this much more simple

2017-02-24 20:05 UTC, maxrothman commented on util/elasticsearch/verify-index-copy.py
> +    for old_key, new_key in zip(old_mapping.keys(), new_mapping.keys()):
Doesn't this mean you'll get the keys in arbitrary order, meaning there's no guarantee you'll get matching keys together?

2017-02-27 14:18 UTC, dianakhuang commented on util/elasticsearch/verify-index-copy.py
> +    for old_key, new_key in zip(old_mapping.keys(), new_mapping.keys()):
Hmm, according to @robrap the order is important for these keys, and what we get out of the elasticsearch library has already been converted into a dictionary. I'll talk it over and see what our options are.

2017-02-27 14:54 UTC, dianakhuang commented on util/elasticsearch/verify-index-copy.py
> +def check_mappings(old_mapping, new_mapping):
Difflib seems to be more about comparing linear sequences rather than weird nested structures like this. We're not doing a straight comparison on everything, because newer ES has more fields in the mappings than the old.

2017-02-28 15:59 UTC, robrap commented on util/elasticsearch/verify-index-copy.py
> +        help='Percentage of randomly found docs to check between old and new indices (default: .1)'
@maxrothman 
1. If you have a couple of problems, how do you know whether or not you can ignore them?  Can you see the timestamp of the document, and will you know if it will be fixed during the reindex?
2. I thought you had a later step of doing a full validation?  Doesn't that have to end at a specific time, or does the script just make sure that all docs in the old are in the new?  @dianakhuang?

2017-02-28 16:03 UTC, robrap commented on util/elasticsearch/verify-index-copy.py
> +    search_result = es.mget(index=index, body=body)
@dianakhuang: I don't see the comment.  Also, as @maxrothman mentioned the other day, we need to determine if we can really ignore this other metadata?  
Or, did you add but just not update the comment and I am missing the code?

2017-02-28 16:26 UTC, dianakhuang commented on util/elasticsearch/verify-index-copy.py
> +    search_result = es.mget(index=index, body=body)
I believe the convo with @maxrothman was specifically about mappings. For this, I believe we agreed that checking the body and the id was sufficient. I added the comment to the docstring here: https://github.com/edx/configuration/pull/3700/files#diff-7a0dc9e15666855efef7dce951d51334R66

2017-03-01 15:39 UTC, maxrothman commented on util/elasticsearch/verify-index-copy.py
> +        help='Percentage of randomly found docs to check between old and new indices (default: .1)'
1. Conflicting documents will have to be hand-inspected. Anything the script can do to make that easier (e.g. deepdiff) would be appreciated.
2. I forgot that in my plan above. After the whole thing is done, I will run the full validation. It'll scan every document in the old cluster and make sure they're in new (and output conflicts when there are any)

2017-03-01 17:11 UTC, robrap approved these changes

2017-08-24 17:19 UTC, robrap commented
@feanil @MichaelRoytman: What should happen to this PR?  Should it just be closed?  Does anything need to be merged or fixed anywhere?

2017-08-24 17:48 UTC, MichaelRoytman commented
@robrap I'm not sure which of (if any) of these scripts would be useful moving forward, since I was not directly involved in resolving the issues with the elasticsearch indexes during the last push that you and @feanil were involved in with notes and edx-search. It looks like from the runbook updates Feanil made that none of these resources are necessary for a re-index. Is that true for the forums as well? Or does it remain as complicated as described in the original runbook, because those scripts are used there.

2017-08-24 18:06 UTC, feanil commented
The forums is as complicated as described here, so we should merge this since that part of the run book mentions this.

2017-08-24 18:08 UTC, feanil commented
I've squased this, I'll merge once it's passing tests.

2017-08-24 18:16 UTC, merged