rabbitmq memory alerting
openedx-unsupported/configuration pull request #3710
Opened 2017-02-23 14:22 UTC by nadeemshahzad

2017-02-23 14:33 UTC, feanil commented on playbooks/roles/rabbitmq/templates/edx/app/rabbitmq/log-rabbitmq-memory.py.j2
> +    process_mem=run_cmd("/usr/sbin/rabbitmqctl status | grep total | awk -F',|}' 'NR==1{print $2}'")
This python script seems like overkill, why not just make it a shell script that runs this command and appends the output to the relevant file along with a timestamp?

2017-02-23 14:34 UTC, feanil commented
You'll also need to setup a log-rotate rule for the new output file that you are generating.

2017-02-27 20:01 UTC, feanil commented
This generally looks good, but you're still missing a log rotation rule for the new file.

2017-02-27 21:49 UTC, nadeemshahzad commented
@feanil Log file is going to "rabbitmq_log_dir" on which log rotation is already working.

2017-02-28 14:16 UTC, feanil requested changes
@nadeemshahzad good point, if you just put your file under the `rabbitmq_log_dir` it should get picked up automatically since it inds in `.log`

2017-02-28 14:16 UTC, feanil commented on playbooks/roles/rabbitmq/defaults/main.yml
> +rabbitmq_mem_log: "{{ COMMON_LOG_DIR }}/rabbitmq.memory.log"
Memory log location should go under `rabbitmq_log_dir`

2017-02-28 14:16 UTC, feanil commented on playbooks/roles/rabbitmq/templates/etc/logrotate.d/rabbitmq.j2
> +{{ rabbitmq_log_dir }}/*.log {{ rabbitmq_log_dir }}/*/*.log {{ rabbitmq_mem_log }}{
Onec the memory file is under the `rabbitmq_log_dir` you don't need to make this change.

2017-03-01 14:02 UTC, nadeemshahzad commented
@edx/devops Please review this

2017-03-01 14:57 UTC, feanil approved these changes

2017-03-01 15:30 UTC, merged