Change the default XQUEUE_RABBITMQ_TLS value to false
openedx-unsupported/configuration pull request #3718
Opened 2017-02-28 01:22 UTC by bdero

This PR changes the default value of `XQUEUE_RABBITMQ_TLS` to be `false`, which makes `xqueue` the same as before #3447 (without TLS).
This is necessary because the RabbitMQ role does not configure it to use TLS by default, so enabling TLS by defauly may break builds like issue #3717 explains.

Closes #3717.

Configuration Pull Request
---

Make sure that the following steps are done before merging

  - [ ] A devops team member has commented with :+1:
  - [x] **(Possibly)** are you adding any new default values that need to be overridden when this goes live?
    - [ ] Open a ticket (DEVOPS) to make sure that they have been added to secure vars.
    - [ ] Add an entry to the CHANGELOG.

2017-02-28 01:22 UTC, edx-webhook commented
Thanks for the pull request, @bdero! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fconfiguration&number=3718"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-02-28 01:24 UTC, edx-webhook commented
Thanks for the pull request, @bdero! I've created [OSPR-1689](https://openedx.atlassian.net/browse/OSPR-1689) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

2017-02-28 08:25 UTC, itsjeyd approved these changes
@bdero This LGTM. I had one comment, :+1: once you address it.

- [x] ~~I tested this:~~ Implements a known fix, cf. https://github.com/edx/configuration/issues/3717#issue-210566286.
- [x] I read through the code
- [x] ~~I checked for accessibility issues~~ N/A
- [x] Includes documentation

2017-02-28 08:25 UTC, itsjeyd commented on CHANGELOG.md
> +  - Added `XQUEUE_RABBITMQ_PORT` to allow configuring the RabbitMQ port.
@bdero We should move the items in L216-L217 to the `Role: xqueue` entry above.

2017-02-28 14:18 UTC, feanil requested changes

2017-02-28 14:18 UTC, feanil commented on CHANGELOG.md
> +  - Changed `XQUEUE_RABBITMQ_TLS` default from `true` to `false`.
This should be at the top of the change log, not at the bottom.  New changes should go to the top of the changelog.

2017-03-01 00:40 UTC, bdero commented on CHANGELOG.md
> +  - Added `XQUEUE_RABBITMQ_PORT` to allow configuring the RabbitMQ port.
Fixed, thanks.

2017-03-01 00:40 UTC, bdero commented on CHANGELOG.md
> +  - Changed `XQUEUE_RABBITMQ_TLS` default from `true` to `false`.
Ah ok, fixed.

2017-03-01 00:40 UTC, bdero commented
@itsjeyd @feanil Thanks for the reviews - I've addressed your comments!

2017-03-01 14:46 UTC, feanil approved these changes

2017-03-01 19:50 UTC, merged