Add a playbook for installing and configuring Graphite.
openedx-unsupported/configuration pull request #3723
Opened 2017-03-01 20:00 UTC by tobz

This playbook will install `carbon-cache` and `graphite-api` to provide a minimalistic starting point for metrics collection.  A server would be ready to accept metrics (from anything that could speak the Graphite line protocol, such as `statsd`) and be a target for a Grafana installation after running this playbook on its own.

It currently installs all components from their upstream source (albeit with defaults that point to tags, and not master/development branches).  It uses systemd, and so is tailored specifically to Ubuntu 16.04.

It currently does not support any of the advanced configuration such as multiple `carbon-cache` process + `carbon-relay`.  It is also lacking many variables to fully tweak the various configuration files, although there's support for fully configuring the storage schemas.

There is a small "master" playbook -- `edx-monitoring` -- for running the role, and in the future, supporting the culmination of other playbooks to build out an all-in-one monitoring server: Graphite, Grafana, etc.

Configuration Pull Request
---

Make sure that the following steps are done before merging

  - [ ] A devops team member has commented with :+1:
  - [ ] are you adding any new default values that need to be overridden when this goes live?
    - [ ] Open a ticket (DEVOPS) to make sure that they have been added to secure vars.
    - [ ] Add an entry to the CHANGELOG.

2017-03-01 20:10 UTC, tobz commented
/cc @edx/devops

2017-03-01 20:15 UTC, tobz commented
Point of order: I cribbed this playbook from an existing playbook (https://github.com/azavea/ansible-graphite) and so the LICENSE from the original project is included, with an amendment at the top pointing back to the original project.

2017-03-02 20:53 UTC, e0d commented
@tobz high-level question, can you summarize what changes you made from the source ansible artifacts and why you chose this one?

2017-03-03 00:56 UTC, tobz commented
High-level changes:
- make it use a virtualenv
- install graphite-api over graphite-web (don't need all the web baggage if running Grafana on top)
- make it install gunicorn (because we don't want to hit graphite-api directly)
- use systemd (instead of SysV) to ensure both carbon-cache and graphite-api get supervised properly

I mostly chose this one because it worked off of the tagged source, had a suitable license for derivations, and was one of the smaller ones that I found.  Many of them were versions that appeared to be tailored to the individual's own needs / company needs.

2017-03-03 13:46 UTC, e0d commented
I think we should have a docker CI build that can run in travis:

https://github.com/edx/configuration/tree/master/docker/build

2017-03-03 13:46 UTC, e0d reviewed
First pass.

2017-03-03 13:46 UTC, e0d commented on playbooks/roles/graphite/handlers/main.yml
> +- name: Restart Carbon
We've been typically avoiding handlers as their behavior can be surprising and we typically don't do rolling upgrades.  We've been using tags to target tasks to give us flexibility around which sets are run at any invocation:

https://openedx.atlassian.net/wiki/display/OpenOPS/Role+Life-cycle+Tags

2017-03-03 13:46 UTC, e0d commented on playbooks/roles/graphite/tasks/carbon.yml
> +- name: install Carbon dependencies
why not use the pip module?

2017-03-03 13:46 UTC, e0d commented on playbooks/roles/graphite/tasks/carbon.yml
> +  file: path={{ graphite_root }}/storage
Feels like we should separate out the storage root from the app root.  It may be that by default graphite_storage is set to {{ graphite_root }}/storage, but I'd think we'd relocate the storage at scale.

2017-03-03 13:46 UTC, e0d commented on playbooks/roles/graphite/tasks/graphite-api.yml
> +  git: repo=https://github.com/brutasse/graphite-api.git
repo should be a var I think, makes groking from defaults easier, supports forks, etc.

2017-03-03 13:46 UTC, e0d commented on playbooks/roles/graphite/tasks/graphite-api.yml
> +  command: "{{ graphite_root }}/bin/pip install -r {{ graphite_root }}/src/api/requirements.txt"
pip module

2017-03-03 13:46 UTC, e0d commented on playbooks/roles/graphite/tasks/main.yml
> +- name: create common Graphite directories
I like doing this using with_items and data:

https://github.com/edx/configuration/blob/master/playbooks/roles/vhost/defaults/main.yml#L18

2017-03-03 13:46 UTC, e0d commented on playbooks/roles/graphite/tasks/main.yml
> +  with_items:
use a var: https://github.com/edx/configuration/blob/master/playbooks/roles/common_vars/defaults/main.yml#L110

2017-03-03 13:46 UTC, e0d commented on playbooks/roles/graphite/defaults/main.yml
> +---
Can you add boilerplate and explanatory comment, c.f., https://github.com/edx/configuration/blob/master/playbooks/roles/vhost/tasks/main.yml#L2

2017-03-03 13:46 UTC, e0d commented on playbooks/roles/graphite/templates/carbon/conf/carbon.conf.j2
> +LINE_RECEIVER_INTERFACE = 0.0.0.0
Seems like some of these are things we'd want to var out.  Listening on 0.0.0.0 for sure seems like something we'd want to make obvious in the defaults.  Other things we'd expect ourselves or others to reasonably change should be as well.

2017-03-03 13:46 UTC, e0d commented on playbooks/roles/nginx/templates/edx/app/nginx/sites-available/graphite.j2
> +#
Play will need to include nginx.

2017-03-03 13:46 UTC, e0d commented on playbooks/roles/graphite/templates/graphite-api/systemd/graphite-api.service.j2
> +ExecStart={{ graphite_root }}/bin/gunicorn -w 2 graphite_api.app:app
I think workers should be configurable.

2017-03-03 13:46 UTC, e0d commented on playbooks/roles/graphite/tasks/main.yml
> +  group: name=graphite
we should make this a var and the group so we can pass to templates later.

2017-03-03 13:46 UTC, e0d commented on playbooks/roles/graphite/templates/graphite-api/systemd/graphite-api.service.j2
> +User=graphite
Use user/group vars defined above.

2017-03-03 13:46 UTC, e0d commented on playbooks/roles/graphite/tasks/main.yml
> +- name: Find all example configuration files
what's wrong with the examples?

2017-03-03 14:21 UTC, tobz commented on playbooks/roles/graphite/tasks/main.yml
> +- name: Find all example configuration files
Nothing, really.  There's just like 10 of them and it felt like it was just a little harder than it ought to be to peek at the file listing and see the actual configuration files being used.

2017-03-03 14:22 UTC, tobz commented on playbooks/roles/graphite/tasks/carbon.yml
> +- name: install Carbon dependencies
There's a pip module? Sweet! I'll use that.

2017-03-03 14:23 UTC, tobz commented on playbooks/roles/graphite/tasks/main.yml
> +  group: name=graphite
Good point.  Will do.

2017-03-07 14:36 UTC, tobz commented on playbooks/roles/graphite/defaults/main.yml
> +---
I addressed this in `tasks/main.yml` specifically.

2017-03-07 14:36 UTC, tobz commented on playbooks/roles/nginx/templates/edx/app/nginx/sites-available/graphite.j2
> +#
Yup, this is now taken care of.

2017-03-07 14:36 UTC, tobz commented on playbooks/roles/graphite/handlers/main.yml
> +- name: Restart Carbon
I opted to stick with handlers for the time being.

2017-03-07 17:26 UTC, tobz commented
@edx/devops Since Ed is out, can someone take another pass at this for review?

2017-03-09 14:08 UTC, fredsmith commented
@tobz can you add tags on all tasks according to https://openedx.atlassian.net/wiki/display/OpenOPS/Role+Life-cycle+Tags ?  We've been doing this for all ansible code that gets merged.

You should also re-write your handlers as tasks, and make sure they're tagged appropriately.

2017-03-09 19:07 UTC, tobz commented
@fredsmith This should be all set now.

2017-03-09 19:29 UTC, fredsmith requested changes
I think we can remove the handler definitions, then :+1:

2017-03-09 19:29 UTC, fredsmith commented on playbooks/roles/graphite/handlers/main.yml
> +- name: Restart Carbon
I think this can go away now.

2017-03-09 19:38 UTC, tobz commented
Ah right, my mistake.  Fixed.

2017-03-09 20:01 UTC, fredsmith approved these changes

2017-03-09 20:02 UTC, fredsmith commented
looks good to merge :+1:

2017-03-09 20:25 UTC, merged