Update mariadb role for Ficus and Xenial and add groups capability
openedx-unsupported/configuration pull request #3729
Opened 2017-03-03 14:07 UTC by panessa

- Add Xenial support keeping compatibility with previous Ubuntu release like Precise and Trusty
- ANALYTICS_API_CONFIG is not defined anymore and the role "edxlocal" is used to create all databases and users. Mariadb role is now updated to be inline with this
- Use ansible module mysql_user for creating haproxy monitor user. It's better to use ansible mysql_user to avoid creation of user on every node of the cluster and crash the installation
- Use groups[group_names[0]]| instead of hostvars.keys(). This add the capability to use different deploying solution that takes advantage of ansible groups. This fix is compatible with previous solution
- Updated to be compatible with Ansible 2.2

2017-03-03 14:07 UTC, edx-webhook commented
Thanks for the pull request, @panessa! I've created [OSPR-1696](https://openedx.atlassian.net/browse/OSPR-1696) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

2017-03-18 15:39 UTC, gsong commented
@edx/devops Can we get this on your radar?

2017-03-20 17:52 UTC, feanil requested changes

2017-03-20 17:52 UTC, feanil commented on playbooks/roles/mariadb/tasks/cluster.yml
> +  lineinfile: >
Why did you switch back to the old format?

2017-03-20 17:52 UTC, feanil commented on playbooks/roles/mariadb/tasks/cluster.yml
> +  fetch: >
Same as above, the yaml format is much clearer and we are generally trying to move towards it, not away from it.

2017-03-20 17:52 UTC, feanil commented on playbooks/roles/mariadb/tasks/cluster.yml
> +  mysql_user: >
+1 to switching to use the standard module but this should use the yaml syntax format.

2017-03-20 17:52 UTC, feanil commented on playbooks/roles/mariadb/tasks/main.yml
> +    priv: "{{ item.db }}.*:ALL"
The application user should not have `ALL`.  It should just have `SELECT,INSERT,UPDATE,DELETE`

2017-03-20 17:52 UTC, feanil commented on playbooks/roles/mariadb/tasks/main.yml
> +- name: setup the edx-notes-api db user
Why is this user not being created along with the rest in the above iteration of app users?

2017-03-20 17:52 UTC, feanil commented on playbooks/roles/mariadb/tasks/main.yml
> +    priv: "*.*:ALL"
Should not have `ALL`, it should only have `SELECT`

2017-03-21 09:21 UTC, panessa commented on playbooks/roles/mariadb/tasks/main.yml
> +    priv: "{{ item.db }}.*:ALL"
I got those permissions from edxlocal tasks, probably some changes are needed also there to keep permissions inline

2017-03-21 09:26 UTC, panessa commented on playbooks/roles/mariadb/tasks/main.yml
> +- name: setup the edx-notes-api db user
I don't know, I got those stuff from edxlocal role. I think there's a reason, but it's obscure to me.

2017-03-21 09:28 UTC, panessa commented on playbooks/roles/mariadb/tasks/main.yml
> +    priv: "*.*:ALL"
Same as above. I got those permissions from edxlocal tasks, probably some changes are needed also there to keep permissions inline.

2017-03-21 11:00 UTC, panessa commented
Hello @feanil, I commited all changes. I just left hive and edx-notes-api releated tasks. I will change it if you think that it's needed.

2017-03-21 21:21 UTC, feanil commented on playbooks/roles/mariadb/tasks/cluster.yml
> +    state: present
You need to set the privileges for this user so they can only `flush previleges`.

2017-03-21 21:21 UTC, feanil commented on playbooks/roles/mariadb/tasks/main.yml
> +    priv: '{{ ANALYTICS_API_DATABASES.default.NAME }}.*:ALL/reports.*:SELECT'
You also want just `SELECT,INSERT,UPDATE,DELETE` for the ANALYTICS_API_DATABASE instead of `ALL`

2017-03-21 21:21 UTC, feanil commented on playbooks/roles/mariadb/tasks/main.yml
> +- name: setup the edx-notes-api db user
I think you should roll this up with the other databases.

2017-03-29 11:24 UTC, panessa commented
@feanil I commited changes

2017-03-29 11:32 UTC, panessa reviewed
Added RELOAD as privileges

2017-03-29 11:32 UTC, panessa commented on playbooks/roles/mariadb/tasks/main.yml
> +- name: setup the edx-notes-api db user
The difference here is all databases are created using encoding utf-8; Hive database has encoding latin1. That's why tasks are separated.

2017-03-29 11:32 UTC, panessa commented on playbooks/roles/mariadb/tasks/cluster.yml
> +    state: present
Using default you got

SHOW GRANTS FOR 'haproxy'@'mariadb_haproxy_hosts';
+---------------------------------------------------------------+
| Grants for haproxy@mariadb_haproxy_hosts                                |
+---------------------------------------------------------------+
| GRANT USAGE ON *.* TO 'haproxy'@'mariadb_haproxy_hosts'  |
+---------------------------------------------------------------+

How do you want to change it?

2017-04-19 17:37 UTC, gsong commented
@feanil When you get a chance, can you pick up the review of this PR again? Thanks.

2017-06-27 20:24 UTC, gsong commented
@edx/devops Ping.

2017-08-28 18:26 UTC, feanil approved these changes

2017-08-28 18:27 UTC, merged