script to shovel between rabbitmq clusters
openedx-unsupported/configuration pull request #3736
Opened 2017-03-06 20:44 UTC by nadeemshahzad

@edx/devops Please review

2017-03-07 14:47 UTC, feanil commented
@nadeemshahzad this script currently only takes one queue name as input, I think what we want is the ability to point the script at one cluster and it would find all the queues on that cluster that were not `celereyev` queues and run shovel for each of them.

2017-03-09 13:05 UTC, nadeemshahzad commented
@feanil I have updated script to iterate through queues of old cluster and create shovel for each of them except **celeryev** and **.pidbox** queues

2017-03-09 14:10 UTC, feanil requested changes

2017-03-09 14:10 UTC, feanil commented on util/rabbitmq/shovel.py
> +src_uri="\"amqp://%s:%s@%s\"" % (args.src_user,args.src_user_pass,args.src_host)
Use single quotes on the outside so you don't have to escape the double quotes.

Also use `str.format()` instead of `%`

2017-03-09 14:10 UTC, feanil commented on util/rabbitmq/shovel.py
> +dest_uri="\"amqp://%s:%s@%s\"" % (args.dest_user,args.dest_user_pass,args.dest_host)
Same note as the line above.

2017-03-09 14:10 UTC, feanil commented on util/rabbitmq/shovel.py
> +    url="http://%s:%d/api/vhosts" % (args.src_host,port)
Use `str.format()`

2017-03-09 14:10 UTC, feanil commented on util/rabbitmq/shovel.py
> +    vhosts=[v['name'] for v in response.json() if v['name'].startswith('/')]
You should do error checking on the response before trying to pull out the json response.

2017-03-09 14:10 UTC, feanil commented on util/rabbitmq/shovel.py
> +        url="http://%s:%d/api/queues/%s" % (args.src_host,port,vhost)
Use `str.format()`

2017-03-09 14:10 UTC, feanil commented on util/rabbitmq/shovel.py
> +        queues=[q['name'] for q in response.json()]
Add error checking before reading out of the request response.

2017-03-09 14:10 UTC, feanil commented on util/rabbitmq/shovel.py
> +    cmd="/usr/sbin/rabbitmqctl set_parameter shovel %s '%s'" % (shovel,arg)
Use `str.format()`

2017-03-09 14:10 UTC, feanil commented on util/rabbitmq/shovel.py
> +    subprocess.call(
Use [check_output](https://docs.python.org/3.5/library/subprocess.html#subprocess.check_output) instead. If the call fails, check the exception and store the output.  At the end of the run, it should produce a list of all queues where shovel call failed and the output of the call.

2017-03-09 14:10 UTC, feanil commented on util/rabbitmq/shovel.py
> +            args="{\"src-uri\": %s, \"src-queue\": \"%s\",\"dest-uri\": %s,\"dest-queue\": \"%s\"}" % (src_uri,queue,dest_uri,queue)
Use single quotes on the outside so you don't have to escape all the double quotes.

Use `str.format()` instead of `%`

2017-03-10 12:55 UTC, nadeemshahzad commented
@feanil Updated error handling and template formatting

2017-03-10 15:08 UTC, feanil commented on util/rabbitmq/shovel.py
> +    print "\n".join(output)
Can you also include the name of the queue that failed or is that already provided in the output?

2017-03-10 15:08 UTC, feanil approved these changes
One last comment to address then I think this is good to go.

2017-03-13 10:41 UTC, nadeemshahzad commented
@feanil Added queue name to output if call failed

2017-03-13 10:46 UTC, merged