tentative stab at adding newrelic monitoring to coursegraph (SUST-81)
openedx-unsupported/configuration pull request #3789
Opened 2017-04-03 14:42 UTC by adampalay

Configuration Pull Request

@fredsmith , may you please provide some comments and guidance? Here are my questions:

1. When do we use the `lineinfile` module instead of the `template` module? I used the `template` module for the newrelic.yml configuration file. Should I have used `lineinfile` instead?
2. Are the settings sensible for newrelic.yml? They're just the default ones
3. I didn't include newrelic.jar in this PR, because I wasn't sure if it was somehow specific to our newrelic installation.
4. How can I test these configuration changes?

---

Make sure that the following steps are done before merging

  - [ ] A devops team member has commented with :+1:
  - [ ] are you adding any new default values that need to be overridden when this goes live?
    - [ ] Open a ticket (DEVOPS) to make sure that they have been added to secure vars.
    - [ ] Add an entry to the CHANGELOG.

2017-04-03 14:44 UTC, adampalay commented
@benpatterson , would be curious to get your thoughts on `template vs `lineinfile`

2017-04-03 19:56 UTC, feanil commented on playbooks/roles/neo4j/tasks/main.yml
> +    src: newrelic.jar
What version of agent is this?  Also can we download it on demand from newrelic as a part of the playbook.  Basically provide a URL to the agent jar and it gets downloaded onto the machine if it's a different version from the one that is currently installed there.  The way you have it now, I think we would need a code change before we can update the agent if it's already there on the remote machine.

2017-04-03 20:11 UTC, benpatterson commented
@adampalay the decision between `template` vs `lineinfile` for me comes down to whether or not a configuration file will arrive for free when something is installed. So, if installing the agent includes pulling down a yml file, then lineinfile sounds good to me. If, OTOH, the configuration file always has to be put in separately, I might instead have a pared-down yml file with only the configuration settings you want (and comments explaining what they are, and where to find the list of all conf options). HTH?

2017-04-03 20:15 UTC, adampalay commented on playbooks/roles/neo4j/tasks/main.yml
> +    src: newrelic.jar
It looks like we can't download it as part of the playbook—the various methods of downloading it from newrelic all involve clicking a button, while authenticated, to get a zip file that contains `newrelic.jar`: https://docs.newrelic.com/docs/agents/java-agent/installation/java-agent-manual-installation. I don't see a way just to get that agent itself.

I don't know how we'd get newrelic.jar onto the box without including it in a configuration file.

2017-04-07 17:12 UTC, fredsmith requested changes

2017-04-07 17:12 UTC, fredsmith commented on playbooks/roles/neo4j/tasks/main.yml
> +    # owner: do I need one?
you do need an owner.  make it the 'neo4j' user.

2017-04-07 17:12 UTC, fredsmith commented on playbooks/roles/neo4j/tasks/main.yml
> +    src: newrelic.jar
Because of the reasons adam cited, I think that pulling this in via a copy command is the right way to do this.

2017-04-07 17:12 UTC, fredsmith commented on playbooks/roles/neo4j/tasks/main.yml
> +    # just guessing? No idea what mode we'd need
needs an owner, 'neo4j'

2017-04-24 13:56 UTC, adampalay commented on playbooks/roles/neo4j/tasks/main.yml
> +    src: newrelic.jar
@feanil , other thoughts?

2017-04-24 14:50 UTC, feanil commented on playbooks/roles/neo4j/tasks/main.yml
> +    src: newrelic.jar
For things like this in the past we've uploaded them to s3.  I think that's better so that we have a backup of it that is not on a developer machine.  There is also a concern that if the file exists on the destination machine, it won't get updated, we should either do some version checks or always copy the file over to the destination.

2017-04-24 15:02 UTC, adampalay commented on playbooks/roles/neo4j/tasks/main.yml
> +    src: newrelic.jar
@feanil that makes sense! That way we can put it behind auth too!

2018-04-19 19:49 UTC, edx-webhook commented
Thanks for the pull request, @adampalay! I've created [OSPR-2354](https://openedx.atlassian.net/browse/OSPR-2354) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

2018-04-20 14:08 UTC, mduboseedx commented
@edx/devops Is this something that is still worth pursuing?

2018-04-23 18:04 UTC, closed without merging