Make changes for running analyticstack on 16.04.
openedx-unsupported/configuration pull request #3808
Opened 2017-04-12 18:04 UTC by brianhw

* Replace llvm-gcc with gcc.
* Define new Hadoop services.
* Add retry when first using Hadoop.
* Add procps to debian packages to address bug.

Configuration Pull Request
---

Make sure that the following steps are done before merging

  - [ ] A devops team member has commented with :+1:

2017-04-19 14:35 UTC, brianhw commented
This has finally been tested against a matching version of edx-analytics-pipeline (see https://github.com/edx/edx-analytics-pipeline/pull/379), and all acceptance tests pass.   (Or, rather, no acceptance tests fail.)

@edx/devops This is ready for final review.     FYI:  @tobz , @HassanJaveed84 , @azafty468.

@nedbat FYI. Once merged, ficus.master should be ready for ficus.3.

2017-04-19 14:50 UTC, brianhw commented
@tobz I cloned your system definitions -- hopefully I did it the right way.

2017-04-20 14:49 UTC, fredsmith requested changes
Two minor chages, otherwise looks good.

2017-04-20 14:49 UTC, fredsmith commented on playbooks/roles/analytics_pipeline/tasks/main.yml
> +    - install:configuration
I think this is still manage, manage:start, not install, install:configuration.   Can you separate enabled and state into two tasks and tag the enabled:true one install, install:configuration and the state: started one manage, manage:start ?

2017-04-20 14:49 UTC, fredsmith commented on playbooks/roles/hadoop_common/templates/hdfs-datanode.service.j2
> +[Unit]
Can all these files go in the templates/etc/systemd/system/ directory in the role?  This is our standard practice for templates.

2017-04-20 14:53 UTC, brianhw commented on playbooks/roles/analytics_pipeline/tasks/main.yml
> +    - install:configuration
I'll give it a try -- thanks!

2017-04-20 14:53 UTC, brianhw commented on playbooks/roles/hadoop_common/templates/hdfs-datanode.service.j2
> +[Unit]
Yes, I will.

2017-04-20 15:02 UTC, nedbat approved these changes
Seems good, though I know nothing about hadoop-world.

2017-04-20 16:59 UTC, brianhw commented
@fredsmith I made the changes you requested, rebuilt an analyticstack box, and ran some edx-analytics-pipeline acceptance tests against it successfully.  I ran some tests both before and after a "vagrant halt", to confirm that pipeline services were available.   Awaiting a thumb.

2017-04-20 17:29 UTC, fredsmith approved these changes

2017-04-20 17:30 UTC, merged