[WIP] ENT-306: Added a feature flag to show/hide account activation message on edx-platform dashboard
openedx-unsupported/configuration pull request #3817
Opened 2017-04-14 12:38 UTC by saleem-latif

@mattdrayer , @brittneyexline -- FYI

I will add more info once https://github.com/edx/edx-platform/pull/14874 is merged and we are ready to test this.

Configuration Pull Request
---

Make sure that the following steps are done before merging

  - [ ] A devops team member has commented with :+1:
  - [ ] are you adding any new default values that need to be overridden when this goes live?
    - [ ] Open a ticket (DEVOPS) to make sure that they have been added to secure vars.
    - [ ] Add an entry to the CHANGELOG.

2017-04-14 19:11 UTC, feanil commented on playbooks/roles/edxapp/defaults/main.yml
> +EDXAPP_DISPLAY_ACCOUNT_ACTIVATION_MESSAGE_ON_DASHBOARD: true
Does this need to be a permanent feature flag? Are three times when you wouldn't want this to be true?

2017-04-18 16:52 UTC, brittneyexline commented on playbooks/roles/edxapp/defaults/main.yml
> +EDXAPP_DISPLAY_ACCOUNT_ACTIVATION_MESSAGE_ON_DASHBOARD: true
Hi @feanil , there is a possibility that this could be changed to false (though unlikely), but I'm curious if there are other options for flagging that you think would be more appropriate?

2017-04-19 19:15 UTC, haikuginger requested changes

2017-04-19 19:15 UTC, haikuginger commented on playbooks/roles/edxapp/defaults/main.yml
> +EDXAPP_DISPLAY_ACCOUNT_ACTIVATION_MESSAGE_ON_DASHBOARD: true
I'm confused as to why the default value for this variable appears _after_ its use in `EDXAPP_FEATURES`. Can you clarify this?

2017-04-20 08:06 UTC, saleem-latif commented on playbooks/roles/edxapp/defaults/main.yml
> +EDXAPP_DISPLAY_ACCOUNT_ACTIVATION_MESSAGE_ON_DASHBOARD: true
@haikuginger I have seen usages of variables before their declaration and they work, But I am moving variable declaration before its usage to be on the safe side.

2017-04-24 15:13 UTC, feanil commented
@brittneyexline responding to the conversation on the outdated diff.  Feature flags in the dictionary are permanent and hard to change.  It sounds like this is a thing where we want the feature flag so that we can push out the code while leaving the flag off but then turn it on so that the feature can be flipped independent of the release, is that right?  If so, then this is a really good use case for a temporary waffle flag.

2017-07-19 08:43 UTC, saleem-latif commented
closing this for now, I will reopen it once https://openedx.atlassian.net/browse/ENT-363 is prioritized and pulled into a sprint.

2017-07-19 08:43 UTC, closed without merging