Automate required vagrant plugin installation for any number of plugins.
openedx-unsupported/configuration pull request #3843
Opened 2017-04-30 14:34 UTC by UmanShahzad

Configuration Pull Request
---

Make sure that the following steps are done before merging

  - [ ] A devops team member has commented with :+1:
  - [ ] are you adding any new default values that need to be overridden when this goes live?
    - [ ] Open a ticket (DEVOPS) to make sure that they have been added to secure vars.
    - [ ] Add an entry to the CHANGELOG.

---

Don't think the checklist above is really relevant for this change, except the first point, so ignoring it unless someone says otherwise.

### Problem

Save new users some typing (`vagrant plugin install PLUGIN1`, `vagrant plugin install PLUGIN2`, ...).

### Solution

In case `vagrant` needs more plugins in the future, one can simply add them to the list in the method call `install_plugins` in `Vagrantfile` and automate installation for all of them (given '`y`').

Because `vagrant` doesn't seem to detect the additional installed plugins mid-run, one has to manually kill the current `vagrant` process and restart it with Ruby's `exec`.

Long story short, this should save future users some typing! Especially if more plugins become required.

### Future Work

- Plugin version locking.

@bradenmacdonald For recommending me to commit this feature here.

2017-04-30 14:34 UTC, edx-webhook commented
Thanks for the pull request, @UmanShahzad! I've created [OSPR-1757](https://openedx.atlassian.net/browse/OSPR-1757) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     If you like, you can add yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

2017-05-02 15:32 UTC, feanil commented
@nedbat I think you or @gsong would be the right people to review this.

2017-05-04 15:52 UTC, nedbat reviewed
@UmanShahzad have you sent in your contributor's agreement? Also, full disclosure: we are in the process of building out a Docker-based infrastructure.  We likely won't get rid of Vagrantfiles just yet, but they are definitely not our preferred technology for the longer-term.

I'll add a few comments now, but we do need to get that contributor's agreement. Thanks for the pull request! :)

2017-05-04 15:52 UTC, nedbat commented on vagrant/.vagrantplugins.rb
> +# vi: set ft=ruby :
I would rather not have editor mode files in every source file. I think emacs and vim users probably have their editors configured to recognize .rb files as Ruby.

2017-05-04 15:52 UTC, nedbat commented on vagrant/.vagrantplugins.rb
> +# -*- mode: ruby -*-
Why name this as a hidden file?  Let's find a good place for a real file with a real name.

2017-05-04 15:58 UTC, gsong commented
@nedbat: @UmanShahzad is good on the CLA. 👍

2017-05-04 16:59 UTC, UmanShahzad commented on vagrant/.vagrantplugins.rb
> +# -*- mode: ruby -*-
I agree -- this is only what I originally saw a similar solution doing and thought it may be the preferred method. But looking at it again it could be better. Please consider the new change and let me know if it's more reasonable!

2017-05-04 16:59 UTC, UmanShahzad commented on vagrant/.vagrantplugins.rb
> +# vi: set ft=ruby :
Good point, didn't catch that, even though I'm using vim myself -_- Removed it.

2017-05-04 17:01 UTC, UmanShahzad commented
@nedbat Thanks for reviewing the PR! I've handed in the CLA as @gsong noted and made some changes according to your review.

I definitely understand your moving to Docker. I hope I can stay in touch to help on that if needed. Let me know if this change is worth merging.

2017-05-04 18:50 UTC, nedbat requested changes

2017-05-04 18:50 UTC, nedbat commented on vagrant/base/analyticstack/Vagrantfile
> +unless ARGV.empty?
This is probably a fine line, but I don't understand it: why check if ARGV is empty?  Also, unless the "require" is a problem, we could check it inside the install_plugins function, and avoid the duplicated if-statements.

2017-05-04 18:50 UTC, nedbat commented on vagrantplugins.rb
> +def install_plugins(plugins)
Let's put this in the vagrant directory.
Also, the configuration repo is inconsistent, but we've decided on 4-space indents, so this new file should follow that rule.  We have a .editorconfig file if you have the Vim plugin.

2017-05-04 18:50 UTC, nedbat commented on vagrantplugins.rb
> +def install_plugins(plugins)
(actually, new lines in the Vagrantfiles should also follow that 4-space indent. sorry to be picky...)

2017-05-04 19:34 UTC, UmanShahzad commented on vagrant/base/analyticstack/Vagrantfile
> +unless ARGV.empty?
So the reason for checking if ARGV is empty is to exempt the normal, argument-less `vagrant` command from raising the plugin error or asking for input (i.e. if you just typed `vagrant` to see the subcommand list, with either the old version or this one, then if you don't have the plugin it throws the error; I assume that isn't intentional so we exempt the requirement check in this case). Unfortunately commands like `vagrant help` are still not exempt with what's here, so I think your recommendation to encapsulate this logic inside of `install_plugins` may be a fine idea to keep it hidden and still cover all cases.

2017-05-04 19:34 UTC, UmanShahzad commented on vagrantplugins.rb
> +def install_plugins(plugins)
No no, that's fine, I am picky myself :) Thanks for that, I'll follow it.

2017-05-04 20:07 UTC, UmanShahzad commented
@nedbat Updated -- let me know if you feel the ARGV situation should be handled differently.

2017-05-05 16:15 UTC, nedbat commented
Thanks, looks good!

2017-05-05 16:15 UTC, nedbat approved these changes

2017-05-05 16:16 UTC, merged

2017-05-05 20:14 UTC, nedbat commented
@UmanShahzad I had to revert this for now, a developer had an issue with the require_relative path.

2017-05-05 20:31 UTC, nedbat commented
@UmanShahzad ugh, I feel terrible about this.  The way we install devstack is with install_devstack.sh, which curls the Vagrantfile without the rest of the configuration repo.  It also installs the plugins for you.

2017-05-05 21:48 UTC, UmanShahzad commented
@nedbat No worries! Nothing terrible about it. I walked through `install_stack.sh` and saw where the plugin installation occurs. It's explicitly called (i.e. `vagrant plugin install vagrant-vbguest` written straight in the script). Automating it for further plugins is trivial:

```
for plugin in vagrant-vbguest vagrant-plugin2 vagrant-plugin3 ...
do
    vagrant plugin install $plugin
end
```

But considering only a single plugin's being used right now and you guys are moving to Docker, this is totally unnecessary.

Hopefully I can help contribute else where next time :) Thanks for reviewing!

2017-05-08 17:02 UTC, nedbat commented
@UmanShahzad it's been a pleasure working with you.  I hope you can do more in the future. Thanks.