Make edx_notes_api endpoint HTTPS aware
openedx-unsupported/configuration pull request #3847
Opened 2017-05-02 11:23 UTC by tkeemon

The edx-notes API endpoint isn't HTTPS aware by default, but setting:

```
NGINX_REDIRECT_TO_HTTPS: true
```

does force HTTP requests to HTTPS:

https://github.com/edx/configuration/blob/0271c34899f7d8b6208787c0def1ea66b58e7ae6/playbooks/roles/nginx/templates/edx/app/nginx/sites-available/edx_notes_api.j2#L17

The resulting HTTPS request connects to whatever Nginx service is defined as `default` (in most cases, the LMS).

This PR enables HTTPS when:

```
NGINX_ENABLE_SSL: true
```

One thing I'm unsure of is whether or not to set a different default port number for the newly created variable `edx_notes_api_ssl_nginx_port`. Other services have seemingly random port numbers assigned. e.g.:

- [EDXAPP_LMS_SSL_NGINX_PORT: 48000](https://github.com/edx/configuration/blob/a3b27e91e2f46ac3a12f22b5421331e587e33559/playbooks/roles/edxapp/defaults/main.yml#L275)
- [EDXAPP_CMS_SSL_NGINX_PORT: 48010](https://github.com/edx/configuration/blob/a3b27e91e2f46ac3a12f22b5421331e587e33559/playbooks/roles/edxapp/defaults/main.yml#L278)
- [ECOMMERCE_SSL_NGINX_PORT: 48130](https://github.com/edx/configuration/blob/2656eb9f36bcdd9283fe34a0ec95fc0de263caee/playbooks/roles/ecommerce/defaults/main.yml#L21)
- [INSIGHTS_NGINX_SSL_PORT: "18113"](https://github.com/edx/configuration/blob/2656eb9f36bcdd9283fe34a0ec95fc0de263caee/playbooks/roles/insights/defaults/main.yml#L149)

Also, the newly created variable doesn't follow the convention of using all uppercase letters for variables that are often changed. But in the edx_notes_api role, neither does `edx_notes_api_nginx_port` (among others). 

---

Make sure that the following steps are done before merging

  - [ ] A devops team member has commented with :+1:
  - [ ] are you adding any new default values that need to be overridden when this goes live?
    - [ ] Open a ticket (DEVOPS) to make sure that they have been added to secure vars.
    - [ ] Add an entry to the CHANGELOG.

2017-05-02 11:23 UTC, edx-webhook commented
Thanks for the pull request, @tkeemon! I've created [OSPR-1759](https://openedx.atlassian.net/browse/OSPR-1759) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

2017-05-02 14:55 UTC, feanil requested changes
One change, otherwise this looks good.

2017-05-02 14:55 UTC, feanil commented on playbooks/roles/edx_notes_api/defaults/main.yml
> +edx_notes_api_ssl_nginx_port: 443
The default port shouldn't be 443, it should be a `4` prefixed version of the gunicorn port.

2017-05-03 09:28 UTC, tkeemon commented
@feanil thanks for the feedback. I've pushed that change to the PR.

2017-05-07 14:44 UTC, feanil approved these changes

2017-05-07 14:44 UTC, feanil commented
@edx/devops can I get a second review for this.

2017-05-08 17:07 UTC, jibsheet approved these changes

2017-05-10 01:14 UTC, tkeemon commented
@feanil @jibsheet thanks for the reviews. Do you need anything else from me?

2017-05-10 14:16 UTC, merged