Updated discovery play to use edx_django_service play
openedx-unsupported/configuration pull request #3861
Opened 2017-05-09 21:18 UTC by clintonb

- This removes the duplication across the various IDA configurations
- Updated Dockerfile for Docker-based devstack

LEARNER-817

2017-05-09 21:22 UTC, clintonb commented
@edx/devops please review
FYI @edx/docker-devstack-working-group @edx/learner 

This will be the first of three PRs to update credentials, discovery, and ecommerce to use the `edx_django_service` role.

2017-05-09 21:23 UTC, clintonb commented
Our Docker devstack images have been running this configuration for the past five months.

2017-05-10 18:54 UTC, feanil commented
Have you built AMIs from this?

2017-05-11 16:46 UTC, clintonb commented
loadtest deployments are failing due to https://github.com/edx/configuration/blob/f8cc6369a8e1b556fb92b9ad4960bb252daa5eb4/playbooks/roles/discovery/defaults/main.yml#L127-L133. I'm open to ideas for workarounds. (I'm working on another story at the moment, so I can't dedicate any attention to this this week.)

2017-05-11 16:50 UTC, jibsheet commented
Ah, the discovery.yml playbook in edx-east overrides that.
This looks like an oversight in where the default is declared vs some documentation.

I'm on a bunch of other things this week, but I probably know more than @e0d the original author about current usage so can help later.

2017-05-11 16:56 UTC, clintonb commented
I'll ping you next week, @jibsheet. Thanks!

2017-06-02 19:05 UTC, clintonb commented on playbooks/edx-east/discovery.yml
> -    - role: automated
@e0d @jibsheet please advise on the need for this role. Only discovery and edxapp are using it. Is the intention to use this for all IDAs? If so, it might make sense to add it to `edx_django_service`. For now I have removed it to see if there are other issues with deploying to loadtest-edx-discovery.

2017-06-02 19:30 UTC, jibsheet commented on playbooks/edx-east/discovery.yml
> -    - role: automated
If you want to run management commands from jenkins, you need it.
Otherwise you don't and we'll add it later.

2017-06-02 20:56 UTC, clintonb commented on playbooks/edx-east/discovery.yml
> -    - role: automated
This role is now part of `edx_django_service`.

2017-06-06 11:47 UTC, feanil requested changes

2017-06-06 11:47 UTC, feanil commented on playbooks/edx-east/discovery.yml
> -      AUTOMATED_USERS: "{{ DISCOVERY_AUTOMATED_USERS | default({}) }}"
You removed this line but did not update meta/main.yml to pass the `DISCOVERY_AUTOMATED_USERS` to the `edx_django_service` role.

2017-06-06 13:55 UTC, clintonb commented on playbooks/edx-east/discovery.yml
> -      AUTOMATED_USERS: "{{ DISCOVERY_AUTOMATED_USERS | default({}) }}"
@feanil, does it actually need to be overridden, or are the defaults in `playbooks/roles/edx_django_service/defaults/main.yml` sufficient for the long-term?

2017-06-06 14:00 UTC, feanil commented on playbooks/edx-east/discovery.yml
> -      AUTOMATED_USERS: "{{ DISCOVERY_AUTOMATED_USERS | default({}) }}"
The defaults in `playbooks/roles/edx_django_service/defaults/main.yml` is just an example.  DISCOVERY_AUTOMATED_USERS needs to exist as a variable because that is what we override in our internal config to define all the various commands that the automated user is allowed to run.

2017-06-06 16:53 UTC, clintonb commented on playbooks/edx-east/discovery.yml
> -      AUTOMATED_USERS: "{{ DISCOVERY_AUTOMATED_USERS | default({}) }}"
Restored. In the future should we consider moving the overrides in edx-internal to configuration? What about the override makes it edX-specific/private?

2017-06-06 18:12 UTC, clintonb commented
Related PRs
* Add OAuth URLs to edx-internal: https://github.com/edx/edx-internal/pull/95
* Update pipelines to use loadtest-<play> branch for edx-internal: https://github.com/edx/edx-gomatic/pull/341

2017-06-06 18:14 UTC, clintonb commented
@feanil ready for final review
FYI @edx/learner

2017-06-06 18:20 UTC, jibsheet commented on playbooks/edx-east/discovery.yml
> -      AUTOMATED_USERS: "{{ DISCOVERY_AUTOMATED_USERS | default({}) }}"
We should be able to define SERVICE_AUTOMATED_USERS as an empty dictionary and override in internal.  The dictionary contains public ssh keys and commands we run in production, so is not good for public config.

2017-06-07 19:21 UTC, feanil approved these changes

2017-06-09 15:50 UTC, clintonb commented
I will merge/deploy this on Monday since I don't have time/attention to dedicate to debugging if anything goes wrong...not that anything will go wrong.

2017-06-13 16:47 UTC, merged