Add optional fallback DNS servers to resolvconf
openedx-unsupported/configuration pull request #3872
Opened 2017-05-17 23:06 UTC by bdero

This change allows for optionally adding a list of fallback DNS servers for resolvconf. This is useful when using base images that don't have a terribly reliable DNS configuration out of the box (for example, OVH images default to using OVH's DNS, but we've seen occasional availability issues).

If the `COMMON_FALLBACK_DNS_SERVERS` var is not overridden, this should normally result in no difference. I've added the resolvconf package explicitly to the package install lists, but I believe it's safe to assume that the vast majority of base images people are running Open edX on should already have resolvconf pre-installed.

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] ~~Are you adding any new default values that need to be overridden when this change goes live? If so:~~
    - [ ] ~~Update the appropriate internal repo (be sure to update for all our environments)~~
    - [ ] ~~If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.~~
    - [x] Add an entry to the CHANGELOG.
  - [ ] Have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?

2017-05-17 23:06 UTC, edx-webhook commented
Thanks for the pull request, @bdero! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=3872&repo=edx%2Fconfiguration"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-05-17 23:07 UTC, edx-webhook commented
Thanks for the pull request, @bdero! I've created [OSPR-1770](https://openedx.atlassian.net/browse/OSPR-1770) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

2017-06-27 18:29 UTC, gsong commented
@edx/devops Please chime in on this PR when you get the chance. Thanks.

2017-07-03 22:49 UTC, bdero commented
@edx/devops gentle bump :)

2017-07-11 20:59 UTC, e0d requested changes
We like to avoid handlers if at all possible.

Did you consider making this a separate role?  I'm on the fence, but leaning toward preferring that as there's an additional OS package required.

2017-07-12 21:47 UTC, bdero commented
@e0d I'm totally fine with changing the network restart to be a regular task. I've hit a couple of awful corner cases with them in legacy versions of Ansible, but I'm curious what the reason is for avoiding handlers now?

I think resolvconf is very likely to be already installed on any supported OS already, but I've tossed it in the package lists for good measure. I didn't make this a separate role mostly because the default case should result in no behavior change.

2017-07-18 23:05 UTC, bdero commented
@e0d Do you have any other review comments for this change?

2017-08-15 15:00 UTC, gsong commented
@edx/devops Are we interested in including this? If so, I'll ask @bdero to resolve the conflict.

2017-08-17 16:32 UTC, e0d commented
@gsong this change looks good to me :+1: @bdero sorry for the delays, but please fix the conflict and we'll push it through.

2017-08-17 19:04 UTC, bdero commented
@e0d Thanks! Conflict resolved.

2017-09-07 07:20 UTC, haikuginger commented
@bdero, I'm running into issues when trying to deploy with this because `restart networking` isn't set up as a handler when the previous play attempts to notify it.

2017-09-07 19:28 UTC, bdero commented
@haikuginger Thanks, fixed!

2017-09-25 15:46 UTC, jdmulloy requested changes

2017-09-25 15:46 UTC, jdmulloy commented on playbooks/roles/common/tasks/main.yml
> +  lineinfile:
There is an issue with using lineinfile for this. Once a DNS server is added, it will never be removed, even if it's removed from the ```COMMON_FALLBACK_DNS_SERVERS``` list. 

For example if you run with ```COMMON_FALLBACK_DNS_SERVERS = [ '8.8.8.8' ]``` and then later change it to ```COMMON_FALLBACK_DNS_SERVERS = [ '8.8.4.4' ]```, /etc/resolvconf/resolv.conf.d/tail will then have the following contents.

```
nameserver 8.8.8.8
nameserver 8.8.4.4
```

There is also no guarantee of the ordering. I would suggest using a template for /etc/resolvconf/resolv.conf.d/tail, so that the nameserver lines exactly match the contents and order of ```COMMON_FALLBACK_DNS_SERVERS```

2017-09-25 15:46 UTC, jdmulloy commented on playbooks/roles/common/tasks/main.yml
> +    name: networking
I would suggest restarting the resolvconf service, since it shouldn't be necessary to restart networkring and all dependent services to apply these changes.

Additionally you should use a when clause on this task so that it only runs when there is a change. You'll need to add a register variable to the task above that changes the setting. It will look something like this.
```
- name: Add fallback DNS servers to resolvconf
  lineinfile:
    dest: /etc/resolvconf/resolv.conf.d/tail
    line: "nameserver {{ item }}"
    create: yes
    state: present
  with_items: "{{ COMMON_FALLBACK_DNS_SERVERS }}"
  register: resolvconf_tail

- name: restart resolvconf
  service:
    name: resolvconf
    state: restarted
  when: resolvconf_tail|changed
```

2017-09-25 22:07 UTC, bdero commented on playbooks/roles/common/tasks/main.yml
> +  lineinfile:
Ah, great catch. Thanks! I've made this fix.

2017-09-25 22:07 UTC, bdero commented on playbooks/roles/common/tasks/main.yml
> +    name: networking
Both good suggestions, thank you. I've added these changes.

2017-09-25 22:13 UTC, bdero commented
@jdmulloy Thanks for the review! I've addressed your comments and this is ready for another round.

2017-09-25 23:27 UTC, bdero commented
The build failure appears to be due to [this Ansible bug](https://github.com/ansible/ansible/issues/19013). The fix is to apply [this change](https://github.com/ansible/ansible-modules-core/pull/5487). The simple fix for this is to upgrade to at least Ansible 2.2.1, which I verified contains this change, although the [changelog](https://github.com/ansible/ansible/blob/devel/CHANGELOG.md#221-the-battle-of-evermore---2017-01-16) doesn't mention it.

Note that 2.2.0 -> 2.2.1 should be a pretty safe upgrade as it's a bug fix release, and also fixes a serious vulnerability where a compromised host with a playbook running over it could arbitrarily execute code on the machine running the playbook.

Thoughts? @jdmulloy @e0d

2017-09-26 14:54 UTC, jdmulloy commented
@bdero I'm in favor of bumping Ansible to 2.2.1. Can you update requirements.txt so that Travis will rerun with 2.2.1?

2017-09-26 14:56 UTC, jdmulloy requested changes

2017-09-26 14:56 UTC, jdmulloy commented on playbooks/roles/common/templates/resolvconf_tail.j2
> +{% for dns in COMMON_FALLBACK_DNS_SERVERS %}
This is a nitpick. Can you change the variable from `dns` to `dns_server` for clarity?

2017-09-26 23:03 UTC, bdero commented on playbooks/roles/common/templates/resolvconf_tail.j2
> +{% for dns in COMMON_FALLBACK_DNS_SERVERS %}
Added this change :+1:

2017-09-26 23:31 UTC, feanil commented
@bdero @jdmulloy please remove the Ansible version bump.  There is a know issue with the newer version of ansible that we're waiting to fix before we bump up.  It doesn't handle certain AWS init process well.

2017-09-26 23:50 UTC, bdero commented
@feanil @jdmulloy Removed the bump. Would you be cool with updating the docker test container to have resolvconf pre-installed?
I don't think it's currently possible to add any new packages to `common_debian_pkgs` (and pass CI) unless we update the test container in advance due to the bug mentioned [here](https://github.com/edx/configuration/pull/3872#issuecomment-332042123).

2017-09-27 00:21 UTC, feanil commented
@bdero that sounds fine, can you add that as a separate PR, we can merge that in and push a new common container up.

2017-09-28 17:21 UTC, bdero commented
@feanil Alright, I added resolvconf in a separate PR: https://github.com/edx/configuration/pull/4116

2017-11-03 19:35 UTC, nedbat commented
Feanil's comment on #4116 says we are still waiting for other infrastructure work to unblock this.

2017-12-21 19:48 UTC, nedbat commented
@feanil @bdero any update on this?

2018-02-26 21:47 UTC, nedbat commented
@bdero What's the status of this? It's on the Hawthorn page, but nothing's happened in a while.

2018-02-26 21:58 UTC, bradenmacdonald commented
@nedbat Since @bdero recently moved on to a new job, @smarnach will take over this PR on our end. I believe that both this PR and https://github.com/edx/configuration/pull/4116 are waiting for an update from @feanil as to whether or not we can merge them.

2018-03-16 16:31 UTC, smarnach commented
@nedbat @feanil Any updates here?  I rebased this PR and #4116, and it would be great if we could get this change into Hawthorn.

2018-05-20 06:06 UTC, pomegranited commented
@smarnach  Travis tests are failing here, could you please address?

2018-05-21 09:36 UTC, smarnach commented
@pomegranited No, I can't. :)  See the discussion here and on #4116.  The failing tests are what have been blocking this ticket for so long, but they need to be addressed by edX.

2018-05-21 12:34 UTC, pomegranited commented
@smarnach Sorry for the misguided pings!  I saw the tests pass on https://github.com/edx/configuration/pull/4563, and so hoped the issue here was resolved too.

2018-07-11 08:39 UTC, smarnach commented
@feanil Do you have any suggestions how we could move this forward?

2018-09-10 11:20 UTC, smarnach commented
Just to make the state of this PR clearer, it is currently blocked on #4116, and the tests can't be fixed until that PR gets merged.

2019-02-12 17:46 UTC, SSPJ commented
@natabene Same question as #4116 , just asking for the status of getting these PRs merged. Thanks.

2019-02-14 04:02 UTC, natabene commented
@SSPJ I don't think there are updates, but let me double-check and post here.

2019-02-14 17:36 UTC, natabene commented
@SSPJ Not done yet, but don't lose hope.

2019-02-14 17:41 UTC, SSPJ commented
Thanks, @natabene . I'll check back in later.

2019-04-16 17:08 UTC, natabene commented
@SSPJ Great news, ansible upgrade finished.

2019-05-06 14:50 UTC, SSPJ commented
@natabene I'm not 100% sure but I don't think the test failures here and on #4116 are related to the code changes. Would you be able to have someone take a look or restart the jobs?

2019-05-06 16:50 UTC, natabene commented
@SSPJ Sure, I just restarted.

2019-05-21 20:47 UTC, edx-webhook commented
Thanks for the pull request, @bdero! I've created [OSPR-3505](https://openedx.atlassian.net/browse/OSPR-3505) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

2019-05-24 17:11 UTC, natabene commented
@SSPJ Do you think this is ready for review or do you want to attempt to address the failing test still?

2019-05-28 16:44 UTC, SSPJ commented
@natabene Thanks for checking in! Sorry for the delay on our end. I would like to see if I can discover why the tests are failing before getting a review, but I won't have time this week. I will post a status update as soon as I am able to do that (or am unable to do that, as case may be).

2019-07-15 15:21 UTC, SSPJ commented
@natabene Sorry for the long radio silence on here and #4116 . I do not know what is causing

```
Unpacking resolvconf (1.78ubuntu6) ...
Processing triggers for systemd (229-4ubuntu21.21) ...
Setting up resolvconf (1.78ubuntu6) ...
ln: cannot remove '/etc/resolv.conf': Device or resource busy
dpkg: error processing package resolvconf (--configure): subprocess installed post-installation script returned error exit status 1
Processing triggers for systemd (229-4ubuntu21.21) ...
Errors were encountered while processing:
 resolvconf
```

Can I get a reviewer for a second opinion? It might be something obvious I am missing here.

2019-07-17 17:20 UTC, natabene commented
@feanil Could you help us out here?

2019-07-17 19:31 UTC, feanil commented
@SSPJ is this happening as a part of the package installation step or when you try to restart after updating the configuration?

2019-07-17 20:03 UTC, SSPJ commented
Hi @feanil , this is happening as part of the failing Travis CI build. [Example](https://travis-ci.com/edx/configuration/jobs/216149434).

2019-07-22 21:58 UTC, bradenmacdonald commented
> I do not know what is causing
> ln: cannot remove '/etc/resolv.conf': Device or resource busy
> happening as part of the failing Travis CI build.

@SSPJ  It's a bug when trying to install old `resolvconf` packages in a docker environment. https://stackoverflow.com/a/45908415 has a possible fix and a link to more info.

2019-11-25 21:21 UTC, natabene commented
@bdero Please let me know whether you plan to continue working on this.

2019-11-26 15:56 UTC, fredsmith approved these changes

2019-12-02 00:54 UTC, swalladge commented
Warning: do not merge; the related PR (https://github.com/edx/configuration/pull/4116) installing resolveconf is breaking devstack provisioning. See also @bradenmacdonald's comment above for a possible solution.

2019-12-03 03:10 UTC, natabene commented
@swalladge Please let me know steps 3 and 4 are done.

2019-12-05 02:03 UTC, bdero commented
@natabene Hey! I actually haven't been actively working on Open edX for a while (see https://github.com/edx/configuration/pull/3872#issuecomment-368665507). Please direct questions about this PR to OpenCraft, who own the repository where the branch connected to this PR resides. Based on recent comments here and in #4116, I assume @swalladge and @SSPJ currently own these. You might already be on the same page though (if so, sorry for the noise).

@swalladge These PRs were separated in response to this comment by Feanil -- right around the time when we originally found and fixed some Docker devstack-related issues. I think you may have already seen it based on your last comment, but just in case: https://github.com/edx/configuration/pull/3872#issuecomment-332905295

FWIW, we actually did verify these changes against Docker devstack build at the time, but that devstack was _not_ ready for prime-time and I'm sure a lot has changed, to say the least.

2019-12-05 02:36 UTC, swalladge commented
@bdero Thanks for checking in! I don't doubt that it was tested at the time, but unfortunately a lot has changed since so it no longer works. :(

I think we're on the same page now - we're still not exactly sure how the CI works in these cases, but at least we have an updated attack plan. :)

2019-12-12 17:43 UTC, SSPJ commented
@natabene Okay to close this PR. This is my last week at OpenCraft and I was not able to find anyone able to take it over.

2019-12-12 18:28 UTC, closed without merging

2019-12-12 18:28 UTC, edx-webhook commented
@bdero Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/3872&entry.1484655318=https://github.com/bdero&entry.752974735=2017-05-17+23:06&entry.1917517419=2019-12-12+18:28&entry.2133058324=No) so we can improve your experience in the future.