Added yarn to IDAs
openedx-unsupported/configuration pull request #3877
Opened 2017-05-22 14:47 UTC by clintonb

The credentials, discovery, ecommerce, and edx_django_service roles now include yarn as a replacement for npm.

2017-05-22 14:48 UTC, clintonb commented
Currently, only the Credentials Service uses yarn: https://github.com/edx/credentials/pull/243.

2017-05-22 14:48 UTC, clintonb commented
FYI @edx/learner 
@edx/devops please review/advise on the new role.

2017-05-22 15:23 UTC, rlucioni approved these changes
Looks like you'll have to rebuild this once https://github.com/edx/credentials/pull/246 lands to get a clean build.

2017-06-02 13:32 UTC, feanil requested changes

2017-06-02 13:32 UTC, feanil commented on playbooks/roles/yarn/tasks/main.yml
> +  become: yes
We generally use `true` instead of `yes`

2017-06-02 13:32 UTC, feanil commented on playbooks/roles/yarn/tasks/main.yml
> +  become_user: root
You don't need this.  By default `become: true` will become root.

2017-06-02 13:32 UTC, feanil commented on playbooks/roles/yarn/tasks/main.yml
> +- name: "Yarn | Ensure Debian sources list file exists"
Use `apt_repository` instead?

http://docs.ansible.com/ansible/apt_repository_module.html

2017-06-02 13:32 UTC, feanil commented on playbooks/roles/yarn/tasks/main.yml
> +    name: yarn
Pull this out into `defaults/main.yml` as a list that's passed into here.  That's a general pattern we use and helps keep things flexible.

2017-06-21 20:21 UTC, thallada commented
We are interested in using this in Insights too!

2017-06-21 20:29 UTC, clintonb commented
@thallada I'm holding off on this since Node 8.x and npm 5 incorporate similar changes. My preference is to not include an extra dependency if one we already have achieves the same goals. If you want to move forward with `yarn`, feel free to take over this branch.

2017-06-21 21:38 UTC, thallada commented
I didn't realize npm 5 had all those features. I'll upgrade to that instead, thanks.

2017-06-23 16:40 UTC, feanil commented
@clintonb please close and delete the branch if we're done with it.

2017-06-23 16:41 UTC, clintonb commented
Note to future viewers: we will use Node 8.x, once an LTS is released, and npm 5 which implements similar features.

2017-06-23 16:44 UTC, closed without merging