Add feature flag for footer language selector
openedx-unsupported/configuration pull request #3882
Opened 2017-05-23 21:38 UTC by amangano-edx

Adds a new feature flag for the footer language selector, added in https://github.com/edx/edx-platform/pull/15133
 
Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] Have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?

2017-05-23 21:40 UTC, amangano-edx commented
@edx/devops, is this all that needs to be done to ensure this flag gets set to `true` in production?

2017-05-23 21:47 UTC, amangano-edx commented
Actually, I think it makes more sense to default to false. @edx/devops , how can I make sure that the default is overridden and set to `true` in production?

2017-05-24 14:16 UTC, amangano-edx commented
@edx/devops is the 'Ops Ansible Testing Checklist' required for a change like this?

2017-05-24 19:48 UTC, jibsheet requested changes
You have two flags in https://github.com/edx/edx-platform/pull/15133/files you should expose both of them here (Setting both to false seems reasonable)

2017-05-24 19:49 UTC, jibsheet commented
@amangano-edx no need for the checklist, make a PR here adding your flag set to TRUE to the existing FEATURES dictionary in each environment https://github.com/edx/edx-internal (make sure you touch edge-internal if it also needs to change).

2017-05-24 19:56 UTC, amangano-edx commented
@jibsheet I added the other setting. Please look again when you have a chance.

2017-05-24 20:22 UTC, jibsheet approved these changes

2017-05-25 14:47 UTC, merged