Updated PhantomJs version
openedx-unsupported/configuration pull request #3893
Opened 2017-06-02 07:20 UTC by aamishbaloch

Configuration Pull Request
Update PhantomJs version as the version (1.9.8) uses an old version of JavaScriptCore. That causes some tests to fail on PhantomJs. The issue is now resolved in the version (2.1.1).

----------------------------------------------------------------------------------------------------

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] Have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?

2017-06-02 19:33 UTC, jzoldak commented
@aamishbaloch I am in the process of reviewing this PR. I'll need to make a new jenkins worker with this change, to verify that there will be no problems there. I will be able to do that early next week.

2017-06-06 17:08 UTC, jzoldak commented
I've created a jenkins worker with the changes in the configuration repo, and used it to run the accessibility tests. They all passed.
I'm currently re-running the tests to make sure that there are no flakiness issues. I will keep this PR posted with status.

2017-06-07 19:15 UTC, jzoldak requested changes
@aamishbaloch - it looks like this change will need more in-depth exploration. I created a new jenkins worker AMI and updated the configuration of the edx-platform-accessibility-master job to use that new version.

Unfortunately the worker is hanging when running the builds, and then timing out.
See for example [#4516](https://build.testeng.edx.org/job/edx-platform-accessibility-master/4516/) which ran successfully with the existing jenkins-worker, and [#4517](https://build.testeng.edx.org/job/edx-platform-accessibility-master/4517/) which ran unsuccessfully with the new phantom2-worker.

In the failure case, you can see from the timestamps that something is hanging. 
```
16:27:42 test_certificates_a11y (common.test.acceptance.tests.lms.test_lms_instructor_dashboard.CertificatesTest) ... ok
17:22:09 test_data_download_a11y (common.test.acceptance.tests.lms.test_lms_instructor_dashboard.DataDownloadsTest) ... Build timed out (after 75 minutes). Marking the build as aborted.
```

Unfortunately the tools team doesn't have time in our current sprint to prioritize troubleshooting this further. If you'd like, we can work together to get you the tools or access that need to dig in yourself. Let me know if you want to do that.

cc: @arizzitano @estute

2017-06-12 09:54 UTC, aamishbaloch commented
@jzoldak thanks for the help. How can I debug this issue as I am unable to reproduce this locally.

2017-06-12 15:11 UTC, estute commented
@aamishbaloch if you are unable to test against an AWS machine, you could create an Ubuntu 16.04 VM, and run the following scripts/plays:
* https://github.com/edx/configuration/blob/master/util/packer/stop-automatic-updates.sh
* https://github.com/edx/configuration/blob/master/util/install/ansible-bootstrap.sh
* https://github.com/edx/configuration/blob/master/playbooks/edx-east/jenkins_worker.yml

This will give you an system equivalent to what we use for our tests. To run the accessibility tests, look at the following script:
https://github.com/edx/edx-platform/blob/master/scripts/accessibility-tests.sh

2017-06-14 11:26 UTC, aamishbaloch commented
@estute just wanted to know from which user should I run this script "accessibility-tests.sh". As I am facing slight issues like:
`scripts/jenkins-common.sh: line 5: /edx/app/edxapp/jenkins_env: No such file or directory`

2017-06-14 16:21 UTC, estute commented
@aamishbaloch This should be run as the 'jenkins' user. The jenkins_env file is in jenkins $HOME

2017-06-15 07:37 UTC, aamishbaloch commented
@estute Unfortunately, I didn't have any Jenkins user. Should I expect any of the above mention scripts to create a jenkins user or we have any other way of creating that?

2017-06-15 16:02 UTC, estute commented
@aamishbaloch the jenkins user is created when you run the jenkins_worker play mentioned above.

In particular, it runs this https://github.com/edx/configuration/blob/master/playbooks/roles/jenkins_worker/tasks/system.yml

2017-06-16 07:39 UTC, aamishbaloch commented
@estute I guess I am having an issue in running **jenkins_worker.yml** successfully. That could be the reason I am not getting the user _Jenkins_. It is throwing a warning as below:
```
 [WARNING]: Failure using method (v2_playbook_on_stats) in callback plugin (</edx/app/edx_ansible/edx_ansible/playbooks/callback_plugins/task_timing.CallbackModule object at 0x7f4efc163350>): 'NoneType'
object has no attribute 'stop'
```

2018-05-04 10:34 UTC, closed without merging