ENT-435: Enable third_party_auth flag by default
openedx-unsupported/configuration pull request #3911
Opened 2017-06-13 20:14 UTC by shrlyhe

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] Have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?

2017-06-13 22:49 UTC, feanil commented
Why enable 3rd party auth by default?  Will this work without any auth providers defined?

2017-06-14 12:50 UTC, brittneyexline commented
@feanil this is something I requested as part of a series of changes for Shirley's summer project around improving our development environments out of the box. This is just one of a number of small things we have to configure every time we reprovision an environment, and it acts as a gate to configuring auth providers. If it's on and no auth providers are added, then I don't think it changes behavior. If there is a better way to get this configured by default for the things we provision (vagrant, docker, sandboxes) without impacting others, we're happy to explore.

2017-06-15 14:39 UTC, brittneyexline approved these changes
We've discussed this in person, but I just wanted to add that this is already turned on in all of our production environments, and that it has no behavioral impact unless providers are configured.

2017-06-15 14:43 UTC, brittneyexline commented
@shrlyhe it looks like you need to go through the testing instructions linked in the description of this ticket - it might make sense to add the changes for https://github.com/edx/configuration/pull/3916 into this PR and close the other one, and execute the testing with both changes.

2017-06-15 14:44 UTC, brittneyexline requested changes
See above comment about testing and consolidating PRs.

2017-06-15 19:54 UTC, fredsmith approved these changes

2017-06-15 19:55 UTC, merged