script to find asgs and active instances for clusters
openedx-unsupported/configuration pull request #3938
Opened 2017-06-22 15:20 UTC by hchen15

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] Have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?

2017-06-22 18:28 UTC, feanil requested changes

2017-06-22 18:28 UTC, feanil commented on util/cluster_instance_monitoring.py
> +import pprint
You can just do `from pprint import pprint` and then you don't have to instantiate your own pretty printer.

2017-06-22 18:28 UTC, feanil commented on util/cluster_instance_monitoring.py
> +    pp = pprint.PrettyPrinter()
See above comment.  You should be able to delete this line.

2017-06-22 18:28 UTC, feanil commented on util/cluster_instance_monitoring.py
> +    f = open(cluster_file)
Use a context manager instead.  See the last paragraph of [this section](https://docs.python.org/2/tutorial/inputoutput.html#methods-of-file-objects) if you haven't used them before.

2017-06-22 18:28 UTC, feanil commented on util/cluster_instance_monitoring.py
> +    region = 'us-east-1'
Let's make this a configurable option that can be passed in from the command-line.

2017-06-22 18:28 UTC, feanil commented on util/cluster_instance_monitoring.py
> +    #check to make sure each ASG has at least 1 running instance
You don't need to make sure that each ASG has a instance in it, just that one ASG for a triple has an instance in it.  The case can occur where an ASG doesn't have instances in it because it is currently being terminated.  We don't care about this if there is a second ASG for the same triple that can support traffic.

2017-06-22 18:28 UTC, feanil commented on util/cluster_monitoring_requirements.txt
> +boto3==1.4.4
Any reason that this can't be added to the toplevel requirements file?  I would just add it there instead of making a new file if it's just this.

2017-06-22 21:11 UTC, jibsheet commented
git rm the requirements file you added, it's still here but empty.

2017-06-23 16:14 UTC, feanil approved these changes

2017-06-23 16:46 UTC, merged