WIP: Updated language code and cookie for ecommerce
openedx-unsupported/configuration pull request #3950
Opened 2017-06-27 19:01 UTC by BenjiLee

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] Have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?

2017-06-27 19:43 UTC, feanil requested changes

2017-06-27 19:43 UTC, feanil commented on playbooks/roles/ecommerce/defaults/main.yml
> +ECOMMERCE_LANGUAGE_COOKIE_NAME: 'openedx-language-preference
Missing trailing quote.

2017-06-27 19:49 UTC, feanil commented on CHANGELOG.md
> +  - Added `ECOMMERCE_LANGUAGE_COOKIE` which is used to set the django language cookie.
@BenjiLee wrong var name.  Also, maybe the below is a more descriptive entry? Use or adapt if you want:

Added `ECOMMERCE_LANGUAGE_COOKIE_NAME` which is the name of the cookie the ecommerce app looks at for determining the language preference.

2017-06-27 19:54 UTC, feanil approved these changes

2017-06-27 19:57 UTC, feanil approved these changes
Once tests pass, please squash before merging.

2017-06-28 14:34 UTC, bderusha approved these changes

2017-06-28 19:33 UTC, merged