ENT-433: Provision a default admin user for developer environments
openedx-unsupported/configuration pull request #3952
Opened 2017-06-27 20:38 UTC by shrlyhe

Configuration Pull Request
---

Created sandbox here: https://defaultadmin.sandbox.edx.org. Tested changes by logging in as staff, and checking that admin privileges are there. 

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] Have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?

2017-06-28 12:17 UTC, douglashall commented on playbooks/roles/demo/tasks/deploy.yml
> +  when: demo_checkout
Instead of doing this, I think you want to do something similar to what we are doing with the [staff](https://github.com/edx/configuration/blob/3527e8f1c3fd107e233e81adf022914f3b656756/playbooks/roles/demo/defaults/main.yml#L35) user. How about we also define a `demo_admin_user` user that is both staff and superuser (email = admin@example.com, username = admin). Then we can define a `DEMO_CREATE_ADMIN_USER` variable much like the `DEMO_CREATE_STAFF_USER` defined [here](https://github.com/edx/configuration/blob/3527e8f1c3fd107e233e81adf022914f3b656756/playbooks/roles/demo/defaults/main.yml#L14). We can then use that variable in this file to optionally add the admin user to the list of users to create (like we are doing with the staff user [above](https://github.com/edx/configuration/pull/3952/files#diff-0750bfc060595a366d62dc4b8f47671cR19).

2017-06-28 14:27 UTC, douglashall commented on playbooks/edx-east/manage_edxapp_users_and_groups.yml
> +
Can you revert the addition of this extra line?

2017-06-28 14:28 UTC, douglashall approved these changes

2017-06-28 14:50 UTC, shrlyhe commented
I rebuilt the sandbox with the new changes, but I'm not able to log in with the new admin user

2017-06-28 15:07 UTC, feanil submitted a review, later dismissed
@shrlyhe I'm generally opposed to this idea,  this role gets built in a lot of different cases and having a user that has admin level access with a know password seems like a bad idea from a security perspective.  What's the motivation here?

2017-06-28 15:26 UTC, shrlyhe commented
@feanil My reasoning is that since the demo role sets up users in multiple environments, it could be a good place to provision a default admin there. Is there a better place to add a user with admin level access, or another fix that can be done?

2017-06-28 16:08 UTC, feanil commented
@shrlyhe  I'm more curious about what you need the admin level user for?  What's the problem that you're trying to solve?

2017-06-28 17:02 UTC, shrlyhe commented
@feanil I’m trying to work on improving developer environments out of box. Since a management command needs to be run every time an environment is provisioned, it would be helpful for a user to automatically be assigned privileges

2017-07-03 11:59 UTC, feanil commented
@shrlyhe it looks like your rebase isn't correct and pulled in commits that have already been merged to master.

2017-07-05 20:05 UTC, brittneyexline commented on playbooks/roles/demo/defaults/main.yml
> +  - email: 'staff@example.com'
looks like you have an extra '-' here, maybe that is what is causing your failure?

2017-07-06 08:14 UTC, asadiqbal08 commented on playbooks/roles/demo/tasks/deploy.yml
> +  when: not SANDBOX_CREATE_ADMIN_USER
@shrlyhe  where is this `SANDBOX_CREATE_ADMIN_USER` defined?

2017-07-06 12:43 UTC, shrlyhe commented on playbooks/roles/demo/tasks/deploy.yml
> +  when: not SANDBOX_CREATE_ADMIN_USER
@asadiqbal08 I defined it in the sandbox-internal repo

2017-07-06 19:37 UTC, shrlyhe commented
@feanil I made some changes and rebuilt the sandbox, which seems to have passed: https://tools-edx-jenkins.edx.org/job/sandboxes/job/CreateSandbox/2246/

2017-07-07 17:48 UTC, fredsmith requested changes

2017-07-07 17:48 UTC, fredsmith commented on playbooks/roles/demo/tasks/deploy.yml
> +  when: not SANDBOX_CREATE_ADMIN_USER
@shrlyhe you should set a default in the defaults/main.yml

2017-07-07 18:02 UTC, shrlyhe commented
@fredsmith should the `SANDBOX_CREATE_ADMIN_USER` be removed from sandbox-internal then?

2017-07-10 08:03 UTC, asadiqbal08 commented on playbooks/roles/demo/tasks/deploy.yml
> +- name: build staff, admin, and test user list
Can we use something generic instead of `admin` here? As `SANDBOX_EDXAPP_USERS` may contain other user lists as well.

2017-07-10 08:04 UTC, asadiqbal08 commented on playbooks/roles/demo/tasks/deploy.yml
> +    demo_test_admin_and_staff_users: "{{ demo_test_and_staff_users }}"
`admin` in `demo_test_admin_and_staff_users` would contain any admin user if `not SANDBOX_CREATE_ADMIN_USER` ?

2017-07-11 14:58 UTC, shrlyhe commented
@fredsmith could you take a second look when you get a chance?

2017-07-12 13:30 UTC, fredsmith approved these changes

2017-07-12 13:57 UTC, merged

2017-07-13 13:23 UTC, jibsheet commented
@shrlyhe Your merge broke the nightly sandbox from scratch build.
https://tools-edx-jenkins.edx.org/job/Sandboxes/job/CreateSandbox/2482/console

Did you forget to merge other branches related to this?

2017-07-13 13:27 UTC, shrlyhe commented
@jibsheet I'm waiting for a merge on my PR in sandbox-internal

2017-07-13 14:25 UTC, jibsheet commented
@shrlyhe Please don't merge branches out of order, you cause failures that we have to spend time looking into in case they're legitimate failures.

2017-07-13 14:55 UTC, brittneyexline commented
@jibsheet we apologize for the confusion - we had gotten approval on both PRs but didn't realize that the other one couldn't be merged by us and had to be merged by a member of devops.

2017-07-17 19:14 UTC, clintonb commented
This seems to be the cause of https://github.com/edx/devstack/issues/186.