Add check-ses-limits python script
openedx-unsupported/configuration pull request #3953
Opened 2017-06-28 16:20 UTC by jdmulloy

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] Have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?

2017-06-28 18:04 UTC, hchen15 approved these changes

2017-06-28 18:08 UTC, feanil commented
What's the value of leaving the number of thresholds open-ended?  Why not just take a warn threshold and a critical threshold explicitly?

2017-06-28 18:29 UTC, jdmulloy commented
@feanil Probably not much value if we won't be wanting to add more thresholds. I could change it to take a warn and crit threshold via options. If I do that should I have defaults or require them to be provided?

2017-06-29 18:25 UTC, feanil requested changes

2017-06-29 18:25 UTC, feanil commented on util/jenkins/check-ses-limits.py
> +parser.add_argument('-c', '--crit', required=True, type=float,
If we're going to have a word let's just make it the whole word `--critical`

2017-06-29 18:25 UTC, feanil commented on util/jenkins/check-ses-limits.py
> +    print("ERROR: Warning threshold (" + str(args.warn) +
Use, `str.format` instead of string concatenation.

2017-06-29 18:25 UTC, feanil commented on util/jenkins/check-ses-limits.py
> +    out_str = str(current) + "/" + str(limit) + " (" + str(percent) + "%)"
Use `str.format` instead of string concatenation.

2017-06-29 18:25 UTC, feanil commented on util/jenkins/check-ses-limits.py
> +        print(region + " " + out_str + " - CRITICAL!")
Use `str.format` instead of string concatenation.

2017-06-29 18:25 UTC, feanil commented on util/jenkins/check-ses-limits.py
> +        print(region + " " + out_str + " - WARNING!")
Use `str.format` instead of string concatenation.

2017-06-29 18:25 UTC, feanil commented on util/jenkins/check-ses-limits.py
> +parser = argparse.ArgumentParser()
Put all of the logic inside a `if __name__ == "__main__":` block.
http://ibiblio.org/g2swap/byteofpython/read/module-name.html

2017-06-30 15:03 UTC, feanil approved these changes

2017-06-30 20:04 UTC, merged