Update neo4j to 3.2.1
openedx-unsupported/configuration pull request #3968
Opened 2017-07-06 16:07 UTC by adampalay

Configuration Pull Request
---

@fredsmith here's a PR to upgrade neo4j from 3.0.3—its current version—to 3.2.2, the most recent. As part of the upgrade, there are few things that I think will be prudent to do:

* As part of the [upgrade](https://neo4j.com/guides/upgrade/), neo4 changes the way it stores data. In order to mitigate the risk of the the updated data storage format, it makes a backup of the data before it does anything. As a result, we need to make sure we have 2x the storage that neo4j is currently taking up.
* It probably doesn't hurt to download a backup of the database before we run the update anyway

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] ~Update the appropriate internal repo (be sure to update for all our environments)~
    - [ ] ~If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.~
    - [ ] Add an entry to the CHANGELOG.
  - [ ] Have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?

2017-07-06 16:09 UTC, adampalay commented
I've tested this upgrade locally, using a docker image of neo4j with a few local courses. I also tested this upgrade on a sandbox, but without data in it.

2017-07-06 16:45 UTC, adampalay commented on playbooks/roles/neo4j/tasks/main.yml
> +- name: set log dir for neo4j
this shouldn't be here :)

2017-07-06 17:33 UTC, adampalay commented
@fredsmith  this is ready for a new review.

2017-07-07 20:00 UTC, fredsmith requested changes

2017-07-07 20:00 UTC, fredsmith commented on playbooks/roles/neo4j/tasks/main.yml
> +- name: turn off authentication (we're accessing neo4j from behind a private vpn)
@adampalay if we're expecting people outside of edx to be using this, we should put this behind a when: feature flag and override it in configuration internal.  I think the default should be that authentication is on.

2017-07-07 20:02 UTC, adampalay commented on playbooks/roles/neo4j/tasks/main.yml
> +- name: turn off authentication (we're accessing neo4j from behind a private vpn)
@fredsmith fair enough.

2017-07-07 20:16 UTC, adampalay commented
@fredsmith this better? (corresponding branch: https://github.com/edx/edx-internal/compare/neo4j-server-auth?expand=1)

2017-07-10 12:21 UTC, fredsmith approved these changes

2017-07-10 13:41 UTC, adampalay commented
@fredsmith , thanks for the 👍 . I'm going to hold off merging this now until [OPS-2265](https://openedx.atlassian.net/browse/OPS-2265) is completed. Let me know how I can assist on that ticket.

2017-07-25 18:45 UTC, adampalay commented
@fredsmith , updated and rebased, just a heads up!

2017-07-25 18:52 UTC, merged