Add a CONTRIBUTING.md
openedx-unsupported/configuration pull request #4005
Opened 2017-07-21 15:10 UTC by jibsheet

https://help.github.com/articles/adding-support-resources-to-your-project/

I took Ned's boilerplate

@nedbat @gsong Any objections / thoughts about this?

2017-07-21 15:10 UTC, jibsheet commented
@edx/devops please review

2017-07-21 15:48 UTC, nedbat requested changes

2017-07-21 15:48 UTC, nedbat commented on CONTRIBUTING.md
> +GitHub issues are not the best place to get support with OpenEDX. The mailing list and Slack channels are explained here: http://open.edx.org/getting-help. If it turns out there's a bug in the config
Let's spell it properly: "Open edX".

Also, this isn't about Contributing exactly.... though I think it is a good message to get in front of people.

2017-07-21 15:57 UTC, gsong commented on CONTRIBUTING.md
> +GitHub issues are not the best place to get support with OpenEDX. The mailing list and Slack channels are explained here: http://open.edx.org/getting-help. If it turns out there's a bug in the config
I would word it even more strongly:

> **Do not** use GitHub issues for Open edX support. Instead, use the mailing list or Slack channels as explained in [Getting Help](https://open.edx.org/getting-help#where_to_ask_questions). If you do find a bug, feel free to open an issue or PR in this repo.

2017-07-21 16:07 UTC, jibsheet commented
Agreed - not 100% contributing, but I saw their blog and thought "great, maybe I can redirect even more people".  Thanks for the edit requests.

2017-08-03 17:58 UTC, nedbat commented on CONTRIBUTING.md
> +GitHub issues are not the best place to get support with OpenEDX. The mailing list and Slack channels are explained here: http://open.edx.org/getting-help. If it turns out there's a bug in the config
It's still not spelled right... :(

2017-08-03 18:02 UTC, jibsheet commented
@nedbat hopefully better now

2017-08-04 15:33 UTC, nedbat commented
"Open edX"

2017-08-10 13:50 UTC, jibsheet commented
@nedbat Ope NedX, right?  I think it's right this time.

2017-08-10 15:21 UTC, nedbat approved these changes

2017-08-10 15:21 UTC, merged