add mongo to system packages for tools-jenkins
openedx-unsupported/configuration pull request #4012
Opened 2017-07-24 19:18 UTC by hchen15

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] Have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?

2017-07-24 19:21 UTC, feanil commented on playbooks/roles/tools_jenkins/defaults/main.yml
> +MONGODB_APT_KEY: "7F0CEB10"
Why is this in the tools-jenkins role? can we make a mongo-client role that encapsulates this that tools_jenkins depends on?

2017-07-24 20:39 UTC, feanil requested changes

2017-07-24 20:39 UTC, feanil commented on playbooks/roles/mongo_client/defaults/main.yml
> +mongo_version: 3.2.12
Change this to `mongo_client_version`

2017-07-24 20:39 UTC, feanil commented on playbooks/roles/mongo_client/defaults/main.yml
> +MONGODB_REPO: "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse"
Change this to `MONGO_CLIENT_MONGODB_REPO`

2017-07-24 20:39 UTC, feanil commented on playbooks/roles/mongo_client/defaults/main.yml
> +MONGODB_APT_KEYSERVER: "keyserver.ubuntu.com"
Change this to `MONGO_CLIENT_MONGODB_APT_KEYSERVER`

2017-07-24 20:39 UTC, feanil commented on playbooks/roles/mongo_client/defaults/main.yml
> +MONGODB_APT_KEY: "7F0CEB10"
Change this to `MONGO_CLIENT_MONGODB_APT_KEY`

2017-07-25 13:28 UTC, fredsmith approved these changes

2017-07-25 14:20 UTC, feanil approved these changes

2017-07-25 14:20 UTC, merged