SSO Broken for sandbox
openedx-unsupported/configuration pull request #4036
Opened 2017-08-08 11:14 UTC by ahsan-ul-haq

LEARNER-2107

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] Have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?

2017-08-08 12:04 UTC, clintonb requested changes
Ensure that every OAuth/JWT-related variable is updated to rely on the common vars: https://github.com/edx/configuration/blob/master/playbooks/roles/common_vars/defaults/main.yml#L213-L221

2017-08-08 12:04 UTC, clintonb commented on playbooks/roles/credentials/defaults/main.yml
>  CREDENTIALS_JWT_AUDIENCE: '{{ EDXAPP_JWT_AUDIENCE | default("SET-ME-PLEASE") }}'
The audience and secret key need to be updated, too.

2017-08-08 12:09 UTC, ahsan-ul-haq commented on playbooks/roles/credentials/defaults/main.yml
>  CREDENTIALS_JWT_AUDIENCE: '{{ EDXAPP_JWT_AUDIENCE | default("SET-ME-PLEASE") }}'
Couldn't find audience in Ecommerce. Also we don't need to add them in ansible-provision.sh

2017-08-08 12:18 UTC, clintonb requested changes
`CREDENTIALS_SOCIAL_AUTH_EDX_OIDC_ISSUER` should point to `CREDENTIALS_SOCIAL_AUTH_EDX_OIDC_ISSUER`.
`CREDENTIALS_OAUTH_URL_ROOT` should point to `COMMON_OAUTH_URL_ROOT`
`CREDENTIALS_OIDC_LOGOUT_URL` should point to `COMMON_OAUTH_LOGOUT_URL `

Make similar changes for the other IDAs. You'll know you're done when there are no references to edxapp for OAuth or JWT-related variables.

2017-08-08 12:18 UTC, clintonb commented on playbooks/roles/credentials/defaults/main.yml
>  CREDENTIALS_JWT_AUDIENCE: '{{ EDXAPP_JWT_AUDIENCE | default("SET-ME-PLEASE") }}'
Ecommerce doesn't matter here. This should be updated to refer to `COMMON_JWT_AUDIENCE`. The eventual goal is that we have a single place, `common_vars`, to change values for all IDAs.

2017-08-08 12:18 UTC, clintonb commented on playbooks/roles/credentials/defaults/main.yml
>  CREDENTIALS_JWT_SECRET_KEY: '{{ EDXAPP_JWT_SECRET_KEY | default("lms-secret") }}'
`COMMON_JWT_SECRET_KEY`

2017-08-08 12:43 UTC, clintonb commented
Nit: update your commit message to describe the solution (Fixed SSO for sandboxes), not the problem.

2017-08-08 15:21 UTC, jibsheet commented on playbooks/roles/credentials/defaults/main.yml
>  CREDENTIALS_JWT_AUDIENCE: '{{ EDXAPP_JWT_AUDIENCE | default("SET-ME-PLEASE") }}'
Agree with Clinton - if we're going to change one of these vars, we should change them all, otherwise it's just confusing (and prevents us from being able to clean up the tech debt of the old settings)

Will this require secure changes, or are passthrough dummy vars still in place?  I forget what Clinton had us do in the backend.

2017-08-08 16:55 UTC, clintonb commented on playbooks/roles/credentials/defaults/main.yml
>  CREDENTIALS_JWT_AUDIENCE: '{{ EDXAPP_JWT_AUDIENCE | default("SET-ME-PLEASE") }}'
Unsecure defaults were setup by https://github.com/edx/edx-internal/pull/95. Secure overrides were also setup via DEVOPS ticket.

2017-08-09 11:45 UTC, ahsan-ul-haq commented
@clintonb made the suggested changes

2017-08-09 12:06 UTC, clintonb requested changes
Go ahead and squash your commits for the next round. This PR is small, and we don't gain anything from seeing the fixups. Also, I imagine the next round will get approved, and we can merge this.

2017-08-09 12:06 UTC, clintonb commented on playbooks/roles/credentials/defaults/main.yml
> +CREDENTIALS_OAUTH_URL_ROOT: '{{ COMMON_OAUTH_URL_ROOT | default("http://127.0.0.1:8000") }}/oauth2'
Ditch the defaults to avoid confusion and a potential source of bugs. The `common_vars` play will always be used.

2017-08-09 12:06 UTC, clintonb commented on playbooks/roles/ecommerce/defaults/main.yml
> +ECOMMERCE_OAUTH_URL_ROOT: '{{ COMMON_OAUTH_URL_ROOT | default("http://127.0.0.1:8000") }}/oauth2'
Ditch the defaults for these lines, too.

2017-08-09 12:06 UTC, clintonb commented on playbooks/roles/credentials/defaults/main.yml
> +CREDENTIALS_JWT_AUDIENCE: '{{ COMMON_JWT_AUDIENCE | default("SET-ME-PLEASE") }}'
Same as above.

2017-08-09 12:06 UTC, clintonb commented on util/jenkins/ansible-provision.sh
> +COMMON_JWT_ISSUER: "https://${deploy_host}/oauth2"
You want to define `COMMON_OAUTH_BASE_URL` here. Everything else is composed of it. See https://github.com/edx/configuration/blob/master/playbooks/roles/common_vars/defaults/main.yml#L212.

2017-08-09 12:31 UTC, ahsan-ul-haq commented on util/jenkins/ansible-provision.sh
> +COMMON_JWT_ISSUER: "https://${deploy_host}/oauth2"
@clintonb should it stay` http://127.0.0.1:8000` as defined in `common_vars`

2017-08-09 12:33 UTC, clintonb commented on util/jenkins/ansible-provision.sh
> +COMMON_JWT_ISSUER: "https://${deploy_host}/oauth2"
No. `COMMON_OAUTH_BASE_URL: "https://${deploy_host}"`

2017-08-09 12:37 UTC, ahsan-ul-haq commented
@clintonb made the change

2017-08-09 12:57 UTC, clintonb requested changes
Once you've removed the paths, make sure you create a sandbox (with ecommerce and credentials) to actually test these changes.

2017-08-09 12:57 UTC, clintonb commented on playbooks/roles/credentials/defaults/main.yml
> +CREDENTIALS_OAUTH_URL_ROOT: '{{ COMMON_OAUTH_URL_ROOT }}/oauth2'
You don't need a path. See the values of the variables in https://github.com/edx/configuration/blob/master/playbooks/roles/common_vars/defaults/main.yml#L212.

2017-08-09 13:12 UTC, ahsan-ul-haq commented
@clintonb is the change looks fine now?

2017-08-09 13:14 UTC, clintonb approved these changes
Looks good. Please test on a sandbox before merging.

2017-08-09 14:00 UTC, feanil commented on playbooks/roles/ecommerce/defaults/main.yml
> +ECOMMERCE_OAUTH_URL_ROOT: '{{ COMMON_OAUTH_URL_ROOT }}'
You no longer use this variable below, does something else still use it?

2017-08-09 14:00 UTC, feanil commented on playbooks/roles/credentials/defaults/main.yml
> +CREDENTIALS_OAUTH_URL_ROOT: '{{ COMMON_OAUTH_URL_ROOT }}'
You no longer use this variable below, does something else still use it?

2017-08-09 14:25 UTC, ahsan-ul-haq commented on playbooks/roles/credentials/defaults/main.yml
> +CREDENTIALS_OAUTH_URL_ROOT: '{{ COMMON_OAUTH_URL_ROOT }}'
yes it is being use in three other places as per I know.

2017-08-09 14:26 UTC, ahsan-ul-haq commented on playbooks/roles/ecommerce/defaults/main.yml
> +ECOMMERCE_OAUTH_URL_ROOT: '{{ COMMON_OAUTH_URL_ROOT }}'
yes this is also being used on other places

2017-08-09 14:43 UTC, feanil commented on playbooks/roles/ecommerce/defaults/main.yml
> +ECOMMERCE_OAUTH_URL_ROOT: '{{ COMMON_OAUTH_URL_ROOT }}'
@ahsan-ul-haq can you point me to where?  This seems confusing because the app doesn't use it's own OAUTH_URL_ROOT setting.

2017-08-09 15:21 UTC, ahsan-ul-haq commented on playbooks/roles/ecommerce/defaults/main.yml
> +ECOMMERCE_OAUTH_URL_ROOT: '{{ COMMON_OAUTH_URL_ROOT }}'
[here](https://github.com/edx/configuration/blob/b05150e32f8430e38d08376315bd631ced9d1d90/playbooks/roles/ecommerce/defaults/main.yml#L77) it is being used

2017-08-09 15:26 UTC, clintonb commented on playbooks/roles/ecommerce/defaults/main.yml
> +ECOMMERCE_OAUTH_URL_ROOT: '{{ COMMON_OAUTH_URL_ROOT }}'
Use `COMMON_OIDC_ISSUER` instead of the role-specific variable. A goal here, in addition to getting sandboxes working, is to consolidate these variables as much as possible. As the person who probably wrote many of them, I find it confusing to have to mentally evaluate these variables when I need to make changes. The more we can get to using `COMMON_*` values, the better.

2017-08-09 15:54 UTC, ahsan-ul-haq commented
@clintonb I made some changes does this look like moving towards right direction?

2017-08-09 16:25 UTC, clintonb approved these changes
There is still room for improvement, but this is good enough for now. The remaining variables will be taken care of when we consolidate to the common role.

Again, make sure this is tested on a sandbox before merging. Also, squash commits.

2017-08-09 16:25 UTC, clintonb commented on playbooks/roles/credentials/defaults/main.yml
> +CREDENTIALS_JWT_AUDIENCE: '{{ COMMON_JWT_AUDIENCE }}'
If these are no longer used, they should be removed.

2017-08-09 17:38 UTC, feanil commented on playbooks/roles/ecommerce/defaults/main.yml
> +ECOMMERCE_OAUTH_URL_ROOT: '{{ COMMON_OAUTH_URL_ROOT }}'
Right, so we should be able to delete the role specific `ECOMMERCE_OAUTH_URL_ROOT` from this role when this PR is ready.

2017-08-09 17:50 UTC, clintonb commented on playbooks/roles/ecommerce/defaults/main.yml
> +ECOMMERCE_OAUTH_URL_ROOT: '{{ COMMON_OAUTH_URL_ROOT }}'
@feanil given that the main goal here is to get SSO working on sandboxes are you okay with holding off on any additional variable consolidation? I am willing to let this go as-is (once tested). Additional cleanup can happen later, or resources can dedicated to [LEARNER-812](https://openedx.atlassian.net/browse/LEARNER-812).

2017-08-09 18:05 UTC, feanil commented on playbooks/roles/ecommerce/defaults/main.yml
> +ECOMMERCE_OAUTH_URL_ROOT: '{{ COMMON_OAUTH_URL_ROOT }}'
@clintonb my biggest concern is that there is a variable called `ECOMMERCE_OAUTH_URL_ROOT` does not actually set the ecommerce app's 'OAUTH_URL_ROOT'  If you think that it will be fixed quickly enough, I think we should add a TODO comment to that effect and merge this.

2017-08-09 18:29 UTC, clintonb commented on playbooks/roles/ecommerce/defaults/main.yml
> +ECOMMERCE_OAUTH_URL_ROOT: '{{ COMMON_OAUTH_URL_ROOT }}'
I went ahead and finished the cleanup so as not to bog down @ahsan-ul-haq. My goal was expose someone else to configuration. That goal has been sufficiently met.

2017-08-09 18:30 UTC, feanil commented
@ahsan-ul-haq please also add a CHANGELOG entry since we are removing "public" variables.  And make a DEVOPS support ticket to clean up our internal/secure config.

2017-08-09 18:38 UTC, clintonb commented
Sandbox building: https://tools-edx-jenkins.edx.org/job/Sandboxes/job/CreateSandbox/3421/console

2017-08-09 21:32 UTC, clintonb commented
I tested this on my sandbox, and it "works". By that I mean the Django settings are correct. However, logins fail because the tenants aren't setup in the respective services and the OAuth clients (in LMS) aren't not linked to users. This PR is good to merge (after commits are squashed), but at least two more commits/PRs will be needed:

1. Create service users, and associate them with the OAuth clients.
2. Create tenants for ecommerce and credentials at provision time.

2017-08-10 10:53 UTC, ahsan-ul-haq commented
@feanil updated changelog @clintonb removed unused vars.

2017-08-10 11:58 UTC, clintonb commented on CHANGELOG.md
> +  - Removed `CREDENTIALS_OAUTH_URL_ROOT` which is no longer used, as `COMMON_OAUTH_URL_ROOT` from `common_vars` is used
These can be more succinct, shorter: Replaced `x` with `y` from `common_vars`

2017-08-10 11:58 UTC, clintonb commented on playbooks/roles/credentials/defaults/main.yml
> +CREDENTIALS_SOCIAL_AUTH_EDX_OIDC_ISSUER: '{{ COMMON_JWT_ISSUER }}'
This variable is no longer needed. Replace its usages with the `COMMON_JWT_ISSUER`.

2017-08-10 11:58 UTC, clintonb commented on playbooks/roles/ecommerce/defaults/main.yml
> +ECOMMERCE_SOCIAL_AUTH_EDX_OIDC_ISSUER: '{{ COMMON_JWT_ISSUER }}'
This variable is no longer needed. Replace its usages with the `COMMON_JWT_ISSUER`.

2017-08-10 12:35 UTC, ahsan-ul-haq commented
@clintonb Do you think we need to create new service users for credentials and Ecommerce? Also can you explain how we can create tenants for ecommerce and credentials at provision time?

2017-08-10 12:39 UTC, clintonb commented
Yes. Every service needs its own service user. That's how we do it in production. That's how we should do it everywhere else. There should already be an example of this for ecommerce.

Provisioning sites is a matter of calling the appropriate management command. Here is an example for ecommerce: https://github.com/edx/devstack/blob/master/provision-ecommerce.sh#L7. Search the management commands in edx/credentials to find the appropriate one there. When you do, please update Docker Devstack, too, since others refuse to step up and take responsibility for doing so. :(

2017-08-10 13:33 UTC, schenedx approved these changes
👍

2017-08-10 14:54 UTC, feanil approved these changes

2017-08-10 15:32 UTC, clintonb approved these changes

2017-08-10 15:32 UTC, clintonb commented
Remember to squash commits.

2017-08-11 05:33 UTC, merged

2017-08-14 14:16 UTC, andy-armstrong commented
FYI, it appears that this caused a production issue when rolled out this morning:

https://openedx.atlassian.net/browse/LEARNER-2235