WIP: Mongo 3.2 role
openedx-unsupported/configuration pull request #4048
Opened 2017-08-16 21:15 UTC by jdmulloy

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] Have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?

2017-08-16 21:23 UTC, jdmulloy commented
Looking at individual commits may be helpful since I started by copying the 3.0 role and then making changes. The combined view in the PR shows everything as an add, so there's no way to see the changed from the 3.0 role.

2017-08-16 21:24 UTC, jdmulloy commented
This will give you a proper diff of changes since I copied the 3.0 role.

https://github.com/edx/configuration/compare/1411e5c2a6fbcdc53625f04f9d6d6ed3a1b79a85...jdmulloy/ops2205/mongo_3.2

2017-08-17 13:19 UTC, feanil reviewed
Generally looks good.

2017-08-17 13:19 UTC, feanil commented on playbooks/test-mongo.yml
> +# ansible-playbook -i '54.164.134.57,' -u ubuntu edx-east/mongo_3_2.yml -e@test-mongo.yml
Move this config to https://github.com/edx/configuration/tree/master/playbooks/sample_vars

2017-08-17 13:19 UTC, feanil commented on playbooks/test-mongo.yml
> +MONGO_REPL_SET: 'jdmulloy-3.2'
Replace your name with a generic repl_set name.  Maybe `test-repl-set`

2017-08-17 13:19 UTC, feanil commented on playbooks/test-mongo.yml
> +EDXAPP_MONGO_DB_NAME: 'jdmulloy-32'
Use a generic DB name.  Maybe `test-mongo-db`

2017-08-17 13:19 UTC, feanil commented on playbooks/test-mongo.yml
> +EDXAPP_MONGO_REPLICA_SET: 'jdmulloy-3.2'
Should refere to the `MONGO_REPL_SET` variable right?

2017-08-17 13:19 UTC, feanil commented on playbooks/test-mongo.yml
> +# ansible-playbook -i '54.164.134.57,' -u ubuntu edx-east/mongo_3_2.yml -e@test-mongo.yml
It may also be good to add a comment about how all the secrets in here are examples and should all be replaced.  Maybe change the secrets to have values that obviously need to be replaced.  eg. "PLEASE-SET-ME"

2017-08-17 13:53 UTC, jdmulloy commented on playbooks/test-mongo.yml
> +# ansible-playbook -i '54.164.134.57,' -u ubuntu edx-east/mongo_3_2.yml -e@test-mongo.yml
I can make it more generic. I wasn't intending to leave it like this. I just checked it in so the work could be easily handed off.

2017-08-17 14:24 UTC, jdmulloy commented on playbooks/test-mongo.yml
> +EDXAPP_MONGO_REPLICA_SET: 'jdmulloy-3.2'
Maybe? I copied variable from the real configs until it worked. I don't understand enough about why the real configs are the way they are.

2017-08-17 14:28 UTC, jdmulloy commented on playbooks/test-mongo.yml
> +EDXAPP_MONGO_REPLICA_SET: 'jdmulloy-3.2'
Maybe we should at some point collapse these variables to one in the real configs, but that's a risky surgery I can't do right now.

2017-08-17 14:42 UTC, jibsheet commented on playbooks/test-mongo.yml
> +EDXAPP_MONGO_REPLICA_SET: 'jdmulloy-3.2'
EDXAPP_MONGO_REPLICA_SET is an internal variable we use.  We set it in edx-internal to a name based on deployment/environment and then it's consumed into the code that makes users (custom to edx) and our split modulestore configuration.

It comes from the confused time where we had 2 repl sets, one for edxapp one for forums.  Now we (edX) have one repl set with two databases.

We can dedupe it in our config, but out of scope here.  Now that I'm aware of it, I may try to do it while moving secure -> internal

@jdmulloy you shouldn't need it, I'll look at what the rest of this file contains when I get here for real.

2017-08-18 16:59 UTC, jibsheet requested changes
Looks great, one important change around the bind ip and a bunch of small tweaks (mostly deleting things that shouldn't have been in the 3.0 role to start or other cleanups we can do)

2017-08-18 16:59 UTC, jibsheet commented on playbooks/sample_vars/test-mongo.yml
> +mongo_bind_ip: 0.0.0.0
This isn't the variable we use anymore.  I believe it worked by accident (because in cluster mode we used Mongo's bind to 0.0.0.0 default), strike it from your sample/test data.
We'll want to change the secure/internal config to use the correct uppercase var.

2017-08-18 16:59 UTC, jibsheet commented on playbooks/sample_vars/test-mongo.yml
> +##### edx-olive/olive-secure/ansible/vars/prod-olivex.yml
This is a public repo - I'd rather not have repo paths in it, particularly not repo paths of things we are handing off to another team.

2017-08-18 16:59 UTC, jibsheet commented on playbooks/sample_vars/test-mongo.yml
> +      cacheSizeGB: "{{ (( ansible_memtotal_mb / 1024 ) * 0.70 ) | round(1,'ceil') | int }}" # 70% of available ram - 11GB on m4.xlarge
Please test without the STORAGE_ENGINE and  STORAGE_ENGINE_OPTIONS override.  Mongo 3.2 uses wiredTiger by default, it should come up properly.  We're also going to test dropping the cacheSizeGB because of some memory issues we've seen.

2017-08-18 16:59 UTC, jibsheet commented on playbooks/roles/mongo_3_2/defaults/main.yml
> +# Storage engine options in 3.0: "mmapv1" or "wiredTiger"
Update this comment, this is the 3.2 play (same comment the line below).  mmapv1 and WT are supported in both versions.

2017-08-18 16:59 UTC, jibsheet commented on playbooks/roles/mongo_3_2/defaults/main.yml
> +MONGO_BIND_IP: 127.0.0.1
You removed the use of this in the mongod.conf.j2 however we need to support this.  For single instance edxapp deploys (like sandboxes) we should not be listening on 0.0.0.0, but that is what we now do. 

Please see https://github.com/edx/configuration/pull/3594/files for some sense of the bugfix we had to do because people were running wide open mongods listening on 0.0.0.0.  This was a regression from the mongo installation config file which has set it to 127.0.0.1 for a while https://docs.mongodb.com/manual/reference/configuration-options/#net.bindIp

I think we want to leave it as 127.0.0.1 and add documentation saying "if you're running a cluster, you must set this to 0.0.0.0 or some other variable to allow mongo to talk to other cluster members".  You'll also need to re-add support to the config file.

2017-08-18 16:59 UTC, jibsheet commented on playbooks/edx-east/mongo_3_2.yml
> +    - aws
Note for later - we should figure out how to make the AWS part optional (not part of this PR)

2017-08-18 16:59 UTC, jibsheet commented on playbooks/roles/mongo_3_2/defaults/main.yml
> +MONGO_BIND_IP: 127.0.0.1
See my later comment where I mention that you copied config that says mongo_bind_ip, but the variable is MONGO_BIND_IP, you should PR that change since it's wrong for 3.0 as well as 3.2.

2017-08-18 16:59 UTC, jibsheet commented on playbooks/roles/mongo_3_2/files/disable-transparent-hugepages.conf
> +description     "set transparent hugepage to never"
We don't use this anymore, right?  Can we delete it

2017-08-18 16:59 UTC, jibsheet commented on playbooks/roles/mongo_3_2/defaults/main.yml
> +pymongo_version: 3.2.2
We have a different version in our requirements.txt, can we normalize them

2017-08-18 16:59 UTC, jibsheet commented on playbooks/roles/mongo_3_2/tasks/main.yml
> +- name: create super user
In retrospect, this task seems superfluous.
You either create the ADMIN_USER above when initialize_replica_set or you already have an admin_user.  I think the intent was to log in as MONGO_ADMIN_USER and make sure MONGO_ADMIN_USER was set, but that doesn't actually do anything.  If you want to use it to change the password, you can't even do that here.  

I suggest deleting this task (the when: not initialize_replica_set) unless you saw some use for it that I'm missing.

2017-08-18 16:59 UTC, jibsheet commented on playbooks/roles/mongo_3_2/templates/create_root.js.j2
> +// Add super user
Do we use this?  I think this is a holdover from the 2.6 role.  It's probably unused in the 3.0 role also.

2017-08-18 16:59 UTC, jibsheet commented on playbooks/roles/mongo_3_2/templates/mongod.conf.j2
> +# Do not edit this file directly, it was generated by ansible
Switch this to {{ ansible_managed }}

2017-08-18 20:02 UTC, jdmulloy commented on playbooks/sample_vars/test-mongo.yml
> +##### edx-olive/olive-secure/ansible/vars/prod-olivex.yml
That makes sense. I was just trying to keep track of where I got sample data from. Is there some way I can express the source without leaking sensitive info? It gets a bit confusing having info spread out across multiple repos.

2017-08-18 20:04 UTC, jdmulloy commented on playbooks/sample_vars/test-mongo.yml
> +mongo_bind_ip: 0.0.0.0
I can strike it from the test data that is checked in but I'll still need to set it when I use the file for my testing right?

2017-08-18 20:06 UTC, jdmulloy commented on playbooks/roles/mongo_3_2/files/disable-transparent-hugepages.conf
> +description     "set transparent hugepage to never"
Mongo still gives a warning if we don't disable THP.

2017-08-18 20:09 UTC, jdmulloy commented on playbooks/roles/mongo_3_2/defaults/main.yml
> +pymongo_version: 3.2.2
Should I bring the one in requirements.txt up to 3.2 then? In the 3_0 role it was very old and didn't work with 3.2. I'm guessing it's backwards compatible.

2017-08-21 14:33 UTC, jibsheet commented
@jdmulloy I just close/opened to attempt to get it into travis' build queue now that github seems marginally healthier

2017-08-21 16:08 UTC, jibsheet commented on playbooks/roles/mongo_3_2/files/disable-transparent-hugepages.conf
> +description     "set transparent hugepage to never"
But this is the upstart file, right?  You replaced it with the systemd version, and we don't expect to run this role on anything other than 16.04 and higher?

2017-08-21 16:08 UTC, jibsheet commented on playbooks/roles/mongo_3_2/defaults/main.yml
> +pymongo_version: 3.2.2
I think you've brought up requirements.txt, which is the right fix in my mind

2017-08-21 16:09 UTC, jibsheet commented on playbooks/sample_vars/test-mongo.yml
> +##### edx-olive/olive-secure/ansible/vars/prod-olivex.yml
Unfortunately, not a great way.  I'll often just say secure vs internal and leave it at that.

2017-08-21 16:09 UTC, jibsheet commented on playbooks/sample_vars/test-mongo.yml
> +mongo_bind_ip: 0.0.0.0
You'll want to replace it with MONGO_BIND_IP

2017-08-22 14:39 UTC, jdmulloy commented on playbooks/roles/mongo_3_2/files/disable-transparent-hugepages.conf
> +description     "set transparent hugepage to never"
Correct. I will remove this file.

2017-08-22 21:19 UTC, jibsheet approved these changes
Please add a note about the BIND IP called out in the review comment, add a CHANGELOG entry (mentioning new 3.2 role and the removal of MONGO_CLUSTERED) then squash (As makes sense) and merge.

2017-08-22 21:19 UTC, jibsheet commented on playbooks/roles/mongo_3_2/defaults/main.yml
> +MONGO_BIND_IP: 127.0.0.1
Can you document here that if you're clustering more than one machine with our play, MONGO_BIND_IP should be set to either 0.0.0.0 to listen on all IPs, or set to more specific IPs as needed for their configuration.

2017-08-23 15:52 UTC, jibsheet commented on CHANGELOG.md
> +  - Removed MONGO_CLUSTED variable. In this role mongo replication is always configured, even if there is only one node.
CLUSTERED

2017-08-23 19:02 UTC, merged