Create ansible role that deploys a custom theme
openedx-unsupported/configuration pull request #4052
Opened 2017-08-20 19:58 UTC by clemente

This PR includes an ansible role that creates a new theme with custom SASS overrides and custom provided files.

**JIRA tickets**: none

**Discussions**: Still in progress, particularly about downloading files.

**Dependencies**: None

**Screenshots**:

**Sandbox URL**: None

**Partner information**: None

**Deployment targets**: None that I know of

**Merge deadline**: None

**Testing instructions**:

1. In the vagrant VM, enter into /edx/app/edx_ansible/edx_ansible and checkout the branch from this PR
2. As "vagrant" user:
```
    export PYTHONUNBUFFERED=1
    source /edx/app/edx_ansible/venvs/edx_ansible/bin/activate
    cd /edx/app/edx_ansible/edx_ansible/playbooks
    ansible-playbook -i localhost, -c local run_role.yml -e role=simple_theme  -e configuration_version=master -e edx_platform_version=master
```
3. This will create a new theme in the themes directory (the one that's shared by NFS), by default it's called: "simplet1". It will have content inside, and the content has the SASS overrides, the image overrides, the extra template code, and the downloaded external images that the file defaults/main.yml requested. No other theme will be modified
4. If not enabled, enable comprehensive theming and add the theme through admin. update_assets as usual or restart LMS to compile the theme
5. You should see some theme changes (red titles, icon at top right, wide blue footer top border, …)

**Author notes and concerns**:

1. The code contains an example theme with sample colors and images that will be changed; it's just provided as example and it's not meant to be pretty.
2. I'm rather new with openedx and ansible, so please help me if I missed something.
3. The way to call this role still needs to be improved, e.g. whether it should be included by another role or run manually. When run manually, it won't actually change the current theme 

**Reviewers**
- [ ] @smarnach 
- [ ] @mtyaka 
- [ ] edX reviewer[s] TBD

**Settings**
In defaults/main.yml

---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] Have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?

2017-08-20 19:58 UTC, edx-webhook commented
Thanks for the pull request, @clemente! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=4052&repo=edx%2Fconfiguration"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-08-21 15:53 UTC, smarnach requested changes

2017-08-21 15:53 UTC, smarnach commented on playbooks/roles/simple_theme/defaults/main.yml
> +themes_dir: "/edx/app/edxapp/themes"
Isn't there already a variable for this?

If you introduce new variable, they should be prefixed with the role name.  See the [Ansible code conventions](https://openedx.atlassian.net/wiki/spaces/OpenOPS/pages/26837527/Ansible+Code+Conventions) for details.

2017-08-21 15:53 UTC, smarnach commented on playbooks/roles/simple_theme/defaults/main.yml
> +  - "/edx/app/edxapp/themes/edx-platform"
I'm actually not sure how the variable precedence works out if we override this here, in particular given that we don't know yet whether the role is run by `include_role`.  It's possible we need to move these overrides to `vars/default.yml` after all, to give them high enough priority.  If we do so, however, we need to make sure that the overrides only take effect if we actually want them.  Ansible is a bit special in this regard – even if a role is disabled by a `when` clause, all it's variables are set anyway.

So if we can't find a reasonable way to make the overrides here, we need to document what variables need to be set to use this role instead.

2017-08-21 15:53 UTC, smarnach commented on playbooks/roles/simple_theme/defaults/main.yml
> +    value: '#07f'
The default should be something neutral; probably just an empty list.

2017-08-21 15:53 UTC, smarnach commented on playbooks/roles/simple_theme/tasks/main.yml
> +  file: path={{ theme_folder }}/lms/static/images/profiles state=directory
It looks like all these directories are created as the root user, which doesn't seem like a good idea.

You should also use the newer dictionary syntax for module parameters:

    - name: Create dir
      file:
        path: /some/path
        state: directory

See the coding conventions I linked before.

2017-08-21 15:53 UTC, smarnach commented on playbooks/roles/simple_theme/templates/lms/static/sass/_lms-overrides.scss.j2
> +/* Extra SASS as defined by simple_theme: */
This does not seem like a useful template, since it simply expands to what is in `EDXAPP_THEME_EXTRA_SASS`.  You can use the `copy` role with the `content` parameter to achieve the same purpose.  (If you prefer it the way it is for consistency and flexibility, this is also fine with me.  So up to you.)

2017-08-22 07:46 UTC, mtyaka reviewed
Thanks for working on this @clemente, it's looking very nice.

The main thing missing is ability to specify a different theme template/skeleton, where you can use your own custom theme as the base.

2017-08-22 07:46 UTC, mtyaka commented on playbooks/roles/simple_theme/defaults/main.yml
> +theme_folder: "{{ themes_dir}}/edx-platform/{{ theme_name }}"
Themes are usually located in `"/edx/app/edxapp/{{ theme_name }}"`. I don't think the `"/edx-platform/"` in the middle is necessary.

2017-08-22 07:46 UTC, mtyaka commented on playbooks/roles/simple_theme/defaults/main.yml
> +  - "/edx/app/edxapp/themes/edx-platform"
Should this be `- "{{ theme_folder }}"` ?

2017-08-22 07:46 UTC, mtyaka commented on playbooks/roles/simple_theme/defaults/main.yml
> +theme_name: "simplet1"
Can we change the default to something more readable? Perhaps `"simple-theme"`?

2017-08-22 07:46 UTC, mtyaka commented on playbooks/roles/simple_theme/defaults/main.yml
> +      border-top: 3px solid $main-color;
Nit: indentation is not consistent with the rules above.

2017-08-22 07:46 UTC, mtyaka commented on playbooks/roles/simple_theme/defaults/main.yml
> +# Files will be copied from "files" directory in this role to the specified path.
Custom files should not be included in the role itself (except as a default example). There should be an ansible variable that lets you specify the folder where static files are located.

2017-08-22 07:46 UTC, mtyaka commented on playbooks/roles/simple_theme/defaults/main.yml
> +  'https://clix.tiss.edu/wp-content/uploads/2015/11/icon-student-1.png': '/lms/static/images/profiles/default_50.png'
I don't think we will need this. I should have removed that from the task description, sorry.

2017-08-22 07:46 UTC, mtyaka commented on playbooks/roles/simple_theme/defaults/main.yml
> +  favicon.ico: '/lms/static/images/favicon.ico'
I think we can simplify this. Instead of specifying the source and destination of each file, we could specify a folder that contains all custom static files, and just copy them all to the appropriate location in the theme folder, maintaining the folder hierarchy. Sorry for not thinking of this when I created the task.

For example source folder could look like this:

```
- lms
  - images
    - logo.png
    - favicon.ico
  - js
    - myscript.js
- cms
  - images
    - logo.png
```

would copy the files into the static folders in the theme:

```
- lms
  - static
    - images
      - logo.png
      - favicon.ico
    - js
      - myscript.js
- cms
  - static
    - images
      - logo.png
```

2017-08-22 07:46 UTC, mtyaka commented on playbooks/roles/simple_theme/defaults/main.yml
> +    of my ToS page</p>
I think I would prefer if all customizations were empty by default, but code comments containing examples like these will be appreciated.

2017-08-22 07:46 UTC, mtyaka commented on playbooks/roles/simple_theme/defaults/main.yml
> +EDXAPP_THEME_EXTRA_SASS: |
Same here - there should probably be no extra sass by default, but it would be nice if we kept this example in a code comment.

2017-08-22 07:46 UTC, mtyaka commented on playbooks/roles/simple_theme/templates/lms/templates/static_templates/tos.html.j2
> +<!-- <h2>On April 1, 2017, adopted Terms of Service, providing as follows:</h2> -->
Remove this line.

2017-08-22 07:46 UTC, mtyaka commented on playbooks/roles/simple_theme/templates/lms/templates/static_templates/tos.html.j2
> +</section>
We will eventually want to support other static pages (about, contact, privacy policy...), but I think this is fine for first implementation.

2017-08-23 15:12 UTC, clemente commented on playbooks/roles/simple_theme/defaults/main.yml
> +theme_folder: "{{ themes_dir}}/edx-platform/{{ theme_name }}"
They recommend it in here (and in following pages): http://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/configuration/changing_appearance/theming/theme_directories.html

2017-08-23 17:56 UTC, smarnach commented on playbooks/roles/simple_theme/defaults/main.yml
> +theme_folder: "{{ themes_dir}}/edx-platform/{{ theme_name }}"
I think the path should be `/edx/app/edxapp/themes/{{theme _name}}`, which is what we are generally using.  I can't see how the additional layer with `edx-platform` would make sense, since the `ecommerce` theme would go in `/edx/app/ecommerce/themes` anyway.

2017-08-23 19:41 UTC, clemente commented on playbooks/roles/simple_theme/defaults/main.yml
> +  favicon.ico: '/lms/static/images/favicon.ico'
I implemented this. The part about adding the „static/“ to every path was the hardest (not because of the reg.expr. needed, but because i can't directly copy everything, instead I must process every folder to do the path change). Ansible is not bash and I might have resorted to a strange system; but it works. Any idea of how could have been easier?

2017-08-24 09:19 UTC, mtyaka commented on playbooks/roles/simple_theme/templates/lms/static/sass/lms-course.scss.j2
> +@import 'lms-overrides';
This file, as well as `lms-main-v1.scss` and `lms-main-v2.scss` don't have to be jinja templates.

2017-09-10 19:21 UTC, smarnach reviewed
I just noticed that I have pending comments here since Monday – some of them are probably out of date by now.  I'll send the comments now and remove the ones that don't apply after sending, since the Github UI doesn't give me any better way to do this.

2017-09-10 19:21 UTC, smarnach commented on playbooks/roles/simple_theme/defaults/main.yml
> +theme_folder: "{{ EDXAPP_COMPREHENSIVE_THEME_DIRS.0 }}/{{ EDXAPP_DEFAULT_SITE_THEME }}"
All variables you introduce should be prefixed with the role name, or at least with a common prefix, so this should be `simpletheme_folder`.  Ansible does not have scopes, so we need to simulate scopes by prefixes.

2017-09-10 19:21 UTC, smarnach commented on playbooks/roles/simple_theme/meta/main.yml
> +# At the moment the simple_theme doesn't depend on other roles
Just make this

    dependencies: []

This says the same as the comment. just more succinctly.  There are also some cases where this file must evaluate to a dictionary (it might be only necessary for ansible-galaxy, but I don't quite remember), so it should not be completely empty.

2017-09-10 19:21 UTC, smarnach commented on playbooks/roles/simple_theme/defaults/main.yml
> +#
Thanks for writing the documentation!  I think it will be easier to find if you move it to a `README.md` file at the top level of the role.  Also include the documentation from `tasks/main.yml` in the same file.

2017-09-10 19:21 UTC, smarnach commented on playbooks/roles/simple_theme/tasks/main.yml
> +# ansible-playbook -i localhost, -c local run_role.yml -e role=simple_theme  -e configuration_version=master -e edx_platform_version=master -e EDXAPP_DEFAULT_SITE_THEME=mytheme2 -e '{"SIMPLETHEME_SAS
I'm not sure we need to document this.  This was more of a development tool, but it's not actually the intended use of this role.

2017-09-10 19:21 UTC, smarnach commented on playbooks/roles/simple_theme/tasks/main.yml
> +  when: EDXAPP_COMPREHENSIVE_THEME_SOURCE_REPO != ""
What happens if `EDXAPP_COMPREHENSIVE_THEME_SOURCE_REPO` is not set?  We won't clone a skeleton repo, so will it make sense to continue this role?

2017-09-10 19:21 UTC, smarnach commented on playbooks/roles/simple_theme/tasks/main.yml
> +    src: "./{{ item }}.j2"
Any reason to prefix this with `./`?  I'm just curious.

2017-09-10 19:31 UTC, smarnach requested changes
@clemente Here is another set of comments, in addition to the ones sent before.  Please also look at the comments mark as "outdated" by Github.  They are only marked as outdated since the main tasks file was renamed, so they are all still relevant.

2017-09-10 19:31 UTC, smarnach commented on playbooks/roles/simple_theme/tasks/deploy.yml
> +    msg: "Simple-theme needs to know the name the name of the deployed them. Pass it in EDXAPP_DEFAULT_SITE_THEME"
Typo: duplicate "the name".

2017-09-10 19:31 UTC, smarnach commented on playbooks/roles/simple_theme/tasks/deploy.yml
> +# Adapt to the list of directories that you need created
If this is supposed to be user-defined, shouldn't we take the list of directories from a variables that can be configured?  Otherwise people would need to modify the role source.

If there is a default set of directories that almost always needs to be created, it's even better to make this _two_ variables:  One for the list of default directories, and one for the additional user-defined directories, so the user does not need to repeat the default directories when overriding the list.

2017-09-10 19:31 UTC, smarnach commented on playbooks/roles/simple_theme/tasks/deploy.yml
> +# Adapt to the list of files that define your theme
Same here – if this is meant to be configurable, it needs to be made configurable.

2017-09-10 22:23 UTC, clemente commented on playbooks/roles/simple_theme/tasks/main.yml
> +# ansible-playbook -i localhost, -c local run_role.yml -e role=simple_theme  -e configuration_version=master -e edx_platform_version=master -e EDXAPP_DEFAULT_SITE_THEME=mytheme2 -e '{"SIMPLETHEME_SAS
I have added more information and labelled it as „testing“.
But it's good that it's there. Whoever uses this role will need to test it in local for some time, and it's not good to hide the information about how to test it.
Also, I think a very common requirement will be to deploy theme changes to a running instance (as Xavier asked), so I wrote about this option too. We can discourage it more strongly, for now, but it actually works.

2017-09-10 22:25 UTC, clemente commented on playbooks/roles/simple_theme/tasks/main.yml
> +    src: "./{{ item }}.j2"
Well yes, to make it fail if someone writes an absolute path there; that is, to show that you're expected to write relative paths.
I removed because it appeared only once in the file.
In fact I would like to force ansible not to allow accessing absolute paths in the host unless explicitly allowed. But I cannot control this yet.

2017-09-10 22:32 UTC, clemente commented on playbooks/roles/simple_theme/tasks/deploy.yml
> +# Adapt to the list of directories that you need created
It started being a list of „files that compose your theme“, but now it's actually not needed anymore: you should provide your files through a skeleton theme, and these two tasks only process the internal files used by the simple_theme role, which are only 2 (_lms-overrides.scss and _variables.scss.j2) and you're not expected to change them. The skeleton themes should be built in such a way that they can have these 2 files overwritten with no problem (from @mtyaka 's proposal: https://tasks.opencraft.com/browse/OC-2685?focusedCommentId=44488&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-44488)
I rewrote the descriptions.

2017-09-16 10:37 UTC, smarnach reviewed
@clemente Here's another round of comments, mostly stylistic.

2017-09-16 10:37 UTC, smarnach commented on playbooks/roles/simple_theme/tasks/deploy.yml
> +      - "EDXAPP_COMPREHENSIVE_THEME_DIRS is defined"
Are all the "is defined" tests necessary?  I have never needed one.

In general, we define default values for  all variables in `defaults/main.yml`, so they are guaranteed to exist.  This case is a bit special, since we are accessing a variable from the edxapp role.  However, since the simple_theme role is designed to only be run from the edxapp role, I think we can rely on the variables of that role, and let Ansible error out otherwise.  It will error out anywat if the assertion fails.

2017-09-16 10:37 UTC, smarnach commented on playbooks/roles/simple_theme/tasks/deploy.yml
> +  when: EDXAPP_COMPREHENSIVE_THEME_SOURCE_REPO is defined and EDXAPP_COMPREHENSIVE_THEME_SOURCE_REPO != "" and simpletheme_folder_stat.stat.exists == False
I would omit the `is defined` test here as well (unless you disagree with the reasoning I gave).

I also dislike comparisons with Boolean values and I prefer `not xxx` over `xxx == False`, but that's more of a style nit, so up to you.

2017-09-16 10:37 UTC, smarnach commented on playbooks/roles/simple_theme/tasks/deploy.yml
> +  when: (EDXAPP_COMPREHENSIVE_THEME_SOURCE_REPO is not defined or EDXAPP_COMPREHENSIVE_THEME_SOURCE_REPO == "") and simpletheme_folder_stat.stat.exists == False
I would prefer for the condition to go at the top, since this is what I'm used from most other programming languages, like

    if condition:
        do_something_cool()

In Ansible people tend to write the condition at the end, so we should likely follow that convention.

In the condition itself, I'd again remove the `is defined` bit and simplify `== False` – see above.

2017-09-16 10:37 UTC, smarnach commented on playbooks/roles/simple_theme/tasks/deploy.yml
> +- name: Adjust owner/group of skeleton theme
I think this task should go directly after the git task.

2017-09-16 10:37 UTC, smarnach commented on playbooks/roles/simple_theme/tasks/main.yml
> +# this role to the 2nd run, the one without celery_worker
I don't think it's clear whether it's the first or the second run, and I don't think this captures the gist of the condition we added.

The idea of being able to run the edxapp role in two different modes is that edX themselves deploy the celery workers to different machines than the web application.  Since there is a lot of overlap between the setups for both, they use the same role with slight variations triggered by the `celery_worker` flag.  In our playbook, we want to install the celery workers into the same environment as the web app, so we include the role twice.

So the actual reason for the condition below is that the theme is only needed for the web app, and it's useles for the celery workers.  Even in contexts where the role is included only once with `celery_worker: True`, we don't want the simple_theme role to run.  So I'd change the comment to something like
> The theme is only needed for the web application, so we skip running the role for the Celery workers.

2017-09-16 21:59 UTC, clemente commented on playbooks/roles/simple_theme/tasks/deploy.yml
> +      - "EDXAPP_COMPREHENSIVE_THEME_DIRS is defined"
bq. However, since the simple_theme role is designed to only be run from the edxapp role,
I'm always taking into account that we might want to run this role outside edxapp too, e.g. for deploying theme changes.
But I'm ok with the ansible role crashing if called in an unsupported way, so I'll remove the „is defined“.

2017-09-16 22:02 UTC, clemente commented on playbooks/roles/simple_theme/tasks/deploy.yml
> +  when: EDXAPP_COMPREHENSIVE_THEME_SOURCE_REPO is defined and EDXAPP_COMPREHENSIVE_THEME_SOURCE_REPO != "" and simpletheme_folder_stat.stat.exists == False
Ok. This was copied from somewhere.
I still don't trust ansible boolean variables enough to be sure that „not xxx“ will always work. But if it works for you, I'll use it and try it.

2017-09-16 22:10 UTC, clemente commented on playbooks/roles/simple_theme/tasks/deploy.yml
> +  when: (EDXAPP_COMPREHENSIVE_THEME_SOURCE_REPO is not defined or EDXAPP_COMPREHENSIVE_THEME_SOURCE_REPO == "") and simpletheme_folder_stat.stat.exists == False
> I would prefer for the condition to go at the top,

Good idea, all „when:“ could be written first. But yes, the rest of the code (including edx roles) tend to put it at the end, so I'll leave it there.

Also, it seems to me that ansible have put some effort into making ansible *not* seem a programming language. E.g. no variable assignments, strange variable scoping, no print(), no debug, …

2017-09-17 15:53 UTC, smarnach approved these changes
@clemente Thanks for the changes!  Looks good to me now, :+1:.

To prepare this for upstream review, here are a few things that are still left to do:
* Trigger the bot to create an OSPR ticket (see the first comment) and add the ticket number to the PR description.
* Make sure the PR desrciption is up to date – e.g. testing instructions and author notes.

2017-09-18 15:32 UTC, edx-webhook commented
Thanks for the pull request, @clemente! I've created [OSPR-1896](https://openedx.atlassian.net/browse/OSPR-1896) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

2017-10-02 19:17 UTC, gsong commented
@clemente I would also consider squashing some commits.

2017-10-02 20:07 UTC, clemente commented
@gsong Of course. I squashed all commits to just 1, because it's just 1 feature. I also rebased on top of master.

2017-10-23 12:15 UTC, clemente commented
I added a new feature, to download static files from URL. @smarnach could you review the commit? Soon I'll check the feature as part of the deployment process.
I'll squash commits and rebase after it's reviewed.

2017-10-23 12:33 UTC, smarnach commented
@clemente I can't review before Wednesday, so if you want feedback earlier than that please ask someone else.

2017-10-23 12:39 UTC, clemente commented
@smarnach that's ok, no hurry, could be late in the week. I tested it and it works, and the review isn't blocking anything from my side.

2017-10-25 12:39 UTC, clemente commented
Rebased on top of master.

2017-11-03 18:44 UTC, nedbat commented
@smarnach are we still waiting for your review?

2017-11-05 20:54 UTC, smarnach commented
@nedbat You are right, sorry about that.  This was an internal miscommunication on our end, so this fell through the cracks.  I will review this on Tuesday.

2017-11-10 23:18 UTC, smarnach commented
@clemente The latest changes look good to me.

I haven't tested this myself, but I verified the logs of [this appserver](https://stage.console.opencraft.com/instance/1460/edx-appserver/360/) (only accessible for OpenCraft), and all is looking fine. :+1:

2017-11-12 20:30 UTC, smarnach commented on playbooks/roles/simple_theme/tasks/deploy.yml
> +      path: "{{ simpletheme_folder }}/{{ item.dest | regex_replace('/[^/]*$','') }}"
Can we use the `dirname` filter here instead of `regez_replace`?  (Sorry I did not notice this earlier.)

2017-11-12 23:26 UTC, clemente commented on playbooks/roles/simple_theme/tasks/deploy.yml
> +      path: "{{ simpletheme_folder }}/{{ item.dest | regex_replace('/[^/]*$','') }}"
I added a commit; I can squash it with the first one if you prefer.
I added this to our other internal branches (1 new PR, 1 new commit in existing PR).

2017-11-13 10:45 UTC, smarnach commented on playbooks/roles/simple_theme/tasks/deploy.yml
> +      path: "{{ simpletheme_folder }}/{{ item.dest | regex_replace('/[^/]*$','') }}"
Thanks!  please wait for upstream review before squashing.

2017-11-13 10:46 UTC, smarnach commented
@nedbat We've finished the internal review on this PR now – sorry for the noise.

2017-12-11 09:06 UTC, clemente commented
@nedbat Any news on this review?
We already use this code in our servers and it's working.

2017-12-11 22:32 UTC, nedbat commented
@edx/devops is this in your backlog?

2017-12-12 14:36 UTC, coryleeio commented
It is:
https://openedx.atlassian.net/browse/OSPR-1896

@feanil

2017-12-12 19:57 UTC, feanil commented
I've scheduled this for 2 sprints out.  So we likely won't get to reviewing it until the new year, but it is now scheduled for review.

2017-12-12 20:06 UTC, clemente commented
@feanil Great, thanks!

2018-01-09 14:42 UTC, nadeemshahzad approved these changes

2018-01-09 14:45 UTC, nadeemshahzad commented
Thanks @clemente for the contribution. I have tested PR on sandbox and changes are looking good to me.

2018-01-09 14:45 UTC, merged

2018-01-09 14:45 UTC, edx-webhook commented
@clemente 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/4052&entry.1484655318=https://github.com/clemente&entry.752974735=2017-08-20+19:58&entry.1917517419=2018-01-09+14:45&entry.2133058324=Yes) so we can improve your experience in the future.

2018-01-09 19:41 UTC, clemente commented
@nadeemshahzad thanks for reviewing.