[WIP] Setting up new jenkins roles
openedx-unsupported/configuration pull request #4058
Opened 2017-08-23 19:59 UTC by michaelyoungstrom

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] Have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?

2017-09-05 14:28 UTC, jzoldak requested changes

2017-09-05 14:28 UTC, jzoldak commented on playbooks/roles/jenkins_build/defaults/main.yml
> +
totally optional style thing here - IMO it would be  more readable with an empty line before these headings but no empty line between the heading and its first item.

2017-09-05 14:28 UTC, jzoldak commented on playbooks/roles/jenkins_common/tasks/main.yml
> +    - jenkins
Is there documentation for when/why you would use certain tags, and what effect doing so would have?

2017-09-05 14:28 UTC, jzoldak commented on playbooks/roles/jenkins_test/files/ec2/mongo_init_script.sh
> +# This confirms that mongo is running and is accessible on localhost
It seems like most if not all of playbooks/roles/jenkins_test/files is a duplicate of playbooks/roles/jenkins_build/files. Is there a way that we can avoid this repetition? Maybe we could use symbolic links?

My concern is for DRY code, and also I'm concerned that the two folder contents will get unintentionally out of step with each other, and thus test-jenkins will be dissimilar to build-jenkins and no longer a valid environment for verifying functionality before it gets to production.

2017-09-05 18:44 UTC, michaelyoungstrom commented on playbooks/roles/jenkins_build/defaults/main.yml
> +
Agreed. Fixed

2017-09-05 18:45 UTC, michaelyoungstrom commented on playbooks/roles/jenkins_common/tasks/main.yml
> +    - jenkins
For the most part I followed the jenkins_master role, but there is some general documentation here: https://openedx.atlassian.net/wiki/spaces/OpenOPS/pages/39584735/Role+Life-cycle+Tags . If you see any you disagree with let me know. A few seemed tough to categorize

2017-09-05 18:46 UTC, michaelyoungstrom commented on playbooks/roles/jenkins_test/files/ec2/mongo_init_script.sh
> +# This confirms that mongo is running and is accessible on localhost
Fixed this by getting rid of the jenkins_test role. It really wasnt necessary. The difference in secrets is already handled in our secure repo, and any differences in variables can still be addressed in the actual play for test jenkins

2017-09-05 19:31 UTC, michaelyoungstrom commented
CC: @edx/devops

2017-09-05 21:07 UTC, jzoldak approved these changes
This looks awesome @michaelyoungstrom!

2017-09-06 16:54 UTC, jibsheet reviewed
This looks great.  I called out a few things where we're putting edX specific data in a public repo.

Larger-scale, I wonder if that ec2 config should get pulled back internally since it's *so* specific to what we do, and making everything a var would get tedious (unless you can easily have a list of dictionaries and use ansible/jinja2 to generate that file).
If you do pull it into an internal repo, we'd want to document the use of it for folks

2017-09-06 16:54 UTC, jibsheet commented on playbooks/roles/jenkins_build/defaults/main.yml
> +build_jenkins_debian_pkgs:
This looks like the same list used in jenkins_common.  You don't need to override and pass unless you're changing it (you can just leave this var out of the meta call later).  I didn't check the rest, but we may be able to prune a few overrides here?

2017-09-06 16:54 UTC, jibsheet commented on playbooks/roles/jenkins_build/files/ec2_config.yml
> +    - NAME: 'us-east-1'
I would make regions a variable (this is where the secure vs internal thing comes in, but for you folks I'd just stuff all your vars in your secure repo).

Update: imagine I put this like 5 lines later where you have REGION: 'us-east-1' - sentiment stands

2017-09-06 16:54 UTC, jibsheet commented on playbooks/roles/jenkins_build/files/ec2_config.yml
> +          - AMI_ID: 'ami-33580448'
these are unlikely to be public AMIs, right

2017-09-06 16:54 UTC, jibsheet commented on playbooks/roles/jenkins_build/files/git_config.yml
> +EMAIL: 'jenkins@edx.org'
Don't put edx email addresses in the confirmation repo, folks will try to deploy this and you'll be super confused when you get emails (we generally use jenkins@example.com as a default with a variable to override)

2017-09-06 16:54 UTC, jibsheet commented on playbooks/roles/jenkins_build/files/mailer_config.yml
> +DEFAULT_SUFFIX: '@edx.org'
similar to earlier comments about edx.org

2017-09-06 16:54 UTC, jibsheet commented on playbooks/roles/jenkins_common/defaults/main.yml
> +jenkins_common_port: 8080
Looks like we can just use the defaults for many of these in the jenkins_build role

2017-09-06 19:52 UTC, estute commented on playbooks/roles/jenkins_build/files/ec2_config.yml
> +          - AMI_ID: 'ami-70fea467'
Perhaps we should just put the publicly available Xenial amis here. Open source users won't have access to it. Also, not sure if this value registers on the sensitivity scale.

2017-09-06 19:54 UTC, estute commented on playbooks/roles/jenkins_build/files/main_config.yml
> +    ADMIN_EMAIL: 'edx-platform-build <ci@edx.org>'
^not sure if we should have emails in the open

2017-09-06 20:03 UTC, estute commented on playbooks/roles/jenkins_build/meta/main.yml
> +  - role: docker-tools
What is going on here? While I want to get to a point where we are using Docker for our Jenkii, we don't currently. I think we should simplify this effort into generating an identical matching Build Jenkins to what we have today.

2017-09-06 20:05 UTC, estute approved these changes
This looks great! I have a question about the docker-tools role, but maybe there is something that I am missing. Otherwise :+1:

2017-09-11 17:45 UTC, jibsheet commented on playbooks/roles/jenkins_build/defaults/main.yml
> +JENKINS_MAILER_DEFAULT_SUFFIX: '@edx.org'
These are still edx.org defaults

2017-09-11 17:45 UTC, jibsheet commented on playbooks/roles/jenkins_build/files/main_config.yml
> +    URL: 'https://build.testeng.edx.org/'
We shouldn't have edx.org real URLs in here (or at least they should be easier to override)

2017-09-11 17:45 UTC, jibsheet commented on playbooks/roles/jenkins_build/templates/ec2_config.yml.j2
> +---
This looks so much better

2017-09-11 17:45 UTC, jibsheet commented on playbooks/roles/jenkins_common/defaults/main.yml
> +jenkins_common_port: 8080
stand by this note, can you tell me if I missed something?

2017-09-12 15:44 UTC, estute commented on playbooks/roles/jenkins_build/meta/main.yml
>    - browsers
Just realized that this is here. Browsers and edxapp_common are unnecessary on the build Jenkins master.

2017-09-13 14:39 UTC, jibsheet approved these changes

2017-09-13 15:32 UTC, estute commented on playbooks/roles/jenkins_build/defaults/main.yml
> +# plugins
Sorry to hold this up, but this should an easy fix (or separate PR): The complete list of needed plugins for build jenkins can be found here https://github.com/edx/configuration/pull/3969/files

2017-09-13 15:41 UTC, estute commented
:+1: thanks for the update!!

2017-09-13 16:26 UTC, merged