Add flag EDXAPP_REINDEX_ALL_COURSES (reindex courses on deploy)
openedx-unsupported/configuration pull request #4082
Opened 2017-09-10 04:07 UTC by clemente

This adds a task to call reindex_course on deploy. Togglable through a flag `EDXAPP_REINDEX_ALL_COURSES` (disabled by default).
 
**JIRA tickets**: N/A

**Discussions**: N/A

**Dependencies**: None

**Screenshots**:

**Sandbox URL**: TBD - sandbox is being provisioned.

**Merge deadline**: None

**Testing instructions**:

1. Do a deploy with this variable set to False. Nothing should change
2. Test in local in an already deployed devstack with some course, with:
3. cd /edx/app/edx_ansible
4. source venvs/edx_ansible/bin/activate
5. cd edx_ansible/playbooks/
6. ansible-playbook -e "{role: 'edxapp'}" -i "localhost," -c local --tags testing-clemente-reindex-courses  run_role.yml -e EDXAPP_REINDEX_ALL_COURSES=true -e edxapp_settings=devstack -vvv
7. Verify (in the verbose info) that some courses are processed and reindexed

**Author notes and concerns**:

- This is supposed to be a one-time operation, on deploy, for the cases when an instance is using a local ElasticSearch.
- The command doesn't depend on any particular ModuleStore

**Reviewers**
- [ ] @pomegranited 
- [ ] @mtyaka 
- [ ] edX reviewer[s] TBD

**Settings**
```yaml
EDXAPP_REINDEX_ALL_COURSES: true
```

---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [X] Add an entry to the CHANGELOG.
  - [ ] Have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?

2017-09-10 04:07 UTC, edx-webhook commented
Thanks for the pull request, @clemente! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fconfiguration&number=4082"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-09-11 08:44 UTC, pomegranited requested changes
@clemente  Some changes are needed before this task will work.

Please see my comments above.

2017-09-11 08:44 UTC, pomegranited commented on playbooks/roles/edxapp/tasks/deploy.yml
> +    - migrate:db
@clemente  In order for your PR instructions to work, you need to manually add your temporary tag name here.  Please update the PR instructions to add this step.

2017-09-11 08:44 UTC, pomegranited commented on playbooks/roles/edxapp/tasks/deploy.yml
> +      Re-indexing all courses might be a time consuming operation. Do you want to continue: "y"
@clemente This `expect`/`response` wasn't working for me, so I had another look at the management command, and there's an additional option that helps us here: [`--setup`](https://github.com/edx/edx-platform/blob/open-release/ginkgo.1/cms/djangoapps/contentstore/management/commands/reindex_course.py#L27).

So you can use that instead of `--all`, and you don't get a prompt.

```diff
diff --git a/playbooks/roles/edxapp/tasks/deploy.yml b/playbooks/roles/edxapp/tasks/deploy.yml
index c23ad719f..64e18edd1 100644
--- a/playbooks/roles/edxapp/tasks/deploy.yml
+++ b/playbooks/roles/edxapp/tasks/deploy.yml
@@ -438,13 +438,9 @@
     - manage:db
 
 - name: reindex all courses
-  expect:
-    command: "{{ edxapp_venv_bin }}/python ./manage.py cms reindex_course --all --settings={{ edxapp_settings }}"
-    responses:
-      Re-indexing all courses might be a time consuming operation. Do you want to continue: "y"
+  shell: "{{ edxapp_venv_bin }}/python ./manage.py cms reindex_course --setup --settings={{ edxapp_settings }}"
+  args:
     chdir: "{{ edxapp_code_dir }}"
-    timeout: 60
-    echo: true
   become_user: "{{ common_web_user }}"
   when: EDXAPP_REINDEX_ALL_COURSES
   tags:
```

2017-09-11 14:55 UTC, clemente commented on playbooks/roles/edxapp/tasks/deploy.yml
> +      Re-indexing all courses might be a time consuming operation. Do you want to continue: "y"
It's strange because „expect“ is working well in my devstack…
I had seen --setup but it clearly says that it's for devstack, so can we use it still for sandboxes?
I changed the code to use it.

2017-09-11 14:57 UTC, pomegranited commented on playbooks/roles/edxapp/tasks/deploy.yml
> +      Re-indexing all courses might be a time consuming operation. Do you want to continue: "y"
@clemente  I wasn't able to get `expect` to work at all -- it would timeout every time!  Not sure what's different about my environment though.

But yes, I think it's ok to use that `--setup` argument in this case.  We're setting up a new appserver with an empty localhost ElasticSearch instance, just like devstacks have.

2017-09-11 14:58 UTC, clemente commented on playbooks/roles/edxapp/tasks/deploy.yml
> +    - migrate:db
Done.

2017-09-11 15:46 UTC, pomegranited commented on CHANGELOG.md
> +  - Added `EDXAPP_REINDEX_ALL_COURSES` to rebuild the course index on deloy. Disabled by default.
nit: typo: "deloy" should be "deploy"

2017-09-11 16:04 UTC, pomegranited approved these changes
@clemente -- thanks for those fixes!

:+1: once one nit is fixed.  Also, could you rebase to fix the conflict with CHANGELOG?

Once that's done, you can follow the bot link above to create an OSPR for this change, and ping @gsong to get it into edX's review queue.

- [x] I tested this on my devstack using the PR instructions
- [x] I read through the code
- [x] <strike>I checked for accessibility issues</strike>
- [x] Includes documentation

2017-09-12 01:02 UTC, edx-webhook commented
Thanks for the pull request, @clemente! I've created [OSPR-1888](https://openedx.atlassian.net/browse/OSPR-1888) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

2017-09-12 01:04 UTC, clemente commented
Hi @gsong, I think I'd need your review for this. Thanks.
@pomegranited: Fixed and rebased.

2017-09-13 18:28 UTC, feanil commented on playbooks/roles/edxapp/tasks/deploy.yml
> +    - migrate:db
@clemente @pomegranited why tag this task with the 'migrate and migrate:db' tags?  This seems like it should maybe be tagged with 'install'?

2017-09-14 22:12 UTC, clemente commented on playbooks/roles/edxapp/tasks/deploy.yml
> +    - migrate:db
@feanil @pomegranited  ok, changed tags

2017-10-30 14:44 UTC, coryleeio approved these changes

2017-10-30 15:30 UTC, pomegranited commented
Thanks @coryleeio !  Squashing and merging now.

2017-10-30 15:32 UTC, merged

2017-10-30 15:32 UTC, edx-webhook commented
@clemente 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/4082&entry.1484655318=https://github.com/clemente&entry.752974735=2017-09-10+04:07&entry.1917517419=2017-10-30+15:32&entry.2133058324=Yes) so we can improve your experience in the future.