YONK-752: add j2 templates for scorm xblock static content access
openedx-unsupported/configuration pull request #4085
Opened 2017-09-11 15:35 UTC by wajeeha-khalid

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] Have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?

2017-09-11 15:35 UTC, edx-webhook commented
Thanks for the pull request, @wajeeha-khalid! I've created [OSPR-1887](https://openedx.atlassian.net/browse/OSPR-1887) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

2017-09-11 17:09 UTC, wajeeha-khalid commented
@fredsmith Please review
Also, I dont have access to [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)

2017-09-11 19:30 UTC, fredsmith requested changes
I think this needs to be restructured to move the map for the cors origin out of the server context. It should be included conditionally.  We should also only conditionally include the SCORM locations.  Finally, you'll need to either set a default for your SCORM_PKG_STORAGE_DIR and SCORM_PLAYER_LOCAL_STORAGE_ROOT, probably by pulling them out into an ansible variable, or figure out another way to not reference them if they're not declared.

2017-09-11 19:30 UTC, fredsmith commented on playbooks/roles/nginx/templates/edx/app/nginx/sites-available/extra_locations_lms.j2
> +location ~ ^/{{ EDXAPP_MEDIA_URL }}/{{ XBLOCK_SETTINGS.ScormXBlock.SCORM_PKG_STORAGE_DIR }}/(?P<file>.*) {
This will require either a default or a when defined conditional, because https://github.com/edx/configuration/blob/master/playbooks/roles/edxapp/defaults/main.yml#L635 EDXAPP_XBLOCK_SETTINGS is empty by default.  We don't want to ship these changes for people who aren't using the SCORM xblock.

2017-09-11 19:30 UTC, fredsmith commented on playbooks/roles/nginx/templates/edx/app/nginx/sites-available/extra_locations_lms.j2
> +map $http_origin $cors_origin {
Because you are including this inside the server definition for the LMS, this will attempt to declare this map at the server context.  Maps are only valid at the top level - http context:  http://nginx.org/en/docs/http/ngx_http_map_module.html#map

2017-09-11 19:30 UTC, fredsmith commented on playbooks/roles/nginx/templates/edx/app/nginx/sites-available/static-files-extra.j2
> +map $http_origin $cors_origin {
when you move this map to the global context, you shouldn't duplicate it.

2017-09-11 19:32 UTC, fredsmith commented
Also, your tests failed:  
```
failed: [127.0.0.1] (item=lms) => {"failed": true, "item": "lms", "msg": "AnsibleUndefinedVariable: 'CORS_ORIGIN_WHITELIST' is undefined"}
failed: [127.0.0.1] (item=cms) => {"failed": true, "item": "cms", "msg": "AnsibleUndefinedVariable: 'CORS_ORIGIN_WHITELIST' is undefined"}
```

2017-09-12 09:52 UTC, wajeeha-khalid commented
@fredsmith Where do i define default values for 
`SCORM_PKG_STORAGE_DIR`
and 
`SCORM_PLAYER_LOCAL_STORAGE_ROOT`

I am guessing i should not set it to [mckinsey-internal mckinsey.yml](https://github.com/edx/mckinsey-internal/blob/master/ansible/vars/mckinsey.yml#L138) because this is only for mckinsey where there is xblock setting; where does all edx defaults used by jinja files go to?

2017-09-12 20:03 UTC, fredsmith requested changes
Basically, your role shouldn't reference EDXAPP_ENV_EXTRA, but can reference things that are declared in https://github.com/edx/configuration/blob/master/playbooks/roles/edxapp/defaults/main.yml.  any variables you define in this role should be prefixed with NGINX_.  You also shouldn't define variables in this role that are defined in other roles.

2017-09-12 20:03 UTC, fredsmith commented on playbooks/roles/nginx/defaults/main.yml
> +EDXAPP_ENV_EXTRA:
you don't need to define this variable in this role - the template for the lms is only generated if the edxapp role is used.

2017-09-12 20:03 UTC, fredsmith commented on playbooks/roles/nginx/defaults/main.yml
> +SCORM_PKG_STORAGE_DIR: "scorms"
these variables should be prefixed with NGINX_, and should probably default to the case where this feature is not turned on, eg.  !!null

2017-09-12 20:03 UTC, fredsmith commented on playbooks/roles/nginx/templates/edx/app/nginx/sites-available/extra_locations_lms.j2
> +{% if EDXAPP_ENV_EXTRA.XBLOCK_SETTINGS.ScormXBlock %}
Trigger these blocks based on a top level NGINX variable.   eg.  NGINX_SCORM_PKG_STORAGE_DIR.

2017-09-12 20:03 UTC, fredsmith commented on playbooks/roles/nginx/templates/edx/app/nginx/sites-available/lms.j2
> +
I would conditionalize this based on EDXAPP_CORS_ORIGIN_WHITELIST

2017-09-12 20:03 UTC, fredsmith commented on playbooks/roles/nginx/templates/edx/app/nginx/sites-available/lms.j2
> +  {% for host in EDXAPP_ENV_EXTRA.CORS_ORIGIN_WHITELIST %}
loop over EDXAPP_CORS_ORIGIN_WHITELIST, not EDXAPP_ENV_EXTRA

2017-09-12 20:03 UTC, fredsmith commented on playbooks/roles/nginx/templates/edx/app/nginx/sites-available/extra_locations_lms.j2
> +        root {{ edxapp_media_dir }}/{{ EDXAPP_ENV_EXTRA.XBLOCK_SETTINGS.ScormXBlock.SCORM_PKG_STORAGE_DIR or SCORM_PKG_STORAGE_DIR}};
No one else uses EDXAPP_ENV_EXTRA the way our environment does - you shouldn't use it like this.   We should probably move our environment to use EDXAPP_XBLOCK_SETTINGS instead of EDXAPP_ENV_EXTRA in the settings. https://github.com/edx/configuration/blob/master/playbooks/roles/edxapp/defaults/main.yml#L635

Figure out another way to reference this variable, or just only use the local NGINX role variable.

2017-09-12 20:03 UTC, fredsmith commented on playbooks/roles/nginx/templates/edx/app/nginx/sites-available/static-files-extra.j2
> +      try_files /{{ EDXAPP_ENV_EXTRA.XBLOCK_SETTINGS.ScormXBlock.SCORM_PLAYER_LOCAL_STORAGE_ROOT }}/$file =404;
same as above.  don't reference EDXAPP_ENV_EXTRA.

2017-09-13 10:58 UTC, wajeeha-khalid commented
@fredsmith  Thank you for your suggestions. I have updated changes according to your feedback, also created https://github.com/edx/mckinsey-internal/pull/13 for mckinsey to use edxapp vars

Please review again. Also, please see travis error for npm; any idea about it?

`TASK [edxapp : install node dependencies] **************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "cmd": "/edx/app/edxapp/nodeenvs/edxapp/bin/npm install", "failed": true, "msg": "npm ERR! Linux 4.4.0-93-generic\nnpm ERR! argv \"/edx/app/edxapp/nodeenvs/edxapp/bin/node\" \"/edx/app/edxapp/nodeenvs/edxapp/bin/npm\" \"install\"\nnpm ERR! node v6.11.1\nnpm ERR! npm  v3.10.10\n\nnpm ERR! shasum check failed for /tmp/npm-11195-7b2878f0/registry.npmjs.org/core-js/-/core-js-2.5.1.tgz\nnpm ERR! Expected: ae6874dc66937789b80754ff5428df66819ca50b\nnpm ERR! Actual:   381fdc929403e1676177987659c72a26602f898f\nnpm ERR! From:     https://registry.npmjs.org/core-js/-/core-js-2.5.1.tgz\nnpm ERR! \nnpm ERR! If you need help, you may report this error at:\nnpm ERR!     <https://github.com/npm/npm/issues>\n\nnpm ERR! Please include the following file with any support request:\nnpm ERR!     /edx/app/edxapp/edx-platform/npm-debug.log", "rc": 1, "stderr": "npm ERR! Linux 4.4.0-93-generic\nnpm ERR! argv \"/edx/app/edxapp/nodeenvs/edxapp/bin/node\" \"/edx/app/edxapp/nodeenvs/edxapp/bin/npm\" \"install\"\nnpm ERR! node v6.11.1\nnpm ERR! npm  v3.10.10\n\nnpm ERR! shasum check failed for /tmp/npm-11195-7b2878f0/registry.npmjs.org/core-js/-/core-js-2.5.1.tgz\nnpm ERR! Expected: ae6874dc66937789b80754ff5428df66819ca50b\nnpm ERR! Actual:   381fdc929403e1676177987659c72a26602f898f\nnpm ERR! From:     https://registry.npmjs.org/core-js/-/core-js-2.5.1.tgz\nnpm ERR! \nnpm ERR! If you need help, you may report this error at:\nnpm ERR!     <https://github.com/npm/npm/issues>\n\nnpm ERR! Please include the following file with any support request:\nnpm ERR!     /edx/app/edxapp/edx-platform/npm-debug.log\n", "stdout": "", "stdout_lines": []}
	to retry, use: --limit @/edx/app/edx_ansible/edx_ansible/docker/plays/edxapp.retry
PLAY RECAP *********************************************************************
127.0.0.1                  : ok=63   changed=50   unreachable=0    failed=1   `

2017-09-13 12:36 UTC, fredsmith requested changes
some minor fixes left.  I think your failing travis build was due to npm being down/unavailable.

2017-09-13 12:36 UTC, fredsmith commented on playbooks/roles/edxapp/defaults/main.yml
> +EDXAPP_SCORM_PKG_STORAGE_DIR: ""
These should default to !!null.

2017-09-13 12:36 UTC, fredsmith commented on playbooks/roles/nginx/templates/edx/app/nginx/sites-available/lms.j2
> +{% if EDXAPP_CORS_ORIGIN_WHITELIST %}
Since this defaults to an empty list, it will always be defined.   you should do:
```
{% if EDXAPP_CORS_ORIGIN_WHITELIST|length > 0​ %}
```

2017-09-13 12:36 UTC, fredsmith commented on playbooks/roles/nginx/templates/edx/app/nginx/sites-available/static-files-extra.j2
> +      try_files /{{ EDXAPP_XBLOCK_SETTINGS.ScormXBlock.SCORM_PLAYER_LOCAL_STORAGE_ROOT or EDXAPP_SCORM_PLAYER_LOCAL_STORAGE_ROOT}}/$file =404;
I don't understand why you'd want to do an 'or' here - just use the EDXAPP_SCORM_PLAYER_LOCAL_STORAGE_ROOT variable. it needs to be defined to get into this block, anyway.

2017-09-13 12:36 UTC, fredsmith commented on playbooks/roles/nginx/templates/edx/app/nginx/sites-available/static-files-extra.j2
> +    try_files /{{ EDXAPP_XBLOCK_SETTINGS.ScormXBlock.SCORM_PLAYER_LOCAL_STORAGE_ROOT or EDXAPP_SCORM_PLAYER_LOCAL_STORAGE_ROOT}}/$file =404;
same as above, just use EDXAPP_SCORM_PLAYER_LOCAL_STORAGE_ROOT

2017-09-13 12:36 UTC, fredsmith commented on playbooks/roles/nginx/templates/edx/app/nginx/sites-available/extra_locations_lms.j2
> +    location ~ ^/{{ EDXAPP_MEDIA_URL }}/{{ EDXAPP_XBLOCK_SETTINGS.ScormXBlock.SCORM_PKG_STORAGE_DIR or EDXAPP_SCORM_PKG_STORAGE_DIR}}/(?P<file>.*) {
just use EDXAPP_SCORM_PKG_STORAGE_DIR, don't bother looking into EDXAPP_XBLOCK_SETTINGS.  I don't think this or block will ever do what we want, especially since we're gating this entire section on EDXAPP_SCORM_PKG_STORAGE_DIR being defined.

2017-09-13 15:10 UTC, wajeeha-khalid commented
@fredsmith updated; travis still cannot convert some ascii

2017-09-13 18:03 UTC, feanil submitted a review, later dismissed

2017-09-13 18:03 UTC, feanil commented on CHANGELOG.md
> +
Changelog entries should go at the top of the file.

2017-09-13 18:03 UTC, feanil commented on playbooks/roles/nginx/templates/edx/app/nginx/sites-available/extra_locations_lms.j2
> +        expires 31536000s;
Can the files change? Are these files hashed or some how guaranteed to be unique?   If the change and aren't uniquely named, we may want to reduce the length of the cache expiry.

2017-09-13 18:04 UTC, feanil requested changes
Meant to request changes.

2017-09-13 19:11 UTC, wajeeha-khalid commented
@feanil  I have updated changelog. 
For cache expiry of these files; they should not change once tested and finalized. In case during testing we need to refresh cache, can we do that explicitly on testing servers? 
After confirming from McKinsey, I have reduced cache to 6 months instead of one year anyways.

2017-09-13 19:26 UTC, feanil commented
@wajeeha-khalid remember this caching will take place on the Client not on the server so there will be nothing we can do once the client caches the content until it expires.   Can you tell me more about what these files are to help me understand the use case?

2017-09-13 19:30 UTC, wajeeha-khalid commented
@feanil We have made these changes in order to use [SCORM xblock by appsembler](https://github.com/appsembler/edx_xblock_scorm/blob/nyif/master/README.md)

`EDXAPP_SCORM_PKG_STORAGE_DIR` is the location of the directory where SCORM files will be uploaded from Studio view of SCORM Xblock and then the course content will be rendered at LMS in SCORM Xblock

2017-09-13 19:30 UTC, wajeeha-khalid commented
@feanil FYI its related ticket is https://openedx.atlassian.net/browse/YONK-752

2017-09-13 19:32 UTC, feanil commented
@wajeeha-khalid I understand those things but that does not answer my question.  What will the actual files be?  HTML partials? JS? CSS? something else?

2017-09-13 19:36 UTC, fredsmith commented
@feanil https://github.com/appsembler/edx_xblock_scorm/tree/nyif/master/scormxblock/static is installed via pip - html, javascript, css, etc. none have versioned naming schemes, afaict.

2017-09-13 19:54 UTC, fredsmith commented
@wajeeha-khalid you forcepushed over my change that removed the stray unicode character at https://github.com/edx/configuration/pull/4085/files#diff-51941ae57c3547868d18d7b4f6480c9cR47 so travis broke again - please re-implement that change.  There is a U+200b after the 0 on that line.

2017-09-13 19:56 UTC, wajeeha-khalid commented
@feanil I will contain .xsd .swf .jpg .xml and .js

2017-09-13 19:58 UTC, feanil commented
And none of those are hashed correct? Their names are static?

2017-09-13 19:58 UTC, fredsmith commented
![](https://files.derf.us/atlas-2017-09-13-15-58-11.png)

2017-09-13 20:07 UTC, wajeeha-khalid commented
@feanil yes

@fredsmith oops; sorry updating

2017-09-13 20:37 UTC, feanil commented
@wajeeha-khalid  if their names are static, I recommend a much smaller expiration date because if you need to wait 6-months before the asset is refreshed, it will make it very hard to deploy any updates to the scorm settings in the future.  For example when there is a new version of the upstream xblock.

2017-09-14 07:04 UTC, wajeeha-khalid commented
@feanil This caches the course content that we upload to that xblock (at `EDXAPP_SCORM_PKG_STORAGE_DIR`) and that course content won't change frequently. This cache is not for itself xblock's static content (i.e. [scormxblock/static](https://github.com/appsembler/edx_xblock_scorm/tree/nyif/master/scormxblock/static)) so, if new version of xblock comes in it should not affect this cache.

Do you still think of a reason to decrease time?

2017-09-14 12:12 UTC, fredsmith commented
@wajeeha-khalid I would set it to 1 week, at the most.

2017-09-14 12:38 UTC, fredsmith approved these changes

2017-09-14 13:18 UTC, wajeeha-khalid commented
reduced cache to 1 week as per Fred's suggestion; IMO longer cache should also not create problem but to be on safe side i have now set it to 1 week

2017-09-14 15:29 UTC, feanil approved these changes

2017-09-14 15:31 UTC, merged