Feanil/jenkins workers mongo update
openedx-unsupported/configuration pull request #4160
Opened 2017-10-18 19:27 UTC by feanil

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

2017-10-19 15:12 UTC, jdmulloy requested changes

2017-10-19 15:12 UTC, jdmulloy commented on playbooks/roles/mongo_3_2/tasks/main.yml
> +  when: initialize_replica_set
These tasks are needed in situations that don't involve initializing a replica set, such as updating a replica set configuration or adding mongo users. Can we add a tag to the tasks that need to be skipped and use --skip-tags instead?

2017-10-20 14:08 UTC, feanil commented on playbooks/roles/mongo_3_2/tasks/main.yml
> +  when: initialize_replica_set
@jdmulloy any suggestions on what to name that tag?

2017-10-20 17:26 UTC, jdmulloy commented on playbooks/roles/mongo_3_2/tasks/main.yml
> +  when: initialize_replica_set
@feanil I don't have any great ideas. There is a wiki page of tags, but I haven't found it to be to helpful. https://openedx.atlassian.net/wiki/spaces/OpenOPS/pages/39584735/Role+Life-cycle+Tags

Maybe `skip_for_jenkins`, although I don't really like it.

2017-10-27 17:55 UTC, feanil commented on playbooks/roles/mongo_3_2/tasks/main.yml
> +  when: initialize_replica_set
@jdmulloy looking more closely at the tasks that I am adding the when condition to.  All of them expect the replica set to be created or don't work.  Thinking back, that is why I had to add the when condition to these tasks in the first place.

2017-10-27 19:39 UTC, estute commented on util/packer/jenkins_worker.json
>        "delete_or_keep": "{{user `delete_or_keep`}}"
@feanil I think you will need to expose JENKINS_WORKER_KEY_URL in the packer script as an environment variable

2017-10-27 19:43 UTC, estute requested changes
See comment

2017-10-30 18:09 UTC, feanil commented on util/packer/jenkins_worker.json
>        "delete_or_keep": "{{user `delete_or_keep`}}"
I had forgotten to push up that commit.  @estute ready for re-review.

2017-10-30 21:05 UTC, estute approved these changes

2017-10-31 13:45 UTC, feanil commented
@jdmulloy I think this is ready for a final review.

2017-11-01 14:38 UTC, jdmulloy approved these changes

2017-11-01 15:45 UTC, merged