Move splunk data from cold to frozen on s3 bucket
openedx-unsupported/configuration pull request #4218
Opened 2017-11-27 10:10 UTC by nadeemshahzad

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

2017-11-27 10:10 UTC, nadeemshahzad commented
@edx/devops Please review

2017-11-27 18:25 UTC, fredsmith approved these changes
two nits, otherwise LGTM

2017-11-27 18:25 UTC, fredsmith commented on playbooks/roles/splunk-server/templates/opt/splunk/bin/coldToFrozenS3.j2
> +#!/bin/bash
should be:
```
#! /usr/bin/env bash
```
for portability

2017-11-27 18:25 UTC, fredsmith commented on playbooks/roles/splunk-server/templates/opt/splunk/bin/coldToFrozenS3.j2
> +    echo "Usage: /bin/bash coldToFrozenS3 <bucket_dir_to_archive>"
no need to specify the interpreter.

2017-11-27 18:28 UTC, fredsmith requested changes
I think this will error without a default value.  Alternately, make installing your cold to frozen script conditional based on this variable being defined.

2017-11-27 18:28 UTC, fredsmith commented on playbooks/roles/splunk-server/defaults/main.yml
> +SPLUNK_FROZEN_DB_S3_BUCKET: "{{ SPLUNK_FROZEN_DB_DATA_S3_BUCKET }}"
I think this should have a default value

2017-11-28 13:56 UTC, nadeemshahzad commented
@fredsmith Can you please review the changes?

2017-11-29 15:08 UTC, fredsmith approved these changes

2017-11-30 08:09 UTC, merged