Ibrahimahmed443/wl 1043 sandbox automation
openedx-unsupported/configuration pull request #4221
Opened 2017-11-28 12:39 UTC by ibrahimahmed443

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

2017-11-28 12:41 UTC, ibrahimahmed443 commented
@bill-filler @afzaledx Here's the work in progress related to the ansible scripts.

2017-12-04 15:26 UTC, feanil commented
@ibrahimahmed443 this is very specific to edx, our specific DNS setting for whitelabels shouldn't be exposed here.  There should be variables that we override in sandbox-internal that allows us to add more sites.

2017-12-21 13:51 UTC, fredsmith commented on playbooks/roles/discovery/defaults/main.yml
> +DISCOVERY_VERSION: "hasnain-naveed/WL-1295"
why?

2017-12-21 13:51 UTC, fredsmith commented on playbooks/roles/discovery/defaults/main.yml
> +    VERSION: "hasnain-naveed/WL-1295"
you're setting this to the same as the above.  seems unnecessary.  Also, we shouldn't change the default to a dev branch.

2017-12-21 14:41 UTC, ibrahimahmed443 commented on playbooks/roles/discovery/defaults/main.yml
> +    VERSION: "hasnain-naveed/WL-1295"
This is because DISCOVERY_VERSION is overridden from somewhere else. So I had to set this explicitly here. We will remove this code anyway, as the branch gets merged.

2018-01-03 10:28 UTC, ibrahimahmed443 commented
@fredsmith its ready for another look.

2018-01-05 16:31 UTC, fredsmith requested changes
We shouldn't be calling ansible-playbook -c local from within a playbook.  Please find a way to do that using roles.

2018-01-05 16:31 UTC, fredsmith commented on playbooks/roles/whitelabel/tasks/main.yml
> +    /edx/app/edx_ansible/venvs/edx_ansible/bin/ansible-playbook -i localhost, -c local
the relevant parts of this playbook should either be included in your playbook, or should have their roles meta'ed in as dependencies.

2018-01-05 16:31 UTC, fredsmith commented on playbooks/roles/whitelabel/defaults/main.yml
> +  - "GRANT ALL PRIVILEGES ON {{ DISCOVERY_DEFAULT_DB_NAME }}.* TO '{{ DISCOVERY_MYSQL_USER }}'@'{{ DISCOVERY_MYSQL }}';"
the app user should only have the required permissions, not all permissions.

2018-01-05 16:31 UTC, fredsmith commented on playbooks/edx-east/whitelabel.yml
> +    - "roles/edxapp/defaults/main.yml"
I'm not crazy about this, but I see that there is prior art in edx_provision.yml for including another role's vars.    The right way to do this is to have a vars role that both roles include, but I think that is out of scope here.

2018-01-08 17:53 UTC, bill-filler commented
@ibrahimahmed443 
please address the comments that Fred made last week so we can get this landed

2018-01-12 12:46 UTC, ibrahimahmed443 commented
@fredsmith I copied the required part from discovery into my playbook [here](https://github.com/edx/configuration/pull/4221/commits/735a0f393d5d19dd8783b2113d062f9a2c62f25c); however, by doing so I started getting the same errors as  we would if we setup discovery by ticking the discovery checkbox from Jenkins. That is, "Access denied for user 'migrate'@'localhost' to database 'discovery'".

If I run the discovery playbook directly as I was doing earlier, this runs successfully. I am not fully aware of the history of why this happens, but it was documented by another team that discovery doesn't work by ticking the checkbox, rather we have to run the playbook after setting up the sandbox. And I was doing a similar thing by ansible-playbook -c local.

2018-01-29 18:48 UTC, fredsmith commented
@ibrahimahmed443 have you tried to make sure that the edxlocal role is creating the correct databases before your discovery playbook is run?  

The database appears to be defined in here:  https://github.com/edx/configuration/blob/master/playbooks/roles/edxlocal/defaults/main.yml#L16

The discoery database should be created (https://github.com/edx/configuration/blob/master/playbooks/roles/edxlocal/tasks/main.yml#L13) and granted access (https://github.com/edx/configuration/blob/master/playbooks/roles/edxlocal/tasks/main.yml#L30)

So if that task is run before your failed task above, something is not being passed properly into your task.  If that task is not run before your failed task, you should figure out how to structure the meta dependencies to make it happen first.

2018-02-05 16:20 UTC, bill-filler commented
@ibrahimahmed443 
courses no longer configured for WL sites. I see none on HMS, Wharton and mitxpro after configuring the sandbox

2018-02-06 08:32 UTC, ibrahimahmed443 commented
@bill-filler On Friday, Kashif pointed out that we should be able to specify the "course display name/title" and we found out the management command used to create course does not support that. We created a new branch in LMS: hasnain-naveed/create_course_change which makes this change. Hence for now, while creating a sandbox, this branch needs to be specified in the edxapp version field.

2018-02-07 14:23 UTC, ibrahimahmed443 commented
@fredsmith Can you give a thumbs up on this PR?

2018-02-07 16:41 UTC, fredsmith approved these changes
Looks great 👍

2018-02-13 11:25 UTC, merged