OPS-2492 Support redis as an ecommerce celery backend in edx/configur…
openedx-unsupported/configuration pull request #4232
Opened 2017-12-04 16:11 UTC by coryleeio

…ation Ansible

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

2017-12-04 18:41 UTC, feanil approved these changes
One nit to fix if you want.

2017-12-04 18:41 UTC, feanil commented on playbooks/roles/ecommerce/defaults/main.yml
> +ECOMMERCE_CELERY_BROKER_HOSTNAME: '{{ ECOMMERCE_BROKER_HOST }}'
NIT: You should flip this around so the default value for `ECOMMERCE_BROKER_HOST` is `{{ ECOMMERCE_CELERY_BROKER_HOST }}` and then set the default value for `ECOMMERCE_CELERY_BROKER_HOST` to `{{ ansible_default_ipv4.address }}`

That way when it comes time to delete things we can just remove the line for the old var and not have to do any other updates.

2017-12-05 16:50 UTC, jdmulloy requested changes

2017-12-05 16:50 UTC, jdmulloy commented on playbooks/roles/ecommerce/defaults/main.yml
> +ECOMMERCE_CELERY_BROKER_HOSTNAME: '{{ ECOMMERCE_BROKER_HOST }}'
@feanil How will this affect configurations that are currently setting `ECOMMERCE_BROKER_HOST`? What Cory did here is similar to what I did in #4189 for backwards compatibility.

2017-12-05 16:50 UTC, jdmulloy commented on playbooks/roles/ecommerce/defaults/main.yml
> +ECOMMERCE_BROKER_URL: '{{ ECOMMERCE_CELERY_BROKER_TRANSPORT }}://{{ ECOMMERCE_BROKER_USERNAME }}:{{ ECOMMERCE_BROKER_PASSWORD }}@{{ ECOMMERCE_CELERY_BROKER_HOSTNAME }}:{{ ECOMMERCE_BROKER_PORT }}'
Some of these variables say Celery and some don't. Can and/or should we rework it to make them consistent? Unfortunately it will require some changes to existing configs and some backwards compatibility. So I would like opinions on whether or not it's worth it.

2017-12-05 18:01 UTC, coryleeio commented on playbooks/roles/ecommerce/defaults/main.yml
> +ECOMMERCE_BROKER_URL: '{{ ECOMMERCE_CELERY_BROKER_TRANSPORT }}://{{ ECOMMERCE_BROKER_USERNAME }}:{{ ECOMMERCE_BROKER_PASSWORD }}@{{ ECOMMERCE_CELERY_BROKER_HOSTNAME }}:{{ ECOMMERCE_BROKER_PORT }}'
Took care of this by removing celery so it would be consistent with the other ecommerce variables if not edxapp, for consistency as we discussed.

2017-12-05 18:07 UTC, coryleeio commented on playbooks/roles/ecommerce/defaults/main.yml
> +ECOMMERCE_CELERY_BROKER_HOSTNAME: '{{ ECOMMERCE_BROKER_HOST }}'
I went ahead and flipped them for ease, I'd say it's not a big deal if they're not perfectly consistent.  The tickets are pretty straight forward anyway, just having you delete a variable or two for cleanup

2017-12-05 18:22 UTC, jdmulloy requested changes

2017-12-05 18:22 UTC, jdmulloy commented on playbooks/roles/ecommerce/defaults/main.yml
> +ECOMMERCE_BROKER_HOST: '{{ ECOMMERCE_BROKER_HOSTNAME }}'
Now that the diff has been simplified, I'm wondering if we need to rename `ECOMMERCE_BROKER_HOST` to `ECOMMERCE_BROKER_HOSTNAME`

2017-12-05 18:24 UTC, coryleeio commented on playbooks/roles/ecommerce/defaults/main.yml
> +ECOMMERCE_BROKER_HOST: '{{ ECOMMERCE_BROKER_HOSTNAME }}'
We need to keep ECOMMERCE_BROKER_HOST for backwards compatibility until hawthorne I believe

2017-12-05 18:49 UTC, coryleeio commented on playbooks/roles/ecommerce/defaults/main.yml
> +ECOMMERCE_CELERY_BROKER_HOSTNAME: '{{ ECOMMERCE_BROKER_HOST }}'
@feanil @jdmulloy I realized actually you can't flip them unless you continue to use HOST in the URL instead of hostname, otherwise you will overwrite what the user may have set HOST to with HOSTNAME

example:
If we use the new value of HOSTNAME in the URL
user has legacy value of HOST set to 10.10.10.10
we set HOSTNAME to '{{ ansible_default_ipv4.address }}' , they dont have HOSTNAME in the config so in the URL we just changed their host to localhost.

We could continue to key the URL off of the old value HOST to fix this, however then you can't just delete the variable anymore.   I'm going to revert this change I made to align it back with the way the other variable is being done for consistency and to not break backwards compatibility.

2017-12-05 19:07 UTC, coryleeio commented on playbooks/roles/ecommerce/defaults/main.yml
> +ECOMMERCE_BROKER_HOST: '{{ ECOMMERCE_BROKER_HOSTNAME }}'
After discussion we removed Hostname keeping only host.

2017-12-05 22:55 UTC, feanil approved these changes

2017-12-06 21:20 UTC, jdmulloy requested changes

2017-12-06 21:20 UTC, jdmulloy commented on CHANGELOG.md
> +  - Added `ECOMMERCE_BROKER_TRANSPORT` with a default value of 'ampq' to be backwards compatible with rabbit.  Set to 'redis' if you wish to use redis instead of rabbit as a queue for ecommerce.
Can you also mention the equivalent variable for worker?

2017-12-06 21:20 UTC, jdmulloy commented on playbooks/roles/ecomworker/defaults/main.yml
> +ECOMMERCE_WORKER_BROKER_TRANSPORT: 'amqp'
Maybe this should reference ECOMMERCE_BROKER_TRANSPORT.

i.e. `ECOMMERCE_WORKER_BROKER_TRANSPORT: '{{ ECOMMERCE_BROKER_TRANSPORT }}'`

2017-12-06 21:39 UTC, coryleeio commented on playbooks/roles/ecomworker/defaults/main.yml
> +ECOMMERCE_WORKER_BROKER_TRANSPORT: 'amqp'
That is in the other PR with the other worker shims:
https://github.com/edx/edx-internal/pull/266/files

2017-12-06 21:56 UTC, coryleeio commented on CHANGELOG.md
> +  - Added `ECOMMERCE_BROKER_TRANSPORT` with a default value of 'ampq' to be backwards compatible with rabbit.  Set to 'redis' if you wish to use redis instead of rabbit as a queue for ecommerce.
For our reference - we discussed this and decided to split it into two entries.

2017-12-07 15:25 UTC, jdmulloy approved these changes

2017-12-07 19:59 UTC, merged