Add Analytics API configuration parameters to edxapp configuration file
openedx-unsupported/configuration pull request #4238
Opened 2017-12-06 17:43 UTC by jaebradley

# Introduction
The `Learner - Growth` team is creating a test that will display a learner's metrics in a view in the LMS. We will be relying on data available via the [`edx-analytics-data-api`](https://github.com/edx/edx-analytics-data-api). 

In order to connect to the Analytics API, we need to specify Analytics API configuration parameters in the LMS configuration file.

# TODO

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

2017-12-06 17:47 UTC, jaebradley commented on playbooks/roles/edxapp/defaults/main.yml
> +EDXAPP_LMS_ANALYTICS_API_URL: 'http://localhost:18100'
I know the [`EDXAPP_ECOMMERCE_API_URL`](https://github.com/edx/configuration/blob/master/playbooks/roles/edxapp/defaults/main.yml#L589) points to `http://localhost:8002/api/v2` but I didn't make this URL value more specific because it looks like [there are Analytics API paths that live at the same level as `api` that we may want to access](https://github.com/edx/edx-analytics-data-api/blob/master/analyticsdataserver/urls.py). Let me know if this is the wrong approach.

2017-12-06 17:49 UTC, jaebradley commented on playbooks/roles/edxapp/defaults/main.yml
> +EDXAPP_LMS_ANALYTICS_API_URL: 'http://localhost:18100'
@fredsmith verified that `18100` is the nginx port value for the Analytics API in sandboxes.

2017-12-07 14:31 UTC, fredsmith approved these changes

2017-12-07 14:32 UTC, fredsmith requested changes
You're setting a default, but you're not using this value.  it needs to be added to the LMS env dictionary.

2017-12-07 14:44 UTC, fredsmith approved these changes

2017-12-07 14:51 UTC, fredsmith requested changes

2017-12-07 14:51 UTC, fredsmith commented on playbooks/roles/edxapp/defaults/main.yml
> +  ANALYTICS_API_KEY: "{{ EDXAPP_LMS_ANALYTICS_API_KEY }}"
should go in lms_auth_config, not env.

2017-12-07 16:20 UTC, fredsmith commented on playbooks/roles/edxapp/defaults/main.yml
> +  ANALYTICS_API_URL: "{{ EDXAPP_LMS_ANALYTICS_API_URL }}"
The URL should go in env_config, the key should go in auth_config.

2017-12-11 13:40 UTC, fredsmith approved these changes
:shipit:

2017-12-11 13:41 UTC, merged