Add BRANCH_KEY to configure branch.io banners.
openedx-unsupported/configuration pull request #4241
Opened 2017-12-07 11:41 UTC by waheedahmed

LEARNER-2731

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

2017-12-07 11:41 UTC, waheedahmed commented
@fredsmith, @feanil Can I get a quick review for this PR please?

2017-12-08 13:23 UTC, feanil requested changes
Can you also link to the edx-platform PR that integrates this setting into the platform?

2017-12-08 13:23 UTC, feanil commented on CHANGELOG.md
> +
Changelog entries should go at the top of the file. not at the bottom.

2017-12-08 13:23 UTC, feanil commented on playbooks/roles/edxapp/defaults/main.yml
> +  BRANCH_KEY: "{{ EDXAPP_BRANCH_KEY }}"
`BRANCH_KEY` is a very generic name, please change it to `BRANCH_IO_KEY` and please change `EDXAPP_BRANCH_KEY` to `EDXAPP_BRANCH_IO_KEY`

2017-12-08 13:35 UTC, waheedahmed commented
@feanil made the suggested changes and here is the platform PR https://github.com/edx/edx-platform/pull/16823, kindly take another look.

2017-12-08 13:52 UTC, feanil approved these changes

2017-12-08 14:13 UTC, merged