Adding in a new go-agent to use for marketing pipelines. Contains nec…
openedx-unsupported/configuration pull request #4249
Opened 2017-12-13 22:24 UTC by Dillon-Dumesnil

…essary modules to make requirements in edx-mktg

@macdiesel @feanil 

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

2017-12-14 16:15 UTC, Dillon-Dumesnil commented on docker/build/go-agent-marketing/Dockerfile
> +    apt-get install -y rvm && /bin/bash -c "source /usr/share/rvm/scripts/rvm && \
I have the /bin/bash -c "{commands}" here because it failed in travis without it. I'm not sure if the merged version of this PR should also have it or not so if I could have feedback on that, that would be awesome and I'll update accordingly.

2017-12-14 16:17 UTC, Dillon-Dumesnil commented on docker/build/go-agent-marketing/README.rst
> +``docker exec -i -t CONTAINER-ID tail -f /var/log/go-agent/go-agent.log``
Throughout this file, I'm not sure if there are areas that should be switched from "go-agent" to "go-agent-marketing". If you see any parts that are incorrect, please let me know.

2017-12-14 16:21 UTC, Dillon-Dumesnil commented
PR is finally ready for review. Please take a look when you have a chance. Travis test is failing due to the incomplete URL in the go-agent-marketing/Dockerfile

2017-12-14 19:29 UTC, Dillon-Dumesnil commented
@robrap

2017-12-19 15:15 UTC, Dillon-Dumesnil commented
@feanil The way this is currently designed, it requires manual input in the Dockerfile for the ECS URL and in the go-agent-marketing/config/autoregister.properties file for the server's autoregister key. FYI @doctoryes

2017-12-21 16:58 UTC, feanil commented on docker/build/go-agent/Dockerfile
> -RUN apt-get update && apt-get install -y \
Do this later as a cleanup PR.  Just incase we need to fall back to this agent.

2017-12-21 17:08 UTC, coryleeio requested changes

2017-12-21 17:08 UTC, coryleeio commented on docker/build/go-agent-marketing/README.rst
> +``docker exec -i -t CONTAINER-ID tail -f /var/log/go-agent/go-agent.log``
I think what's confusing here is that the doc is just copy pasted from:
https://hub.docker.com/r/gocd/gocd-agent-deprecated/



replace gocd/gocd-agent with edx/go-agent     in the docs for the original, and in the docs for the marketing one replace it with 'edx/go-agent-marketing'

I think that will make more sense

2017-12-21 17:08 UTC, coryleeio commented on docker/build/go-agent-marketing/Dockerfile
> +FROM ############.dkr.ecr.us-east-1.amazonaws.com/edx/release-pipeline/prod-tools-goagent:latest
Go ahead and just use a local image here, and just tell the user to build the go-agent first locally in the docs, dont pull it from ECR

2017-12-21 19:10 UTC, coryleeio approved these changes

2017-12-21 19:10 UTC, coryleeio commented on docker/build/go-agent-marketing/Dockerfile
> +# !!!!NOTICE!!!! ---- Runner of this pipeline take heed!! You must replace the following URL with the REAL URL
I wouldn't say URL, I would either delete this comment, or explain that this should be a tag on a locally build image of the go-agent

2017-12-22 14:10 UTC, macdiesel approved these changes

2017-12-22 14:21 UTC, merged