Adding the acquia github key directly into the goagent
openedx-unsupported/configuration pull request #4264
Opened 2017-12-21 16:06 UTC by Dillon-Dumesnil

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

2017-12-21 17:41 UTC, Dillon-Dumesnil commented
FYI @robrap

2017-12-21 19:39 UTC, macdiesel requested changes

2017-12-21 19:39 UTC, macdiesel commented on docker/build/go-agent/Dockerfile
> +ADD docker/build/go-agent/files/acquia_github_key.pem /var/go/.ssh/id_rsa
This overwrites the github key. You need to give it a different name.

2017-12-21 19:41 UTC, macdiesel commented on docker/build/go-agent/Dockerfile
> +ADD docker/build/go-agent/files/acquia_github_key.pem /var/go/.ssh/id_rsa
And you will also need to modify the marketing jobs that use the key to point to this new location.

2017-12-21 21:07 UTC, Dillon-Dumesnil commented
FYI @macdiesel I'm changing this to put the acquia key in the marketing go agent instead of the regular one.

Also, do I need to run these commands after setting up my acquia key as well?

`# setup the known_hosts
RUN touch /var/go/.ssh/known_hosts && \
    chmod 600 /var/go/.ssh/known_hosts && \
    chown go:go /var/go/.ssh/known_hosts && \
    ssh-keyscan -t rsa,dsa github.com > /var/go/.ssh/known_hosts
`

2017-12-21 21:17 UTC, coryleeio approved these changes

2017-12-22 14:08 UTC, macdiesel approved these changes

2017-12-22 14:17 UTC, merged