Removing config since it is being added into terraform
openedx-unsupported/configuration pull request #4268
Opened 2017-12-22 22:26 UTC by Dillon-Dumesnil

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

2017-12-27 14:56 UTC, coryleeio requested changes

2017-12-27 14:56 UTC, coryleeio commented on docker/build/go-agent-marketing/config/autoregister.properties
> -agent.auto.register.key=dev-only-override-this-key
build is failing bc this is still referenced in the Dockerfile

2017-12-27 16:16 UTC, Dillon-Dumesnil commented on docker/build/go-agent-marketing/config/autoregister.properties
> -agent.auto.register.key=dev-only-override-this-key
Resolved

2017-12-28 21:50 UTC, coryleeio approved these changes

2017-12-28 21:51 UTC, merged