Fix location of sass variables for simple-theme role
openedx-unsupported/configuration pull request #4396
Opened 2018-03-20 16:11 UTC by akovari

Configuration Pull Request
---

*Testing instructions*:
- use docker based devstack, master, enable comprehensive theming.
- in lms shell:

    export PYTHONUNBUFFERED=1
    source /edx/app/edx_ansible/venvs/edx_ansible/bin/activate
    cd /edx/app/edx_ansible/edx_ansible/playbooks
     # Here comes the part you'll want to customize (this line is in README.rst too):
    ansible-playbook -i localhost, -c local run_role.yml -e role=simple_theme  -e configuration_version=master -e edx_platform_version=master -e EDXAPP_DEFAULT_SITE_THEME=mytheme2 -e '{"SIMPLETHEME_SASS_OVERRIDES": [{"variable": "main-color", "value":"#823456"}, {"variable": "action-primary-bg", "value":"$main-color"}]}' -e EDXAPP_COMPREHENSIVE_THEME_SOURCE_REPO="https://github.com/open-craft/edx-theme/" -e EDXAPP_COMPREHENSIVE_THEME_VERSION="harvard-dcex" -e edxapp_user=root -e common_web_group=www-data -e SIMPLETHEME_ENABLE_DEPLOY=true -e '{"SIMPLETHEME_STATIC_FILES_URLS": [{"url": "http://docs.ansible.com/ansible/latest/_static/images/logo_invert.png", "dest":"lms/static/images/logo.png"}, {"url": "http://docs.ansible.com/favicon.ico", "dest":"lms/static/images/favicon.ico"}]}' -e '{"EDXAPP_COMPREHENSIVE_THEME_DIRS":["/edx/var/edxapp/themes"], "EDXAPP_ENABLE_COMPREHENSIVE_THEMING": true}'

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

2018-03-20 16:11 UTC, edx-webhook commented
Thanks for the pull request, @akovari! I've created [OSPR-2310](https://openedx.atlassian.net/browse/OSPR-2310) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     If you like, you can add yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

2018-03-21 18:22 UTC, nedbat commented
@akovari Thanks for the contribution!  Will you be signing the contributor agreement? Or are you covered by an existing company's agreement?
Also, I'm concerned that you say there is a problem with the UI, and with accessibility.  Are you sure this is the right direction to be going?

2018-03-26 09:13 UTC, akovari commented
@nedbat sorry for late response, I created this PR so we can discuss it internally but now I need to provide more clarifications:
- I should be covered by OpenCraft's agreement.
- The problem in the UI was a copy&paste error, there is no UI issue with this PR, it merely the locations of sass files in the simple_theme Ansible role

2018-03-26 09:18 UTC, akovari commented
Also, just to provide more context, after edX started using `theme-color` mixin from Bootstrap, it is no longer possible to override `header-bg` and `footer-bg` variables (because they are not used anymore) so I think a simple solution for now would be: https://github.com/open-craft/opencraft/pull/289

2018-03-27 10:46 UTC, clemente commented on playbooks/roles/simple_theme/README.rst
> +Note, that header and footer background coolor needs to be overriden using SIMPLETHEME_EXTRA_SASS variable, previously those colors were defined as SASS variables, now they are defined using bootstra
typo: coolor.  needs → need
were defined as SASS variables ← it can be useful to add the names: $header_bg
You can say „since Hawthorn“ instead of „now“.
„ and to override just footer and header background now needs to be done this way.“ ← can be removed or included in the previous phrases if you want.

2018-03-28 18:12 UTC, clemente requested changes

2018-03-28 18:12 UTC, clemente commented on playbooks/roles/xqueue/templates/xqueue_consumer.conf.j2
> +command={{ xqueue_venv_bin }}/django-admin.py run_consumer --pythonpath={{ xqueue_code_dir }} --settings=xqueue.{{ XQUEUE_SETTINGS }}
This file shouldn't be changed as part of this PR, right?
Could you remove it?
You can squash your commits whenever you feel it's ready (edX always wants to see 1 commit).

2018-03-28 18:38 UTC, nedbat commented
@akovari Thanks, we have you now as an OpenCraft contributor.

2018-03-28 18:39 UTC, nedbat commented
@akovari Ping me when you are ready for an edX review.

2018-04-02 09:46 UTC, akovari commented
Screenshot of the hawthorn deployed sandbox after invoking updated simple_theme from this PR:

![screenshot-2018-3-31 your platform name here](https://user-images.githubusercontent.com/1730454/38192054-715c6f28-366b-11e8-941d-884e05278e4a.png)

2018-04-02 11:27 UTC, clemente approved these changes
:+1: ok, this is finally complete. Great work @akovari !

The change to README.rst is small but represents a lot of tests. The old way of setting colors doesn't work in Hawthorn. The new example reflects the new way of setting colors, which includes $theme-colors (a Bootstrap „map“) and requires overwriting header and footer (because they don't have a specific $theme-colors).
In addition the role was fixed to look for the new files in the right places (earlier, deployment failed because of this).

- [X] I tested this: I ran the role in local (inside my docker devstack) with the example command (from README.rst) and it created a new theme with the header color, footer color, primary color (used e.g. for button backgrounds) and link color that I requested.
- [X] I read through the code
- [X] I checked for accessibility issues: none
- [X] Includes documentation, and explanation of why some colors are set is SIMPLETHEME_SASS_OVERRIDES and some in SIMPLETHEME_EXTRA_SASS

Note that the sandbox isn't working right now; we'll fix it and ping back. For now you can use the devstack to review this.

2018-04-03 16:47 UTC, akovari commented
@nedbat , so sorry setting up the sandbox took so long. It is ready for your review now: https://hawthorn-simple-theme.opencraft.hosting/

2018-04-04 16:34 UTC, tomaszgy commented
@nedbat just a note - it'd be lovely to have this included in Hawthorn :)

2018-04-10 21:17 UTC, nedbat commented
@edx/fedx-team Anyone on fedx well-versed enough in ansible to be able to comment?

2018-05-21 11:33 UTC, akovari commented
@nedbat, @edx/fedx-team just a friendly ping to see if anyone might be able to review this?

2018-05-21 11:58 UTC, akovari commented
@mduboseedx: I was told to ping you, to see if you know about anyone who could review this please.

2018-05-21 14:42 UTC, mduboseedx commented
@edx/devops Could this be reviewed soon? @akovari is hoping that this can be merged before the Hawthorn release.

2018-06-02 22:29 UTC, tomaszgy commented
@edx/devops @mduboseedx A friendly ping :) Would someone be able to review it before Hawthorn is cut? Thanks!

2018-06-04 22:01 UTC, ormsbee approved these changes
Thank you for the reminder. Very thorough writeup.

2018-06-04 22:04 UTC, ormsbee commented
@feanil: Am I free to merge this, or does it need a check from your team?

2018-06-11 14:38 UTC, tomaszgy commented
@feanil A friendly ping :)

2018-06-11 19:25 UTC, mduboseedx commented
@tomaszgy I'm checking with our DevOps team about this PR

2018-06-11 20:18 UTC, tomaszgy commented
@mduboseedx thanks! Please let me know if we can help somehow with getting this merged :)

2018-06-28 20:25 UTC, tomaszgy commented
@mduboseedx A friendly ping :) Did you have a chance to talk to DevOps? :)

2018-06-28 20:37 UTC, jibsheet commented
@ormsbee This defaults off. so should be fine for you to merge.  Otherwise I'll try to remember to look at it next week.

2018-06-28 20:47 UTC, merged

2018-06-28 20:47 UTC, edx-webhook commented
@akovari 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/4396&entry.1484655318=https://github.com/akovari&entry.752974735=2018-03-20+16:11&entry.1917517419=2018-06-28+20:47&entry.2133058324=Yes) so we can improve your experience in the future.

2018-06-29 12:47 UTC, tomaszgy commented
Thanks @ormsbee !