WIP: Split out log sync into its own role
openedx-unsupported/configuration pull request #4398
Opened 2018-03-20 19:11 UTC by xitij2000

This PR splits out the log syncing bits of the openstack and AWS roles to their own roles such that either or both can be enabled.

The aim is to decouple the log syncing destination from the AWS/OpenStack so a server deployed on OpenStack can sync to S3 and a server deployed to AWS can sync to SWIFT, or a server can sync to both.

This replaces #3522 

**Dependencies**: None

**Sandbox URL**: TBD - sandbox is being provisioned.

**Merge deadline**:  We would love to get this into Hawthorn

**Testing instructions**:
TBD

**Reviewers**
- [ ] @pomegranited 
- [ ] edX reviewer[s] TBD

**Settings**
```yaml
COMMON_SWIFT_LOG_SYNC: true
```
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

2018-03-20 19:12 UTC, edx-webhook commented
Thanks for the pull request, @xitij2000! I've created [OSPR-2311](https://openedx.atlassian.net/browse/OSPR-2311) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

2018-03-21 18:27 UTC, nedbat commented
@edx/devops More deploy-agnosticism to review!

2018-03-22 01:45 UTC, pomegranited requested changes
This works great @xitij2000 !  I'm ready to approve once my comments below have been addressed and re-tested.

Would like to see this run on an AWS deployment though..  @feanil is this covered by the automated tests, or do we need to set up an AWS sandbox?

- [x] I tested this on OpenStack deployments using the various configuration options, by deploying a new OpenStack Open edX appserver using each of the following configurations, and force-rotating the tracking logs to ensure that they were synced to the intended storage locations.
  Permutations tested:
  * No log syncing enabled: Log rotation works without error.
    Default behaviour; requires no special configuration.
  * S3 only.  Backwards compatibility with the `COMMON_OBJECT_STORE_LOG_SYNC*` variables is also preserved.
     ```yaml
       COMMON_S3_LOG_SYNC: true
       COMMON_S3_LOG_SYNC_BUCKET: bucket-name
       AWS_S3_LOGS_ACCESS_KEY_ID: ***
       AWS_S3_LOGS_SECRET_KEY: ***
      ```
   * SWIFT only. Backwards compatibility with the `COMMON_OBJECT_STORE_LOG_SYNC_*` variables is also preserved.
     ```yaml
      COMMON_SWIFT_LOG_SYNC: true
      COMMON_SWIFT_LOG_SYNC_BUCKET: container-name
      SWIFT_LOG_SYNC_AUTH_URL: ***
      SWIFT_LOG_SYNC_PASSWORD: ***
      SWIFT_LOG_SYNC_REGION_NAME: ***
      SWIFT_LOG_SYNC_TENANT_NAME:  ***
      SWIFT_LOG_SYNC_USERNAME: ***
      ```
  * SWIFT + S3.  Achieved by combining the two stanzas above.
- [x] I read through the code
- [x] <strike>I checked for accessibility issues</strike> N/A
- [x] Includes documentation.

2018-03-22 01:45 UTC, pomegranited commented on playbooks/roles/log_sync_s3/templates/send-logs-to-s3.j2
> +
I understand that this change was introduced to avoid having `unavailable/` show up in the S3 log path. But since it doesn't cause any issues, and this adds some unneeded complexity, I'd rather e419f58 and the associated b17204a were reverted.

The most important thing is that the log file paths are unique so existing log files are not overridden with different data. This behaviour is guaranteed from an OpenStack perspective by the `${instance_id}`, and from an AWS perspective by the `${sec_grp}/${instance_id}`.

2018-03-22 01:45 UTC, pomegranited commented on playbooks/roles/aws/defaults/main.yml
> -aws_redhat_pkgs: []
Hmm.. AWS instances need these `aws_debian_pkgs`, `aws_pip_pkgs`, and `aws_pip_pkgs` installed regardless of whether they're doing log syncing.

Please reinstate these lines and the [aws/task/main.yml](https://github.com/edx/configuration/pull/4398/files#diff-90728b6b056d14ca52343976567da408) lines below which use them, and instead, make the `aws` role a [`meta` dependency of `log_sync_s3`](https://github.com/edx/configuration/pull/4398/files#diff-90728b6b056d14ca52343976567da408), instead of [the other way around](https://github.com/edx/configuration/pull/4398/files#diff-4d904541a67a1c73de020ae462dd684dR16).

We can ask edX for help deploying an AWS sandbox using this configuration, to make double sure it works, if the automated tests aren't already covering this.

2018-03-22 01:45 UTC, pomegranited commented on playbooks/roles/log_sync_s3/defaults/main.yml
> +aws_s3_logfile: "{{ vhost_dirs.logs.path }}/s3-log-sync.log"
These lines (and [these, in the `log_sync_swift` role](https://github.com/edx/configuration/pull/4398/files#diff-a5459cf279c2ed65699ea505b6b69cc8R30)), are why these files get created in `/edx/app/openstack` when installed on Openstack VMs.

Since the file names are different, and [symlinks are created](https://github.com/edx/configuration/pull/4398/files#diff-5db8e604a10161d0278fbc97fa4419adR52), I don't think this is a problem to leave as-is.

2018-03-22 01:45 UTC, pomegranited commented on playbooks/roles/log_sync_s3/defaults/main.yml
> +aws_region: "us-east-1"
Irrelevant to this change, but I'd really like to see this variable be made configurable, to better support other AWS regions.

2018-03-22 01:48 UTC, pomegranited commented on playbooks/roles/log_sync_s3/templates/send-logs-to-s3.j2
> -  chown syslog.syslog "{{ aws_s3_logfile }}"
Thank you for fixing this!  It's always bugged me 😄

2018-03-22 18:07 UTC, xitij2000 commented on playbooks/roles/aws/defaults/main.yml
> -aws_redhat_pkgs: []
@pomegranited I made {{log_sync_s3}} a dependency of {{aws}} for backwards compatibility because currently people running that role might expect it to also set up log syncing. 

Additionally, I don't know the side-effect of running the AWS role on a non-AWS instance, so I wasn't sure about making log syncing to S3 depend on that role.

2018-03-22 18:12 UTC, xitij2000 commented on playbooks/roles/log_sync_s3/defaults/main.yml
> +aws_region: "us-east-1"
@pomegranited  I've added a setting to override this.

2018-03-22 23:12 UTC, pomegranited commented on playbooks/roles/aws/defaults/main.yml
> -aws_redhat_pkgs: []
> I made `log_sync_s3` a dependency of `aws` for backwards compatibility because currently people running that role might expect it to also set up log syncing.

Ok that makes sense, since we don't know what playbook people might be running the `aws` role from.

Thanks for the explanation!

2018-03-22 23:17 UTC, pomegranited commented on playbooks/roles/log_sync_s3/defaults/main.yml
> +aws_region: "us-east-1"
Oo thank you! 😄

2018-03-23 02:10 UTC, pomegranited approved these changes
:+1: Thanks for addressing my comments @xitij2000 ! 

- [x] I re-tested this as described in https://github.com/edx/configuration/pull/4398#pullrequestreview-105953268
- [x] I read through the code
- [x] <strike>I checked for accessibility issues</strike> N/A
- [x] Includes documentation

2018-03-23 08:10 UTC, xitij2000 commented
@nedbat  @feanil This PR is ready for review now.

2018-03-23 20:19 UTC, nedbat commented
@xitij2000 Thanks.  Could you please squash the commits?

2018-03-23 20:29 UTC, xitij2000 commented
@nedbat Sure! Just rebased and squashed.

2018-05-04 20:40 UTC, mduboseedx commented
@edx/devops I believe this is now ready for review

2018-05-07 15:46 UTC, feanil commented
@mduboseedx I've updated the ticket status and prioritized it in our backlog.

For all concerned, I think we'll be able to start this review next week or so.

2018-05-07 15:54 UTC, pomegranited commented
Awesome, thank you @feanil  and @mduboseedx !

2018-05-07 18:19 UTC, xitij2000 commented
Thanks!

2018-06-07 16:12 UTC, xitij2000 commented
@feanil Were you able to review this then? I'd love to get some feedback in case we need to make changes. 

Thanks!

2018-06-13 18:53 UTC, nedbat commented
@edx/devops this is a request we'd like in Hawthorn.

2018-06-14 19:50 UTC, nedbat commented
@edx/devops Can we get a response about when this might be reviewed?  It's mentioned on the [Hawthorn wiki page](https://openedx.atlassian.net/wiki/spaces/COMM/pages/158045104/Hawthorn)

2018-06-19 15:48 UTC, nedbat commented
@edx/devops @fredsmith @jibsheet @coryleeio @jdmulloy @feanil Is there some other process we should be using to communicate about pull requests?

2018-06-19 21:11 UTC, coryleeio commented
The communication channel is correct.  Unfortunately, we haven't had time to review due to internal deadlines. I am bumping the review ticket and we will check it's priority in standup in the morning.

2018-07-19 21:55 UTC, xitij2000 commented
We're closing this PR since we've decided to phase out our use of SWIFT in our Open edX deployments.

While it would be nice to see support for alternative storage backends in the Open edX platform, a combination of factors such as issues with our SWIFT provider, issues with the SWIFT integration in Open edX and the general lack of reactivity in getting fixes like this merged, make this work untenable for us.

We would be happy to help anyone willing to take over that work though. We could also work on removing support for SWIFT if preferred.
CC: @johnmark  @nedbat

2018-07-19 21:55 UTC, closed without merging

2018-07-19 21:55 UTC, edx-webhook commented
@xitij2000 Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/4398&entry.1484655318=https://github.com/xitij2000&entry.752974735=2018-03-20+19:11&entry.1917517419=2018-07-19+21:55&entry.2133058324=No) so we can improve your experience in the future.