Update splunk forwarder role so it can be installed on Amazon Linux OS
openedx-unsupported/configuration pull request #4407
Opened 2018-03-21 14:53 UTC by schenedx

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

2018-03-22 15:02 UTC, feanil requested changes
@schenedx one small change needed otherwise looks good.

2018-03-22 15:02 UTC, feanil commented on CHANGELOG.md
>  - Role: server_utils
Changelog entries should go at the top of the file.

2018-03-22 17:22 UTC, schenedx commented on CHANGELOG.md
>  - Role: server_utils
@feanil This is one address.

2018-03-22 17:22 UTC, schenedx commented
@feanil I addressed your feedback. Please approve and merge.

2018-03-22 19:19 UTC, feanil commented on CHANGELOG.md
>  - Role: server_utils
@schenedx generally new entries in a changelog should go at the top of the changelog.  This makes it easier to see what's changed recently.  The line below and the two lines about the splunkforwarder should all go to the top of this file.

2018-03-22 20:00 UTC, schenedx commented on CHANGELOG.md
>  - Role: server_utils
@feanil Gotcha. Made the updates.

2018-03-22 20:02 UTC, feanil approved these changes

2018-03-22 20:58 UTC, merged

2018-03-26 17:46 UTC, jibsheet commented on playbooks/roles/splunkforwarder/tasks/main.yml
> +  when: download_package.changed
On an ubuntu box, the second declaration of download_deb for rpm paves over the one set for the deb download. (even though you have when,  ansible still paves over the register for you)

This empty download_deb means that splunk's user is never created, app is never started, etc.

This is breaking build from scratches for me https://gocd.tools.edx.org/go/tab/build/detail/stage-xqueue/16/build_ami/1/stage_edx

2018-03-28 16:03 UTC, schenedx commented on playbooks/roles/splunkforwarder/tasks/main.yml
> +  when: download_package.changed
This is now fixed forward with https://github.com/edx/configuration/pull/4427