Updated the NGINX configuration for IDAs to return a maintenance page
openedx-unsupported/configuration pull request #4411
Opened 2018-03-22 19:36 UTC by staubina

[LEARNER-4264]

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

2018-03-22 19:39 UTC, staubina commented
@feanil @edx/devops 
This is the addition of the maintenance page to support the upcoming Ecommerce migrations.

2018-03-22 19:40 UTC, staubina commented
@feanil How would you suggest I test these changes?

2018-03-26 14:17 UTC, staubina commented
I have tested this on my Sandbox, https://ecommerce-staubina.sandbox.edx.org/dashboard.  It seems to be working once the following was added to the local vars.

NGINX_EDXAPP_S3_MAINTENANCE_FILE: "/edx-static/maintenance/maintenance.html"
NGINX_EDXAPP_ENABLE_S3_MAINTENANCE: true

Please let me know if there are any other questions.

2018-03-26 15:18 UTC, staubina commented
@edx/devops Please review this PR when you have time.

2018-03-26 19:18 UTC, feanil reviewed
We shouldn't use the vars for edxapp for the service.

Can you update the var name to `EDX_DJANGO_SERVICE_ENABLE_S3_MAINTENANCE` and `EDX_DJANGO_SERVICE_S3_MAINTENANCE_FILE` and set defaults in `playbooks/roles/edx_django_service/defaults/main.yml`

2018-03-27 11:33 UTC, staubina commented
@feanil I updated the names.  Also please take a look at the defaults I added to see if they match your expectations.  Do I need to create a new Sandbox to test these?

2018-03-27 18:19 UTC, feanil commented on CHANGELOG.md
> +  - Added maintenance page under the flag NGINX_EDXAPP_ENABLE_S3_MAINTENANCE.
Update the changelog entry to the new vars as well and move your changelog entry to the top of the file.

2018-03-27 18:21 UTC, feanil approved these changes
Other than the nit, I think this is good to go.

2018-03-30 14:27 UTC, coryleeio commented
assigning to myself so I can merge if CI passes

2018-03-30 14:29 UTC, staubina commented
@coryleeio I am testing on a new Sandbox right now.  My Sandbox went away this morning

2018-03-30 14:37 UTC, coryleeio commented
@staubina Kk - write back here once testing is complete

2018-03-30 16:20 UTC, staubina commented
@feanil @coryleeio I am having an issue building a new Sandbox to test my recent changes.  Are we comfortable merging with without me testing on a Sandbox again?

2018-03-30 16:21 UTC, staubina commented
Otherwise I am not sure I can get a Sandbox built until the Ticket is completed. https://openedx.atlassian.net/browse/OPS-2986

2018-03-30 16:21 UTC, staubina commented
Failed Sandbox build https://tools-edx-jenkins.edx.org/job/Sandboxes/job/CreateSandbox/9616/console

2018-04-02 20:57 UTC, coryleeio commented
I will check with joe and see when the django 11 sandboxes are going to be fixed.

2018-04-02 21:10 UTC, coryleeio requested changes

2018-04-02 21:10 UTC, coryleeio commented on playbooks/roles/edx_django_service/defaults/main.yml
> +EDX_DJANGO_SERVICE_ENABLE_S3_MAINTENANCE: true
@staubina We may need to set this to false and override it in edx-internal/ansible/vars/edx.yml alongside NGINX_EDXAPP_ERROR_PAGES in a separate PR, as the default values for NGINX_EDXAPP_ERROR_PAGES includes a 502 entry.   While it is true that in edx-internal we override this to not include the 502, we dont override it everywhere, (olive-internal, mckinsey-internal, somebody-we-dont-know-internal).  This means that unless they have explicitly set this value to false, when they run this playbook their nginx config for LMS and CMS would wind up with two error page 502 entries.

2018-04-02 21:11 UTC, coryleeio commented on playbooks/roles/edx_django_service/defaults/main.yml
> +EDX_DJANGO_SERVICE_ENABLE_S3_MAINTENANCE: true
I realize that is difficult to follow, feel free to stop by my desk and I can try to explain more clearly

2018-04-03 13:30 UTC, staubina commented
@coryleeio Please take a look here: https://ecommerce-staubina.sandbox.edx.org/admin

2018-04-03 17:13 UTC, coryleeio approved these changes

2018-04-03 17:14 UTC, coryleeio approved these changes

2018-04-03 17:14 UTC, merged