Allow adding custom maintenance pages with static contents.
openedx-unsupported/configuration pull request #4558
Opened 2018-05-15 11:11 UTC by akovari

Configuration Pull Request
---

This change allows adding custom maintenance / error pages and static contents to nginx.

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

2018-05-15 11:11 UTC, edx-webhook commented
Thanks for the pull request, @akovari! I've created [OSPR-2409](https://openedx.atlassian.net/browse/OSPR-2409) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

2018-05-15 14:53 UTC, mduboseedx commented
jenkins ok to test

2018-05-15 15:03 UTC, mduboseedx commented
@edx/devops Could you take a look at this?

2018-05-17 10:08 UTC, mtyaka requested changes

2018-05-17 10:08 UTC, mtyaka commented on playbooks/roles/nginx/templates/edx/app/nginx/sites-available/lms.j2
> +    location {{ item.location }} {
I don't think we need this, since a location that serves static files from the static dir [already exists](https://github.com/open-craft/configuration/blob/f7f09d3f577a25515d7d29700864ced5def11d1a/playbooks/roles/nginx/templates/edx/app/nginx/sites-available/static-files.j2#L1-L5). You can see it in action by visiting https://courses.edx.org/server/rate-limit.html for example.

But we do need some way to toggle the maintenance page on and off.

Adding something like this (not tested) near the top of the `server { ... }` block might work:

```
if (-f {{ nginx_server_static_dir }}/maintenance.html) {
   rewrite ^(.*)$ /server/maintenance.html last;
}
```

That way you can have a `maintenance.html.disabled` template for example, and just copy it to `maintenance.html` when you want to enable it.

2018-05-17 10:08 UTC, mtyaka commented on playbooks/roles/nginx/tasks/main.yml
> +  with_items: "{{ NGINX_SERVER_MAINTAINANCE_LOCATIONS }}"
Can we rename the variables to `NGINX_SERVER_STATIC_FILES` instead, since it's more generic than just maintenance pages and can be used for any static file?

2018-05-17 10:08 UTC, mtyaka commented on playbooks/roles/nginx/defaults/main.yml
> +NGINX_SERVER_MAINTAINANCE_LOCATIONS: []
As mentioned below, I suggest to replace this with `NGINX_SERVER_STATIC_FILES` and make it just a list of files (or folders) to be copied over to nginx static dir.

2018-05-29 09:22 UTC, mtyaka requested changes
Found a small problem with missing default variable value, but otherwise this is looking good.

2018-05-29 09:22 UTC, mtyaka commented on playbooks/roles/nginx/tasks/main.yml
> +    src: {{ NGINX_SERVER_TEMPLATE }}
The default value for the new `NGINX_SERVER_TEMPLATE` variable needs to be defined in `defaults/main.yml`.

2018-05-29 10:25 UTC, akovari commented on playbooks/roles/nginx/tasks/main.yml
> +    src: {{ NGINX_SERVER_TEMPLATE }}
Good catch! Thanks

2018-05-30 07:59 UTC, mtyaka requested changes

2018-05-30 07:59 UTC, mtyaka commented on playbooks/roles/nginx/tasks/main.yml
> +    src: {{ NGINX_SERVER_TEMPLATE }}
`{{ NGINX_SERVER_TEMPLATE }}` needs to be wrapped in quotes (`"{{ NGINX_SERVER_TEMPLATE }}"`), otherwise  it's not valid YAML - that's why tests are currently failing.

2018-05-30 08:13 UTC, akovari commented on playbooks/roles/nginx/tasks/main.yml
> +    src: {{ NGINX_SERVER_TEMPLATE }}
Hmm, I fixed it, thanks

2018-05-30 08:53 UTC, mtyaka requested changes

2018-05-30 08:53 UTC, mtyaka commented on playbooks/roles/nginx/defaults/main.yml
> ++NGINX_SERVER_STATIC_FILES: []
@akovari Sorry for noticing this earlier, but there's an extra `+` character in front of the variable name.

2018-05-30 09:16 UTC, akovari commented on playbooks/roles/nginx/defaults/main.yml
> ++NGINX_SERVER_STATIC_FILES: []
Ooops! Thanks @mtyaka ! fixed

2018-05-31 08:40 UTC, mtyaka approved these changes

2018-05-31 08:45 UTC, mtyaka commented
@akovari I tested this and it works well :+1:

Can you please add an entry to the [CHANGELOG](https://github.com/edx/configuration/blob/master/CHANGELOG.md) to list the new variables and explain what they do?

- [x] I tested this: I used this code to deploy a custom maintenance page to an Open EdX installation.
- [x] I read through the code
- [ ] ~~I checked for accessibility issues~~ n/a
- [ ] Includes documentation - not yet: we should add an entry to the changelog

2018-05-31 11:27 UTC, akovari commented
@mtyaka , thanks for the review. I've updated the CHANGELOG

2018-06-30 07:52 UTC, mtyaka commented
Rebased from f79f8daa0880857e767c7a33e469a17be88cbfde

2018-07-03 14:28 UTC, mduboseedx commented
@mtyaka Is this ready for a review?

2018-07-03 14:56 UTC, mtyaka commented
@mduboseedx Yes, this is ready for review.

2018-07-03 17:51 UTC, mduboseedx commented
@edx/devops @jdmulloy Could you give this a review when you have a chance?

2018-07-05 21:13 UTC, jdmulloy reviewed
This looks reasonable but I still need to do some more testing. There are a few other things we need for this to work for edx.org, but this is a good start. The other goals we have are below, if you would like to address them feel free, but if not we can build on top of your work to implement them.

Thanks

- API endpoints should return a 503 with an empty body
- Static assets should still be served normally to avoid accidental caching by the CDN.

2018-07-05 21:13 UTC, jdmulloy commented on CHANGELOG.md
> +  - When there is file named `maintenance.html` in the `nginx_server_static_dir`, it will be shown if the backend is unavailable
I'm still working on the full review, but one thing I've noticed and confirmed with testing is that if this file exists it will be served regardless of the backend's availability, which I believe is the desired behavior. This changelog line should be updated to reflect this.

2018-07-09 09:21 UTC, mtyaka commented
Thanks for reviewing this @jdmulloy! I'll schedule some time to address your comments in the next two weeks.

2018-07-09 21:10 UTC, jdmulloy commented
Hi @mtyaka,
I found out that we already have similar functionality in the nginx config that serves a maintenance html file from S3 if nginx can't reach gunicorn. To activate the maintenance we stop gunicorn, which also prevents writes to the database. We would prefer to adapt the existing code instead of adding a second way of doing a maintenance page. Perhaps you could adapt the existing code to optionally use a local file instead of S3 for those who aren't using S3.

There are some issues with the existing code that I've addressed in PR #4673. Primarily the /heartbeat endpoint returns a 502 which causes the ELB to stop sending the instances traffic, so users never see the maintenance page.

Please let me know if there are issues with the current code for your use case.

Thanks

2018-07-10 20:53 UTC, jdmulloy commented
I've also created a playbook to toggle the maintenance page in PR #4676.

2018-07-13 13:17 UTC, jdmulloy commented
@mtyaka I am closing this PR for now since I believe PRs #4673 and #4676 cover the same use case. Please let me know if you have a use case that these do not solve, or submit a PR to adapt the existing code to you use case. For instance make it so that a maintenance page can be served from somewhere other than S3.

Thanks

2018-07-13 13:17 UTC, closed without merging

2018-08-07 03:34 UTC, mtyaka commented
Thank you @jdmulloy!

I opened #4714 and #4715 to address some use cases that haven't been covered by merged code yet. If you could take a look that would be great!