WIP: Reconfigure the jenkins_analytics role to reference jenkins_commons
openedx-unsupported/configuration pull request #4647
Opened 2018-06-26 19:49 UTC by azafty468

Initial PR.  Not ready to be merged yet.  

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

2018-07-19 14:10 UTC, azafty468 commented on playbooks/roles/jenkins_common/defaults/main.yml
> +jenkins_node_usage: EXCLUSIVE
We use a smaller environment on the DE team and the master node executes most of our work

2018-07-19 14:11 UTC, azafty468 commented on playbooks/roles/jenkins_common/defaults/main.yml
> +jenkins_commons_seed_job_source: '{{ role_path }}/files/xml/*'
Our seed file has a few different parameters and uses multiple SCMs.  This parameter is overridden in the jenkins_analytics role to point to it's local version of the seed template.  I'm open to suggestions if you have an alternative here.

2018-07-19 14:13 UTC, azafty468 commented on playbooks/roles/jenkins_common/tasks/main.yml
> +- name: Create jenkins home and set ownership
We mount a drive in the /var/lib/jenkins folder, which then requires we grant ownership of jenkins to this folder.  I believe this command will not cause an issue when run on an environment that doesn't have a drive mounted.

2018-07-19 14:13 UTC, azafty468 commented
I highlighted the reasoning for the few changes I carried up into jenkins_commons.

2018-07-19 14:18 UTC, pomegranited commented
Hi @azafty468, thanks for the ping :)
What's your timeline for getting this merged?  Would it be ok if I had a look during the first week of August and gave my feedback then?

We are using this role to deploy our analytics clients, and so at a quick glance, my main concern is whether or not the seed jobs you're referencing are in edx's public repos?  I'm all for using DSLs wherever possible with Jenkins, just want to make sure that we can access them.

Re Jenkins access -- I don't think we're using github auth anywhere, but we are using the unix auth realm.

2018-07-19 14:44 UTC, azafty468 commented
The seed job hits a secure repo which has the definitions for the jobs that need to be loaded.   @HassanJaveed84 can provide a more detail.  We can certainly refrain from merging while you review.  

Oh also I forgot to mention that the tag 'open-release/ginkgo.2' represents the state of the world prior to any changes incorporated from this PR.

2018-07-19 15:08 UTC, pomegranited commented
Thanks @azafty468 @HassanJaveed84 -- are you planning to move these seed jobs into a public repo, since we'll need them in order to use `analytics_jenkins`?

2018-07-19 18:16 UTC, azafty468 commented
Some of it contains repo URLs, email addresses and other sensitive information.  This we are definitely going to keep secure.  The rest of the structure should be available to open source.  Hassan do you know if the base job configs are visible outside of our secure repo?  Or is the job definition entirely secured?

2018-07-19 18:29 UTC, estute commented on playbooks/roles/jenkins_common/defaults/main.yml
> +jenkins_commons_seed_job_source: '{{ role_path }}/files/xml/*'
This seems fine

2018-07-19 18:29 UTC, estute commented on playbooks/roles/jenkins_common/tasks/main.yml
> +- name: Create jenkins home and set ownership
We also mount a drive here, but currently that step isn't automated, and is only done when creating a new instance, not performing updates. Jenkins automatically creates the $JENKINS_HOME on first boot, then we mount into it. I suppose this won't interfere with our process, but I can test it out.

2018-07-23 00:24 UTC, HassanJaveed84 commented
@pomegranited the seed jobs' definition would be in a public repo. We are yet to bring pipeline jobs over to the DSL, but we did merge some initial work on the DSL in this [PR](https://github.com/edx/jenkins-job-dsl/pull/385/files)

We would be following a similar pattern to write DSL for the pipeline jobs.

2018-07-23 04:51 UTC, pomegranited commented
That's great news @HassanJaveed84 !  It must be tricky work, extracting out the private details from what can be made public.  I did some of the initial work on the pipeline DSLs, and so would love to have that public so I can use it for our clients' deployments.  Thanks for the info!

2018-08-02 11:49 UTC, pomegranited requested changes
Hi @azafty468 , I've tried this updated role by running the `ansible-jenkins.yml` playbook on an empty ubuntu EC2 server, but as noted below, my Jenkins service won't start and is throwing errors.

To get around the undefined variables noted below, I ran the playbook with these variables:
```yaml
---
JENKINS_CONFIGURATION_REPO_BRANCH: 'master'
JENKINS_ANALYTICS_AUTH_ADMINISTRATORS: ["{{ jenkins_user }}"]
PAGER_NOTIFY: false
jenkins_additional_environment_variables: []
JENKINS_JOB_DSL_SCRIPT_NAME: 'sample/jobs/sampleJob.groovy'
JENKINS_JOB_DSL_REPO_BRANCH: 'master'

JENKINS_JOB_DSL_SECURE_BRANCH: ''
JENKINS_JOB_DSL_SECURE_REPO_SSH: !!null

JENKINS_SERVER_NAME: 'localhost'
JENKINS_MAIN_URL: 'http://localhost:8080/'

AUTOMATION_PRIVATE_KEY_SOURCE_PATH: '/home/ubuntu/ec2_key'
AUTOMATION_PUBLIC_KEY_SOURCE_PATH: '/home/ubuntu/ec2_key.pub'
```

Have you been able to run this role to set up Jenkins on a fresh server?  Are there variables I'm missing?

Please let me know if you'd like to see the full `jenkins.log` file, or if you'd like access to the server I created.

2018-08-02 11:49 UTC, pomegranited commented on playbooks/roles/jenkins_analytics/meta/main.yml
> +    jenkins_common_jenkins_configuration_branch: '{{ JENKINS_CONFIGURATION_REPO_BRANCH }}'
`JENKINS_CONFIGURATION_REPO_BRANCH` is undefined -- should have default `master` like [`jenkins_common_jenkins_configuration_branch`](https://github.com/edx/configuration/blob/88286b598862f16fcb977e59e24594e820f875c8/playbooks/roles/jenkins_common/defaults/main.yml#L22) does.

2018-08-02 11:49 UTC, pomegranited commented on playbooks/roles/jenkins_analytics/meta/main.yml
> +        USERS: '{{ JENKINS_ANALYTICS_AUTH_ADMINISTRATORS }}'
`JENKINS_ANALYTICS_AUTH_ADMINISTRATORS` is undefined.  Should this default to `["{{ jenkins_user }}"]`?

2018-08-02 11:49 UTC, pomegranited commented on playbooks/roles/jenkins_analytics/defaults/main.yml
> +    VALUE: '{{ PAGER_NOTIFY }}'
`PAGER_NOTIFY` is undefined.  Can this be set to `false` by default?

2018-08-02 11:49 UTC, pomegranited commented on playbooks/roles/jenkins_analytics/meta/main.yml
> +    jenkins_common_main_env_vars: '{{ jenkins_base_environment_variables }} + {{ jenkins_additional_environment_variables }}'
`jenkins_additional_environment_variables` is undefined.  Should be `[]` by default.

2018-08-02 11:49 UTC, pomegranited commented on playbooks/roles/jenkins_analytics/files/xml/seed_job.xml
> +          <defaultValue>{{ JENKINS_JOB_DSL_SCRIPT_NAME }}</defaultValue>
`JENKINS_JOB_DSL_SCRIPT_NAME` is undefined.

Does it make sense to use `sample/jobs/sampleJob.groovy` as the default here, with a FIXME comment that this should be updated to match the analytics task seed job once it's made public?

2018-08-02 11:49 UTC, pomegranited commented on playbooks/roles/jenkins_analytics/files/xml/seed_job.xml
> +          <defaultValue>{{ JENKINS_JOB_DSL_REPO_BRANCH }}</defaultValue>
`JENKINS_JOB_DSL_REPO_BRANCH` is undefined, should be `master` by default.

2018-08-02 11:49 UTC, pomegranited commented on playbooks/roles/jenkins_analytics/files/xml/seed_job.xml
> +          <defaultValue>{{ JENKINS_JOB_DSL_SECURE_BRANCH }}</defaultValue>
`JENKINS_JOB_DSL_SECURE_BRANCH` is undefined, and should at least be defined in defaults/main.xml as an empty string, if not `master`.

2018-08-02 11:49 UTC, pomegranited commented on playbooks/roles/jenkins_analytics/files/xml/seed_job.xml
> +            <url>https://github.com/edx/jenkins-job-dsl.git</url>
To allow for forks on this repo, could this be pulled into a variable, e.g. `JENKINS_JOB_DSL_PUBLIC_REPO_URL`

2018-08-02 11:49 UTC, pomegranited commented on playbooks/roles/jenkins_analytics/files/xml/seed_job.xml
> +            <url>{{ JENKINS_JOB_DSL_SECURE_REPO_SSH }}</url>
`JENKINS_JOB_DSL_SECURE_REPO_SSH` is undefined, and should at least be pulled out into defaults/main.xml and set to `!!null` by default.

but given that not everyone has access to or will require the secure jenkins job DSL repo, can this stanza be made conditional on the state of `JENKINS_JOB_DSL_SECURE_REPO_SSH`?

2018-08-02 11:49 UTC, pomegranited commented on playbooks/roles/jenkins_analytics/meta/main.yml
> +    jenkins_common_server_name: '{{ JENKINS_SERVER_NAME }}'
`jenkins_common_server_name` doesn't appear to be used at all in `roles/jenkins_common`?  Instead, it uses `JENKINS_SERVER_NAME`, and passes that to `jenkins_server_name` in jenkins_common/meta/main.yml.

2018-08-02 11:49 UTC, pomegranited commented on playbooks/roles/jenkins_analytics/tasks/main.yml
> +  shell: "curl -D - --silent --max-time 5 {{ JENKINS_MAIN_URL }}cli/"
I'm confused about the difference between the `JENKINS_MAIN_URL` and the `JENKINS_SERVER_NAME` and `jenkins_common_protocol_https` variables.  It seems like `JENKINS_MAIN_URL` should be generated from these, so that only a single variable needs to be set?

2018-08-02 11:49 UTC, pomegranited commented on playbooks/roles/jenkins_analytics/defaults/main.yml
> +JENKINS_SERVER_NAME: 'jenkins.analytics.edx.org'
Could `localhost` be the default here instead of this edx-specific name?

2018-08-02 11:49 UTC, pomegranited commented on playbooks/roles/jenkins_analytics/meta/main.yml
> +      - 4configureGHOAuth.groovy
Error in the`/var/log/jenkins/jenkins.log` for this:
```
WARNING: Failed to run script file:/var/lib/jenkins/init.groovy.d/4configureGHOAuth.groovy
java.lang.RuntimeException: Failed to serialize jenkins.model.Jenkins#securityRealm for class hudson.model.Hudson
```

2018-08-02 11:49 UTC, pomegranited commented on playbooks/roles/jenkins_analytics/meta/main.yml
> +          - com.cloudbees.plugins.credentials.CredentialsProvider.Create
Error thrown in `4configureSecurity.groovy` which is preventing `jenkins` service from starting.

From `/var/log/jenkins/jenkins.log`:
```
SEVERE: Permission com.cloudbees.plugins.credentials.CredentialsProvider.Create is not supported in Jenkins
```

If I comment out this line in `/var/lib/jenkins/init-configs/security.yml`, I get the same error for all the rest of the `com.cloudbees.plugins.credentials.CredentialsProvider.*`, and the `hudson.model.Computer.*` permissions below it.

Can see these lines in the log file though, which indicate that the credentials plugins loaded fine?  Let me know if you'd like to see the rest of the log file.
```
INFO: Plugin credentials @ version 2.1.13 is installed
INFO: Plugin credentials-binding @ version 1.7 is installed
INFO: Plugin ssh-agent @ version 1.5 is installed
INFO: Plugin ssh-credentials @ version 1.13 is installed
...
INFO: All expected plugins are installed correctly
```

2018-08-02 11:49 UTC, pomegranited commented on playbooks/roles/jenkins_analytics/tasks/main.yml
> +    src: '{{ AUTOMATION_PUBLIC_KEY_SOURCE_PATH }}'
`AUTOMATION_PUBLIC_KEY_SOURCE_PATH` is undefined.  Could it at least be pulled out into `default/main.yml` like [`AUTOMATION_PRIVATE_KEY_SOURCE_PATH`](https://github.com/edx/configuration/pull/4647/files#diff-90dee0aabc03ecef11e93a08bbfb4f2eR40) and defaulted to `null`?

2018-08-02 11:49 UTC, pomegranited commented on playbooks/roles/jenkins_analytics/tasks/main.yml
> +- name: Wait for Jenkins to start up before proceeding.
The jenkins service fails to start, I believe due to the [errors noted above](https://github.com/edx/configuration/pull/4647/files#diff-90dee0aabc03ecef11e93a08bbfb4f2eR48).

2018-08-02 15:53 UTC, azafty468 commented
Thanks for the feedback Jill!  There's a lot here.  It might take me a few days to get through it.  Thanks!

2018-08-03 00:29 UTC, pomegranited commented
No worries, @azafty468 !  Please let me know if you need any more information.

2018-08-24 15:31 UTC, azafty468 commented
Ok, I've been dragging my feet on this one a bit while we got some operational experience internally.  We are close but we're still answering some questions on how we would like to process seed jobs.  Until these questions are resolved it's a bit premature to migrate this role.  As such I have opened a new PR https://github.com/edx/configuration/pull/4748 that will create the new Jenkins DSL playbook for Data Engineering.  This PR leaves the jenkins_analytics playbook intact.  Once we have a bit more operational experience I'd suggest revisiting migrating the analyitics-jenkins role to use the new playbook (and incorporate any additional changes required by the open source community).  This is my last day at edX so this work will be carried forward by the rest of the Data Engineering team.

@pomegranited just a heads up.  There are a few security procedures that are common place in Jenkins 2.x and were implemented by the Tools team here at edX.  These changes go beyond the typical "upgrade because older versions potentially contain unaddressed risks."  First, downstream jobs no longer accept all job parameters passed to them.  I'm not positive any Analytics Pipeline jobs used this feature, however we did find it used in the Analytics Exporter.  The resolution here is pretty direct: any downstream Jenkins job running on 2.x needs to confirm that the parameter list is accurate and up to date with all calling parameters.  Second, the Jenkins CLI was disabled in favor of using groovy scripts during startup.  The Tools team provides a large number of scripts to handle a variety of activities.  I found everything we needed when converting our internal Jenkins box.  You guys use a few different features than we do so I can't guaranty feature parity but I suspect with enough examination you can find a suitable replacement for any CLI calls you need to replace.

I'm wrapping up my work today so I may add a few more comments here as I close out my TODOs.

2018-08-25 01:04 UTC, pomegranited commented
Thanks for your work here, and for the heads up @azafty468 !  I'll book some time in the next 2 weeks to re-test and review.

2022-05-19 15:01 UTC, closed without merging

2022-05-19 15:01 UTC, openedx-webhooks commented
Although this pull request is already closed, I've created [OSPR-6695](https://openedx.atlassian.net/browse/OSPR-6695) so that we can track it in Jira.

There is nothing you have to do. No action is needed from your side.  Thanks.

<!-- comment:welcome_closed -->
<!-- comment:external_pr -->
<!-- comment:no_survey_needed -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->