Make edx_django_service CONN_MAX_AGE default to 0.
openedx-unsupported/configuration pull request #4666
Opened 2018-07-03 15:54 UTC by mtyaka

The default gunicorn worker class is 'gevent', which is not compatible with django's `CONN_MAX_AGE` because it leaks database connections.

We noticed this problem when our MySQL server stopped accepting new connections with 'too many open connections' error because there were hundreds of stale connections from ecommerce. Setting `CONN_MAX_AGE` to zero fixes the problem for us.

See: https://github.com/benoitc/gunicorn/issues/996#issuecomment-93301359

**Testing instructions**:

1. Spawn a new sandbox using the `edx_sandbox.yml` playbook.
2. Verify that services that are based on the `edx_django_service` role (ecommerce, discovery, analytics_api, credentials, ...) are configured with `CONN_MAX_AGE` value `0`. The configurations can be found in `/edx/etc/<service-name>.yml` file.

**Author notes and concerns**:

This changes the default for `CONN_MAX_AGE` from `60` to `0`, which is not backwards compatible. Since the default configuration of `60` was buggy, I think that's acceptable, but I'm also fine with reverting the default back to `60` as long as the value is overridable, if that's preferred.

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

2018-07-03 15:54 UTC, edx-webhook commented
Thanks for the pull request, @mtyaka! I've created [OSPR-2502](https://openedx.atlassian.net/browse/OSPR-2502) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

2018-07-03 18:49 UTC, mduboseedx commented
@edx/devops Could you give this a review?

2018-07-04 02:44 UTC, kaizoku commented
This should fix our issues. Thanks for doing the research on this one @mtyaka 
:+1:

2018-09-07 07:43 UTC, mtyaka commented
@mduboseedx Any idea when this could get reviewed?

2018-09-07 13:58 UTC, mduboseedx commented
@mtyaka I'm checking in with our DevOps team. I'll let you know when I have more info.

2018-09-07 14:42 UTC, mtyaka commented
Thank you @mduboseedx  :)

2018-10-23 07:03 UTC, kaizoku commented
@mduboseedx has there been any update on this one?
Just checking as it's been a bit, and this could be a problem for other providers with many users.

2018-10-24 18:47 UTC, mduboseedx commented
@feanil Could you or someone on your team give this a look?

2018-11-02 09:54 UTC, UmanShahzad commented
This is a pretty simple config change that effectively fixes some buggy behavior.

2018-11-02 14:16 UTC, feanil requested changes

2018-11-02 14:16 UTC, feanil commented on playbooks/roles/edx_django_service/defaults/main.yml
> +edx_django_service_default_db_conn_max_age: 0
By changing this default here, we are changing the behavior of all  services already running.  I think making this configurable but then over-ridable per service makes sense but the default should remain 60 for now I think.

2018-11-03 08:20 UTC, UmanShahzad commented on playbooks/roles/edx_django_service/defaults/main.yml
> +edx_django_service_default_db_conn_max_age: 0
Thanks, good point. cc @kaizoku since this recently bit us, can you check this out?

2018-11-06 00:49 UTC, kaizoku commented on playbooks/roles/edx_django_service/defaults/main.yml
> +edx_django_service_default_db_conn_max_age: 0
Alright, I think we can leave the default at 60, but use the extra variable to set this to 0 on our instances.

2018-11-06 15:50 UTC, natabene commented
@kaizoku  Please let me know once it is ready to be looked at again. Thanks

2018-11-07 02:55 UTC, kaizoku commented
@natabene, I've updated the default to match the original 60 seconds again.

2018-11-07 17:03 UTC, natabene commented
@feanil  What do you think?

2018-11-13 16:54 UTC, feanil approved these changes

2018-11-13 16:54 UTC, feanil commented
@jdmulloy can you do a second review of this when you have a sec?

2018-11-14 21:43 UTC, jdmulloy approved these changes

2018-11-14 21:44 UTC, merged

2018-11-14 21:44 UTC, edx-webhook commented
@mtyaka 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/4666&entry.1484655318=https://github.com/mtyaka&entry.752974735=2018-07-03+15:54&entry.1917517419=2018-11-14+21:44&entry.2133058324=Yes) so we can improve your experience in the future.

2018-11-15 00:40 UTC, kaizoku commented
Thanks for merging this @jdmulloy !