Maintenance page playbook
openedx-unsupported/configuration pull request #4676
Opened 2018-07-10 19:09 UTC by jdmulloy

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

2018-07-10 20:36 UTC, jibsheet commented on playbooks/roles/edx_maintenance/tasks/main.yml
> +# Tasks for role edx_maintenance
Docs from here down are cloned from edx_service, can we remove them

2018-07-10 20:41 UTC, jibsheet requested changes
the cms template also has a location /api which we need the same thing for

2018-07-10 20:41 UTC, jibsheet commented on playbooks/roles/edx_maintenance/tasks/main.yml
> +- name: Stop lms/cms
We need to stop workers as well (which will be edxapp:*)
Remember that in production lms and cms are on separate instances, so we need to handle that (maybe skip/fail gracefully if one of the 2 doesn't exist)

2018-07-10 20:41 UTC, jibsheet commented on playbooks/roles/nginx/templates/edx/app/nginx/sites-available/lms.j2
> +    {% if NGINX_SET_X_FORWARDED_HEADERS %}
If from here down is identical to proxy_to_lms_app can we 
{% include lms_proxy.j2 %} or something similar?

2018-07-10 20:44 UTC, jdmulloy commented on playbooks/roles/edx_maintenance/tasks/main.yml
> +# Tasks for role edx_maintenance
Fixd

2018-07-10 20:56 UTC, jdmulloy commented on playbooks/roles/nginx/templates/edx/app/nginx/sites-available/lms.j2
> +    {% if NGINX_SET_X_FORWARDED_HEADERS %}
I can do that, although I will do it on the other PR. This shouldn't be on this branch. I will fix that too.

2018-07-10 20:58 UTC, jibsheet commented on playbooks/roles/nginx/templates/edx/app/nginx/sites-available/lms.j2
> +    {% if NGINX_SET_X_FORWARDED_HEADERS %}
Sounds good, this is what I was trying to ask about in the meeting earlier, but I just decided to review it in one huge block to keep some context for myself

2018-07-11 18:36 UTC, jibsheet approved these changes
Looks good assuming the : vs :* syntax thing

2018-07-11 18:36 UTC, jibsheet commented on playbooks/roles/edx_maintenance/defaults/main.yml
> +    - 'edxapp_worker:'
I assumed you've tested, because I can never remember if this syntax is edxapp_worker: or edxapp_worker:*

2018-07-11 21:04 UTC, jdmulloy commented on playbooks/roles/edx_maintenance/defaults/main.yml
> +    - 'edxapp_worker:'
@jibsheet I've tested and the Ansible doc page for supervisorctl says the behavior is a colon is treated as a group.

https://docs.ansible.com/ansible/latest/modules/supervisorctl_module.html

2018-07-12 13:16 UTC, jibsheet commented on playbooks/roles/edx_maintenance/defaults/main.yml
> +    - 'edxapp_worker:'
gread

2018-07-12 20:07 UTC, merged