Isabelgk/ops 3270 upgrade dev env bionic
openedx-unsupported/configuration pull request #4726
Opened 2018-08-06 13:14 UTC by isabelgk

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

2018-08-06 13:17 UTC, isabelgk commented on docker/build/go-server/Dockerfile
> +FROM edxops/bionic-common:${BASE_IMAGE_TAG}
This won't work until bionic-common is added to Dockerhub.

2018-08-06 20:45 UTC, coryleeio requested changes

2018-08-06 20:45 UTC, coryleeio commented on util/install/ansible-bootstrap.sh
> +  apt-get update
There is an apt-get update down a few lines from this one - you can move this block down a few lines and remove this update statement if you run it after the update that is already there.

2018-08-06 20:45 UTC, coryleeio commented on docker/build/go-server/Dockerfile
> +FROM edxops/bionic-common:${BASE_IMAGE_TAG}
Added

2018-08-07 13:08 UTC, isabelgk commented on util/install/ansible-bootstrap.sh
> +  apt-get update
Fixed

2018-08-13 19:00 UTC, coryleeio approved these changes

2018-08-14 13:37 UTC, isabelgk commented on util/install/ansible-bootstrap.sh
>  # Upgrade the OS
@coryleeio I think this change is what breaks on the TravisCI build, so perhaps I misunderstood your comment earlier when I made this edit? 

```
Running the edx_ansible bootstrap script with the following arguments:
ANSIBLE_REPO="https://github.com/edx/ansible"
ANSIBLE_VERSION="master"
CONFIGURATION_REPO="https://github.com/edx/configuration.git"
CONFIGURATION_VERSION="master"
******************************************************************************
+ grep -q 'Xenial Xerus' /etc/os-release
+ grep -q 'Bionic Beaver' /etc/os-release
+ SHORT_DIST=bionic
+ EDX_PPA='deb http://ppa.edx.org bionic main'
+ apt-get update -y
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Reading package lists...
+ apt-key update -y
E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation
The command '/bin/sh -c /tmp/ansible-bootstrap.sh' returned a non-zero code: 255
make: *** [docker.test.bionic-common] Error 255
make: Target `docker.test.shard' not remade because of errors.
rm .build/bionic-common/Dockerfile.test .build/go-server/Dockerfile.test
/home/travis/.travis/job_stages: line 190:  9447 Terminated              travis_jigger $! $timeout $cmd
The command "travis_wait 50 make --keep-going $MAKE_TARGET SHARD=$SHARD SHARDS=$SHARDS" exited with 2.
```

2018-08-14 14:12 UTC, isabelgk commented on util/install/ansible-bootstrap.sh
>  # Upgrade the OS
Update: reverting this change seems to fix the problem?

2018-08-14 15:26 UTC, coryleeio requested changes

2018-08-14 15:26 UTC, coryleeio commented on util/install/ansible-bootstrap.sh
> +  apt-get install -y software-properties-common python-software-properties
apt-get install -y software-properties-common -qy
if [[ "${SHORT_DIST}" != bionic ]] ;then
  apt-get install python-software-properties -qy
fi

2018-08-14 15:26 UTC, coryleeio commented on util/install/ansible-bootstrap.sh
> +if [[ "${SHORT_DIST}" == bionic ]] ;then
apt-get update -y
if [[ "${SHORT_DIST}" == bionic ]] ;then
  apt-get install -y gnupg
fi
apt-key update -y

2018-08-14 15:36 UTC, isabelgk commented on util/install/ansible-bootstrap.sh
> +  apt-get install -y software-properties-common python-software-properties
done

2018-08-14 15:36 UTC, isabelgk commented on util/install/ansible-bootstrap.sh
> +if [[ "${SHORT_DIST}" == bionic ]] ;then
done

2018-08-14 15:40 UTC, coryleeio approved these changes

2018-08-14 15:46 UTC, merged