Moved Nginx log format name override
openedx-unsupported/configuration pull request #4763
Opened 2018-09-07 17:06 UTC by blarghmatey

When the `NGINX_LOG_FORMAT_NAME` var is set to something different than `p_combined` it breaks the Nginx configuration as there is no long a `p_combined` format defined for the main nginx config. This also prevents users from being able to specify their own format and using it throughout the various Nginx configs.

Removed the `NGINX_LOG_FORMAT_NAME` setting from the `log_format` definition to allow for the default log format to function properly. Users can define an alternate format with a different name and pass that via the `NGINX_LOG_FORMAT_NAME` to be used in the CMS/LMS etc.

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

2018-09-07 17:07 UTC, edx-webhook commented
Thanks for the pull request, @blarghmatey! I've created [OSPR-2602](https://openedx.atlassian.net/browse/OSPR-2602) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

2018-09-07 20:30 UTC, mduboseedx commented
@edx/devops Could you give this a look?

2018-11-07 15:35 UTC, coryleeio commented on playbooks/roles/nginx/templates/etc/nginx/nginx.conf.j2
> +        log_format p_combined '$http_x_forwarded_for - $remote_addr - $remote_user [$time_local]  '
Why are you no longer using NGINX_LOG_FORMAT_NAME, 
It seems to currently be defaulted to p_combined?

2018-11-19 18:56 UTC, blarghmatey commented on playbooks/roles/nginx/templates/etc/nginx/nginx.conf.j2
> +        log_format p_combined '$http_x_forwarded_for - $remote_addr - $remote_user [$time_local]  '
@coryleeio that's because if you override the value of NGINX_LOG_FORMAT_NAAME in this location then two lines below that where `p_combined` is referenced as the default log format, there is no such format defined. The use of the Ansible var in this location has no use as if it is changed from p_combined then the Nginx configuration ends up broken.

2018-11-26 19:20 UTC, natabene commented
@coryleeio  Did you have a chance to look at response from @blarghmatey ?

2018-11-26 21:34 UTC, coryleeio requested changes

2018-11-26 21:34 UTC, coryleeio commented on playbooks/roles/nginx/templates/etc/nginx/nginx.conf.j2
> +        log_format p_combined '$http_x_forwarded_for - $remote_addr - $remote_user [$time_local]  '
I would remove the NGINX_LOG_FORMAT_NAME entirely or change two lines down to:

`access_log {{ nginx_log_dir }}/access.log {{ NGINX_LOG_FORMAT_NAME }};`

You are using the variable in one place but not the other, I would be happy to see the variable removed entirely, or see it used two lines down. I'm happy to merge either of those.

2018-12-03 17:37 UTC, natabene commented
@blarghmatey  Please let us know once you have addressed Cory's comments.

2018-12-03 22:29 UTC, blarghmatey commented on playbooks/roles/nginx/templates/etc/nginx/nginx.conf.j2
> +        log_format p_combined '$http_x_forwarded_for - $remote_addr - $remote_user [$time_local]  '
@coryleeio I'm not sure I understand what you are asking... The Ansible variable in question is not present in this file at all. It is still present in the other template files because it is possible to specify an additional log format in a file located under the `conf.d` directory which can then be referenced by the applications, which is what I am doing for my deployment.

2018-12-12 17:12 UTC, coryleeio commented on playbooks/roles/nginx/templates/etc/nginx/nginx.conf.j2
> +        log_format p_combined '$http_x_forwarded_for - $remote_addr - $remote_user [$time_local]  '
@blarghmatey So in playbooks/roles/nginx/defaults/main.yml


NGINX_LOG_FORMAT_NAME is defaulted to 'p_combined' by this line:

    NGINX_LOG_FORMAT_NAME: 'p_combined' 


The break you are fixing is when you override NGINX_LOG_FORMAT_NAME to somtehing else, and so it breaks on line 44 which currently reads:

    access_log {{ nginx_log_dir }}/access.log p_combined;

because p_combined doesnt exist if you override the format.

However, if line 44 read: 
         access_log {{ nginx_log_dir }}/access.log {{ NGINX_LOG_FORMAT_NAME }};

both approaches would work, yes? or do I misunderstand something?

2018-12-12 17:24 UTC, blarghmatey commented on playbooks/roles/nginx/templates/etc/nginx/nginx.conf.j2
> +        log_format p_combined '$http_x_forwarded_for - $remote_addr - $remote_user [$time_local]  '
@coryleeio it would allow Nginx to run, yes, but it would also force you to still use the same log format as if you never changed that variable. The reason for having that variable is to allow users to specify a new log format and use it in the LMS/CMS/etc.

2018-12-17 21:49 UTC, coryleeio requested changes

2018-12-17 21:49 UTC, coryleeio commented on playbooks/roles/nginx/templates/etc/nginx/nginx.conf.j2
> +        log_format p_combined '$http_x_forwarded_for - $remote_addr - $remote_user [$time_local]  '
@blarghmatey Ooh okay right, that makes sense.

One last thing then:
I think we want to leave 
$http_x_forwarded_proto
in place, was it causing you issues?  You removed it from the default format.

2019-01-02 21:38 UTC, coryleeio commented on playbooks/roles/nginx/templates/etc/nginx/nginx.conf.j2
> +        log_format p_combined '$http_x_forwarded_for - $remote_addr - $remote_user [$time_local]  '
after holidays bump =]

If you can put $http_x_forwarded_proto back I will merge, I think it is used to track AWS ELB ips for us

2019-01-22 18:39 UTC, coryleeio approved these changes
Great thank you for the fix - I'll merge it now

2019-01-22 18:39 UTC, merged

2019-01-22 18:39 UTC, edx-webhook commented
@blarghmatey 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/4763&entry.1484655318=https://github.com/blarghmatey&entry.752974735=2018-09-07+17:06&entry.1917517419=2019-01-22+18:39&entry.2133058324=Yes) so we can improve your experience in the future.

2019-01-22 18:40 UTC, coryleeio commented
Thank you for the contribution @blarghmatey =]

2019-02-11 19:18 UTC, nedbat commented
I've cherry-picked this onto Ironwood.