Adds in prospectus playbook
openedx-unsupported/configuration pull request #4764
Opened 2018-09-07 18:41 UTC by jlajoie

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

2018-09-10 19:47 UTC, fredsmith requested changes

2018-09-10 19:47 UTC, fredsmith commented on playbooks/roles/prospectus/tasks/main.yml
> +    src: "{{ PROSPECTUS_SRC_DIR }}" # /godata/pipelines/stage-prospectus/target/public
this code isn't going to run on the goagent, it runs on a running instance that's started by your AMI build pipeline.  You'll need to ship these assets somewhere (s3, git) or build them on the AMI.

2018-09-10 19:47 UTC, fredsmith commented on playbooks/roles/nginx/templates/edx/app/nginx/sites-available/prospectus.j2
> +  {% if NGINX_PROSPECTUS_PROXY_INTERCEPT_ERRORS %}
you should set defaults for all variables used in your templates. use !null if you want them to evaluate this way.

2018-09-10 19:47 UTC, fredsmith commented on playbooks/prospectus.yml
> +      PROSPECTUS_PROXY_PASS: 'https://prod-edx-mktg-backend.edx.org'
this should probably default to something else, and be overridden by an internal variable in the environment, instead of being passed in to the role invocation in the playbook.

2018-09-10 20:25 UTC, jlajoie commented on playbooks/roles/prospectus/tasks/main.yml
> +    src: "{{ PROSPECTUS_SRC_DIR }}" # /godata/pipelines/stage-prospectus/target/public
Oh okay good to know, so I should be able to do a step that clones in the repository on the AMI, does the build via npm, then moves those assets over?

2018-09-10 20:27 UTC, jlajoie commented on playbooks/prospectus.yml
> +      PROSPECTUS_PROXY_PASS: 'https://prod-edx-mktg-backend.edx.org'
Defaulting to something else because this is production, right? So settings this so something like the stage backend would be okay?

2018-09-11 12:13 UTC, fredsmith commented on playbooks/prospectus.yml
> +      PROSPECTUS_PROXY_PASS: 'https://prod-edx-mktg-backend.edx.org'
I would default to something useful to the open source community or devstack.  I realize that this code isn't expected to be used much outside of edx.org yet, but maybe default to the LMS?

2018-09-14 15:38 UTC, fredsmith approved these changes

2018-09-14 15:39 UTC, merged