naveed/node - Install nodejs and required packages to necessary for android automation
openedx-unsupported/configuration pull request #4814
Opened 2018-10-02 13:12 UTC by nedo

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

2018-10-02 18:11 UTC, estute commented on playbooks/roles/jenkins_worker/tasks/node.yml
> +  apt: name=nodejs
can you change this part to follow our conventions? https://openedx.atlassian.net/wiki/spaces/OpenOPS/pages/26837527/Ansible+Code+Conventions#AnsibleCodeConventions-Formatting

2018-10-02 18:11 UTC, estute commented on playbooks/roles/jenkins_worker/defaults/main.yml
> +node_version: "8.x"
I am not familiar with this versioning style. I think we should put explicit versions in our configuration. It makes it easier to reason about.

2018-10-02 18:15 UTC, estute commented on playbooks/roles/jenkins_worker/tasks/node.yml
> +# Install appium
Both appium and webdriver are testing dependencies. Therefore, I think they should be placed in the repo that contains the test code. This way, you don't need to rebuild an AMI in case you need to update or add a library.

2018-10-02 18:24 UTC, estute commented on playbooks/roles/jenkins_worker/tasks/node.yml
> +  shell: "curl -sL https://deb.nodesource.com/setup_{{node_version}} | sudo -E bash -"
In general, it is not advisable to pipe curl to bash (see: https://stackoverflow.com/questions/29382739/why-using-curl-sudo-sh-is-not-advised).

2018-10-02 18:26 UTC, estute commented on playbooks/roles/jenkins_worker/defaults/main.yml
> +node_version: "8.x"
If it is the case that you cannot specify an exact version, you can look into using nodenv, see https://github.com/edx/edx-platform/blob/master/scripts/jenkins-common.sh#L10

2018-10-02 18:26 UTC, estute requested changes
See inline comments

2018-10-04 10:35 UTC, nedo commented on playbooks/roles/jenkins_worker/tasks/node.yml
> +# Install appium
Alright, I'll put `appium` & `wd` installation as testing dependency

2018-10-04 10:38 UTC, nedo commented on playbooks/roles/jenkins_worker/defaults/main.yml
> +node_version: "8.x"
I've put explicit version on Node

2018-10-04 10:40 UTC, nedo commented on playbooks/roles/jenkins_worker/tasks/node.yml
> +  apt: name=nodejs
done

2018-10-04 12:09 UTC, nedo commented on playbooks/roles/jenkins_worker/tasks/node.yml
> +  shell: "curl -sL https://deb.nodesource.com/setup_{{node_version}} | sudo -E bash -"
I've replaced `curl` with `apt`, please have a look and comment

2018-10-04 12:14 UTC, nedo commented on playbooks/roles/jenkins_worker/defaults/main.yml
> +node_version: "8.x"
@estute seems like nodejs has `version.x` scheme now, please have a look on their repos, 
 
https://github.com/nodesource/distributions/tree/master/deb
https://nodejs.org/en/download/package-manager/

If you still feels using version in `x` is not fine, we can probably get their `tar` and install these through shell. wdty?

2018-10-04 12:20 UTC, nedo commented
Hi @estute I've fixed all points based on the recommendations, please have another pass. 
cc @staubina

2018-12-03 19:40 UTC, estute approved these changes
In general, looks good. However, two things:
1) you will nneed to include node.yml in main.yml, similar to this: https://github.com/edx/configuration/blob/master/playbooks/roles/jenkins_worker/tasks/main.yml#L12
2) make sure you can build the role on the build-packer-ami job, as I mentioned on my final comment here: https://github.com/edx/configuration/pull/4813

2019-01-23 12:15 UTC, nedo commented
@estute I am able to successfully build AMI, can you please have a last pass, before I merge this PR?

cc @staubina

2019-01-23 14:10 UTC, merged