Prospectus changes: Only leave secrets to be built by ansible.
openedx-unsupported/configuration pull request #4860
Opened 2018-11-01 17:55 UTC by dianakhuang

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

2018-11-01 17:57 UTC, dianakhuang commented
FYI @BenjiLee

2018-11-01 18:33 UTC, BenjiLee approved these changes

2018-11-01 18:33 UTC, BenjiLee requested changes
Do we also have to remove those variables in https://github.com/edx/configuration/blob/e927f24dafc1a53d671b76829b19d29552174ac3/playbooks/roles/prospectus/defaults/main.yml

2018-11-01 18:52 UTC, dianakhuang commented
Yup, we should pull those out, too. Thanks for catching that @BenjiLee .

2018-11-02 15:19 UTC, BenjiLee approved these changes

2018-11-02 15:48 UTC, coryleeio approved these changes

2018-11-02 16:11 UTC, merged