WIP: Define role to deploy blockstore
openedx-unsupported/configuration pull request #4875
Opened 2018-11-14 07:12 UTC by pkulkark

**Work in progress**. Do not merge yet. We'll ping when it goes through our internal review.

This PR adds a new role to deploy blockstore service. Deploying this service would be optional and would depend on the variable `BLOCKSTORE_ENABLED` to be set to `true`. By default, the value is set to `false`.

**Testing Instructions:**

1. Since the service is not configured with the OCIM, the required database and users need to be created. Once the database and users are created, the variables `BLOCKSTORE_DEFAULT_DB_NAME`, `BLOCKSTORE_DATABASE_HOST`, `BLOCKSTORE_DATABASE_USER`, `BLOCKSTORE_DATABASE_PASSWORD` will need to be overridden with the appropriate values.
2. Checkout the changes from this branch and deploy a sandbox by passing the following variables:
```
BLOCKSTORE_ENABLED: true
BLOCKSTORE_DATABASE_HOST: <mysql-server-to-be-used>
BLOCKSTORE_DATABASE_USER: <created-username>
BLOCKSTORE_DATABASE_PASSWORD: <created-password>
BLOCKSTORE_DEFAULT_DB_NAME: <created-database>
```
3. Once the sandbox is deployed successfully, verify that the service is running in your appserver and test the apis.

---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

2018-11-14 07:12 UTC, edx-webhook commented
Thanks for the pull request, @pkulkark! I've created [OSPR-2800](https://openedx.atlassian.net/browse/OSPR-2800) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

2018-11-14 20:16 UTC, natabene commented
@pkulkark  Thank you for your contribution. Please let me know once it is ready to look at.

2018-11-18 22:51 UTC, bradenmacdonald requested changes
Thanks @pkulkark! This is looking good but I'd like to request a few changes. Sorry for the delay in reviewing.

2018-11-18 22:51 UTC, bradenmacdonald commented on playbooks/roles/edx_django_service/tasks/main.yml
> +  command: pip install -r requirements.txt
I think it would be better to implement `make production-requirements` in blockstore rather than adding this `edx_django_service_without_make_targets` variable and introducing a separate mechanism here.

2018-11-18 22:51 UTC, bradenmacdonald commented on playbooks/roles/edx_django_service/tasks/main.yml
> +  command: python manage.py migrate
Same here - I think we should just implement `make migrate` in blockstore rather than having a separate mechanism here.

2018-11-18 22:51 UTC, bradenmacdonald commented on playbooks/roles/edxapp/defaults/main.yml
> +EDXAPP_BLOCKSTORE_API_URL: "http://localhost:8003/api/v1"
On devstacks, 8003 is already used for something else: https://github.com/edx/configuration/blob/b7313f4070930e7c9ae24d041bdafee218bff0e1/vagrant/base/analyticstack/Vagrantfile#L47

I think we should stick with port 8250 / 18250 for Blockstore?

2018-11-18 22:51 UTC, bradenmacdonald commented on playbooks/roles/blockstore/defaults/main.yml
> +BLOCKSTORE_BLOCKSTORE_URL_ROOT: 'http://localhost:8003'
On devstacks, 8003 is already used for something else: https://github.com/edx/configuration/blob/b7313f4070930e7c9ae24d041bdafee218bff0e1/vagrant/base/analyticstack/Vagrantfile#L47

I think we should stick with port 8250 / 18250 for Blockstore?

2018-11-18 22:51 UTC, bradenmacdonald commented on playbooks/roles/nginx/templates/edx/app/nginx/sites-available/blockstore.j2
> +  listen {{ BLOCKSTORE_NGINX_SSL_PORT }} ssl;
There are two different vars in this PR: `BLOCKSTORE_SSL_NGINX_PORT` not `BLOCKSTORE_NGINX_SSL_PORT` - only one should be used.

2018-11-18 22:51 UTC, bradenmacdonald commented on playbooks/roles/blockstore/defaults/main.yml
> +BLOCKSTORE_SSL_NGINX_PORT: "{{ blockstore_gunicorn_port }}"
These should not be the same as the gunicorn port. Both nginx and gunicorn can't be listening on the same port.

edX convention is that the service uses port 8xxx and then nginx listens on ports 18xxx (HTTP) and 48xxx (HTTPS).

Example:
https://github.com/edx/configuration/blob/538d054bde999a0828441ce3acd055618f4f733b/playbooks/roles/discovery/defaults/main.yml#L39-L40

So this should be:

```
blockstore_gunicorn_port: "8250"
...
BLOCKSTORE_NGINX_PORT: "1{{ blockstore_gunicorn_port }}"
BLOCKSTORE_SSL_NGINX_PORT: "4{{ blockstore_gunicorn_port }}"
```

2018-11-23 18:11 UTC, bradenmacdonald approved these changes
:+1: Looks good, just please consider my comments.

- [x] I tested this: SSH'd into the sandbox server, and confirmed I could run `curl http://localhost:8250/api/v1/` and `curl http://localhost:18250/api/v1/`
- [x] I read through the code
- [x] I checked for accessibility issues: n/a
- [ ] Includes documentation: actually not really, could you please add a `README.rst` file in the root of the blockstore role, or add a comment header to the top of the main .yml files for the role that says, "Role to deploy Blockstore, the next-generation Open edX Learning Object Repository" and which links to the blockstore repo?

2018-11-23 18:11 UTC, bradenmacdonald commented on playbooks/roles/edx_django_service/tasks/main.yml
> +  command: "virtualenv --python=python3.6 {{ edx_django_service_venv_dir }}"
FYI I think the newer syntax is `python3.6 -m venv {{ edx_django_service_venv_dir }}` but you can leave it as is if this works fine.

2018-11-23 18:11 UTC, bradenmacdonald commented on playbooks/roles/edxapp/defaults/main.yml
> +EDXAPP_BLOCKSTORE_PUBLIC_URL_ROOT: "http://localhost:8250"
I wonder if this should be using the nginx port (`BLOCKSTORE_NGINX_PORT`) instead, so that serving static files is done by nginx?

2018-11-24 10:45 UTC, pkulkark commented on playbooks/roles/edxapp/defaults/main.yml
> +EDXAPP_BLOCKSTORE_PUBLIC_URL_ROOT: "http://localhost:8250"
Makes sense. Have changed it to the nginx port.

2018-11-26 22:08 UTC, bradenmacdonald commented
@ormsbee Are you interested in reviewing this before we open an OSPR and/or get DevOps to look at it?

2018-12-06 18:36 UTC, ormsbee commented
@bradenmacdonald: Argh. I thought I replied to this already. Please go ahead.

2018-12-15 01:49 UTC, bradenmacdonald commented
@natabene This is ready for review :)

2018-12-15 02:57 UTC, natabene commented
@edx/devops  CAn you take a look?

2019-01-04 17:43 UTC, symbolist commented
@bradenmacdonald @ormsbee Now that we have added a dependency on ElasticSearch, we will have to add that here as well. Should we go with a docker container, like journals is [doing](https://github.com/edx/configuration/blob/master/playbooks/roles/journals/tasks/main.yml#L49)?

Also how does edX manage ElasticSearch - itself or uses a hosted version?

2019-01-04 18:59 UTC, bradenmacdonald commented
@symbolist I would think that on docker devstack, we should share the existing ElasticSearch instance if possible, and on AWS we should use hosted ElasticSearch.

2019-03-13 10:09 UTC, pkulkark commented
@natabene I've sqashed all the commits and rebased to latest master. Can this be reviewed?

2019-03-13 14:21 UTC, natabene commented
@pkulkark Thank you for letting me know. @edx/devops can you give this a look? @ormsbee Do you also give it a look in addition to devops?

2019-03-18 19:00 UTC, coryleeio commented
@symbolist edX uses AWS hosted elasticsearch internally

2019-03-19 13:51 UTC, feanil requested changes

2019-03-19 13:51 UTC, feanil commented on playbooks/roles/blockstore/defaults/main.yml
> +BLOCKSTORE_SECRET_KEY: 'Your secret key here'
Don't set a default secret key.

2019-03-19 13:51 UTC, feanil commented on playbooks/roles/edx_django_service/tasks/main.yml
> +- name: add python3.6 repository from ppa
I'd rather not have a separate python3 and python 3.6 install.  Is the default python3 the wrong version?  Can we correct that?

2019-03-19 13:51 UTC, feanil commented on playbooks/roles/edx_django_service/tasks/main.yml
> +    repo: ppa:deadsnakes/ppa
Rather than pulling from deadsnakes, we want to use the system python so that we can be gauranteed that we are getting timely security updates.

2019-03-22 17:56 UTC, bradenmacdonald commented on playbooks/roles/blockstore/meta/main.yml
> +    dx_django_service_version: '{{ BLOCKSTORE_VERSION }}'
@pkulkark Shouldn't this be `edx_django_service_version` ? (edx_ vs dx_)

2019-04-01 22:55 UTC, pkulkark commented on playbooks/roles/edx_django_service/tasks/main.yml
> +- name: add python3.6 repository from ppa
python 3.6 is not available by default for Ubuntu 16.04. And I wasn't sure if the other roles which use the default python 3 are compatible with python 3.6. Please let me know if there's any other way around it.

2019-04-01 22:56 UTC, pkulkark commented on playbooks/roles/edx_django_service/tasks/main.yml
> +    repo: ppa:deadsnakes/ppa
This was also due to python 3.6 repo not being available on Ubuntu 16.04.

2019-04-02 00:25 UTC, pkulkark commented on playbooks/roles/blockstore/defaults/main.yml
> +BLOCKSTORE_SECRET_KEY: 'Your secret key here'
Changed it to blank.

2019-04-02 00:26 UTC, pkulkark commented on playbooks/roles/blockstore/meta/main.yml
> +    dx_django_service_version: '{{ BLOCKSTORE_VERSION }}'
Nice catch! I've corrected it. Thanks.

2019-04-11 15:45 UTC, feanil commented on playbooks/roles/blockstore/defaults/main.yml
> +BLOCKSTORE_SECRET_KEY: ''
this should be set to `null` as an empty string is still a valid string.  Sorry for the lack of clarification earlier.

2019-04-11 15:45 UTC, feanil commented on playbooks/roles/edx_django_service/tasks/main.yml
> +- name: add python3.6 repository from ppa
Does it make sense to target 18.04 since that is the newest LTS release?  edX is planning on moving to that for its other services soon, so having now services start on 18.04 wouldn't be a bad idea and 18.04 has python 3.6 as the current version of python3.

2019-04-22 06:21 UTC, pkulkark commented on playbooks/roles/blockstore/defaults/main.yml
> +BLOCKSTORE_SECRET_KEY: ''
Sorry. I've changed it to null.

2019-04-22 06:30 UTC, pkulkark commented on playbooks/roles/edx_django_service/tasks/main.yml
> +- name: add python3.6 repository from ppa
Most of our clients' instances are still using 16.04 LTS. So we won't be able to deploy blockstore to them until all of them have moved to 18.04. Perhaps we can remove the python3.6 install once 16.04 LTS reaches end of life (I think that's April 2021)?

2019-04-22 15:58 UTC, bradenmacdonald commented on playbooks/roles/edx_django_service/tasks/main.yml
> +- name: add python3.6 repository from ppa
If that becomes a problem, we could always consider deploying it inside a docker container; then it doesn't matter what version of Ubuntu the host VM is running.

2019-05-21 20:45 UTC, edx-webhook commented
Thanks for the pull request, @pkulkark! I've created [OSPR-3484](https://openedx.atlassian.net/browse/OSPR-3484) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

2019-05-24 15:14 UTC, natabene commented
@edx/devops This seems to be ready for another round of review. CC @feanil

2019-05-24 15:26 UTC, feanil commented
@natabene I'm still waiting on an answer on whether we can have this role assume it's running on 18.04 so we don't need to have pull in a PPA for python.

2019-05-27 20:23 UTC, symbolist commented
> Does it make sense to target 18.04 since that is the newest LTS release? edX is planning on moving to that for its other services soon, so having now services start on 18.04 wouldn't be a bad idea and 18.04 has python 3.6 as the current version of python3.

@feanil Our instances (client-production and sandboxes) run on a single server so unless all the services are moved to 18.04, we will not be able to run Blockstore.

I see that 16.04 [has](https://packages.ubuntu.com/xenial/python3) Python 3.5.1-3. Would it work if we get Blockstore service compatible with Python 3.5 and removed this extra Python 3.6 install?

2019-05-28 13:36 UTC, feanil commented
If it's not too much work, that would be great,  thanks for the extra context on your setup @symbolist .  If it's too much of a hassel to get this working with python 3.5 we can certainly move ahead with this as is and then plan on removing it later, but if that's easy to do it cuts down on the number of things we have to do in the future to keep this clean.

2019-05-29 15:30 UTC, symbolist commented
@feanil Sounds good. Blockstore is a standard Django+DRF microservice so I do not expect any issues with getting it working with Python 3.5 and I would prefer we do it the right way in the first go. :) We will ping you once this is ready for another pass.

2019-06-19 19:46 UTC, symbolist commented
@feanil I have updated this and it is ready for another review from you.

2019-06-25 19:08 UTC, feanil approved these changes
@symbolist one nit but otherwise I think this is good to go.

2019-06-25 19:08 UTC, feanil commented on playbooks/roles/blockstore/defaults/main.yml
> +SANDBOX_ENABLE_BLOCKSTORE: True
I think this line should be deleted right?

2019-06-25 20:39 UTC, symbolist commented on playbooks/roles/blockstore/defaults/main.yml
> +SANDBOX_ENABLE_BLOCKSTORE: True
Ah yes, I have removed it.

2019-06-25 20:40 UTC, symbolist commented
@feanil I have made the change you requested.

2019-06-26 18:14 UTC, feanil commented
Sounds good, I'm running a final suite of tests and once that's done I'll merge this.  I'll let you know if I run into anything that prevents this from merging.  Though I don't expect there to be anything.

2019-06-28 13:53 UTC, feanil approved these changes

2019-06-28 13:53 UTC, merged

2019-06-28 13:53 UTC, edx-webhook commented
@pkulkark 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/4875&entry.1484655318=https://github.com/pkulkark&entry.752974735=2018-11-14+07:12&entry.1917517419=2019-06-28+13:53&entry.2133058324=Yes) so we can improve your experience in the future.