Restrict ecommerce admin endpoints access to VPN CIDRS (OPS-3138)
openedx-unsupported/configuration pull request #4898
Opened 2018-12-05 12:05 UTC by nadeemshahzad

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

2018-12-06 21:51 UTC, coryleeio requested changes

2018-12-06 21:51 UTC, coryleeio commented on playbooks/roles/edx_django_service/templates/edx/app/nginx/sites-available/concerns/proxy-to-app.j2
> +{% include "concerns/admin_endpoints_access_from_restricted_cidrs.j2" %}
Can we more clearly show that this is specific to ecommerce?
At the moment it is hardcoded to block specific endpoints on ecommerce 'courses|coupons|programs|credit|dashboard|management' that could even be harmful if they were accidentally turned on elsewhere.

I wonder if we could combine these into a CIDR restricted endpoints template, and pass in a list of urls and cidrs?

If that isn't easy to do I think it would atleast make sense to change this to be obviously specific to ecommerce.

2018-12-07 13:40 UTC, nadeemshahzad commented
As we need to restrict the django admin for ecommerce all environments, so keeping it default and overriding admin URLs for stage environment ( https://github.com/edx/edx-internal/pull/662 )

2018-12-07 15:28 UTC, coryleeio commented on playbooks/roles/nginx/defaults/main.yml
> +NGINX_ADMIN_ACCESS_CIDRS: "{{ NGINX_DJANGO_ADMIN_ACCESS_CIDRS }}"
I think you can remove NGINX_DJANGO_ADMIN_ACCESS_CIDRS because it is no longer being read anywhere

2018-12-07 15:33 UTC, coryleeio approved these changes

2018-12-07 15:33 UTC, coryleeio commented on playbooks/roles/nginx/defaults/main.yml
> +NGINX_ADMIN_ACCESS_CIDRS: "{{ NGINX_DJANGO_ADMIN_ACCESS_CIDRS }}"
After cleaning that up feel free to merge - I don't want to block it another day.

2018-12-14 11:16 UTC, merged