Renamed proctoring backend setting
openedx-unsupported/configuration pull request #4905
Opened 2018-12-12 20:51 UTC by davestgermain

As a result of refactoring [edx-proctoring](/edx/edx-proctoring) to enable multiple proctoring backends, the settings have changed to be more flexible.

---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

2018-12-12 21:56 UTC, coryleeio commented
corresponds with:
https://github.com/edx/edx-internal/pull/669/

2018-12-12 22:00 UTC, coryleeio requested changes

2018-12-12 22:00 UTC, coryleeio commented on playbooks/roles/edxapp/defaults/main.yml
> -EDXAPP_PROCTORING_BACKEND_PROVIDER:
Can you add something to the changelog about the rename?

2018-12-13 14:30 UTC, davestgermain commented on playbooks/roles/edxapp/defaults/main.yml
> -EDXAPP_PROCTORING_BACKEND_PROVIDER:
done

2019-01-02 15:58 UTC, coryleeio approved these changes

2019-01-02 16:33 UTC, merged