fix celery script
openedx-unsupported/configuration pull request #4916
Opened 2019-01-02 11:36 UTC by syed-awais-ali

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

2019-01-02 14:46 UTC, feanil commented on util/jenkins/check_celery_progress/check_celery_progress.py
> +            print("Exception: Could not find {} in body".format(e))
This would only happen when a body has no 'task' key in it right?  What does that mean?  Why would that occur?

2019-01-03 01:31 UTC, jdmulloy requested changes

2019-01-03 01:31 UTC, jdmulloy commented on util/jenkins/check_celery_progress/check_celery_progress.py
> +            print("Exception: Could not find {} in body".format(e))
This is catching all exceptions, it should be narrowed to only catch the appropriate exception for a missing key, which I believe is "KeyErro". Also it would be useful to print the entire body so we can better understand the error condition.

2019-01-08 22:34 UTC, jdmulloy approved these changes

2019-01-09 14:31 UTC, merged