Fix devstack auth issues
openedx-unsupported/configuration pull request #4950
Opened 2019-01-16 20:45 UTC by tuchfarber

OAuth in devstack was broken by a mismatch of settings

Correct settings should result in:
SOCIAL_AUTH_EDX_OIDC_ISSUER: http://localhost:18000/oauth2
SOCIAL_AUTH_EDX_OIDC_PUBLIC_URL_ROOT: http://localhost:18000/oauth2
SOCIAL_AUTH_EDX_OIDC_LOGOUT_URL: http://edx.devstack.lms:18000/logout
SOCIAL_AUTH_EDX_OIDC_URL_ROOT: http://edx.devstack.lms:18000/oauth2

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

2019-01-16 21:07 UTC, douglashall approved these changes
Thanks!

2019-01-16 21:08 UTC, tuchfarber commented
@douglashall & @staubina: This should fix the OAuth login issue in devstack. The reason some services were still working even with the bad settings is because they pull OAuth settings from SiteConfiguration, not the `.env` file. Tried to clearly step through it in the comment. Let me know if you have any questions. Hoping to not fix this a third time when I realize I missed something. Hahah. 

@edx/devops : Requesting review to verify this won't mess up anything in non devstack environments. I got the traceback side of this repo down pretty well, but not the propagation side. This will effect some vars in `common_vars` and `edx_django_service`.

2019-01-17 17:40 UTC, staubina approved these changes

2019-01-17 18:08 UTC, coryleeio requested changes

2019-01-17 18:08 UTC, coryleeio commented on playbooks/roles/common_vars/defaults/main.yml
> +COMMON_OIDC_ISSUER: '{{ COMMON_OAUTH_PUBLIC_URL_ROOT }}'
This is extremely difficult to trace - Could you just set in docker/devstack_common_ansible_overrides.yml ?
COMMON_OIDC_ISSUER: '{{ EDXAPP_LMS_ROOT_URL }}/oauth2'

I think that would have the same effect - but only effect devstack

2019-01-17 18:49 UTC, tuchfarber commented on playbooks/roles/common_vars/defaults/main.yml
> +COMMON_OIDC_ISSUER: '{{ COMMON_OAUTH_PUBLIC_URL_ROOT }}'
Change made! Except in this case it needs to be `'{{ EDXAPP_LMS_PUBLIC_ROOT_URL }}/oauth2'` not `'{{ EDXAPP_LMS_ROOT_URL }}/oauth2'` because we want the `localhost:18000` base to be the issuer, as per [this PR that changed things](https://github.com/edx/edx-platform/pull/19453/files#diff-8bebf7b700146de1149a24234c58d292R28)

2019-01-17 19:21 UTC, coryleeio approved these changes

2019-01-17 19:22 UTC, merged