[BB-209] Add option to disable celery heartbeats from celery workers WIP
openedx-unsupported/configuration pull request #4951
Opened 2019-01-17 11:06 UTC by giovannicimolin

This PR adds an option to enable/disable celery heartbeats from the celery workers, and leaves them disabled by default.
It does this by passing the parameter '--without-heartbeat' to the workers when provisioning the services.

The current default setup of Celery in Open edX uses something called heartbeats to detect connection drops to the celery broker. With as many 15 celery processes running on Open edX servers, this can mean that a lot of the RabbitMQ usage is just to check for connection drops, and that is mostly to get around issues with RabbitMQ behind a load-balancer. Disabling heartbeats can have a drastic reduction RabbitMQ usage.

Reviewers
---
- [ ] Opencraft reviewer
- [ ] edX Reviewer TBD

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

2019-01-17 11:06 UTC, edx-webhook commented
Thanks for the pull request, @giovannicimolin! I've created [OSPR-2988](https://openedx.atlassian.net/browse/OSPR-2988) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

2019-01-17 11:45 UTC, jamestait commented on playbooks/roles/edxapp/defaults/main.yml
> +worker_django_disable_heartbeats: true
At first glance, the use of a positive boolean `true` to convey disabling a feature seems a little awkard. Perhaps this could be flipped around:

```suggestion
worker_django_enable_heartbeats: false
```

2019-01-17 11:46 UTC, jamestait commented on playbooks/roles/edxapp/templates/edx/app/supervisor/conf.d.available/workers.conf.j2
> +command={{ edxapp_app_dir }}/worker.sh {{ w.service_variant }} --settings={{ worker_django_settings_module }} celery worker --loglevel=info --queues=edx.{{ w.service_variant }}.core.{{ w.queue }} --h
With the previously-suggested change, this then becomes:

```suggestion
command={{ edxapp_app_dir }}/worker.sh {{ w.service_variant }} --settings={{ worker_django_settings_module }} celery worker --loglevel=info --queues=edx.{{ w.service_variant }}.core.{{ w.queue }} --hostname=edx.{{ w.service_variant }}.core.{{ w.queue }}.%%h --concurrency={{ w.concurrency }} {{ '--maxtasksperchild ' + w.max_tasks_per_child|string if w.max_tasks_per_child is defined else '' }} {{ '--without-heartbeat' if worker_django_enable_heartbeats is false else '' }}
```

2019-01-17 12:06 UTC, giovannicimolin commented on playbooks/roles/edxapp/defaults/main.yml
> +worker_django_disable_heartbeats: true
I agree it seems a little awkward. I'll change this to `worker_django_enable_heartbeats` :grin:

2019-01-17 12:12 UTC, jamestait commented on playbooks/roles/edxapp/defaults/main.yml
> +worker_django_enable_heartbeats: true
This reads better, thanks - but it needs to be `false` to disable the heartbeats. :wink:

2019-01-17 17:23 UTC, natabene commented
@giovannicimolin Thank you for your contribution. @edx/devops Can you give this a look?

2019-01-18 11:42 UTC, jamestait commented
:+1:

- [x] I tested this:
SSH session into the sandbox instance, verified correct generation of `workers.conf` and presence of the `--without-heartbeat` flag on running celery worker processes.
- [x] I read through the code
- [ ] ~I checked for accessibility issues~
- [ ] ~Includes documentation~

2019-01-21 12:52 UTC, lgp171188 commented on playbooks/roles/edxapp/defaults/main.yml
> +worker_django_enable_heartbeats: true
@jamestait, this has to be `true` in order to preserve backward compatibility and can be overridden for specific repositories and deployments.

2019-01-21 12:53 UTC, lgp171188 commented on playbooks/roles/edxapp/defaults/main.yml
> +worker_django_enable_heartbeats: false
@giovannicimolin, the default has to be `true` to retain the current behavior and can be overridden for specific deployments.

2019-02-09 20:47 UTC, giovannicimolin commented
@natabene Do you have any news on this? Just a friendly ping :grin:

2019-02-11 17:59 UTC, natabene commented
@giovannicimolin Sorry, no news yet. I will keep you updated.

2019-02-25 14:45 UTC, feanil requested changes
One change requested then I think this is good to go.

2019-02-25 14:45 UTC, feanil commented on playbooks/roles/edxapp/defaults/main.yml
> +worker_django_enable_heartbeats: true
Lowercase vars are by convention internal and any vars we expect people to change are generally uppercase.  Also the edx ecosystem now has multiple services with workers to I suggest you name this variable `EDXAPP_CELERY_HEARTBEAT_ENABLED`

2019-02-27 19:33 UTC, giovannicimolin commented on playbooks/roles/edxapp/defaults/main.yml
> +worker_django_enable_heartbeats: true
@feanil Sure, I've renamed the variables to `EDXAPP_CELERY_HEARTBEAT_ENABLED`.

2019-02-27 20:17 UTC, feanil approved these changes

2019-02-28 13:01 UTC, giovannicimolin commented
@feanil Can you merge this? I don't have permissions.

2019-02-28 17:31 UTC, merged

2019-02-28 17:31 UTC, edx-webhook commented
@giovannicimolin 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/4951&entry.1484655318=https://github.com/giovannicimolin&entry.752974735=2019-01-17+11:06&entry.1917517419=2019-02-28+17:31&entry.2133058324=Yes) so we can improve your experience in the future.