added notifier queue
openedx-unsupported/configuration pull request #4964
Opened 2019-01-22 14:05 UTC by syed-awais-ali

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

2019-01-22 16:03 UTC, feanil commented on playbooks/roles/ecomworker/defaults/main.yml
>  ECOMMERCE_WORKER_CONCURRENCY: 4
Where is this setting used?  How will this override the default queue name?

2019-01-22 16:03 UTC, feanil commented on playbooks/roles/notifier/defaults/main.yml
> +  NOTIFIER_ROUTING_KEY: "{{ NOTIFIER_CELERY_QUEUE }}"
I don't see anything that uses this key, is there a corresponding change to the notifier code?

2019-01-23 13:57 UTC, syed-awais-ali commented on playbooks/roles/notifier/defaults/main.yml
> +  NOTIFIER_ROUTING_KEY: "{{ NOTIFIER_CELERY_QUEUE }}"
[notifier](https://github.com/edx/notifier/pull/73) will consume this.

2019-02-25 17:29 UTC, coryleeio commented on playbooks/roles/ecomworker/defaults/main.yml
>  ECOMMERCE_WORKER_CONCURRENCY: 4
The consumption should be here:
https://github.com/edx/ecommerce/pull/2129

Once the PR is updated.

2019-02-25 17:31 UTC, coryleeio requested changes

2019-02-25 17:31 UTC, coryleeio commented on playbooks/roles/ecomworker/defaults/main.yml
>  ECOMMERCE_WORKER_CONCURRENCY: 4
@syed-awais-ali Can you separate out the ecommerce bit into a different PR, that will make reverting simpler and less disruptive if need be and let you focus on landing the notifier PR

2019-03-06 22:27 UTC, coryleeio approved these changes

2019-04-10 20:25 UTC, coryleeio approved these changes

2019-06-14 09:52 UTC, closed without merging