WIP: Add configuration files for new Registrar IDA
openedx-unsupported/configuration pull request #5008
Opened 2019-02-11 18:40 UTC by kdmccormick

**This PR is currently a work in progress.**

This PR adds configuration files to create a service environment for the new Registrar IDA.

**Ticket:** https://openedx.atlassian.net/browse/EDUCATOR-3990
**Team:** @edx/educator-neem 

---------
Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

2019-02-13 16:11 UTC, schenedx requested changes
I think there are still questions we need to figure out for this to be ready.
We should figure out if edx-internal should have corresponding value for these to be in stage and prod

2019-02-13 16:11 UTC, schenedx commented on docker/build/registrar/ansible_overrides.yml
> +registrar_create_demo_data: false
Do we need this flag? Unless we have `registrar_post_migrate_commands`. I think we do not have such command at the moment yet

2019-02-13 16:11 UTC, schenedx commented on playbooks/registrar.yml
> +    ENABLE_NEWRELIC: False
Why false here? Shouldn't we enable newrelic on this service?

2019-02-13 16:11 UTC, schenedx commented on playbooks/roles/registrar/defaults/main.yml
> +REGISTRAR_DOMAIN: 'registrar'
I think this domain should be `localhost`? I see all the values here are related to local host, no?

2019-02-13 16:11 UTC, schenedx commented on playbooks/roles/registrar/defaults/main.yml
> +registrar_create_demo_data: false
I don't think we need this flag

2019-02-13 16:11 UTC, schenedx commented on playbooks/roles/registrar/defaults/main.yml
> +registrar_post_migrate_commands:
I don't believe we have this post_migrate command for registrar. So, we can set it to empty string for now

2019-02-13 16:11 UTC, schenedx commented on playbooks/roles/registrar/tasks/main.yml
> +#
So, if everything is commented out here, what is this file used for?

2019-02-13 16:11 UTC, schenedx commented on util/parsefiles_config.yml
> +  - registrar: 3
What does the weights mean? Why `3`?

2019-02-14 14:57 UTC, kdmccormick commented on util/parsefiles_config.yml
> +  - registrar: 3
They are relative build times to help Travis prioritize build jobs smartly. It took Registrar's Dockerfile 3 minutes to build. See https://github.com/edx/configuration/blob/master/util/README.rst.

2019-02-14 14:57 UTC, kdmccormick commented on util/parsefiles_config.yml
> +  - registrar: 3
As Registrar grows we may need to revise this value.

2019-02-14 15:02 UTC, kdmccormick commented on playbooks/roles/registrar/tasks/main.yml
> +#
I believe tasks/main.yml is for defining tasks required to set up the service environment. Currently, Registrar has none. However, every single role in the repository has a tasks/main.yml file (some of them empty) leading me to believe that the file is required.

2019-02-14 15:14 UTC, kdmccormick commented on playbooks/roles/registrar/defaults/main.yml
> +REGISTRAR_DOMAIN: 'registrar'
It seems like some apps use their name, and some apps use `localhost`. I'll check with DevOps.

2019-02-14 15:14 UTC, kdmccormick commented on playbooks/registrar.yml
> +    ENABLE_NEWRELIC: False
Good catch.

2019-02-14 15:22 UTC, kdmccormick commented on playbooks/roles/registrar/defaults/main.yml
> +registrar_post_migrate_commands:
Okay. I'm not sure what it does, but I'll trust you on it.

2019-02-14 16:17 UTC, kdmccormick commented on docker/build/registrar/ansible_overrides.yml
> +registrar_create_demo_data: false
:+1:

2019-02-14 17:45 UTC, feanil commented on playbooks/roles/registrar/defaults/main.yml
> +REGISTRAR_DOMAIN: 'registrar'
This should be 'localhost' in the defaults and then override to 'registrar' for devstack(docker)

2019-02-14 18:18 UTC, schenedx reviewed
Just a mis-spell. Rest LGTM

2019-02-14 18:18 UTC, schenedx commented on CHANGELOG.md
> +- Role: regstrar
mis-spelled

2019-02-14 19:03 UTC, kdmccormick commented on CHANGELOG.md
> +- Role: regstrar
:+1:

2019-02-14 19:32 UTC, feanil reviewed
A few comments, but generally looks good.  Let me know when you think it's ready for a final review.

2019-02-14 19:32 UTC, feanil commented on docker/build/registrar/ansible_overrides.yml
> +REGISTRAR_URL_ROOT: 'http://localhost:18734'
In Docker, this will be `registrar` instead of `localhost`

2019-02-14 19:32 UTC, feanil commented on playbooks/roles/registrar/defaults/main.yml
> +REGISTRAR_SECRET_KEY: 'SET-ME-TO-A-UNIQUE-LONG-RANDOM-STRING'
Don't set a default value, to prevent people from accidentally running with the wrong secret key.  Instead, set one in the docker overrides file for testing/devstack, and work with devops to set them in the various internal repos.

2019-02-14 20:07 UTC, kdmccormick commented on docker/build/registrar/ansible_overrides.yml
> +REGISTRAR_URL_ROOT: 'http://localhost:18734'
:+1:

2019-02-14 20:11 UTC, kdmccormick commented on playbooks/roles/registrar/defaults/main.yml
> +REGISTRAR_SECRET_KEY: 'SET-ME-TO-A-UNIQUE-LONG-RANDOM-STRING'
What should the default value for testing/devstack (by which I assume you mean set in `ansible_overrides.yml`) be?

2019-02-14 20:27 UTC, kdmccormick commented on playbooks/roles/registrar/defaults/main.yml
> +REGISTRAR_DOMAIN: 'registrar'
:+1:

2019-02-14 20:53 UTC, kdmccormick commented
Ready for re-reviews @schenedx @feanil

2019-02-14 20:58 UTC, schenedx approved these changes
👍

2019-02-19 18:17 UTC, feanil approved these changes

2019-02-19 18:47 UTC, merged