Ihassan/ops 3506 missing rds cloudwatch alarms
openedx-unsupported/configuration pull request #5009
Opened 2019-02-12 12:05 UTC by syedimranhassan

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

2019-02-12 18:14 UTC, jdmulloy requested changes

2019-02-12 18:14 UTC, jdmulloy commented on util/jenkins/missing_rds_alarms.py
> +            else:
I don't think we need this else pass block

2019-02-12 18:14 UTC, jdmulloy commented on util/jenkins/missing_rds_alarms.py
> +    if flag == 1:
```suggestion
    if len(missing_alarm) > 0:
```

We can get rid of the flag since we're tracking things in the missing_alarm list anyways.

2019-02-12 18:14 UTC, jdmulloy commented on util/jenkins/missing_rds_alarms.py
> +    flag = 0
```suggestion
```

2019-02-12 18:14 UTC, jdmulloy commented on util/jenkins/missing_rds_alarms.py
> +                flag = 1
```suggestion
```

2019-02-12 18:14 UTC, jdmulloy commented on util/jenkins/missing_rds_alarms.py
> +    sys.exit(flag)
```suggestion
        sys.exit(1)
```

We can call sys.exit to exit with status code 1 if alarms are missing. Otherwise we can let python exit with a 0 as usual.

2019-02-13 20:40 UTC, coryleeio requested changes

2019-02-13 20:40 UTC, coryleeio commented on util/jenkins/missing_rds_alarms.py
> +        client = boto3.client("rds", region_name=region["RegionName"])
I would wrap all the boto3 calls in their own functions and add the @backoff annotation

You can find examples in tubular.

Otherwise little internet blips may cause this to fail.

2019-02-19 22:11 UTC, jdmulloy requested changes

2019-02-19 22:11 UTC, jdmulloy commented on util/jenkins/rds_alarms_checker/missing_rds_alarms.py
> +class BotoEC2:
Since this class is a wrapper around boto classes, I think it would be cleaner to have a class per boto object, so one for EC2, one for RDS and one for CloudWatch. The methods below aren't all applicable to all the client types that could be used here.

See this for an example:
https://github.com/edx/configuration/blob/d119bb14df2569bebc7c1ab711fde9131922c450/util/jenkins/update_celery_monitoring/update_celery_monitoring.py#L37

2019-02-19 22:24 UTC, coryleeio approved these changes

2019-02-19 22:27 UTC, coryleeio requested changes
Changes requested via slack

2019-02-20 18:49 UTC, coryleeio approved these changes

2019-02-20 18:53 UTC, jdmulloy approved these changes

2019-02-21 07:47 UTC, merged