WIP: Slow query logs export to cloudwatch
openedx-unsupported/configuration pull request #5037
Opened 2019-03-05 14:56 UTC by syedimranhassan

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

2019-03-18 16:34 UTC, coryleeio requested changes

2019-03-18 16:34 UTC, coryleeio commented on util/jenkins/export_slow_logs/export_slow_query_logs.py
> +@click.option('--password', required=True, help='Password to speak with RDS')
https://click.palletsprojects.com/en/5.x/options/#password-prompts

Check out the docs here and make this hidden

Read it from an environment variable on Jenkins, as it is bad practice to type a password as an inline arguement to a program as it can be exposed to other users on the system this way.

https://click.palletsprojects.com/en/5.x/options/#values-from-environment-variables

2019-03-18 16:34 UTC, coryleeio approved these changes

2019-03-26 12:51 UTC, syedimranhassan commented on util/jenkins/export_slow_logs/export_slow_query_logs.py
> +@click.option('--password', required=True, help='Password to speak with RDS')
I was picking them up form env variables but feanil commented on the PR that this should be picked up from credentials binding
https://github.com/edx/jenkins-job-dsl/pull/631#discussion_r265301078

2019-04-23 13:48 UTC, merged