BB-987: Add user retirement pipeline setup role [WIP]
openedx-unsupported/configuration pull request #5040
Opened 2019-03-05 18:06 UTC by giovannicimolin

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

2019-03-05 18:06 UTC, edx-webhook commented
Thanks for the pull request, @giovannicimolin! I've created [OSPR-3176](https://openedx.atlassian.net/browse/OSPR-3176) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

2019-03-05 18:11 UTC, giovannicimolin commented
@natabene Can you give me access to https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist?

2019-03-05 19:07 UTC, natabene commented
@giovannicimolin Thank you for your contribution. The document you requested has restricted level of access and is only available to edX. Is there something specific you need from it? Please let me know once this PR is ready for review.

2019-03-07 12:54 UTC, giovannicimolin commented
@natabene I was hoping to check if the playbook role was checking everything from the checklist, so no worries. We'll do a round of internal review before edX's.

2019-03-07 15:47 UTC, jamestait approved these changes
:+1:

- [x] I tested this:
 * Performed the setup as described.
 * Created three users.
 * Logged in as two users and deleted their accounts.
 * Verified the retirement requests via Django admin.
 * Ran the script.
 * Verified console output was as expected.
 * Verified in LMS logs that retirement requests were processed and emails generated.
 * Verified that the retired accounts could not be logged into.
 * Verified that I could not login using the autogenerated placeholder account email.
- [x] I read through the code
- [ ] ~I checked for accessibility issues~
- [x] Includes documentation

2019-03-07 15:47 UTC, jamestait commented on playbooks/roles/user_retirement_pipeline/README.rst
> +```
Is this file written by us, or duplicated from somewhere else? Reason I ask is that it looks familiar, but possibly from an earlier review of this PR - but this command is different to the one given in the testing instructions.

2019-03-07 15:47 UTC, jamestait commented on playbooks/roles/user_retirement_pipeline/defaults/main.yml
> +RETIREMENT_SERVICE_OAUTH_CLIENT_SECRET: "retirement-secret"
Worth adopting a similar approach for these values to that taken in `playbooks/roles/edxapp/defaults/main.yml`? i.e. explicitly state that this should be changed?

2019-03-07 15:47 UTC, jamestait commented on playbooks/roles/user_retirement_pipeline/templates/config.yml.j2
> +  {% endfor %}
Neatly done, I like this!

2019-03-07 15:51 UTC, giovannicimolin commented on playbooks/roles/user_retirement_pipeline/README.rst
> +```
Forgot to update the `README`, I based this file from the readme of the `simple-theme` role.

2019-03-07 15:53 UTC, giovannicimolin commented on playbooks/roles/user_retirement_pipeline/defaults/main.yml
> +RETIREMENT_SERVICE_OAUTH_CLIENT_SECRET: "retirement-secret"
Doing that would break a deployment with default values. 
But I it's fine if we do this only on `RETIREMENT_SERVICE_OAUTH_CLIENT_ID` and `RETIREMENT_SERVICE_OAUTH_CLIENT_SECRET`.

2019-03-07 15:53 UTC, giovannicimolin commented on playbooks/roles/user_retirement_pipeline/defaults/main.yml
> +RETIREMENT_SERVICE_OAUTH_CLIENT_SECRET: "retirement-secret"
I'll change it.

2019-03-07 18:26 UTC, giovannicimolin commented on playbooks/roles/user_retirement_pipeline/defaults/main.yml
> +RETIREMENT_SERVICE_OAUTH_CLIENT_SECRET: "retirement-secret"
Done.

2019-03-07 18:31 UTC, giovannicimolin commented
@natabene This is ready for review. 
@bmedx, @doctoryes: As we discussed [on Slack](https://openedx.slack.com/archives/C08B4LZEZ/p1551212503045300), I've followed your guidelines when writing this role:
- The role is off by default
- The cron job is also off by default, enabling the set up of the user retirement service without the cron job
- This can be deployed independently of the edxapp (if a retirement service is needed outside the AppServer)
- All logs are saved in `/edx/var/log/retirement_service`

2019-03-08 15:19 UTC, natabene commented
@giovannicimolin Thanks for letting me know. @edx/devops Can you give this a look? This is ready for your review.

2019-03-12 15:35 UTC, singuliere commented
@giovannicimolin most of the instructions work, almost there :-) Only I can't figure out why

```
./manage.py lms --settings=devstack_docker populate_retirement_states
WARNING:py.warnings:/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/__init__.py:5: DeprecationWarning: Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported
  warnings.warn("Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported", DeprecationWarning)

2019-03-12 15:30:02,241 WARNING 5162 [enterprise.utils] utils.py:50 - Could not import Registry from third_party_auth.provider
2019-03-12 15:30:02,241 WARNING 5162 [enterprise.utils] utils.py:51 - cannot import name _LTI_BACKENDS
States have been synchronized. Differences:
   Added: set([])
   Removed: set([])
   Remaining: set(['ERRORED', 'PENDING', 'ABORTED', 'COMPLETE'])
States updated successfully. Current states:
PENDING (step 1)
ERRORED (step 11)
ABORTED (step 21)
COMPLETE (step 31)
```
And strace shows it does not read `/edx/app/edxapp/lms.env.json`. Any idea?

2019-03-12 16:16 UTC, singuliere commented
Here are commands to run via `make lms-shell` so the user to be removed is created (instead of going through the web interface):

```
python /edx/app/edxapp/edx-platform/manage.py lms --settings=devstack_docker manage_user frob frob@example.com
echo "from django.contrib.auth import get_user_model; User = get_user_model(); user = User.objects.get(username=\"frob\"); user.set_password(\"frob\"); user.save()" | python /edx/app/edxapp/edx-platform/manage.py lms shell  --settings=devstack_docker
```

2019-03-12 17:03 UTC, singuliere commented
> Create the user and OAuth2 Credentials for the retirement worker:

Since the `retirement_service_worker` user already exists (created by `devstack/provision-retirement-user.sh`), it won't display the desired id/secret. I created another user instead. But maybe it is possible to retrieve the id/secret of the existing user somewhere?

2019-03-12 17:12 UTC, singuliere commented on playbooks/roles/user_retirement_pipeline/tasks/main.yml
> +    job: "{{retirement_service_home}}/retire_users.sh"
Using the following would allow to remove the lock logic inserted in the retire_users.sh script and guard for the unlikely case where the script hangs forever

```
job: "timeout 1800 flock --exclusive --close /edx/var/retirement_service/retirement.lock {{retirement_service_home}}/retire_users.sh"
```

2019-03-12 18:38 UTC, singuliere commented
To facilitate the steps involving id/secret, they can be hardcoded as follows (no need to create the user since it already exists (created by  `devstack/provision-retirement-user.sh`):

3. Create the user and OAuth2 Credentials for the retirement worker:
```
app_name=retirement
user_name=retirement_service_worker
client_secret=EN391NuSmhFFhAARzi3QGBVrrw8sinv6PE31zINfTrIrUYLuy1n43S3kn6k5Nr2tS8fog04psh0YX3Pp2c2seCLANeSIamPpCUMTPqwYY3y3ERh47LLYiftiUoC0WZmJ
client_id=EJlPWHzL9wMMWQwfI3MOlcwqVrVjQ24jfS5ZgSQk
./manage.py lms create_dot_application --settings=devstack_docker --client-secret=$client_secret --client-id=$client_id ${app_name} $user_name
```

4. Now, use the Ansible Role to set up the User Retirement Pipeline:
```
export PYTHONUNBUFFERED=1
source /edx/app/edx_ansible/venvs/edx_ansible/bin/activate
cd /edx/src/configuration/playbooks
ansible-playbook \
  -i localhost, \
  -c local run_role.yml \
  -e role=user_retirement_pipeline \
  -e configuration_version=master \
  -e edx_platform_version=master \
  -e edxapp_user=root \
  -e RETIREMENT_SERVICE_SETUP=true \
  -e RETIREMENT_SERVICE_COOL_OFF_DAYS=0 \
  -e RETIREMENT_SERVICE_ENABLE_CRON_JOB=true \
  -e RETIREMENT_SERVICE_USER_EMAIL=retirement_service_worker@example.com \
  -e RETIREMENT_SERVICE_USER_NAME=retirement_service_worker \
  -e RETIREMENT_SERVICE_OAUTH_CLIENT_ID=$client_id \
  -e RETIREMENT_SERVICE_OAUTH_CLIENT_SECRET=$client_secret
```

2019-03-12 20:07 UTC, singuliere commented
To verify the user was indeed removed

```
$ python /edx/app/edxapp/edx-platform/manage.py lms shell  --settings=devstack_docker <<EOF
from openedx.core.djangoapps.user_api.models import UserRetirementStatus
from student.models import User
User.objects.get(username='$user')
EOF
```
Must fail and exit 1

2019-03-20 01:42 UTC, jamestait approved these changes
:+1:

- [x] I tested this:
 * Checked out the `HEAD^` commit.
 * In the `edx_ansible` virtualenv, ran: ```ansible-playbook -i localhost, -c local run_role.yml -e role=oauth_client_setup -e configuration_version=master -e edx_platform_version=master -e edxapp_user=root -e RETIREMENT_SERVICE_SETUP=true -e RETIREMENT_SERVICE_USER_NAME=retirement_service_worker -e retirement_service_name="retirement_service_worker" -e RETIREMENT_SERVICE_OAUTH_CLIENT_ID=id -e RETIREMENT_SERVICE_OAUTH_CLIENT_SECRET=secret```
 * Observed the (expected) error message relating to `COMMON_BIN_DIR`.
 * Verified no `retirement_service_worker` user and no `retirement` OAuth application were present.
 * In the `edx_ansible` virtualenv, ran: ```ansible-playbook -i localhost, -c local run_role.yml -e role=oauth_client_setup -e configuration_version=master -e edx_platform_version=master -e edxapp_user=root -e RETIREMENT_SERVICE_SETUP=false -e RETIREMENT_SERVICE_USER_NAME=retirement_service_worker -e retirement_service_name="retirement_service_worker" -e RETIREMENT_SERVICE_OAUTH_CLIENT_ID=id -e RETIREMENT_SERVICE_OAUTH_CLIENT_SECRET=secret```
 * Observed the (expected, erroneous) error message relating to `COMMON_BIN_DIR`.
 * Verified no `retirement_service_worker` user and no `retirement` OAuth application were present.
 * In the `edx_ansible` virtualenv, ran: ```ansible-playbook -i localhost, -c local run_role.yml -e role=oauth_client_setup -e configuration_version=master -e edx_platform_version=master -e edxapp_user=root -e RETIREMENT_SERVICE_USER_NAME=retirement_service_worker -e retirement_service_name="retirement_service_worker" -e RETIREMENT_SERVICE_OAUTH_CLIENT_ID=id -e RETIREMENT_SERVICE_OAUTH_CLIENT_SECRET=secret```
 * Observed the (expected, erroneous) error message relating to `COMMON_BIN_DIR`.
 * Verified no `retirement_service_worker` user and no `retirement` OAuth application were present.
 * Checked out the `HEAD` commit.
 * In the `edx_ansible` virtualenv, ran: ```ansible-playbook -i localhost, -c local run_role.yml -e role=oauth_client_setup -e configuration_version=master -e edx_platform_version=master -e edxapp_user=root -e RETIREMENT_SERVICE_SETUP=true -e RETIREMENT_SERVICE_USER_NAME=retirement_service_worker -e retirement_service_name="retirement_service_worker" -e RETIREMENT_SERVICE_OAUTH_CLIENT_ID=id -e RETIREMENT_SERVICE_OAUTH_CLIENT_SECRET=secret```
 * Observed the (expected) error message relating to `COMMON_BIN_DIR`.
 * Verified no `retirement_service_worker` user and no `retirement` OAuth application were present.
 * In the `edx_ansible` virtualenv, ran: ```ansible-playbook -i localhost, -c local run_role.yml -e role=oauth_client_setup -e configuration_version=master -e edx_platform_version=master -e edxapp_user=root -e RETIREMENT_SERVICE_SETUP=false -e RETIREMENT_SERVICE_USER_NAME=retirement_service_worker -e retirement_service_name="retirement_service_worker" -e RETIREMENT_SERVICE_OAUTH_CLIENT_ID=id -e RETIREMENT_SERVICE_OAUTH_CLIENT_SECRET=secret```
 * Observed no error message was produced (no OAuth application was attempted).
 * Verified no `retirement_service_worker` user and no `retirement` OAuth application were present.
 * In the `edx_ansible` virtualenv, ran: ```ansible-playbook -i localhost, -c local run_role.yml -e role=oauth_client_setup -e configuration_version=master -e edx_platform_version=master -e edxapp_user=root -e RETIREMENT_SERVICE_USER_NAME=retirement_service_worker -e retirement_service_name="retirement_service_worker" -e RETIREMENT_SERVICE_OAUTH_CLIENT_ID=id -e RETIREMENT_SERVICE_OAUTH_CLIENT_SECRET=secret```
 * Observed no error message was produced (no OAuth application was attempted).
 * Verified no `retirement_service_worker` user and no `retirement` OAuth application were present.
- [x] I read through the code
- [ ] ~I checked for accessibility issues~
- [x] Includes documentation

2019-03-20 02:08 UTC, pilou- commented on playbooks/openedx_native.yml
> +      when: "{{RETIREMENT_SERVICE_SETUP|default(false)}}"
`RETIREMENT_SERVICE_SETUP` is defined as [`user_retirement_pipeline` role default variable](https://github.com/edx/configuration/blob/8ad74045e341574d592a4953b9706765eb3a96aa/playbooks/roles/user_retirement_pipeline/defaults/main.yml#L46), then `|default(false)` is extraneous and should be removed. 
```suggestion
      when: "{{RETIREMENT_SERVICE_SETUP}}"
```

2019-03-20 02:08 UTC, pilou- commented on playbooks/roles/edxapp/tasks/deploy.yml
> +  when: EDXAPP_RETIREMENT_SERVICE_SETUP
Since `EDXAPP_RETIREMENT_SERVICE_SETUP` is only used here, `EDXAPP_RETIREMENT_SERVICE_SETUP` variable could be removed and `RETIREMENT_SERVICE_SETUP | default(false)` be used instead.

2019-03-20 02:08 UTC, pilou- commented on playbooks/roles/edxapp/defaults/main.yml
> +EDXAPP_RETIREMENT_SERVICE_WORKER_USERNAME: "{{ RETIREMENT_SERVICE_USER_NAME | default('OVERRIDE THIS WITH A VALID LMS USERNAME') }}"
1. `RETIREMENT_SERVICE_USER_NAME` variable seems unnecessary, could not `EDXAPP_RETIREMENT_SERVICE_WORKER_USERNAME` be used directly when needed ?
2. `EDXAPP_RETIREMENT_SERVICE_WORKER_USERNAME` definition could be commented in order to trigger an error when variable is used but not defined.

2019-03-21 14:15 UTC, singuliere approved these changes

2019-03-25 19:47 UTC, giovannicimolin commented on playbooks/roles/edxapp/defaults/main.yml
> +EDXAPP_RETIREMENT_SERVICE_WORKER_USERNAME: "{{ RETIREMENT_SERVICE_USER_NAME | default('OVERRIDE THIS WITH A VALID LMS USERNAME') }}"
Yes! I'll change that and also leave the variable commented.

2019-03-25 19:56 UTC, giovannicimolin commented
@pilou- I've addressed your PR comments. This is ready for review again.

2019-04-09 17:44 UTC, giovannicimolin commented
@pilou- I've implemented the changes you asked, but now the CI fails. Can you take a look at the PR again?

2019-04-19 17:52 UTC, giovannicimolin commented
@natabene Can you schedule a new review for this? 
The changes requested by the reviewer made the CI checks fail, so this is good to be reviewed again.

2019-04-19 20:41 UTC, natabene commented
@edx/devops Can you give this a look? See previous comments.

2019-05-04 07:18 UTC, pilou- commented
@giovannicimolin 
1. in [`playbooks/roles/edxapp/defaults/main.yml`](https://github.com/edx/configuration/blob/5b0a3756f4730d3ab10d0f5dd09688e01cfe2dec/playbooks/roles/edxapp/defaults/main.yml#L1356): `RETIREMENT_SERVICE_WORKER_USERNAME` variable should be removed (this is the cause of the CI failure)
2. [`playbooks/roles/user_retirement_pipeline/README.rst`](https://github.com/edx/configuration/pull/5040/files#diff-94984ee743fcdf5d3ba7e8df1007a7d4R83) should mention `EDXAPP_RETIREMENT_SERVICE_WORKER_USERNAME` instead of `RETIREMENT_SERVICE_WORKER_USERNAME`

2019-05-09 20:46 UTC, giovannicimolin commented
@pilou- I've updated the PR with your feedback, but don't we need to set `RETIREMENT_SERVICE_WORKER_USERNAME` on `generic_env_config`?

2019-05-21 20:44 UTC, edx-webhook commented
Thanks for the pull request, @giovannicimolin! I've created [OSPR-3480](https://openedx.atlassian.net/browse/OSPR-3480) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

2019-05-21 22:32 UTC, pilou- commented
> I've updated the PR with your feedback, but don't we need to set `RETIREMENT_SERVICE_WORKER_USERNAME` on generic_env_config ?

1. My understanding: `user_retirement_pipeline` role doesn't use `EDXAPP_RETIREMENT_SERVICE_WORKER_USERNAME` at all. This variable is used by:
    * [edxapp role](https://github.com/edx/configuration/blob/22bb6cab0856f5ec9283c836f41058d458f9c7fe/playbooks/roles/edxapp/defaults/main.yml#L1629) in `SERVICE_WORKER_USERS`. This variable is only used in `deploy` tasks file of `edxapp` role.
    * by `oauth_client_setup` role which is used:
        * in `oauth_client_setup` playbook which [includes](https://github.com/edx/configuration/blob/22bb6cab0856f5ec9283c836f41058d458f9c7fe/playbooks/oauth_client_setup.yml#L7) default variables of `edxapp`
        * in `openedx_native` playbook which uses `edxapp` role too (then default variables of `edxapp` are available)
        * in `edx_continuous_integration` playbook which uses `edxapp` role too (then default variables of `edxapp` are available)

    Then should not all references of `EDXAPP_RETIREMENT_SERVICE_WORKER_USERNAME` be removed from `user_retirement_pipeline` role (because the role doesn't use this variable) ?

2. In order to follow style/conventions of the current code, should not a sane default of `EDXAPP_RETIREMENT_SERVICE_WORKER_USERNAME` be set [here](https://github.com/edx/configuration/blob/22bb6cab0856f5ec9283c836f41058d458f9c7fe/playbooks/roles/edxapp/defaults/main.yml#L889) (like other service workers) ?

2019-05-29 11:11 UTC, natabene commented
@edx/devops Can you give this a look?

2019-05-30 20:57 UTC, giovannicimolin commented
@pilou- I will address your comments on my next sprint. Thanks for the review :grin:

2019-06-03 14:56 UTC, natabene commented
@edx/edx-data-engineering-admin Could you give this a look?

2019-06-10 19:28 UTC, giovannicimolin commented
@pilou- I've addressed your review comments and renamed a few variables to match the same patterns as other roles. This is ready to review again.

2019-07-02 21:28 UTC, giovannicimolin commented
@pilou- I addressed the review comments, resolved conflicts and rebased on master.

2019-07-03 07:42 UTC, pilou- approved these changes

2019-07-12 13:33 UTC, giovannicimolin commented
@feanil Can you queue this for review?

2019-07-15 14:58 UTC, feanil commented
@giovannicimolin, @natabene will be taking over coordinating this again.

FYI @natabene

2019-07-17 17:24 UTC, natabene commented
@giovannicimolin I am queueing this for a review.

2019-07-17 18:00 UTC, natabene commented
@macdiesel Can you review this when you have a chance?

2019-07-17 19:46 UTC, bmedx commented
I've re-reviewed this and it seems ok to me, but there are significant pieces that I'd really like DevOps review on. @bderusha we've been trying to get DevOps eyes on this for a while, can you lend a hand?

2019-08-07 14:21 UTC, giovannicimolin commented
@bmedx Thanks for the review! :grin: 
@bderusha Friendly ping, can you take a look at this PR?
Any next steps needed for moving this forward? 

CC @natabene

2019-08-27 13:56 UTC, fredsmith commented
Hi, I'll be reviewing this PR this week.

2019-08-28 12:41 UTC, fredsmith requested changes
Looks great.  I want to make sure that this works without people needing to add a value to their overrides yaml.  I think all that will be required for that is to move the main SETUP switch out of your role and into common_vars.

2019-08-28 12:41 UTC, fredsmith commented on playbooks/openedx_native.yml
> +      when: RETIREMENT_SERVICE_SETUP
I think this should be prefixed with 'COMMON' and the default moved out of your role and into the common_vars role.  otherwise I think this will be undefined because ansible won't source the default out of your role until it includes the role.

2019-09-09 19:11 UTC, giovannicimolin commented on playbooks/openedx_native.yml
> +      when: RETIREMENT_SERVICE_SETUP
@fredsmith I moved the variable to `common_vars` and prefixed it with `COMMON_` on all instances.

This is ready for review again.

2019-09-09 19:11 UTC, giovannicimolin commented
@fredsmith Sorry for the delay. I addressed your review comments. Let me know if you have any concerns.

2019-09-19 20:44 UTC, giovannicimolin commented
@fredsmith Friendly ping. Did you had a chance take look at the changes?
Also I think that the configuration failed due to some flakiness, can you trigger the CI run again? I don't seem to have permissions to do it.

2019-10-17 19:01 UTC, fredsmith approved these changes
LGTM

2019-10-17 19:01 UTC, merged

2019-10-17 19:01 UTC, edx-webhook commented
@giovannicimolin 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/5040&entry.1484655318=https://github.com/giovannicimolin&entry.752974735=2019-03-05+18:06&entry.1917517419=2019-10-17+19:01&entry.2133058324=Yes) so we can improve your experience in the future.

2019-10-17 21:53 UTC, pomegranited commented
Thank you so much @fredsmith !