Adding timeout configuration for analytics api proxy.
openedx-unsupported/configuration pull request #5059
Opened 2019-03-19 21:46 UTC by mikedikan

DISCO-494

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

2019-03-20 18:54 UTC, feanil requested changes
One change otherwise looks good.

2019-03-20 18:54 UTC, feanil commented on playbooks/roles/analytics_api/meta/main.yml
> +	edx_django_service_nginx_read_timeout: 300
It looks like you're using a tab? Convert to using the correct number of spaces so that this passes tests.

2019-03-21 16:20 UTC, mikedikan commented on playbooks/roles/analytics_api/meta/main.yml
> +	edx_django_service_nginx_read_timeout: 300
sorry about that, forgot that when i'm in bash, i don't have my editor converting them to spaces...

2019-03-21 16:23 UTC, mikedikan commented
@feanil - ready for another look!

2019-03-21 18:51 UTC, feanil approved these changes

2019-03-21 18:55 UTC, merged