[Ginkgo] Fix issue with rubygems >= 3.0.0 by pinning it to 2.7.9
openedx-unsupported/configuration pull request #5079
Opened 2019-04-14 15:20 UTC by mostafahussein

As Ginkgo needs ruby version 1.9.3 we wont be able to use rubygems with version higher than 2.7.9 otherwise we will face a compatibility issue

It could be solved by using `-v` but i preferred to follow the same way in this PR #5012  to make it as some kind of a standard fix

2019-04-14 15:20 UTC, edx-webhook commented
Thanks for the pull request, @mostafahussein! I've created [OSPR-3310](https://openedx.atlassian.net/browse/OSPR-3310) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://open.edx.org/wp-content/uploads/2019/01/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

2019-04-16 14:46 UTC, natabene commented
@mostafahussein Thank you for the contribution! Once our legal team processes your signed agreement, we will be able to review your code. Please stay tuned for updates.

2019-04-17 16:53 UTC, natabene commented
@mostafahussein Thank you for joining the Open edX community! We have added your user to our records and can now review your code going forward.

2019-04-17 16:54 UTC, natabene commented
@edx/devops This is now ready for your review.

2019-04-18 18:03 UTC, bderusha requested changes

2019-04-18 18:03 UTC, bderusha commented on playbooks/roles/rbenv/tasks/main.yml
> +  shell: "gem update --system {{ rbenv_rubygems_version }}"
@mostafahussein for backward compatibility with versions of rubygems <= 1.5.1 can we specify the version using the  [old syntax](https://github.com/rubygems/rubygems/blob/master/UPGRADING.md#with-rubygems-151-and-lower) to be safe.

2019-04-18 20:42 UTC, mostafahussein commented on playbooks/roles/rbenv/tasks/main.yml
> +  shell: "gem update --system {{ rbenv_rubygems_version }}"
so you mean make it `"gem install rubygems-update -v {{ rbenv_rubygems_version }} && update_rubygems"` ? In fact I have made my installation like this but when I sent the PR I thought it would be better if I used the same way as the other PR. I will send a PR with the old syntax

2019-04-24 15:51 UTC, bderusha requested changes

2019-04-24 15:51 UTC, bderusha commented on playbooks/roles/rbenv/tasks/main.yml
> +  shell: "gem install rubygems-update -v {{ rbenv_rubygems_version }} && update_rubygems"
the `update_rubygems` should also contain the version

Example from the docs (note, the underscores)
```
update_rubygems _1.3.7_
```

2019-04-24 16:31 UTC, mostafahussein commented on playbooks/roles/rbenv/tasks/main.yml
> +  shell: "gem install rubygems-update -v {{ rbenv_rubygems_version }} && update_rubygems"
@bderusha is there anything else needs to be modified ?

2019-04-24 21:52 UTC, bderusha approved these changes
Looks good!  Thank you

2019-04-24 21:52 UTC, merged

2019-04-24 21:52 UTC, edx-webhook commented
@mostafahussein 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/5079&entry.1484655318=https://github.com/mostafahussein&entry.752974735=2019-04-14+15:20&entry.1917517419=2019-04-24+21:52&entry.2133058324=Yes) so we can improve your experience in the future.