Make hermes work for edxapp OPS-3945
openedx-unsupported/configuration pull request #5117
Opened 2019-05-07 20:56 UTC by jdmulloy

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

2019-05-07 20:56 UTC, jdmulloy commented
This does have a bug, it will reload all workers on an lms or cms change.

2019-05-08 19:07 UTC, coryleeio requested changes

2019-05-08 19:07 UTC, coryleeio commented on playbooks/edxapp.yml
> +       - "/bin/cp {{ hermes_download_dir }}/lms.yml {{ COMMON_CFG_DIR }}/cms.yml"
your coping lms.yml to cms.yml here

2019-05-08 19:09 UTC, coryleeio approved these changes

2019-05-09 22:30 UTC, merged