Upgrade go-agent to ubuntu 18.04 (OPS-3967)
openedx-unsupported/configuration pull request #5120
Opened 2019-05-10 10:41 UTC by nadeemshahzad

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

2019-05-10 11:16 UTC, nadeemshahzad commented
Removing python 3.6 compilation step from tools go agent build as Ubuntu 18.04 comes default with python 3.6.
```
docker run -it --rm tools-goagent:latest python3 --version
$ exec python3 --version
Python 3.6.7
```
I used this repo. https://launchpad.net/~ondrej/+archive/ubuntu/php to install PHP packages on marketing go agent  and minimum supported version I found here is 5.6, while current marketing go-agent container it is running with PHP 5.5.

2019-05-13 15:03 UTC, coryleeio commented on docker/build/go-agent-marketing/Dockerfile
> +RUN add-apt-repository -y ppa:ondrej/php && \
Is there any way to do this without adding a ppa?

Is this a trusted and somewhat 'standard' ppa?

2019-05-13 15:06 UTC, coryleeio commented on docker/build/go-agent/files/docker_install.sh
> +		DOWNLOAD_URL="https://mirror.azure.cn/docker-ce"
Is it possible that we could rewrite this to follow the standard docker installation process?
https://docs.docker.com/install/linux/docker-ce/ubuntu/

I'm not sure how out of date these mirrors are, and I think we might be doing ourselves a diservice by getting behind on security updates if they stop maintaining them. (I didn't look into who runs these or how up to date they are, so if you feel it is a trusted mirror or if I lack context feel free to push back)

2019-05-13 15:07 UTC, coryleeio requested changes

2019-05-13 15:07 UTC, coryleeio commented on docker/build/go-agent/files/docker_install.sh
> +		DOWNLOAD_URL="https://mirror.azure.cn/docker-ce"
The reason I ask is that this script is borne of an old docker installation process that I don't believe they are still doing, and I am wondering if we should just update it to use their standard PPA and install in the standard way so that we get security updates, especially if we are going ahead and making substantial changes to it anyway.

2019-05-14 11:16 UTC, nadeemshahzad commented
Thanks @coryleeio  I have updated PR to use standard PPA for docker installation and the repo. ( https://launchpad.net/~ondrej/+archive/ubuntu/php ) that I used to install PHP on marketing agent is not trusted. We can install default PHP version from system repository as we have drupal version 7.66 on acquia which is compatible to drush 8.x and php 5.4.5+ ( https://docs.drush.org/en/8.x/install/ ) .
```
 docker run -it --rm  go-agent-marketing php --version
$ exec php --version
PHP 7.2.17-0ubuntu0.18.04.1 (cli) (built: Apr 18 2019 14:12:38) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.17-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies

docker run -it --rm  go-agent-marketing drush --version
$ exec drush --version
 Drush Version   :  8.2.3 
 docker run -it --rm  go-agent-marketing drush status
$ exec drush status
 PHP configuration      :  /etc/php/7.2/cli/php.ini 
 PHP OS                 :  Linux                    
 Drush script           :  /usr/local/bin/drush     
 Drush version          :  8.2.3                    
 Drush temp directory   :  /tmp                     
 Drush configuration    :                           
 Drush alias files      :                      
```

2019-05-16 16:11 UTC, coryleeio approved these changes

2019-05-20 07:38 UTC, merged