Write Registrar worker configuration file
openedx-unsupported/configuration pull request #5128
Opened 2019-05-16 19:01 UTC by kdmccormick

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

2019-05-16 20:54 UTC, fredsmith commented on playbooks/roles/registrar/templates/edx/app/supervisor/conf.d.available/registrar-workers.conf.j2
> +{% for w in registrar_workers %}
unless you've written something like this (https://github.com/edx/configuration/blob/b195d878a64afb6afb85e6ab231a83ead3406443/playbooks/roles/edxapp/defaults/main.yml#L607) into the defaults, this isn't going to work.

you should probably scan below to see what parts of 'w' are relevant to your workers and add the defaults

2019-05-16 20:55 UTC, fredsmith commented on playbooks/roles/supervisor/files/pre_supervisor_checks.py
> +                    "journals": {'python': args.journals_python, 'env_file': args.journals_env, 'code_dir': args.journals_code_dir},
did spacing here change?

2019-05-16 20:56 UTC, fredsmith commented on playbooks/roles/registrar/templates/edx/app/supervisor/conf.d.available/registrar-workers.conf.j2
> +stopwaitsecs={{ w.stopwaitsecs | default(REGISTRAR_WORKER_DEFAULT_STOPWAITSECS) }}
make sure you add the default value for `REGISTRAR_WORKER_DEFAULT_STOPWAITSECS` to the registrar role.

2019-05-16 20:57 UTC, fredsmith requested changes
see review notes

2019-05-16 21:17 UTC, kdmccormick commented on playbooks/roles/supervisor/files/pre_supervisor_checks.py
> +                    "journals": {'python': args.journals_python, 'env_file': args.journals_env, 'code_dir': args.journals_code_dir},
Trailing whitespace, i think my editor chopped it off automatically. I'll put it back to reduce diff noise

2019-05-16 22:14 UTC, kdmccormick commented
Thanks @fredsmith . One question -- [this](https://github.com/edx/configuration/pull/5128/files#diff-9fbd95606ec576d3fc445df2718f94c8R4) line sets `BOTO_CONFIG="{{ registrar_app_dir }}/.boto)`. Will that work if `.boto` doesn't exist?

2019-05-20 14:48 UTC, kdmccormick commented
@fredsmith do you know what this build failure means?
```
TASK [nginx : Create NGINX server templates] ***********************************
changed: [127.0.0.1] => (item={u'lang': u'en', u'img': u'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Pendleton_Sinking_Ship.jpg/640px-Pendleton_Sinking_Ship.jpg', u'title': u'Rate limit exceeded', u'style_p': u'font-family: Georgia,Cambria,"Times New Roman",Times,serif; margin: auto; margin-bottom: 1em; font-weight: 200; line-height: 1.4em; font-size: 1.1em; max-width: 80%;', u'style_div': u'margin: auto; width: 800px; text-align: center; padding:20px 0px 0px 0px;', u'img_alt': u'', u'heading': u'Uh oh, we are having some server issues..', u'file': u'rate-limit.html', u'msg': u'If think you have encountered this message in error please let us know at <a href="mailto:technical@example.com">technical@example.com</a>', u'style_h1': u'font-family: "Helvetica Neue",Helvetica,Roboto,Arial,sans-serif; margin-bottom: .3em; font-size: 2.0em; line-height: 1.25em; text-rendering: optimizeLegibility; font-weight: bold; color: #000000;', u'style_p_h2': u'font-family: "Helvetica Neue",Helvetica,Roboto,Arial,sans-serif; margin-bottom: .3em; line-height: 1.25em; text-rendering: optimizeLegibility; font-weight: bold; font-size: 1.8em; color: #5b5e63;'})
```

2019-05-20 16:06 UTC, fredsmith approved these changes

2019-05-20 16:10 UTC, fredsmith commented
@kdmccormick the build failure is: https://travis-ci.com/edx/configuration/jobs/201519083#L3744 Not the nginx template line you commented with (somewhere, I can't find it)

2019-05-20 16:11 UTC, fredsmith commented
> Thanks @fredsmith . One question -- [this](https://github.com/edx/configuration/pull/5128/files#diff-9fbd95606ec576d3fc445df2718f94c8R4) line sets `BOTO_CONFIG="{{ registrar_app_dir }}/.boto)"`. Will that work if `.boto` doesn't exist?

It should, as long as the www-data user has write permission to the directory to create it.  I would follow the pattern used in other apps.

2019-05-21 15:24 UTC, kdmccormick commented on playbooks/roles/registrar/defaults/main.yml
> +REGISTRAR_NEWRELIC_WORKERS_APPNAME: registrar-workers
@fredsmith is this a reasonable value?

2019-05-22 13:10 UTC, fredsmith approved these changes

2019-05-22 13:10 UTC, fredsmith commented on playbooks/roles/registrar/defaults/main.yml
> +REGISTRAR_NEWRELIC_WORKERS_APPNAME: registrar-workers
yep

2019-05-22 13:10 UTC, merged