Add registrar to sandboxes.
openedx-unsupported/configuration pull request #5153
Opened 2019-05-24 18:53 UTC by iloveagent57

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

2019-05-31 17:36 UTC, iloveagent57 commented on playbooks/roles/registrar/defaults/main.yml
> +REGISTRAR_SECRET_KEY: 'YOUR SECRET KEY HERE'
Remove this from here, add it in the sandbox-internal repo.

2019-05-31 17:46 UTC, iloveagent57 commented on playbooks/edx_continuous_integration.yml
> -      - xserver
Also - remember to remove the xserver stuff from sandbox internal

2019-06-12 17:49 UTC, fredsmith commented on util/jenkins/ansible-provision.sh
> +registrar="true"
by commenting out the test above, and just hardcoding registrar=true, you can never not provision registrar.

2019-06-12 17:50 UTC, fredsmith requested changes
I'm not sure if you meant to put that test back in.  Otherwise, looks good.

2019-06-12 18:00 UTC, fredsmith approved these changes
LGTM :shipit:

2019-06-12 18:49 UTC, fredsmith approved these changes

2019-06-13 14:41 UTC, merged