WIP: Alert on primary keys
openedx-unsupported/configuration pull request #5156
Opened 2019-05-29 11:59 UTC by syed-awais-ali

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

2019-06-12 21:48 UTC, jdmulloy requested changes
I've made a few suggestions. Title says WIP. Is this still in progress or is it ready for final review? Can you provide some sample output?

2019-06-12 21:48 UTC, jdmulloy commented on util/jenkins/primary_keys/check_primary_keys.py
> +                if len(metric_data) > 0:
```suggestion
        if len(metric_data) > 0:
```
This should be run once after the for item loop.

2019-06-12 21:48 UTC, jdmulloy commented on util/jenkins/primary_keys/check_primary_keys.py
> +                    cloudwatch.put_metric_data(Namespace=namespace, MetricData=metric_data)
```suggestion
            cloudwatch.put_metric_data(Namespace=namespace, MetricData=metric_data)
```

2019-06-13 13:29 UTC, syed-awais-ali commented
Some screenshots attached for your convenience. We want to upload the data to cloudwatch when the job runs to retain the history and to take the diff of the last run and the current run in order to predict when the keys will get exhausted.

<img width="700" alt="Screen Shot 2019-06-13 at 6 25 28 PM" src="https://user-images.githubusercontent.com/13710941/59436508-2e0d8a80-8e09-11e9-8b81-3878aeea4a09.png">
<img width="493" alt="Screen Shot 2019-06-13 at 6 25 15 PM" src="https://user-images.githubusercontent.com/13710941/59436509-2e0d8a80-8e09-11e9-8af0-6a44b60796d0.png">
<img width="346" alt="Screen Shot 2019-06-13 at 6 25 01 PM" src="https://user-images.githubusercontent.com/13710941/59436510-2ea62100-8e09-11e9-977f-c15eff211625.png">

2019-06-13 22:03 UTC, jdmulloy requested changes

2019-06-13 22:03 UTC, jdmulloy commented on util/jenkins/primary_keys/check_primary_keys.py
> +    metric_name = 'check_primary_keys'
```suggestion
    metric_name = 'used_key_space'
```

2019-06-13 22:03 UTC, jdmulloy commented on util/jenkins/primary_keys/check_primary_keys.py
> +                    'Value': tables[6]  # percentage of the usage of primary keys
```suggestion
                    'Value': tables[6],  # percentage of the usage of primary keys
                    'Unit': 'Percent',
```

2019-06-13 22:03 UTC, jdmulloy commented on util/jenkins/primary_keys/check_primary_keys.py
> +            t.table_type = 'base table' and c.extra = 'auto_increment'
```suggestion
            t.table_type = 'base table' and c.extra like '%auto_increment%' 
```
Maybe use a fuzzy match here in case there are other options in extra.

2019-06-13 22:03 UTC, jdmulloy commented on util/jenkins/primary_keys/check_primary_keys.py
> +            # this query will return the tables with usage in percentage, result is limited to 10
Why is this limited to 10?

2019-06-13 22:03 UTC, jdmulloy commented on util/jenkins/primary_keys/check_primary_keys.py
> +            for tables in rds_result:
```suggestion
            for table in rds_result:
```
I believe each item is a single row representing a single table.

2019-06-13 22:03 UTC, jdmulloy commented on util/jenkins/primary_keys/check_primary_keys.py
> +                    'Value': tables[6]  # percentage of the usage of primary keys
```suggestion
                    'Value': table[6]  # percentage of the usage of primary keys
```

2019-06-13 22:03 UTC, jdmulloy commented on util/jenkins/primary_keys/check_primary_keys.py
> +                        "Value": tables[1]
```suggestion
                        "Value": table[1]
```

2019-06-13 22:03 UTC, jdmulloy commented on util/jenkins/primary_keys/check_primary_keys.py
> +            cursor.execute("""
I would suggest using this query instead
```
SELECT
    table_schema,
    table_name, 
    column_name,
    column_type,
    auto_increment,
    max_int,
    ROUND(auto_increment/max_int*100,2) AS used_pct
FROM
    (
     SELECT
        table_schema,
        table_name,
        column_name,
        column_type,
        auto_increment,
        pow
            (2,
                case data_type
                when 'tinyint' then 7
                when 'smallint' then 15
                when 'mediumint' then 23
                when 'int' then 31
                when 'bigint' then 63
                end
            +(column_type like '% unsigned'))-1
        as max_int
    FROM
        information_schema.tables t
        JOIN information_schema.columns c 
            USING (table_schema,table_name)
            WHERE t.table_schema not in ('mysql','information_schema','performance_schema')
            AND t.table_type = 'base table' 
            AND c.extra LIKE '%auto_increment%'
            AND t.auto_increment IS NOT NULL
    )
TMP ORDER BY used_pct desc
LIMIT 10;
```

I would have like to use a ```WHERE used_pct > 75``` clause, but that's not possible on calculated columns. Perhaps we should remove the limit and check in python if the value is over a certain threshold. Although that could wait for a second PR after we merge this as this query will get us enough things to put in cloudwatch.

2019-06-14 17:28 UTC, jdmulloy approved these changes

2019-06-14 17:28 UTC, jdmulloy commented on util/jenkins/primary_keys/check_primary_keys.py
> +    days_remaining_before_exhaustion = cosnumed_keys_percentage/(current_consumption -
It doesn't look like this get used anywhere, but it seems useful. Is there coming functionally to use this?

2019-06-19 12:52 UTC, merged