Update registrar default queue name
openedx-unsupported/configuration pull request #5172
Opened 2019-06-05 14:07 UTC by iloveagent57

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

2019-06-05 15:37 UTC, kdmccormick reviewed
https://github.com/edx/registrar/pull/122#issuecomment-499136499

2019-06-05 19:08 UTC, kdmccormick approved these changes
May want to beef up the changelog entry.

Otherwise :guitar:

2019-06-07 18:55 UTC, jdmulloy requested changes

2019-06-07 18:55 UTC, jdmulloy commented on CHANGELOG.md
> +- Role: registrar
Newest changelog entries should be on the top.

2019-06-07 19:03 UTC, jdmulloy approved these changes

2019-06-07 19:04 UTC, merged

2019-06-12 14:44 UTC, kdmccormick commented on CHANGELOG.md
> +- Role: registrar
@jdmulloy wait, really? I'd add a note to the Changelog indicating that's the case. I've been adding changes to the end of the file for months now.