Celery script cleanup
openedx-unsupported/configuration pull request #5197
Opened 2019-06-14 18:45 UTC by jdmulloy

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

2019-06-14 18:51 UTC, bderusha commented on util/jenkins/check_celery_progress/check_celery_progress.py
> +dev_test_mode = False
Should this be part of the command interface so you dont need to edit the script to toggle this on/off?

2019-06-14 20:08 UTC, jdmulloy commented on util/jenkins/check_celery_progress/check_celery_progress.py
> +dev_test_mode = False
Just tried to an I can't edit the global variable from the click command function ```check_queues()```. A flag would be nice, but this is better than editing it every time to change the return to pass.

2019-06-19 19:00 UTC, coryleeio requested changes
I would consider changing the default to NOT dev mode, OR not defaulting the function parameter and always explicitly specifying it.

2019-06-19 19:00 UTC, coryleeio commented on util/jenkins/check_celery_progress/check_celery_progress.py
> +def create_alert(opsgenie_api_key, environment, deploy, queue_name, threshold, info, dev_test_mode=True):
I probably wouldn't make this default to true, if you forget to pass in the arg it will not create the alert. It'd be better to get an alert that you didn't mean to create than to have it fail silently.

2019-06-19 19:00 UTC, coryleeio commented on util/jenkins/check_celery_progress/check_celery_progress.py
> +def close_alert(opsgenie_api_key, environment, deploy, queue_name, dev_test_mode=True):
default to false

2019-06-19 19:00 UTC, coryleeio commented on util/jenkins/check_celery_progress/check_celery_progress.py
> +        response = AlertApi().close_alert(identifier=alias, identifier_type='alias', body=CloseAlertRequest(source=""))
You did not pass in test_mode here, so it will default to true and not close the alert., this is is what made me think we should change the default to false.

2019-06-20 17:06 UTC, jdmulloy commented on util/jenkins/check_celery_progress/check_celery_progress.py
> +        response = AlertApi().close_alert(identifier=alias, identifier_type='alias', body=CloseAlertRequest(source=""))
@coryleeio This is not my close_alert function, it's the AlertApi's close_alert function from the opsgenie module. Their naming is a bit of a pain as it's very generic.

2019-06-20 17:22 UTC, coryleeio commented on util/jenkins/check_celery_progress/check_celery_progress.py
> +        response = AlertApi().close_alert(identifier=alias, identifier_type='alias', body=CloseAlertRequest(source=""))
Ah okay cool

2019-06-20 17:22 UTC, coryleeio approved these changes

2019-06-20 17:23 UTC, merged