update hermes precheck conditional
openedx-unsupported/configuration pull request #5214
Opened 2019-06-21 17:52 UTC by bderusha

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

2019-06-21 17:53 UTC, jdmulloy requested changes

2019-06-21 17:53 UTC, jdmulloy commented on playbooks/roles/hermes/tasks/main.yml
> +  when: ansible_kernel == "4.4.0-1079-aws"
This is going to change the next time the AMI is updated.

2019-06-21 19:19 UTC, bderusha commented
@jdmulloy ready for another pass

2019-06-21 19:44 UTC, coryleeio approved these changes

2019-06-24 21:29 UTC, jdmulloy commented
@bderusha I chatted with @coryleeio and we decided that a simple switch would be simpler and more reliable. See #5219

2019-06-24 21:29 UTC, closed without merging

2019-06-24 21:31 UTC, bderusha commented
:+1: