Add private key to hermes config (OPS-3836)
openedx-unsupported/configuration pull request #5234
Opened 2019-07-01 13:11 UTC by nadeemshahzad

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

2019-07-01 17:01 UTC, coryleeio commented on playbooks/roles/hermes/defaults/main.yml
> +hermes_private_key: "{{ hermes_app_dir }}/{{ hermes_service_name }}-private-key"
could you append file_path to this variable like the other one so that it is clear the distinction between the file path and the actual key contents?

2019-07-01 17:02 UTC, coryleeio commented on playbooks/roles/hermes/tasks/main.yml
> +  when: HERMES_USE_PRIVATE_KEY
You could key this off of HERMES_PRIVATE_KEY being null, then you dont have to remember to set two variables.
HERMES_PRIVATE_KEY
and 
HERMES_USE_PRIVATE_KEY

2019-07-01 17:05 UTC, coryleeio requested changes
see other comments

2019-07-02 11:20 UTC, nadeemshahzad commented on playbooks/roles/hermes/tasks/main.yml
> +  when: HERMES_USE_PRIVATE_KEY
Thanks @coryleeio , I have addressed your comments and updated PR.

2019-07-02 16:31 UTC, coryleeio approved these changes

2019-07-18 09:54 UTC, merged