Create ansible setup for Program Manager to be in sandbox build
openedx-unsupported/configuration pull request #5260
Opened 2019-07-09 14:25 UTC by schenedx

Configuration Pull Request
Add Program Manager MFE
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

2019-07-10 19:10 UTC, iloveagent57 reviewed
I have some questions about cruft, but if we really need a python virtualenv to install node, I guess that's fine.

2019-07-10 19:10 UTC, iloveagent57 commented on playbooks/roles/program_manager/defaults/main.yml
> +edx_django_service_use_python3: false
does this need to be here?

2019-07-10 19:10 UTC, iloveagent57 commented on playbooks/roles/program_manager/defaults/main.yml
> +  CREDENTIALS_API_BASE_URL: 'http://credentials-{{ COMMON_LMS_BASE_URL }}/api'
Is there a `CREDENTIALS_BASE_URL` we can use instead?  You probably want https:// in stage and prod, right?

2019-07-10 19:10 UTC, iloveagent57 commented on playbooks/roles/program_manager/defaults/main.yml
> +  FACEBOOK_URL: 'https://www.facebook.com'
do we need all of these?

2019-07-10 19:10 UTC, iloveagent57 commented on playbooks/roles/program_manager/tasks/main.yml
> +- name: build virtualenv with python2.7
why do we need this?

2019-07-10 19:10 UTC, iloveagent57 commented on playbooks/roles/program_manager/tasks/main.yml
> +- name: Pin pip to a specific version.
why do we need this?

2019-07-10 19:10 UTC, iloveagent57 commented on playbooks/roles/program_manager/defaults/main.yml
> +program_manager_venv_dir: '{{ program_manager_home }}/venvs/{{ program_manager_service_name }}'
we shouldn't need a python virtualenv for a node app, right?

2019-07-10 19:10 UTC, iloveagent57 commented on playbooks/roles/program_manager/tasks/main.yml
> +  command: pip install nodeenv
wait, we need a python virtualenv just to install node?  that seems counterintuitive

2019-07-10 20:54 UTC, schenedx commented on playbooks/roles/program_manager/defaults/main.yml
> +  FACEBOOK_URL: 'https://www.facebook.com'
These are for the MFE footers. Might as well specify them

2019-07-10 20:54 UTC, schenedx commented on playbooks/roles/program_manager/tasks/main.yml
> +- name: build virtualenv with python2.7
I actually don't know. I can test to remove and see if that make a difference

2019-07-10 20:55 UTC, schenedx commented on playbooks/roles/program_manager/defaults/main.yml
> +program_manager_venv_dir: '{{ program_manager_home }}/venvs/{{ program_manager_service_name }}'
I hope so. I can test to remove

2019-07-11 01:21 UTC, schenedx commented
So, we use `nodeenv` which is a python library to install the nodejs version we want.
If we don't use `nodeenv`, we would have to write ansible tasks to download the node version from internet and install nodejs by doing `apt-get install` command. I rather have `nodeenv` take care of that for me. Let me know if you disagree

2019-07-11 01:35 UTC, schenedx commented on playbooks/roles/program_manager/defaults/main.yml
> +  CREDENTIALS_API_BASE_URL: 'http://credentials-{{ COMMON_LMS_BASE_URL }}/api'
This is not used in Program-manager. I am removing it.

2019-07-11 01:36 UTC, schenedx commented on playbooks/roles/program_manager/defaults/main.yml
> +edx_django_service_use_python3: false
This is needed. Apparently, if I remove it, the error message is 
'''
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'not edx_django_service_use_python3' failed. The error was: error while evaluating conditional (not edx_django_service_use_python3): 'edx_django_service_use_python3' is undefined\n\nThe error appears to have been in '/edx/app/edx_ansible/edx_ansible/playbooks/roles/program_manager/tasks/main.yml': line 27, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: build virtualenv with python2.7\n  ^ here\n"}
'''

2019-07-11 14:00 UTC, iloveagent57 approved these changes

2019-07-11 14:00 UTC, iloveagent57 commented on playbooks/roles/program_manager/defaults/main.yml
> +  FACEBOOK_URL: 'https://www.facebook.com'
Can't the footer component specify these, then?  Things like facebook and twitter URLs are really, really unlikely to change and could basically be hard-coded there.  Not a blocker, but it'd be cool to see them removed from here in the near future.

2019-07-11 14:00 UTC, iloveagent57 commented on playbooks/roles/program_manager/defaults/main.yml
> +edx_django_service_use_python3: false
Alright, fair enough, but for the record, I think this is janky.

2019-07-11 18:42 UTC, fredsmith requested changes
no need to do all the python stuff just to get nodeenv, use the one in apt.

2019-07-11 18:42 UTC, fredsmith commented on playbooks/roles/program_manager/tasks/main.yml
> +- name: build virtualenv with python2.7
if you remove all these tasks, you can remove the unnecessary python variables above.

2019-07-11 18:42 UTC, fredsmith commented on playbooks/roles/program_manager/tasks/main.yml
> +  when: not edx_django_service_use_python3
this when: clause is why you're getting the error that @iloveagent57 says, and I agree, is janky

2019-07-11 18:42 UTC, fredsmith commented on playbooks/roles/program_manager/tasks/main.yml
> +  command: pip install nodeenv
nodeenv is in apt.  don't use pip.

2019-07-11 18:42 UTC, fredsmith commented on playbooks/roles/program_manager/tasks/main.yml
> +- name: Pin pip to a specific version.
you don't, kill it.

2019-07-11 18:42 UTC, fredsmith commented on playbooks/roles/program_manager/defaults/main.yml
> +  FACEBOOK_URL: 'https://www.facebook.com'
I agree, this seems unnecessary to pass into every program execution in the env.

2019-07-11 20:34 UTC, schenedx commented
@fredsmith The nodejs in apt-get, or dpkg is version 4.2.6. It's not the version 10.16.0 we want for this application. Can you tell me what you mean by `nodeenv is in apt`?

2019-07-11 20:40 UTC, fredsmith commented
> @fredsmith The nodejs in apt-get, or dpkg is version 4.2.6. It's not the version 10.16.0 we want for this application. Can you tell me what you mean by `nodeenv is in apt`?

I mean do this:

```
$ apt install nodeenv
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  libllvm7
Use 'sudo apt autoremove' to remove it.
The following NEW packages will be installed:
  nodeenv
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 18.1 kB of archives.
After this operation, 81.9 kB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu bionic/universe amd64 nodeenv all 0.13.4-1 [18.1 kB]
Fetched 18.1 kB in 0s (152 kB/s)   
Selecting previously unselected package nodeenv.
(Reading database ... 180118 files and directories currently installed.)
Preparing to unpack .../nodeenv_0.13.4-1_all.deb ...
Unpacking nodeenv (0.13.4-1) ...
Setting up nodeenv (0.13.4-1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...

$ nodeenv test --node=10.16.0 --prebuilt --force
 * Install node (10.16.0)... done.

$ . test/bin/activate 

$ node --version
v10.16.0
```

Use this module:  https://docs.ansible.com/ansible/latest/modules/apt_module.html to apt install the nodeenv package instead of installing pip and making a virtualenv and pip installing nodeenv just to install node

2019-07-12 13:34 UTC, schenedx commented
@fredsmith Make sense now. I'll try to update my PR shortly

2019-07-12 15:39 UTC, schenedx commented
@fredsmith Changes made. Could you review again?

2019-07-12 17:04 UTC, fredsmith reviewed
Looks good :shipit:

2019-07-12 17:28 UTC, fredsmith approved these changes

2019-07-12 17:45 UTC, merged