Move JWT signature stuff into individual roles, only do it for sandboxes
openedx-unsupported/configuration pull request #5308
Opened 2019-07-22 21:27 UTC by iloveagent57

Still iterating on https://openedx.atlassian.net/browse/EDUCATOR-4498
The problem I'm solving for now: running the `/edx/bin/update` script on a sandbox will blow away any existing config in `/edx/etc/[service].yml`, because that script doesn't call the `masters_sandbox.yml` playbook.  Rather than always running that playbook, I'd like to have this JWT signature-generation stuff only happen (for the LMS and registrar plays) when we're in the context of a registrar sandbox, i.e. when `REGISTRAR_SANDBOX_BUILD` is true.  So this PR basically splits out my previous additions to `masters_sandbox.yml` into edxapp's `deploy.yml` and registrar's `main.yml` tasks file, conditional on `REGISTRAR_SANDBOX_BUILD`.

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

2019-07-23 14:07 UTC, schenedx reviewed
I am fine with this general approach. And I am wondering if you can turn all that steps for setting up the jwt in LMS as its own role. Then you can use conditional role dependency on edxapp? See https://edunham.net/2015/09/10/ansible_conditional_role_dependencies.html

2019-07-23 17:16 UTC, schenedx approved these changes
👍 Nice work!

2019-07-23 18:01 UTC, kdmccormick commented on playbooks/roles/registrar/tasks/main.yml
> +  when: REGISTRAR_SANDBOX_BUILD
`{{ REGISTRAR_SANDBOX_BUILD }}`

2019-07-23 18:01 UTC, kdmccormick commented on playbooks/roles/edxapp/tasks/main.yml
> +  when: EDXAPP_SANDBOX_BUILD
`{{ EDXAPP_SANDBOX_BUILD }}` maybe?

2019-07-23 18:08 UTC, kdmccormick approved these changes
Nice :+1:  Approving with the recommendation that you build Docker images for both edxapp and registrar, and make sure that this role wasn't run on them (to ensure that your conditional logic worked correctly).

2019-07-23 18:42 UTC, iloveagent57 commented
Cool, built a new docker image, spun it up, looked in `/edx/etc/registrar.yml`, didn't have any JWT signature stuff inside the JWT_AUTH dictionary.  Ditto for edxapp/LMS.

2019-07-24 19:45 UTC, schenedx approved these changes
👍

2019-07-24 19:49 UTC, kdmccormick approved these changes
Nice.

2019-07-25 13:36 UTC, coryleeio commented on playbooks/roles/edxapp/tasks/service_variant_config.yml
> +    app_combined_config: '{{lms_env_config|combine(lms_auth_config)}}'
I'd prefer to keep this as lms_combined_config atm because there is also a cms_combined_config. 

We are deleting this in the next few weeks as well if it makes you feel better.

2019-07-25 13:36 UTC, coryleeio commented on playbooks/roles/edxapp/tasks/service_variant_config.yml
> +    app_combined_config: '{{lms_env_config|combine(lms_auth_config)}}'
(Unless there is another reason for the change that i'm not aware of
)

2019-07-25 13:38 UTC, coryleeio commented on playbooks/edxapp.yml
> +    CAN_GENERATE_NEW_JWT_SIGNATURE: True
This will run everywhere, not just for sandboxes - can we set it to true in internal instead of using the default value to roll it out?

2019-07-25 13:43 UTC, coryleeio commented on playbooks/roles/jwt_signature/tasks/main.yml
> +- name: read JWT signature settings
This is fine for sandboxes, but it will be blown away by remote config at the moment, is that okay?

Why can we not just generate one of these and set it in sandbox-internal / sandbox-secure?

2019-07-25 13:44 UTC, coryleeio commented on playbooks/roles/edxapp/tasks/service_variant_config.yml
> +    app_combined_config: '{{lms_env_config|combine(lms_auth_config)}}'
That deletion may cause problems for you doing this also, unclear.  We should probably talk a bit more about this

2019-07-29 13:49 UTC, coryleeio requested changes

2019-07-29 13:49 UTC, coryleeio commented on playbooks/roles/jwt_signature/defaults/main.yml
> +CAN_GENERATE_NEW_JWT_SIGNATURE: False
Update runs the edxapp play so i think this isn't true.  ATM it's going to occur every time you update - perhaps we just do it whenever the play is run?

2019-07-29 15:24 UTC, iloveagent57 commented on playbooks/roles/jwt_signature/defaults/main.yml
> +CAN_GENERATE_NEW_JWT_SIGNATURE: False
Continuing conversation from slack here: that command basically appends a new key id to the list of public key ids it will accept (and presumably does something with the private key to make sure any of those public keys will work), so I can't just replace the existing keys

2019-07-30 14:52 UTC, coryleeio commented on playbooks/roles/jwt_signature/defaults/main.yml
> +CAN_GENERATE_NEW_JWT_SIGNATURE: False
I mostly wanted the comment to be more clear, it doesn't just run once. Maybe just remove that part? It gets run whenever the edxapp play runs

2019-07-30 14:53 UTC, coryleeio approved these changes

2019-07-30 18:55 UTC, merged