Allow ssh access to users (OPS-4232)
openedx-unsupported/configuration pull request #5330
Opened 2019-08-05 07:21 UTC by nadeemshahzad

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

2019-08-05 14:47 UTC, coryleeio requested changes

2019-08-05 14:47 UTC, coryleeio commented on playbooks/roles/user/tasks/main.yml
> +- name: Allow user to login remotely
You have to add the Deny line as well or it doesn't work.

You need to deny *, then explicitly allow the people in the list after the deny

2019-08-05 16:23 UTC, nadeemshahzad commented on playbooks/roles/user/tasks/main.yml
> +- name: Allow user to login remotely
@coryleeio ```DenyUsers *``` will disallow login for all and not working here. ```AllowUsers``` will make sure that login is allowed only for user names provided in list and will deny all other users.

2019-08-07 15:49 UTC, coryleeio approved these changes

2019-08-07 15:49 UTC, coryleeio commented on playbooks/roles/user/tasks/main.yml
> +- name: Allow user to login remotely
You are correct, as per the documentation here:
https://www.freebsd.org/cgi/man.cgi?query=sshd_config&sektion=5

2019-08-07 15:54 UTC, coryleeio requested changes

2019-08-07 15:54 UTC, coryleeio commented on playbooks/roles/user/tasks/main.yml
> +
Can you derive USERS_ALLOWED_TO_SSH from the existing list so that we dont have to remember to add USERS_ALLOWED_TO_SSH when people update their version of configuration?

It should be possible like so:

`{{ ['x','y'] | map('extract', {'x': 42, 'y': 31}) | list }}
results in 
https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#extracting-values-from-containers`

2019-08-08 17:29 UTC, coryleeio commented on playbooks/roles/user/tasks/main.yml
> +
I think you can use the map method even with the ubuntu user if you add him and set github:false on him. Will that make it so that we can use the map method?

2019-08-09 09:45 UTC, nadeemshahzad commented on playbooks/roles/user/tasks/main.yml
> +
Thanks @coryleeio , I have updated PR to dervied users from existing vars and closed the internal PR also added ```AUTOMATED_USERS``` to list as we need these to run the management commands from jenkins.

2019-08-16 17:55 UTC, coryleeio approved these changes

2019-08-22 03:52 UTC, merged

2019-10-22 09:34 UTC, mahyard commented
After a native installation I lost access to my VM because of this line at the end of sshd_config:
```
AllowUsers automated_user #automated_users_allowed_to_ssh
```
It would make trouble for people in the future.
@nadeemshahzad @coryleeio