Include Greenhouse token in prospectus build (for careers page).
openedx-unsupported/configuration pull request #5331
Opened 2019-08-05 19:52 UTC by dianakhuang

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.

2019-08-05 21:45 UTC, coryleeio requested changes

2019-08-05 21:45 UTC, coryleeio commented on playbooks/roles/prospectus/templates/.env.environment.j2
>  NEW_RELIC_APP_ID={{ PROSPECTUS_NEW_RELIC_APP_ID }}
You will also need to set the values here:
https://github.com/edx/configuration/blob/master/playbooks/roles/prospectus/defaults/main.yml#L15-L17

2019-08-05 21:46 UTC, coryleeio commented on playbooks/roles/prospectus/templates/.env.environment.j2
>  NEW_RELIC_APP_ID={{ PROSPECTUS_NEW_RELIC_APP_ID }}
@dianakhuang  If you lastpass share me the key I will add it for you to secure

2019-08-06 12:16 UTC, dianakhuang commented on playbooks/roles/prospectus/templates/.env.environment.j2
>  NEW_RELIC_APP_ID={{ PROSPECTUS_NEW_RELIC_APP_ID }}
@AlasdairSwan can you get DevOps the API key?

2019-08-06 21:28 UTC, coryleeio requested changes

2019-08-06 21:28 UTC, coryleeio commented on playbooks/roles/prospectus/defaults/main.yml
> +GATSBY_GREENHOUSE_API_KEY: 'fake-key'
this should be PROSPECTUS_NEW_RELIC_APP_ID
not GATSBY_GREENHOUSE_API_KEY

2019-08-06 21:29 UTC, coryleeio commented
@AlasdairSwan @dianakhuang Same key for stage vs prod?

2019-08-07 12:23 UTC, AlasdairSwan commented
@coryleeio yes please.

2019-08-07 13:19 UTC, dianakhuang commented on playbooks/roles/prospectus/defaults/main.yml
> +GATSBY_GREENHOUSE_API_KEY: 'fake-key'
I believe I did screw this up, but I fixed it to be `GATSBY_GREENHOUSE_API_TOKEN` instead.

2019-08-07 15:23 UTC, coryleeio requested changes

2019-08-07 15:23 UTC, coryleeio commented on playbooks/roles/prospectus/defaults/main.yml
> +GATSBY_GREENHOUSE_API_TOKEN: 'fake-key'
```suggestion
PROSPECTUS_GREENHOUSE_API_TOKEN: 'fake-key'
```

2019-08-07 15:24 UTC, coryleeio commented on playbooks/roles/prospectus/defaults/main.yml
> +GATSBY_GREENHOUSE_API_TOKEN: 'fake-key'
This results in the same behavior and is consistent with the application specific values above it.

2019-08-07 15:25 UTC, coryleeio commented on playbooks/roles/prospectus/templates/.env.environment.j2
>  NEW_RELIC_APP_ID={{ PROSPECTUS_NEW_RELIC_APP_ID }}
I have the key

2019-08-07 15:27 UTC, dianakhuang commented on playbooks/roles/prospectus/defaults/main.yml
> +GATSBY_GREENHOUSE_API_TOKEN: 'fake-key'
Unfortunately, some of these values have to start with `GATSBY` for uh, gatsby-specific reasons. We can switch the key to `GATSBY_PROSPECTUS_GREENHOUSE_API_TOKEN` if absolutely necessary, but I'm not a big fan of making it that long.

2019-08-07 15:30 UTC, coryleeio approved these changes

2019-08-07 15:30 UTC, merged