Removed override variables for lms/cms
openedx-unsupported/configuration pull request #5431
Opened 2019-10-04 11:40 UTC by syedimranhassan

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

2019-10-07 13:41 UTC, coryleeio commented on playbooks/roles/edxapp/tasks/service_variant_config.yml
> +#- name: create application and auth config
You can remove this, no need to leave the commented code

2019-10-07 13:41 UTC, coryleeio commented on playbooks/roles/edxapp/tasks/service_variant_config.yml
> +#- name: combined lms auth env for yml
go ahead and remove

2019-10-07 13:42 UTC, coryleeio commented on playbooks/roles/edxapp/tasks/service_variant_config.yml
> +#- name: combined cms auth env for yml
remove - we have this in git history,  no reason to keep it

2019-10-07 13:59 UTC, coryleeio commented on playbooks/roles/edxapp/tasks/service_variant_config.yml
> -- name: create helper scripts for managing edxapp
I think we may need to leave these - I see references to them in the documentation and the presupervisor checks

2019-10-07 14:00 UTC, coryleeio approved these changes
I'm thumbing so you can keep moving forward as you have the right idea - I think you may need to review my last comment and undo the deletion of the migrate scripts though

2019-10-16 12:19 UTC, syedimranhassan commented on playbooks/roles/edxapp/tasks/service_variant_config.yml
> -- name: create helper scripts for managing edxapp
After adding this task test are failing with these errors
`"AnsibleUndefinedVariable: 'lms_auth_config' is undefined"`
`"AnsibleUndefinedVariable: 'cms_auth_config' is undefined"`
We had removed these variables in this PR.

2019-10-16 14:54 UTC, coryleeio approved these changes

2019-10-18 18:30 UTC, coryleeio requested changes
This looks good but we can't actually merge it until we get devstack off of the rendered ansible configuration.

I have created https://openedx.atlassian.net/browse/OPS-4397 to represent this.

2020-01-30 18:26 UTC, coryleeio approved these changes

2020-01-31 09:21 UTC, merged

2020-02-21 03:52 UTC, pomegranited commented
Hi @syedimranhassan CC @coryleeio This PR removes the default values for [`EDXAPP_MEMCACHE`](https://github.com/edx/configuration/commit/9920561bffe1f3a3922caeedfe6e6d6ba0017484#diff-9bffb77ca37dcc0aead699b822b29095L144) and [`EDXAPP_ELASTIC_SEARCH_CONFIG`](https://github.com/edx/configuration/commit/9920561bffe1f3a3922caeedfe6e6d6ba0017484#diff-9bffb77ca37dcc0aead699b822b29095L122-L125) and so breaks the playbooks that assume they are defined: [edx-stateless.yml](https://github.com/edx/configuration/blob/cf4d221d384ed396a3008c31487f385544ef08e7/playbooks/edx-stateless.yml) and [openedx_native.yml](https://github.com/edx/configuration/blob/70217a3ded0f623b6ad98218cde3ce46e956c8cc/playbooks/openedx_native.yml).

Could these playbooks please be fixed?

2020-02-21 03:57 UTC, syedimranhassan commented
Hi @pomegranited We are working on this fix. The PR is in progress. Hopefully, we will merge it by today.

2020-02-21 04:04 UTC, pomegranited commented
Awesome, thank you for getting on this so quickly, @syedimranhassan !

2020-02-21 19:54 UTC, bradenmacdonald commented
@syedimranhassan CC @coryleeio Just want to make sure you've seen my comment at https://github.com/edx/configuration/pull/5414#issuecomment-588398918 - we have some concerns about this approach, and I'm hoping you might have a solution in mind that I haven't thought of yet.