add tasks to replace host to sandbox dns name in app config files
openedx-unsupported/configuration pull request #5450
Opened 2019-10-21 12:57 UTC by nadeemshahzad

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

2019-10-23 14:01 UTC, coryleeio requested changes

2019-10-23 14:01 UTC, coryleeio commented on playbooks/roles/edx_service/tasks/main.yml
> +  when: edx_service_decrypt_config_enabled and COMMON_DEPLOY_HOSTNAME|length > 0
Can you add an explicit toggle to this and default it to false
I don't want someone to set COMMON_DEPLOY_HOSTNAME and have their yaml modified, especially given this is a hack for sandboxes.

Alternatively you could change 'COMMON_DEPLOY_HOSTNAME' to be more explicitly obvious that it will make changes to your yaml.  Maybe by appending 'OVERRIDE' or even 'HACK'.  I don't want people to think that this is a value they should set in production and to wind up having odd behaviour because they set it.

2019-10-28 07:28 UTC, nadeemshahzad commented on playbooks/roles/edx_service/tasks/main.yml
> +  when: edx_service_decrypt_config_enabled and COMMON_DEPLOY_HOSTNAME|length > 0
Used ```COMMON_SANDBOX_BUILD```  which is true in ansible provision script. https://github.com/edx/configuration/blob/270149c67cfc3a529c8c7ee81de25ad043cda082/util/jenkins/ansible-provision.sh#L223

2019-10-28 18:29 UTC, coryleeio approved these changes
Looks fine to me, I don't see you passing in COMMON_SANDBOX_BUILD though

2019-10-28 18:43 UTC, nadeemshahzad commented
@coryleeio it is already defined here in ansible-privsion script (https://github.com/edx/configuration/blob/e693ea8d6f98c0b1184d7de5f72d95de41d538d2/util/jenkins/ansible-provision.sh#L223 ) that we are using for to sandboxes .

2019-11-05 05:52 UTC, merged