WIP: Converted ansible version variables
openedx-unsupported/configuration pull request #5691
Opened 2020-03-10 13:14 UTC by syedimranhassan

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

2020-04-13 13:08 UTC, syedimranhassan commented
Converted these variables from lowercase to uppercase

- EDX_PLATFORM_VERSION
- FORUM_VERSION
- CONFIGURATION_VERSION
- CERTIFICATES_VERSION
- MONGO_VERSION
- FIREFOX_VERSION
- CASSANDRA_VERSION
- CERTS_VERSION
- CODEJAIL_PYTHON_VERSIONS
- PYTHON_VERSION
- COMMON_BOTO_VERSION
- COMMON_NODE_VERSION
- COMMON_PIP_VERSION
- CREDENTIALS_NODE_VERSION
- DATADOG_AGENT_VERSION
- DEMO_VERSION
- DISCOVERY_NODE_VERSION
- XSERVER_VERSION
- EDXAPP_NODE_VERSION
- EDXAPP_THEME_VERSION
- FORUM_RUBY_VERSION
- RBENV_RUBY_VERSION
- GITRELOAD_VERSION
- ORACLEJDK_VERSION
- HERMES_VERSION
- INSIGHTS_NODE_VERSION
- JENKINS_ADMIN_VERSION
- JENKINS_VERSION
- BUILD_JENKINS_VERSION
- JENKINS_COMMON_VERSION
- DE_JENKINS_VERSION
- IT_JENKINS_VERSION
- JENKINS_EDX_PLATFORM_VERSION
- JENKINS_NODE_VERSION
- JSCOVER_VERSION
- LEARNER_PORTAL_VERSION
- LEARNER_PORTAL_NODE_VERSION
- LOCALDEV_JSCOVER_VERSION
- MINOS_EDX_SERVER_TOOLS_VERSION
- PYMONGO_VERSION
- MONGO_VERSION_MAJOR_MINOR
- MONGO_VERSION_PATCH
- MONGO_CLIENT_VERSION
- NEO4J_VERSION
- OAUTH2_PROXY_VERSION
- PROGRAM_MANAGER_VERSION
- PROGRAM_MPROGRAM_MANAGER_NODE_VERSION
- PROSPECTUS_VERSION
- PROSPECTUS_NODE_VERSION
- RBENV_VERSION
- RBENV_BUNDLER_VERSION
- RBENV_RAKE_VERSION
- RBENV_RUBYGEMS_VERSION
- S3FS_VERSION
- SUPERVISOR_VERSION
- TEST_EDX_PLATFORM_VERSION
- JENKINS_TOOLS_VERSION
- XSERVER_GRADER_VERSION
- REGISTRAR_VERSION

2020-04-13 14:16 UTC, adzuci reviewed
@jdmulloy do you want to take a quick look at this as well?  The sandbox built successfully, but I'm not sure how to check if there are other things relying on the lowercase naming scheme.
https://openedx.atlassian.net/browse/DOS-456

2020-04-14 18:02 UTC, adzuci requested changes
@jdmulloy and @bderusha suggested we keep both upper and lowercase versions (with a temporary mapping) and post the change in discuss.edx.org to let people know we will eventually remove the lowercase version.

We could also follow the DEPR https://open-edx-proposals.readthedocs.io/en/latest/oep-0021-proc-deprecation.html process.

@syedimranhassan Do you think you could modify this PR so that it is less likely to break anything using the old variables and post to discuss?

2020-04-15 12:49 UTC, syedimranhassan commented
> @jdmulloy and @bderusha suggested we keep both upper and lowercase versions (with a temporary mapping) and post the change in discuss.edx.org to let people know we will eventually remove the lowercase version.
> 
> We could also follow the DEPR https://open-edx-proposals.readthedocs.io/en/latest/oep-0021-proc-deprecation.html process.
> 
> @syedimranhassan Do you think you could modify this PR so that it is less likely to break anything using the old variables and post to discuss?

Thanks @adzuci 
I'm a little bit confused about what I do next and what do you mean by "we keep both upper and lowercase versions".
Should we stop merging this PR for now and post a discussion? or what? Can you please explain it?
Thanks

2020-04-15 13:28 UTC, adzuci commented
Hey @syedimranhassan , I believe we can take the code in this PR and also add a backwards compatible assignment like:

```
firefox_version: {{ FIREFOX_VESION }}
```

for each of the 59 variable.

That way we can have a period of time where the lower case variables exist but are deprecated before we fully remove them

2020-04-22 13:22 UTC, bderusha commented
@adzuci @syedimranhassan  This looks good.  How are we going to track the follow-up deprecation comms & final removal?

2020-04-22 14:17 UTC, adzuci approved these changes
:shipit: I put a few comments which we can pull in now or later.

2020-04-22 14:17 UTC, adzuci commented on playbooks/roles/credentials/meta/main.yml
> +    edx_django_service_node_version: '{{ credentials_node_version }}'
Should we point this at `CREDENTIALS_NODE_VERSION` instead of `credentials_node_version`?

2020-04-22 14:17 UTC, adzuci commented on playbooks/roles/discovery/meta/main.yml
> +    edx_django_service_node_version: '{{ discovery_node_version }}'
Same here, since we want to deprecate the lowercase names, I think we'll want to use the uppercase ones where we can.

2020-04-23 13:10 UTC, syedimranhassan commented
@bderusha I think we should post the change in discuss.edx.org. And follow this document.
https://open-edx-proposals.readthedocs.io/en/latest/oep-0021-proc-deprecation.html

2020-05-04 12:49 UTC, antoviaque commented
What is the reason behind this change? The original reasoning was that upper case variable names where supported over the long term, ie variables that Open edX operators were able to change without risking backward incompatible changes between releases without a notice. Lower case variables, on the other side, were considered internal and could be changed at any time. Does this change mean that all variables get long term support?

2020-05-07 08:15 UTC, merged

2020-05-07 09:27 UTC, syedimranhassan commented
@antoviaque We have a mix of version variables. We want to have all version variables like configuration_version, edx_platform_version, and program_manager_version, etc in uppercase.

2020-05-07 19:49 UTC, antoviaque commented
@syedimranhassan OK - so does that mean that they all get long term support from now on? If so, that's great, but I want to make sure we agree on the meaning of it.

2020-05-08 21:30 UTC, bderusha commented
@antoviaque I don't think the implied split between lowercase unsupported / UPPERCASE LTS was known or intended when this change was proposed.   I will review the variables with that eye and respond back next week.  I think that for many of them we likely do want to support them, but let me review more closely.

2020-05-19 03:21 UTC, pomegranited commented
@bderusha CC @nedbat @toxinu Will this change be in Juniper?

2020-05-19 13:40 UTC, bderusha commented
@antoviaque @pomegranited We can begin to treat these variable as LTS and changes to them will go through the DEPR process.

I don't know if this change will be automatically pulled into Juniper (@nedbat do you know?), but if it would be helpful to have it we can add it.

2020-05-19 19:43 UTC, nedbat commented
We have not yet started the Juniper master branches, so all changes to master will be in Juniper.

2020-05-20 17:47 UTC, antoviaque commented
@bderusha Thank you for the reply, and for the clarity on this! :+1: