add minikube role and install argocd and apps in sandbox
openedx-unsupported/configuration pull request #5809
Opened 2020-06-04 09:38 UTC by nadeemshahzad

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

2020-06-05 12:53 UTC, adzuci approved these changes

2021-02-16 18:40 UTC, edx-abolger approved these changes
Hi @nadeemshahzad I appreciate this moving forward, but I also am not a technical expert in with Ansible, so I cannot meaningfully give you feedback on your PR at this time. I will happily give this a try as a role once it is merged.

2021-03-18 20:30 UTC, adzuci requested changes
I think we can point at an existing checkout of edx-internal.

2021-03-18 20:30 UTC, adzuci commented on util/jenkins/ansible-provision.sh
> +    kustomize build $WORKSPACE/edx-internal/argocd/clusters/development -o cluster.yaml
```suggestion
    kustomize build $WORKSPACE/configuration-internal/argocd/applications/argocd/development -o argocd.yaml
    kustomize build $WORKSPACE/configuration-internal/argocd/clusters/development -o cluster.yaml
```

2021-03-18 20:31 UTC, adzuci commented on util/jenkins/ansible-provision.sh
> +    kustomize build $WORKSPACE/edx-internal/argocd/clusters/development -o cluster.yaml
@coryleeio agrees.

2021-04-01 13:20 UTC, adzuci approved these changes
:shipit:

2021-04-01 13:20 UTC, adzuci commented on util/jenkins/ansible-provision.sh
> +if [[ -z $k8s_apps ]]; then
Does k8s_apps get passed in somewhere currently?

2021-04-01 13:20 UTC, adzuci commented on util/jenkins/ansible-provision.sh
> +if [[ -z $k8s_apps ]]; then
Ah, I see it used here: https://github.com/edx/configuration/pull/5809/files#diff-8d11aca30e575de97b7a4436a10ea0a5031ff0b8f52c7e0eebdb746d760467d9R10

2021-04-02 11:58 UTC, merged