test python 3.8 support for credentials
openedx-unsupported/configuration pull request #5833
Opened 2020-06-25 18:57 UTC by mraarif

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

2020-06-26 09:45 UTC, syedimranhassan requested changes

2020-06-26 09:45 UTC, syedimranhassan commented on playbooks/roles/credentials/meta/main.yml
> +    edx_django_service_use_python38: true
This variable needs to be defined in edx_django_service role defaults.
https://github.com/edx/configuration/blob/master/playbooks/roles/edx_django_service/defaults/main.yml

2020-06-26 09:45 UTC, syedimranhassan commented on playbooks/roles/edx_django_service/tasks/main.yml
> +  when: edx_django_service_use_python38 and not edx_django_service_enable_experimental_docker_shim
Update condition for py2.7 and py3 virtual environment to not install when this variable is set.
You can see a similar example in **build virtualenv with python2.7** task bellow.

2020-06-26 16:24 UTC, morenol commented on playbooks/roles/edx_django_service/tasks/main.yml
> +- name: build virtualenv with python3.8
I think that we can reuse the 

- name: build virtualenv with python3, task by defining something like 

`edx_django_service_python_version` and use that there, we can also use that instead of `edx_django_service_use_python38`

2020-06-26 16:26 UTC, morenol commented on playbooks/roles/edx_django_service/tasks/main.yml
> +  command: apt-add-repository -y ppa:deadsnakes/ppa | apt-get update && apt-get install -y python3.8-dev python3.8-distutils
I think that we should use here

 https://docs.ansible.com/ansible/latest/modules/apt_repository_module.html

And then we can install these packages using https://docs.ansible.com/ansible/latest/modules/apt_module.html just like in the install python3 tasks that is above

2020-06-29 07:52 UTC, mraarif commented on playbooks/roles/edx_django_service/tasks/main.yml
> +- name: build virtualenv with python3.8
currently, there are 3 different python versions we've to deal with, you're suggesting we check for the exact python version while building a virtualenv? (edx_django_service_python_version==3.8)

2020-06-29 17:01 UTC, morenol commented on playbooks/roles/edx_django_service/tasks/main.yml
> +- name: build virtualenv with python3.8
Is there a service that is still using python2.7? In that case I think that the change that you made is Ok, otherwise I think that we should remove the edx_django_service_use_python3 and instead use something like edx_django_service_python_version as you said.

2020-06-29 17:29 UTC, mraarif commented on playbooks/roles/edx_django_service/tasks/main.yml
> +- name: build virtualenv with python3.8
there are a few playbooks that have `edx_django_service_use_python3` set to `false` implying that they use python 2.7

2020-06-29 18:32 UTC, mraarif commented
I was able to successfully create a sandbox ([here](https://tools-edx-jenkins.edx.org/job/sandboxes/job/CreateSandbox/30575/)) using this branch.

2020-06-29 19:36 UTC, morenol approved these changes
This looks good to me, maybe we should check the ubuntu version used in order to decide if we need to add the ppa:deadsnakes/ppa repository. But since we are not working with focal fossa, I think that this is fine.

2020-06-30 09:52 UTC, nadeemshahzad approved these changes

2020-07-06 15:50 UTC, morenol commented
@mraarif I think that the changes made in playbooks/roles/edx_django_service/* can be made in a separate PR, and keep in this one only the change to the playbooks/roles/credentials/meta/main.yml

So we can merge that other PR quickly and we can reuse these changes for the other services, What do you think @awais786 ?

2020-07-06 16:06 UTC, mraarif commented
> @mraarif I think that the changes made in playbooks/roles/edx_django_service/* can be made in a separate PR, and keep in this one only the change to the playbooks/roles/credentials/meta/main.yml
> 
> So we can merge that other PR quickly and we can reuse these changes for the other services, What do you think @awais786 ?

@morenol I think none of the other services are deployed on python 3.8 yet, and as per @jmbowman team owning credentials should be on-board with this change first.

2020-07-06 16:13 UTC, morenol commented
> > @mraarif I think that the changes made in playbooks/roles/edx_django_service/* can be made in a separate PR, and keep in this one only the change to the playbooks/roles/credentials/meta/main.yml
> > 
> > So we can merge that other PR quickly and we can reuse these changes for the other services, What do you think @awais786 ?
> 
> @morenol I think none of the other services are deployed on python 3.8 yet, and as per @jmbowman team owning credentials should be on-board with this change first.


Yes, but I mean, in order to create a PR to change python3.8 for other service, let's say course discovery we would need to repeat the changes that you made in edx_django_service. I think that these changes themselves are OK and they would not affect any of the other services since python3.5 is still the default configuration

2020-07-14 13:33 UTC, jmbowman commented
@mraarif Are you planning to do any further refactoring of this PR, or go with it as is?

@edx/masters-devs Could one of you review this and start making any plans needed to roll out the upgrade?

2020-07-14 13:52 UTC, mraarif commented
@jmbowman as there aren't any services currently blocked because of python 3.8 (i.e these config changes), I think we should go ahead with this and see how credentials deployment goes

2020-07-20 14:20 UTC, morenol commented
Hi @edx/masters-devs, This is a kindly remainder for this PR. Do you have any updates?

2020-07-23 19:45 UTC, matthugs approved these changes
I think testing this change against staging would be a good next step.

Approving on behalf of @edx/masters-devs

2020-07-24 16:57 UTC, syedimranhassan approved these changes

2020-07-28 20:34 UTC, merged

2020-07-29 15:36 UTC, matthugs commented
deployed to production credentials 29 Jul 2020 at 11:35:05