updated the ecommerce config to deploy on python 3.8
openedx-unsupported/configuration pull request #5916
Opened 2020-08-06 16:59 UTC by mraarif

Configuration Pull Request
---
Relevant JIRA issue here: https://openedx.atlassian.net/browse/BOM-1958

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code-shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

2020-08-07 21:57 UTC, mraarif commented
I created. a sandbox here: https://tools-edx-jenkins.edx.org/job/sandboxes/job/CreateSandbox/31734/ using this branch and build seems successful

2020-08-07 22:00 UTC, mraarif commented
I've filed a JIRA issue here: https://openedx.atlassian.net/browse/DOS-1436 for the SRE team to review python 3.8 installation.

2020-08-07 22:01 UTC, mraarif commented
@jmbowman this should be ready for the owning team to review.

2020-08-10 04:29 UTC, syed-awais-ali requested changes
Once that is done I guess this is good to go.

2020-08-10 04:29 UTC, syed-awais-ali commented on playbooks/roles/ecommerce/defaults/main.yml
> +ECOMMERCE_USE_PYTHON38: True
Although Ansible is not truly case-sensitive, I would suggest using what has been used in the whole file and set it to `true` instead of `True`

2020-08-10 12:45 UTC, jmbowman commented
I created [REV-1289](https://openedx.atlassian.net/browse/REV-1289) for owning team review.

2020-08-10 12:59 UTC, syed-awais-ali approved these changes

2020-08-12 16:25 UTC, cpennington approved these changes

2020-08-13 14:18 UTC, merged