Add EDXAPP_MEDIA_URL to cms nginx configuration.
openedx-unsupported/configuration pull request #5990
Opened 2020-09-02 21:46 UTC by misilot

This allows for viewing of scorm media (or any files under /media) on the studio view without having to utilize the preview website.

Without this files under /media/* aren't available for viewing when building elements in studio. The lms site configuration already has this code.

Configuration Pull Request
---

Make sure that the following steps are done before merging:

    - [X] Add an entry to the CHANGELOG.

2020-09-02 21:47 UTC, edx-webhook commented
Thanks for the pull request, @misilot! I've created [OSPR-4939](https://openedx.atlassian.net/browse/OSPR-4939) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

Please let us know once your PR is ready for our review and all tests are green.

:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://open.edx.org/wp-content/uploads/2019/01/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

<!-- comment:no_cla -->


<!-- comment:external_pr -->

2020-09-03 20:50 UTC, misilot commented
Where do I indicate my institutional affiliation?

2020-09-04 02:45 UTC, natabene commented
@misilot Thank you for the contribution! When you have a chance, could you please send in a signed Contributor Agreement mentioned in the earlier comment? You only need to do this once and we can then review all your future code contributions. Thanks

2020-09-17 02:25 UTC, natabene commented
@misilot Thank you for joining the Open edX community! We have added your user to our records and can now review your code going forward.

2020-09-17 02:25 UTC, natabene commented
@fredsmith Can you review this when you have a chance?

2020-09-17 13:39 UTC, fredsmith requested changes

2020-09-17 13:39 UTC, fredsmith commented on playbooks/roles/nginx/templates/edx/app/nginx/sites-available/cms.j2
> +    expires {{ EDXAPP_PROFILE_IMAGE_MAX_AGE }}s;
is this location only serving profile images?  seems like we don't want to overload this variable.

2020-09-17 13:49 UTC, misilot commented on playbooks/roles/nginx/templates/edx/app/nginx/sites-available/cms.j2
> +    expires {{ EDXAPP_PROFILE_IMAGE_MAX_AGE }}s;
Not sure? I can remove line 138 from cms.j2? I believe that was in lms.j2 so I had just copied the EDXAPP_MEDIA_URL. I believe only 135-137 are relevant for accessing media such as videos uploaded via scorm that are stored under the edxapp media directory.

2020-09-18 16:03 UTC, fredsmith commented on playbooks/roles/nginx/templates/edx/app/nginx/sites-available/cms.j2
> +    expires {{ EDXAPP_PROFILE_IMAGE_MAX_AGE }}s;
yeah, just remove 138

2020-09-18 16:10 UTC, misilot commented on playbooks/roles/nginx/templates/edx/app/nginx/sites-available/cms.j2
> +    expires {{ EDXAPP_PROFILE_IMAGE_MAX_AGE }}s;
Done.

2020-09-18 16:49 UTC, fredsmith approved these changes

2020-09-18 16:49 UTC, merged

2020-09-18 16:49 UTC, edx-webhook commented
@misilot 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/5990&entry.1484655318=https://github.com/misilot&entry.752974735=2020-09-02+21:46&entry.1917517419=2020-09-18+16:49&entry.2133058324=Yes) so we can improve your experience in the future.

2020-09-18 17:19 UTC, misilot commented
Thank you @fredsmith. Is there any chance this could be back ported into
juniper?

On Fri, Sep 18, 2020, 11:49 AM edx-webhook <notifications@github.com> wrote:

> @misilot <https://github.com/misilot> 🎉 Your pull request was merged!
>
> Please take a moment to answer a two question survey
> <https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/5990&entry.1484655318=https://github.com/misilot&entry.752974735=2020-09-02+21:46&entry.1917517419=2020-09-18+16:49&entry.2133058324=Yes>
> so we can improve your experience in the future.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/edx/configuration/pull/5990#issuecomment-694973728>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AALBHSHINA4XC22CZMDSHULSGOFSXANCNFSM4QT2PNUA>
> .
>

2020-09-18 18:31 UTC, nedbat commented
I've cherry-picked this to Juniper in 787b628dd

2020-09-18 18:36 UTC, misilot commented
Thank you @nedbat!