Create a new ES7 variable for forums.
openedx-unsupported/configuration pull request #6069
Opened 2020-10-08 19:23 UTC by dianakhuang

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

2020-10-08 19:40 UTC, davidjoy requested changes

2020-10-08 19:40 UTC, davidjoy commented on playbooks/roles/forum/defaults/main.yml
> +  SEARCH_SERVER_ES7: "{{ FORUM_ELASTICSEARCH_URL_ES7 }}"
I think `SEARCH_SERVER` may need to be added to `devstack_forum_env` section as well, but with the `http://edx.devstack.elasticsearch7:9200/` URL instead.

2020-10-09 16:35 UTC, dianakhuang commented on playbooks/roles/forum/defaults/main.yml
> +  SEARCH_SERVER_ES7: "{{ FORUM_ELASTICSEARCH_URL_ES7 }}"
Thanks for catching that. Updated.

2020-10-13 19:58 UTC, robrap commented on playbooks/roles/forum/defaults/main.yml
> +FORUM_ELASTICSEARCH_URL_ES7: "http://localhost:9200"
@dianakhuang: Is there a reason we collapsed host/port/protocol to URL? Note that we don't have a test here to match the old ES: https://github.com/edx/configuration/blob/b314385f3e468d62c05f278507138ef8cbc2ff84/playbooks/roles/forum/defaults/main.yml#L106-L107  Maybe this should be `FORUM_ELASTICSEARCH_HOST_ES7` instead?

2020-10-13 20:05 UTC, dianakhuang commented on playbooks/roles/forum/defaults/main.yml
> +FORUM_ELASTICSEARCH_URL_ES7: "http://localhost:9200"
I thought it was unnecessarily complex to separate it out, but if we need to do that, we can do that.

2020-10-13 20:11 UTC, robrap commented on playbooks/roles/forum/defaults/main.yml
> +  - {service: "elasticsearch7", host: "{{ FORUM_ELASTICSEARCH_HOST_ES7 }}", port: "{{ FORUM_ELASTICSEARCH_PORT }}"}
@feanil: Does this service name need to match something, and could this cause an issue?

2020-10-13 20:31 UTC, feanil commented on playbooks/roles/forum/defaults/main.yml
> +  - {service: "elasticsearch7", host: "{{ FORUM_ELASTICSEARCH_HOST_ES7 }}", port: "{{ FORUM_ELASTICSEARCH_PORT }}"}
It's only used to test connectivity to that service, so it should be safe to add a second item.

https://github.com/edx/configuration/blob/master/playbooks/roles/forum/tasks/test.yml#L7

2020-10-13 20:53 UTC, robrap commented on playbooks/roles/forum/defaults/main.yml
> +  - {service: "elasticsearch7", host: "{{ FORUM_ELASTICSEARCH_HOST_ES7 }}", port: "{{ FORUM_ELASTICSEARCH_PORT }}"}
Great.  Thanks.

2020-10-13 20:56 UTC, robrap approved these changes
@dianakhuang: It probably makes sense for you to give a thumb on this comment, or for someone else to approve my change.  I will add comments to the other PRs to update to use `FORUM_ELASTICSEARCH_HOST_ES7`.

2020-10-13 23:05 UTC, dianakhuang commented
👍 from me on these changes

2020-10-14 14:55 UTC, robrap approved these changes

2020-10-14 14:57 UTC, davidjoy approved these changes

2020-10-14 14:58 UTC, merged