Pin forums to an earlier, pre-ES7 version until we get all our services using ES7.
openedx-unsupported/configuration pull request #6093
Opened 2020-10-26 19:07 UTC by dianakhuang

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

2020-10-27 16:07 UTC, nedbat commented on playbooks/roles/forum/defaults/main.yml
> +FORUM_VERSION: "609eef0fa2f4c69dba92ce2ef98c557b876e77b9"
When do we expect to get to ES7?

2020-10-27 19:12 UTC, nedbat commented on playbooks/roles/forum/defaults/main.yml
> +FORUM_VERSION: "609eef0fa2f4c69dba92ce2ef98c557b876e77b9"
Hmm, I tried this branch, and got the same failure, though I have to dig to see if ended up pinned properly.

2020-10-27 19:14 UTC, nedbat commented on playbooks/roles/forum/defaults/main.yml
> +FORUM_VERSION: "609eef0fa2f4c69dba92ce2ef98c557b876e77b9"
Oh: it didn't work because util/install/native.sh sets FORUM_VERSION to the release you are trying to install.  We need a different way to do this.

2020-10-27 19:15 UTC, nedbat requested changes

2020-10-27 19:15 UTC, nedbat commented on playbooks/roles/forum/defaults/main.yml
> +FORUM_VERSION: "609eef0fa2f4c69dba92ce2ef98c557b876e77b9"
@dianakhuang ^^

2020-10-28 17:25 UTC, dianakhuang commented on playbooks/roles/forum/defaults/main.yml
> +FORUM_VERSION: "609eef0fa2f4c69dba92ce2ef98c557b876e77b9"
Hmm, I was wondering about that. I thought that if you didn't pass in a release that it would try to install the defaults. What version are you trying to install? `master`?

2020-10-28 19:11 UTC, nedbat commented on playbooks/roles/forum/defaults/main.yml
> +FORUM_VERSION: "609eef0fa2f4c69dba92ce2ef98c557b876e77b9"
Right, it would, but I always make a branch using the release-tagging tools, and then install from the branch.   This gives a better approximation to a real community installation.

2020-11-03 14:31 UTC, mavidser commented
Hi @dianakhuang - checking if there's any existing timeline for merging this PR :)

2020-11-06 17:02 UTC, nedbat commented
@mavidser We're working on how to properly get the version of forums that will work for Koa.

2020-11-06 17:02 UTC, closed without merging

2020-11-21 14:51 UTC, mavidser commented
Hi @nedbat - checking if pinning the forum to pre-ES7 is still an option here (we can attempt a PR for this if that's still a valid solution) as the master branch [is still failing](https://groups.google.com/g/open-edx-btr-notifications/c/Qy68eTORzto) to provision correctly right now.

Though of course upgrading the repo to use ES7 would be much more cleaner, but I'm not sure what the timeline for that is. edx-platform seems to have ES7 support now (edx/edx-platform#25596), and going from the [devstack dependencies](https://github.com/edx/devstack/blob/33c792693d14188ba43673ffcdf2877e1259e725/docker-compose.yml#L201), only discovery remains on 1.5 - which did upgrade to use ES7 but reverted due to some issues (edx/course-discovery#2833)

2020-11-24 12:00 UTC, nedbat commented
@mavidser For the Koa branches, we are sticking with ES1.5, if that is what you are asking?  Master branches should be on ES7. /cc @dianakhuang

2020-11-24 12:32 UTC, mavidser commented
@nedbat - Ah. I was mainly exploring ways to get the master configuration working again (as provisioning the stack from master is failing right now - forum needs ES7, `configuration` sets up ES1.5).

> Master branches should be on ES7. 

I assume this means that we should wait while this repo gets updated to install ES7 instead? (as opposed to the pinning solution in this PR)

2020-11-24 18:50 UTC, nedbat commented
I think that is right: master will not install cleanly on one machine right now, because we are mid-stream with the ES upgrade.