[SE-3381] Allows adding new tinymce plugins through platform configuration
openedx-unsupported/configuration pull request #6179
Opened 2020-11-29 16:34 UTC by nizarmah

This makes it possible to install new tinymce plugins through the environment settings.

This PR is responsible for adding the tinymce plugins to the plugins directory and rebuilding the assets.

**JIRA tickets**: SE-3381, SE-3247, OSPR-

**Dependencies**:

- https://github.com/edx/edx-platform/pull/25324

**Sandbox URL**: TBD - sandbox is being provisioned.

**Testing instructions**:

1. Login to Studio using `staff@example.com`/`edx`
2. Create a new Unit with an HTML Text
3. Make sure that the *ADSK Link* shows in the toolbar
4. Create a link and make sure you can preview it, and see it on the LMS

**Reviewers**
- [ ] @pkulkark 
- [ ] @bradenmacdonald 
- [ ] edX reviewer[s] TBD

**Settings**
```yaml
EDXAPP_ENV_EXTRA:
  ADDITIONAL_NODE_ENV_VARS:
    TINYMCE_ADDITIONAL_PLUGINS:
      adsklink:
        linktypes:
        - download
        - offer
        filetypes:
        - PDF
        - zip
        - Video
        - Design
        orientations:
        - Vertical
        - Horizontal
        styles:
        - Primary
        - Normal
        - Secondary

TINYMCE_ADDITIONAL_PLUGINS:
- repo: https://gitlab.com/nizarmah/tinymce-adsk-plugin
  name: adsklink
  plugin_path: "/adsklink"

DEFAULT_CONFIGURATION_REPO_URL: "https://github.com/open-craft/configuration.git"
DEFAULT_CONFIGURATION_VERSION: "nizar/tinymce_plugins_role"
STABLE_EDX_PLATFORM_REPO_URL: "https://github.com/open-craft/edx-platform"
STABLE_EDX_PLATFORM_COMMIT: "nizar/tinymce_plugins_combined_dependencies_master"
```

---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

2020-11-29 16:34 UTC, edx-webhook commented
Thanks for the pull request, @nizarmah! I've created [OSPR-5263](https://openedx.atlassian.net/browse/OSPR-5263) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2020-12-01 15:32 UTC, natabene commented
@nizarmah Thank you for your contribution. Please let me know once it is ready for our review.

2020-12-11 08:16 UTC, pkulkark approved these changes
LGTM :+1: 

- [x] I tested this: verified the sandbox deployed using this config works as expected.
- [x] I read through the code

2020-12-17 02:46 UTC, natabene commented
@nizarmah Is this ready?

2020-12-17 14:55 UTC, nizarmah commented
@natabene yes, this is ready for edX's review 👍🏼

2020-12-18 09:17 UTC, pomegranited commented
@nedbat @feanil  Is this PR suitable for me to review as a core committer? CC @natabene @nizarmah

2020-12-20 22:49 UTC, natabene commented
Waiting for @feanil or @nedbat to confirm

2020-12-20 23:59 UTC, nizarmah commented
@natabene Small note: some further work is going to be required on this pull request, sorry about that. I'd like to do things slightly differently instead of the way they are currently done. But I understand that confirmation is needed first 👍🏼 

Also, small note @pomegranited: initially, I created a new role to install the tinymce plugins and minify the files. If it is preferred to revert to that approach instead of doing the changes to the `edxapp` role, please let me know 👍🏼

2020-12-21 00:32 UTC, pomegranited commented
@nizarmah 

> initially, I created a new role to install the tinymce plugins and minify the files

Since this repo is being deprecated and edX are moving towards having decentralised configuration, I don't think there's any value in pulling the tinymce stuff into a separate role. If it were to be reused for other apps, then yes, but that's not how the decentralised model works so far.

Let me know when this is ready for review?

2020-12-21 00:40 UTC, nizarmah commented
Ah alright, thanks for the clarification 👍🏼 

> Let me know when this is ready for review?

I will! Sorry for this delay. It's just that there seems to be some "leftover" files (after updating the assets with new content), and I'm trying to avoid that. 😃

2020-12-28 00:03 UTC, nizarmah reviewed
Alright, I made the necessary changes, and went over them as part of a self review.

@pomegranited this is ready for your review.

I added an explanation below as to why it wasn't earlier, if you're interested.

---

Previously, the role was being run at the end of the `openedx_native.yml` playbook. However, that would cause the generation of files that become no longer needed later on when updating the assets.

Initially, those bundles are formed without the new tinymce plugins, so once the new bundles are generated, the hashes don't match. This then results in two sets of hashes existing in `/edx/var/edxapp/staticfiles/*`.

In order to prevent that, this change needed to be moved to when the edx platform was being deployed, before the assets were generated, including the bundles, which was finally done (added example below).

```bash
> ls -ltr /edx/var/edxapp/staticfiles/studio/bundles/ | grep -i commons
-rw-r--r-- 1 edxapp edxapp 2016067 Dec 27 17:36 commons.js
-rw-r--r-- 1 edxapp edxapp 2018276 Dec 27 17:36 commons.980c3ba232132656bdfb.js
-rw-r--r-- 1 edxapp edxapp 2016067 Dec 27 17:37 commons.8ff662b5854a.js
-rw-r--r-- 1 edxapp edxapp 2018276 Dec 27 17:37 commons.980c3ba232132656bdfb.9de3aba3ef99.js
```

And now, I can safely say that I am happy with the changes myself and consider them ready for review 🙂 

Sorry about the long delay with the changes, I've had a lot on my plate lately._

2020-12-28 03:39 UTC, pomegranited requested changes
Thanks for the ping and for those updates @nizarmah !

I've requested some documentation, and have a few nits and a question about whether we can simplify this change at all.

Am deploying a sandbox with this PR for config but without any tinymce plugins configured to make sure it works in the default empty condition, so will let you know how that goes.

2020-12-28 03:39 UTC, pomegranited commented on playbooks/roles/tinymce_plugins/defaults/main.yml
> +edx_jake_package: "{{ edxapp_code_dir }}/vendor_extra/tinymce/JakePackage.zip"
Could you add `TINYMCE_ADDITIONAL_PLUGINS_LIST: []` to the defaults here?

2020-12-28 03:39 UTC, pomegranited commented on playbooks/roles/tinymce_plugins/defaults/main.yml
> +edx_jake_package: "{{ edxapp_code_dir }}/vendor_extra/tinymce/JakePackage.zip"
This new `tinymce_plugins` role also needs a README explaining briefly what it's used for, and an example of how to use it.

Then you can also add an entry to the [CHANGELOG.md](https://github.com/edx/configuration/blob/master/CHANGELOG.md).

2020-12-28 03:39 UTC, pomegranited commented on playbooks/roles/tinymce_plugins/tasks/rebuild_tinymce_files.yml
> +      shell: "npm install"
You can combine this and the previous removal of `node_modules` in one command: [npm ci](https://docs.npmjs.com/cli/v6/commands/npm-ci).

2020-12-28 03:39 UTC, pomegranited commented on playbooks/roles/tinymce_plugins/tasks/rebuild_tinymce_files.yml
> +        remote_src: True
I'm not clear why you need to [add this JakePackage.zip to edx-platform](https://github.com/edx/edx-platform/pull/25324).. why can't you use `npm` to install it, and then avoid unpacking here?

2020-12-28 03:39 UTC, pomegranited commented on playbooks/roles/tinymce_plugins/tasks/main.yml
> +    - TINYMCE_ADDITIONAL_PLUGINS_LIST is defined
If `TINYMCE_ADDITIONAL_PLUGINS_LIST: []` is defined in defaults, then you don't need this line ^.

2020-12-28 03:39 UTC, pomegranited commented on playbooks/roles/tinymce_plugins/tasks/main.yml
> +  include_tasks: rebuild_tinymce_files.yml
Can you add a `when` clause here as well, to avoid rebuilding the tinymce plugins if nothing was added?

```yaml
   when: TINYMCE_ADDITIONAL_PLUGINS_LIST|length > 0
```

2020-12-28 04:03 UTC, nizarmah commented on playbooks/roles/tinymce_plugins/tasks/rebuild_tinymce_files.yml
> +      shell: "npm install"
That's awesome! Thank you for linking that 😃 I have addressed this in [`53a8c87e4715997fed6355261c43d3b9f3d274f5`](https://github.com/edx/configuration/pull/6179/commits/53a8c87e4715997fed6355261c43d3b9f3d274f5)

2020-12-28 04:03 UTC, nizarmah commented on playbooks/roles/tinymce_plugins/tasks/main.yml
> +    - TINYMCE_ADDITIONAL_PLUGINS_LIST is defined
Yeap 👍🏼  Addressed in [`0b5b20f703821096181fc354ac50686f6566ea49`](https://github.com/edx/configuration/pull/6179/commits/0b5b20f703821096181fc354ac50686f6566ea49)

2020-12-28 04:05 UTC, nizarmah commented on playbooks/roles/tinymce_plugins/tasks/main.yml
> +  include_tasks: rebuild_tinymce_files.yml
Done 👍🏼 Addressed in [`0b5b20f703821096181fc354ac50686f6566ea49`](https://github.com/edx/configuration/pull/6179/commits/0b5b20f703821096181fc354ac50686f6566ea49)

Please note that I added it here specifically, and not in the `edxapp` role so that it isn't aware of the variables used by the `tinymce_plugins` role, even though there's some repetition now. (If necessary, I can make the `main.yml` a single include, and add the `when` clause once, so please let me know)

2020-12-28 04:35 UTC, nizarmah commented on playbooks/roles/tinymce_plugins/tasks/rebuild_tinymce_files.yml
> +        remote_src: True
I'm not trying to add the JakePackage.zip to the edx-platform, it already was present. I was trying to update the `Jakefile.js` that's present, which we actually need.

The only reason I did this is because I'm still trying to avoid "changing how something is done", but instead making the changes to the same approach that was taken, without changing it.

But you have a great point, instead of actually unpacking here, we can store the content of the JakePackage.zip where they should actually be, and just use `npm` to install everything we need.

I'm considering now closing https://github.com/edx/edx-platform/pull/25324, and addressing the changes in https://github.com/edx/edx-platform/pull/25695 instead.
Accordingly, I can include any extra documentation on how to install new TinyMCE plugins in `https://github.com/edx/edx-platform/blob/master/common/static/js/vendor/tinymce/`.

2020-12-28 05:05 UTC, nizarmah commented on playbooks/roles/tinymce_plugins/defaults/main.yml
> +edx_jake_package: "{{ edxapp_code_dir }}/vendor_extra/tinymce/JakePackage.zip"
I have added the variable to the defaults in [`0b5b20f`](https://github.com/edx/configuration/pull/6179/commits/0b5b20f703821096181fc354ac50686f6566ea49) 👍🏼 

I'll be addressing the changes regarding documentation soon 😃

2020-12-28 05:57 UTC, pomegranited commented on playbooks/roles/tinymce_plugins/tasks/rebuild_tinymce_files.yml
> +        remote_src: True
@nizarmah 

> I'm not trying to add the JakePackage.zip to the edx-platform, it already was present. I was trying to update the Jakefile.js that's present, which we actually need.

👍 ok, I understand now, thanks for clarifying! Also read this [previous commits](https://github.com/edx/edx-platform/commit/2a8529d37a9530c4764d4c661eb49b10017214aa), and it looks like you're following the right procedure.

> But you have a great point, instead of actually unpacking here, we can store the content of the JakePackage.zip where they should actually be, and just use npm to install everything we need.

And yep, you can install the zip file using `npm install /path/to/zipfile.zip` if you want.

> Accordingly, I can include any extra documentation on how to install new TinyMCE plugins in common/static/js/vendor/tinymce/.

Yes, worth adding a note in the [tinymce/BUILD_README.txt](https://github.com/edx/edx-platform/blob/master/common/static/js/vendor/tinymce/BUILD_README.txt) that links to the README you're adding here, since that's somewhere people are likely to look.

2020-12-28 06:00 UTC, pomegranited commented on playbooks/roles/tinymce_plugins/tasks/main.yml
> +  include_tasks: rebuild_tinymce_files.yml
> (If necessary, I can make the main.yml a single include, and add the when clause once, so please let me know)

Nope, I think this way is cleaner, even if there is a little repetition. Thanks!

2020-12-28 06:13 UTC, nizarmah commented on playbooks/roles/tinymce_plugins/tasks/rebuild_tinymce_files.yml
> +        remote_src: True
@pomegranited thanks for your quick reply! 

> And yep, you can install the zip file using npm install /path/to/zipfile.zip if you want.

My suggestion was to actually move the content of that zip to `common/static/js/vendor/tinymce/` and completely get rid of that zip file. 
Installation from the zip is similar to the current procedure taken; we'll still need to unarchive the zip file, because it contains the `Jakefile.js` which is used when running the `jake` command (and the `Jakefile.js` includes other files in that archive).

So here's my follow up question: What are your thoughts about removing the zip file, and moving the `Jakefile.js` and its contents to `common/static/js/vendor/tinymce/`, that way, everything needed already exists there, except the `npm_modules`? We'd no longer need to unarchive, but we'd just change directory and install the packages.

_Note: This might be a large change though, which might be better/clearer to do through in a follow-up pull request._

> Yes, worth adding a note in the tinymce/BUILD_README.txt that links to the README you're adding here, since that's somewhere people are likely to look.

Yes, that's the plan, which is why I haven't made the README changes here, since I'll be doing the changes on both Pull Requests almost at the same time, so that I can properly link them together.

2020-12-29 07:06 UTC, pomegranited commented on playbooks/roles/tinymce_plugins/tasks/rebuild_tinymce_files.yml
> +        remote_src: True
> So here's my follow up question: What are your thoughts about removing the zip file, and moving the `Jakefile.js` and its contents to `common/static/js/vendor/tinymce/`, that way, everything needed already exists there, except the npm_modules? 
> Note: This might be a large change though, which might be better/clearer to do through in a follow-up pull request.

Yes, this does make the changes larger, and for not much gain. So I think you're better off sticking with the approach you've taken.

But if you've got budget and time, you're welcome to ask edX if they want to do something about this zip file. I'd ask @doctoryes since she made [the most recent changes to the zip](https://github.com/edx/edx-platform/commit/2a8529d37a9530c4764d4c661eb49b10017214aa) (albeit in 2014).

2020-12-31 08:06 UTC, nizarmah commented on playbooks/roles/tinymce_plugins/README.rst
> +.. _guide on enabling the plugins through the edX platform: https://github.com/edx/edx-platform/blob/master/docs/guides/extensions/tinymce_plugins.rst
You can find [the guide here](https://github.com/edx/edx-platform/blob/e6803fab65f0e35badf21addb214c46819b5fc91/docs/guides/extensions/tinymce_plugins.rst), since it hasn't been merged yet.

2020-12-31 08:16 UTC, nizarmah commented on playbooks/roles/tinymce_plugins/defaults/main.yml
> +edx_jake_package: "{{ edxapp_code_dir }}/vendor_extra/tinymce/JakePackage.zip"
Addressed the documentation changes as part of [`d342a9a - Adds documentation on how to install custom tinymce plugins`](https://github.com/edx/configuration/pull/6179/commits/d342a9ab4db59ba25b30ebb4faa0f68f654f99d9) 👍🏼 

Addressed the changelog changes as part of [`d9888c0 - Adds changes to changelog markdown file`](https://github.com/edx/configuration/pull/6179/commits/d9888c038f8a99d6bcbb5b12707024dd4df677dd) 👍🏼

2020-12-31 08:19 UTC, nizarmah commented on playbooks/roles/tinymce_plugins/tasks/rebuild_tinymce_files.yml
> +        remote_src: True
> So I think you're better off sticking with the approach you've taken.

Sounds good 👍🏼 

> But if you've got budget and time, you're welcome to ask edX if they want to do something about this zip file. I'd ask @doctoryes since she made the most recent changes to the zip (albeit in 2014).

The changes have already been done in https://github.com/edx/edx-platform/pull/25324, and those changes are really important to merge, because without them, the changes from this branch do not work. cc @doctoryes 

So whatever gets both pull requests merged, I'll do 👍🏼

2020-12-31 08:23 UTC, nizarmah commented
@pomegranited hope you enjoyed your new year's eve! 🎊 
I have applied the changes that you requested 👍🏼 

It seems like the changelog is resulting in a conflict, even though I literally just updated it. That's a funny coincidence, I expected it to happen later, not that fast though 😅 
Anyway, I'll leave that update until you've approved my changes, since it's a slight change

I would like to stress again on the importance of merging https://github.com/edx/edx-platform/pull/25324 before merging this pull request. This pull request depends on the updated `JakePackage.zip`.

I know you won't be able to review the other pull request, but I just wanted to make sure this doesn't get merged before its dependency, that's all.

2021-01-04 05:51 UTC, pomegranited approved these changes
:+1: @nizarmah I'll keep an eye on https://github.com/edx/edx-platform/pull/25324 and merge this once that's merged.

- [x] I tested this by deploying two sandbox servers:
   * [testing without tinymce plugin](https://configpr6179.sandbox.opencraft.hosting/), which uses this branch, but does not override the default empty `TINYMCE_ADDITIONAL_PLUGINS_LIST: []`.
      This sandbox provisioned successfully, demonstrating that this change can be merged without causing deployment issues.
   * [testing with tinymce plugin](https://pr25695.sandbox.opencraft.hosting/) configures `TINYMCE_ADDITIONAL_PLUGINS_LIST` to add the [ADSK plugin](https://gitlab.com/nizarmah/tinymce-adsk-plugin).
      This plugin was installed successfully.
- [x] I read through the code
- [x] <strike>I checked for accessibility issues</strike> N/A
- [x] Includes documentation for the new role.
- [x] <strike>I made sure any change in configuration variables is reflected in the corresponding
    client's `configuration-secure` repository.</strike> N/A

2021-01-04 16:18 UTC, natabene commented
@nedbat Can @pomegranited review this as a core committer?

2021-01-04 19:41 UTC, nedbat commented
I'm fine with @pomegranited using her core committer powers on this pull request.  The GitHub discussion she references does not say that she needs @edx/devops approval.  Feanil said,

> You can ping @edx/devops for review to sanity check you but if you don't hear back from them within 2 business days, use your judgement and feel free to merge if you think it's the right decision based on what you know.

@pomegranited, use your judgment.

2021-01-05 02:35 UTC, pomegranited commented
Thanks for the confirmation @nedbat !
I think this PR is fine to merge, as it is a minimal change which allows the core functionality to be extended without adding code overhead. I also don't think it will complicate the deprecation effort for this repo.

2021-01-05 16:41 UTC, natabene commented
@pomegranited Please feel free to merge.

2021-01-06 00:47 UTC, pomegranited approved these changes

2021-01-06 00:50 UTC, pomegranited commented
Thanks @natabene ! For some reason, github isn't letting me merge, so maybe there's something going on with my permissions? It shows the following, can you help?

![review required](https://user-images.githubusercontent.com/7556571/103715631-10b69780-5011-11eb-8e0e-a6430482107e.png)

2021-01-06 01:25 UTC, natabene commented
@pomegranited Sorry, it was my fault! I will ask IT to add you to the org.

2021-01-06 02:02 UTC, natabene commented
@pomegranited Please accept invitation and you should be able to merge again.

2021-01-06 02:59 UTC, nizarmah commented
Please note that if this pull request is merged before https://github.com/edx/edx-platform/pull/25324 and if `TINYMCE_ADDITIONAL_PLUGINS_LIST` is used, the build will fail, because it relies on the `clean-js` Jake command that was added in that pull request. 😟

2021-01-08 04:19 UTC, pomegranited commented
@nizarmah  Could you fix the conflict in CHANGELOG.md and squash your comments? Since Braden's approved https://github.com/edx/edx-platform/pull/25324, I can merge this when that's done.

2021-01-08 04:27 UTC, nizarmah commented
@pomegranited I resolved the conflict with the CHANGELOG.md 😃 I think it's safe to merge this pull request now if you wish, since https://github.com/edx/edx-platform/pull/25324 is about to get merged 👍🏼 

Initially I was worried about https://github.com/edx/edx-platform/pull/25324 because there was no reviewer.

It won't be useful, until https://github.com/edx/edx-platform/pull/25695 is merged, but I'm resolving the final comments on that one too. So, things will get merged there soon too, hopefully 🤞🏼

2021-01-08 05:28 UTC, merged

2021-01-08 05:28 UTC, edx-webhook commented
@nizarmah 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/6179&entry.1484655318=https://github.com/nizarmah&entry.752974735=2020-11-29+16:34&entry.1917517419=2021-01-08+05:28&entry.2133058324=Yes) so we can improve your experience in the future.