Allow overriding any e-commerce settings
openedx-unsupported/configuration pull request #6300
Opened 2021-02-26 08:35 UTC by shimulch

This PR adds a new `ECOMMERCE_EXTRA_CONFIG_OVERRIDES` configuration, which allows overriding any e-commerce ``settings.py`` variable.

With this PR any e-commerce settings can be overriden. For example, if we want to override ``LANGUAGES`` -
```yml
ECOMMERCE_EXTRA_CONFIG_OVERRIDES:
    LANGUAGES:
    - - en
      - English
    - - ar
      - Arabic
```

**Dependencies**: None

**Merge deadline**: None

**Author notes and concerns**:
N/A

**Reviewers**
- [ ] @kaizoku 
- [ ] @giovannicimolin 
- [ ] edX reviewer[s] TBD

2021-02-26 08:35 UTC, edx-webhook commented
Thanks for the pull request, @shimulch! I've created [OSPR-5643](https://openedx.atlassian.net/browse/OSPR-5643) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2021-02-26 17:56 UTC, natabene commented
@shimulch Thank you for your contribution. Please let me know once it is ready for our review.

2021-03-05 09:22 UTC, kaizoku approved these changes
I have one small comment about variable naming, but otherwise this functions well and I approve :+1:.


- [✓] I tested this: (tested rendering templating using ansible with overrides)
- [✓] I read through the code
- [n/a] ~I checked for accessibility issues~
- [n/a] ~Includes documentation~

2021-03-05 09:22 UTC, kaizoku commented on playbooks/roles/ecommerce/defaults/main.yml
> +ECOMMERCE_EXTRA_CONFIG_OVERRIDES: {}
nit: Should this be `ECOMMERCE_ENV_EXTRA`? This would be more similar to the [naming used in the LMS](https://github.com/edx/configuration/blob/60cf221c977c440878d80b02bd1f615e6af1eb38/playbooks/roles/edxapp/defaults/main.yml#L438), though this naming is partially because there was a separation between `lms.env.json` and `lms.auth.json` for secrets, which may not make sense to keep using since these are all now contained in `lms.yml`.

2021-03-05 23:56 UTC, pomegranited requested changes
@shimulch Could you please add an entry to the [CHANGLOG.md](https://github.com/edx/configuration/blob/master/CHANGELOG.md) for this new variable?

But otherwise this change is good and ready to merge. In fact, it's rather more useful than https://github.com/edx/configuration/pull/5757, which we merged only recently, since your change would have made that one unnecessary :)

2021-03-05 23:56 UTC, pomegranited commented on playbooks/roles/ecommerce/defaults/main.yml
> +ECOMMERCE_EXTRA_CONFIG_OVERRIDES: {}
Since these overrides end up in the [`edx_django_service_config_overrides`](https://github.com/edx/configuration/blob/64de5028bbf9d88205bbc1bda52e3ad9d4650a9d/playbooks/roles/ecommerce/meta/main.yml#L21), I think the proposed name is appropriate, so no need to chang it.

2021-03-07 04:49 UTC, shimulch commented
@pomegranited, I've added an entry on `CHANGELOG.md`. Let me know if that works or I need to change anything else. :-)

2021-03-08 07:56 UTC, pomegranited approved these changes
:+1:  Thanks for updating the CHANGELOG @shimulch !

- [x] I tested this by checking the client instance that uses this change.
- [x] I read through the code.
- [x] <strike>I checked for accessibility issues</strike> N/A
- [x] Includes documentation
- [x] I made sure any change in configuration variables is reflected in the corresponding
    client's `configuration-secure` repository.

CC @edx/devops -- I think this change is good to merge. Will wait 2 business days [as per my core committer guidelines](https://github.com/edx/configuration/pull/5776#issuecomment-665125541) in case there's any objections. Thanks!

2021-03-10 22:42 UTC, merged

2021-03-10 22:42 UTC, edx-webhook commented
@shimulch 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/6300&entry.1484655318=https://github.com/shimulch&entry.752974735=2021-02-26+08:35&entry.1917517419=2021-03-10+22:42&entry.2133058324=Yes) so we can improve your experience in the future.