WIP -- ENT-4519:  Added playbook, role and docker file to setup/test tableau server.
openedx-unsupported/configuration pull request #6398
Opened 2021-05-07 12:50 UTC by saleem-latif

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

2021-05-10 17:45 UTC, moconnell1453 commented on docker/build/tableau/ansible_overrides.yml
> +TABLEAU_REGISTRATION_CONFIG_USER_EMAIL: "salee@edx.org"
address is missing an 'm'

2021-05-10 17:51 UTC, moconnell1453 commented on docker/build/tableau/ansible_overrides.yml
> +TABLEAU_ADMIN_USER: tableau
We've been using 'edx' and 'edx-admin' for the user names in prod. We should be consistent in usage.

2021-05-10 17:51 UTC, moconnell1453 commented on docker/build/tableau/ansible_overrides.yml
> +TABLEAU_SERVER_ADMIN_PASSWORD: "password"
These passwords will need to be read from Vault. We can't commit passwords to this repo.

2021-05-10 17:54 UTC, moconnell1453 commented on playbooks/roles/tableau/defaults/main.yml
> +TABLEAU_ADMIN_PASSWORD: 'tableau001-pass'
Passwords need to come from Vault.

2021-05-10 17:56 UTC, moconnell1453 commented on playbooks/roles/tableau/defaults/main.yml
> +tableau_server_deb_pkg: 'https://downloads.tableau.com/tssoftware/tableau-server-2020-4-1_amd64.deb'
This version is from January. version 2020-4-4 is the latest for this major version, but there is also 2021-1-1 available as well.

2021-05-10 17:58 UTC, moconnell1453 requested changes
I will check with SRE to determine how we can safely retrieve passwords from Vault. Also, can this be targeted at stage? I'd like to test there or in playground, so we don't interfere with the current server in prod.

2021-05-11 07:39 UTC, saleem-latif commented
@moconnell1453 Everything in caps is supposed to be overridden, I have only placed these values as placeholder/test values. I was thinking to use remote config to override these values. I will discuss with SRE to get documentation for doing that.

2021-05-11 12:13 UTC, moconnell1453 commented
Thanks, @saleem-latif. I've created an SRE ticket to track their collaboration with us on this issue. https://openedx.atlassian.net/servicedesk/customer/portal/15/DOS-2376?created=true

2021-05-21 09:58 UTC, saleem-latif commented on playbooks/roles/tableau/defaults/main.yml
> +tableau_server_deb_pkg: 'https://downloads.tableau.com/tssoftware/tableau-server-2020-4-1_amd64.deb'
@moconnell1453 I could not find the URL of the debian package for the release you mentioned, can you share the link?

2021-05-24 13:06 UTC, moconnell1453 commented on playbooks/roles/tableau/defaults/main.yml
> +tableau_server_deb_pkg: 'https://downloads.tableau.com/tssoftware/tableau-server-2020-4-1_amd64.deb'
Sure. I got these urls from this page: https://www.tableau.com/support/releases/server
Here are the latest releases (May 18th, 2021)
2021.1.2 - https://downloads.tableau.com/esdalt/2021.1.2/tableau-server-2021-1-2_amd64.deb
2020.4.5 - https://downloads.tableau.com/esdalt/2020.4.5/tableau-server-2020-4-5_amd64.deb

2021-05-25 11:18 UTC, saleem-latif commented
@moconnell1453 I have incorporated your feedback changes, please take another look. 
Regarding your feedback regarding passwords, username and password will be overridden via edx-internal PR.

2021-05-25 17:43 UTC, moconnell1453 commented on docker/build/tableau/ansible_overrides.yml
> +TABLEAU_SERVER_ADMIN_PASSWORD: "password"
Based on our discussions with SRE, you can send the credentials to either Adam or Nadeem through LastPass, and they will add them to edx-internal: https://openedx.atlassian.net/browse/PSRE-815

2021-05-25 17:44 UTC, moconnell1453 approved these changes

2021-05-26 05:46 UTC, merged