feat: Payment and Ecommerce MFEs support in Native Installation
openedx-unsupported/configuration pull request #6408
Opened 2021-05-17 14:16 UTC by cmltaWt0

Changes:
- add ecommerce configuration for mfe
- set CORS_ALLOW_CREDENTIALS to true
- update ecommerce site configuration, set ecommerce waffle flag
- set LMS SiteConfiguration
- add ORDER_HISTORY_MICROFRONTEND_URL
- add new COMMON_ENABLE_PAYMENT_MFE variable to be able to control payment mfe in ecommerce SiteConfiguration

This PR adds:
- payment and ecommerce mfes support

This PR doesn't add:
- full ecommerce service configuration for native installation

Related PR and ecommerce configuration details:
- https://github.com/edx/configuration/pull/6403
- https://github.com/openedx/build-test-release-wg/issues/30
- https://github.com/openedx/build-test-release-wg/issues/64
- https://github.com/openedx/build-test-release-wg/issues/65

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

2021-05-17 14:16 UTC, edx-webhook commented
Thanks for the pull request, @cmltaWt0! I've created [OSPR-5787](https://openedx.atlassian.net/browse/OSPR-5787) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2021-05-18 11:56 UTC, BbrSofiane commented
@pomegranited @nedbat Could you review & merge this? It would allow us to be ready for the first release candidate.

2021-05-19 21:31 UTC, nedbat commented on playbooks/roles/ecommerce/defaults/main.yml
> +      {{ " --enable-microfrontend-for-basket-page=true" if COMMON_ENABLE_PAYMENT_MFE else "" }}
It seems like COMMON_ENABLE_PAYMENT_MFE won't be defined unless openedx_native.yml is the playbook.  Is it OK to use it in a conditional like this if it's undefined?

2021-05-20 09:04 UTC, cmltaWt0 commented on playbooks/roles/ecommerce/defaults/main.yml
> +      {{ " --enable-microfrontend-for-basket-page=true" if COMMON_ENABLE_PAYMENT_MFE else "" }}
@nedbat Thanks! 
This variable is used by ecommerce role only so I'll add it to the `playbooks/roles/ecommerce/defaults/main.yml`

Thinking about default value - probably we can set It to `false` so it will be enable only for Native Installation.
What do you think?

2021-05-20 11:01 UTC, cmltaWt0 commented on playbooks/roles/ecommerce/defaults/main.yml
> +      {{ " --enable-microfrontend-for-basket-page=true" if COMMON_ENABLE_PAYMENT_MFE else "" }}
Fixed.

2021-05-21 00:16 UTC, pomegranited commented
Looks like you're on this @nedbat  -- do you need anything from me?

2021-05-21 00:33 UTC, nedbat commented
@pomegranited I would appreciate another pair of eyes, I haven't done anything with MFEs.

2021-05-21 06:22 UTC, pomegranited commented
@cmltaWt0 @nedbat  I'm provisioning a sandbox server to test this, and will get back to you next week.

2021-05-24 13:33 UTC, natabene commented
@cmltaWt0 Thank you for your contribution.

2021-05-25 02:39 UTC, pomegranited reviewed
Apologies for my delayed review here, it's taking me longer than expected to build and test this (see comments).

@cmltaWt0 If you have any suggestions, feel free to chime in :)

2021-05-25 02:39 UTC, pomegranited commented on playbooks/openedx_native.yml
> +      - site_id: 1
Best not to specify the site_id here. I'd rather this was left out entirely (the [default `site_id` is used if omitted](https://github.com/edx/configuration/blob/master/playbooks/roles/edxapp/tasks/site_configuration.yml#L24-L32)).

Or if you want to specify something, use the LMS domain instead, e.g.

```suggestion
      - domain: "{{ EDXAPP_LMS_SITE_NAME}}"
```

2021-05-25 02:39 UTC, pomegranited commented on playbooks/roles/mfe_deployer/defaults/main.yml
> +    public_path: "/ecommerce/"
Wow so.. This isn't a criticism of this PR, but:  I wasn't able to build `frontend-app-ecommerce` on my sandbox server, because 20GB of disk isn't enough space to store all the npm modules.

Trying again with a bigger VM.

2021-05-26 05:40 UTC, pomegranited commented on playbooks/roles/mfe_deployer/defaults/main.yml
> +    public_path: "/ecommerce/"
Hi @cmltaWt0 , I've built a sandbox, but am still unable to see the ecommerce frontend.

My extra settings include:

```yaml
MFE_BASE: apps.confpr6408.opencraft.hosting
MFE_DEPLOY_NGINX_PORT: 443
```

And so I was expecting these MFEs to be deployed here, but they're showing a 404:
* https://apps.confpr6408.opencraft.hosting/ecommerce/
* https://apps.confpr6408.opencraft.hosting/payment/

What other ansible variables should I be setting here?

2021-05-26 11:05 UTC, cmltaWt0 commented on playbooks/roles/mfe_deployer/defaults/main.yml
> +    public_path: "/ecommerce/"
Native installation is worked by default and tested on http and on the same domain name as LMS.

My first suggestion is that you nginx standalone config is not suitable for https.
Payment and ecommerce MFEs works exactly as Account MFE.
Could you try to open "{{ EDXAPP_LMS_BASE_SCHEME }}://{{ MFE_BASE }}/account"  in you case?
Does it work?

P.S. for native installation this PR follows the default way to configure nginx to use LMS domain name.

Internally in Raccoon Gang I used our customised deployment with the separate domain for mfes and HTTPS and it was an issue in server name in nginx stand alone config - it gives 404 for ALL mfes with `app.*` server name.
For this case I had to add the full domain name for the mfe application like this:
```
raccoon@lms-lilac-vanilla:~$ cat /edx/app/nginx/sites-available/mfes
#
# This file is created and updated by ansible, edit at your peril
#

server {
  server_name app-lilac-vanilla.raccoongang.com;
  listen 80;

  # If you are changing this be warned that it lives in multiple places
# there is a TLS redirect to same box, and a TLS redirect to externally terminated TLS
# version of this in nginx and in mfe role.

if ($host ~ "\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}") {
  	return 403;
}   rewrite ^ https://$host$request_uri? permanent;

}

server {
  server_name app-lilac-vanilla.raccoongang.com;
  listen 443 ssl;
  ssl_certificate /etc/ssl/certs/ssl-cert-snakeoil.pem;
  ssl_certificate_key /etc/ssl/private/ssl-cert-snakeoil.key;
  add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";


  location ~ ^/profile/?(.*)$  {
      root  /edx/app/profile/frontend-app-profile/dist/;
      try_files /$1 /profile/index.html;
 }


  location ~ ^/gradebook/?(.*)$  {
      root  /edx/app/gradebook/frontend-app-gradebook/dist/;
      try_files /$1 /gradebook/index.html;
 }


  location ~ ^/account/?(.*)$  {
      root  /edx/app/account/frontend-app-account/dist/;
      try_files /$1 /account/index.html;
 }


  location ~ ^/learning/?(.*)$  {
      root  /edx/app/learning/frontend-app-learning/dist/;
      try_files /$1 /learning/index.html;
 }


  location ~ ^/payment/?(.*)$  {
      root  /edx/app/payment/frontend-app-payment/dist/;
      try_files /$1 /payment/index.html;
 }


  location ~ ^/ecommerce/?(.*)$  {
      root  /edx/app/ecommerce/frontend-app-ecommerce/dist/;
      try_files /$1 /ecommerce/index.html;
 }

}
```

Hope it will help.

2021-05-26 11:07 UTC, cmltaWt0 commented on playbooks/roles/mfe_deployer/defaults/main.yml
> +    public_path: "/ecommerce/"
> Trying again with a bigger VM.

To avoid it you can set MFES var to any number of MFEs you want to test in your instance:

```
MFES:
  - name: ecommerce
    repo: frontend-app-ecommerce
    public_path: "/ecommerce/"
  - name: payment
    repo: frontend-app-payment
    public_path: "/payment/"
```

2021-05-26 17:50 UTC, natabene commented
@cmltaWt0  Could you please provide a user centric/business feature description  for this PR?

2021-05-26 18:21 UTC, adzuci reviewed
Thanks for giving such a thorough review @pomegranited !  I'm going to follow up with the edX SRE team about the 20gb issue and try to understand if any MFEs are larger than they need to be, but I wanted to comment here to say that I think it's great this is being added to the native install and that I feel that a review from the two of you is sufficient to merge it once you confirm you can get to the MFE as expected.

2021-05-31 10:17 UTC, pomegranited requested changes

2021-05-31 10:17 UTC, pomegranited commented on playbooks/roles/mfe_deployer/defaults/main.yml
> +    public_path: "/ecommerce/"
Thanks for sharing your nginx config @cmltaWt0 ! That helped me figure out what I misconfigured.

> server {
>    server_name app-lilac-vanilla.raccoongang.com;
>    listen 80;

I missed overriding `MFE_DEPLOY_COMMON_HOSTNAME` -- since it's [set in the `openedx_native.yml`](https://github.com/edx/configuration/blob/4e39bb954a1a00a6c81a7f8ddfb05e4c8a1b8e4c/playbooks/openedx_native.yml#L13) to `"{{ EDXAPP_LMS_BASE }}"`, my MFEs weren't being deployed to my `MFE_BASE`. 

(Also needed to deploy to port 80, since https is terminated at my load balancer but that's specific to OpenCraft's setup.)

I redeployed with these settings:

```yaml
MFE_BASE: "apps.{{ EDXAPP_LMS_BASE }}"
MFE_DEPLOY_NGINX_PORT: 80
MFE_DEPLOY_COMMON_HOSTNAME: "{{ MFE_BASE }}"
```

And now I can see the MFEs at the expected endpoints:

* https://apps.confpr6408.opencraft.hosting/payment/
* https://apps.confpr6408.opencraft.hosting/ecommerce/

Yay!

2021-05-31 10:17 UTC, pomegranited commented on playbooks/roles/mfe_deployer/defaults/main.yml
> +    public_path: "/ecommerce/"
> To avoid this you can set MFES var to any number of MFEs you want to test on your instance:

@cmltaWt0 Sure -- but if the default settings deploy all of these MFEs, then anyone who doesn't know better is going to have this big footprint.

For these two MFEs -- payment + ecommerce -- can we only install them if the ecommerce role is enabled? Otherwise, they're just going to take up space and slow down the deployments.

Something like this should work (I'm testing it now): https://github.com/open-craft/configuration/commit/ed77a2e6055ce1cbf46a0fac4940c484872f1c8e

What do you think? CC  @adzuci

2021-05-31 10:35 UTC, cmltaWt0 commented on playbooks/openedx_native.yml
> +      - site_id: 1
@pomegranited 
The common practice is to use `domain` for sure - we do it for all our projects too.
I just decided to use `site_id` due to hardcoded `example.com` domain.
Also think that it's better to use domain here.

2021-05-31 10:40 UTC, cmltaWt0 commented on playbooks/roles/mfe_deployer/defaults/main.yml
> +    public_path: "/ecommerce/"
@pomegranited
Totally agree. We discussed it internally too - it's convenient to have conditions here. 
My only concern is that ecommerce is enabled by default so for the default native installation it's not very critical due to the fact it will be installed anyway. But for customised installations it will be beneficial.

Another concern is that payment and ecommerce MFEs are not alone - gradebook MFE is also installed by default but never used right now.

2021-05-31 10:44 UTC, cmltaWt0 commented on playbooks/openedx_native.yml
> +      - site_id: 1
@pomegranited 
Let me check it better. Add far as I remember Site for any installation (w/ any EDXAPP_LMS_SITE_NAME) will have `example.com` domain so it won't work.

2021-05-31 10:55 UTC, cmltaWt0 commented on playbooks/roles/mfe_deployer/defaults/main.yml
> +    public_path: "/ecommerce/"
> Something like this should work (I'm testing it now): open-craft@ed77a2e
Great!
Let. me test it too. After testing you want me to cherry-pick it to the base branch or merge it via another PR?

2021-05-31 13:26 UTC, cmltaWt0 commented on playbooks/openedx_native.yml
> +      - site_id: 1
@pomegranited 

Deployed from a scratch:

```
ubuntu@ip-172-31-8-82:~$ cat config.yml                                                                                         │
EDXAPP_LMS_BASE: "lilac.rimikt.be"                                                                                              │
EDXAPP_CMS_BASE: "studio.lilac.rimikt.be" 
```

```
>>> from openedx.core.djangoapps.site_configuration.models import SiteConfiguration                                             │
>>> from django.conf import settings                                                                                            │
>>> settings.LMS_BASE                                                                                                           │
'lilac.rimikt.be'                                                                                                               │
>>> SiteConfiguration.objects.all()                                                                                             │
<QuerySet [<SiteConfiguration: example.com >]> 
```

So probably `domain` won't work for this case as far as I understand.

2021-05-31 17:37 UTC, cmltaWt0 commented on playbooks/roles/mfe_deployer/defaults/main.yml
> +    public_path: "/ecommerce/"
UPD3:
Tested with previous changes and it works fine.

https://github.com/raccoongang/configuration/commit/2967687faf12ac8ab2713f4be619613298eaba9f

So I'll update PR with `ENABLE_ORDER_HISTORY_MICROFRONTEND: "{{ SANDBOX_ENABLE_ECOMMERCE }}"`

What about `- domain: "example.com"` - is it good for us to use this hardcode instead of another one `- site_id: 1` ?

2021-06-01 05:57 UTC, pomegranited requested changes

2021-06-01 05:57 UTC, pomegranited commented on playbooks/openedx_native.yml
> +      - site_id: 1
Ach bummer, I remember that now about the default Site domain name :(

So would you be ok with omitting the `site_id` entirely here, since if there's no domain or site_id, then [the default `settings.SITE_ID` is used](https://github.com/edx/configuration/blob/master/playbooks/roles/edxapp/tasks/site_configuration.yml#L24-L27)?

2021-06-01 05:57 UTC, pomegranited commented on playbooks/roles/mfe_deployer/defaults/main.yml
> +    public_path: "/ecommerce/"
Awesome, glad that change worked with your configuration @cmltaWt0 , thank you for testing it!

It required one further change to work with mine (otherwise the nginx config isn't set up for the `MFES_ECOMMERCE`): https://github.com/edx/configuration/commit/09e952ab5eff6d4628047194728431768b9df7d3

> After testing you want me to cherry-pick it to the base branch or merge it via another PR?

Since it ended up being 2 changes, you're welcome to cherry-pick them and squash them together before pushing to this PR branch. I'm also not fussed about attribution -- so if you want to rewrite them in your own way, feel free :)

I'll just do one more round of testing once the full change set is on this branch, and approve + merge.

> So I'll update PR with ENABLE_ORDER_HISTORY_MICROFRONTEND: "{{ SANDBOX_ENABLE_ECOMMERCE }}"

👍  to this -- good approach!

> What about - domain: "example.com" - is it good for us to use this hardcode instead of another one - site_id: 1 ?

Commented [above](https://github.com/edx/configuration/pull/6408/files#r637769850) on this -- can we just omit both the `domain` and `site_id`?

2021-06-02 09:01 UTC, cmltaWt0 commented on playbooks/openedx_native.yml
> +      - site_id: 1
Yeap. Thanks for the suggestion. Will remove site_id and domain entirely to rely on default `settings.SITE_ID`.

2021-06-02 09:05 UTC, cmltaWt0 commented on playbooks/roles/mfe_deployer/defaults/main.yml
> +    public_path: "/ecommerce/"
Great! 

Going to add and test https://github.com/edx/configuration/commit/09e952ab5eff6d4628047194728431768b9df7d3 and update the PR with results today.

2021-06-02 16:30 UTC, cmltaWt0 commented on playbooks/roles/mfe_deployer/defaults/main.yml
> +    public_path: "/ecommerce/"
@pomegranited 

I've squashed https://github.com/edx/configuration/commit/09e952ab5eff6d4628047194728431768b9df7d3 to your previous commit preserving author (8e69f93d87fb0e4d21f4f58a229e4153dd775fd3) and tested it.

Removed `site_id` and `domain` - works great.

Nginx config generated properly:

```
#
# This file is created and updated by ansible, edit at your peril
#

server {
  server_name lilac.rimikt.be;
  listen 19010;



  location ~ ^/profile/?(.*)$  {
      root  /edx/app/profile/frontend-app-profile/dist/;
      try_files /$1 /profile/index.html;
 }


  location ~ ^/gradebook/?(.*)$  {
      root  /edx/app/gradebook/frontend-app-gradebook/dist/;
      try_files /$1 /gradebook/index.html;
 }


  location ~ ^/account/?(.*)$  {
      root  /edx/app/account/frontend-app-account/dist/;
      try_files /$1 /account/index.html;
 }


  location ~ ^/payment/?(.*)$  {
      root  /edx/app/payment/frontend-app-payment/dist/;
      try_files /$1 /payment/index.html;
 }


  location ~ ^/ecommerce/?(.*)$  {
      root  /edx/app/ecommerce/frontend-app-ecommerce/dist/;
      try_files /$1 /ecommerce/index.html;
 }


}
```

Will test from a scratch now.

2021-06-02 16:43 UTC, cmltaWt0 commented on playbooks/roles/mfe_deployer/defaults/main.yml
> +    public_path: "/ecommerce/"
Also rebased onto master

2021-06-03 04:58 UTC, pomegranited approved these changes
This is working perfectly now @cmltaWt0 !
Thank you for taking the time to contribute this change, and to set the precedent for a more nuanced approach to MFE deployments.

I'm approving this conditional on a couple of documentation updates. Please:
* Add an entry to [CHANGELOG](https://github.com/edx/configuration/blob/master/CHANGELOG.md) describing the new variables added: `ECOMMERCE_CSRF_TRUSTED_ORIGINS`, `ECOMMERCE_ENABLE_PAYMENT_MFE`, `MFE_DEPLOY_ECOMMERCE_MFES`, `MFES_ECOMMERCE`
* Update [mfe_deployer/README](https://github.com/edx/configuration/tree/master/playbooks/roles/mfe_deployer#configuration--deployment) to add info on how to use `MFE_DEPLOY_ECOMMERCE_MFES` and `MFES_ECOMMERCE`.
   For `MFES_ECOMMERCE`, it's enough to say that its structure matches `MFES`; no need to repeat the list of fields etc.

:+1:

- [x] I tested this on my Ocim sandbox with the following custom configuration:

   ```yaml
   MFE_BASE: "apps.{{ EDXAPP_LMS_BASE }}"
   MFE_DEPLOY_NGINX_PORT: 80
   MFE_DEPLOY_COMMON_HOSTNAME: "{{ MFE_BASE }}"
   ```
   
   This resulted in all the MFEs, including the new ecommerce ones, being deployed to my configured MFE subdomain:
   https://apps.confpr6408.opencraft.hosting/ecommerce/orders/
   https://apps.confpr6408.opencraft.hosting/payment/
   
   Also checked
   * the ecommerce site configuration was updated to enable the payment MFE, at the configured URL.
   * (after manually fixing the default Site URL to match the LMS site name instead of the default example.com): the LMS user menu shows Order History, pointing to the Order History MFE.
- [x] I read through the code
- [x] <strike>I checked for accessibility issues</strike>
- [ ] Includes documentation : requested above ^
- [x] Commit structure follows [OEP-0051](https://github.com/edx/open-edx-proposals/pull/189)

2021-06-04 11:07 UTC, cmltaWt0 commented
@natabene Oh sorry - miss your [comment](https://github.com/edx/configuration/pull/6408#issuecomment-848991746)

I will try not to postpone this description / documentation too much.

2021-06-04 11:07 UTC, edx-webhook commented
@cmltaWt0 Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/6408&entry.1484655318=https://github.com/cmltaWt0&entry.752974735=2021-05-17+14:16&entry.1917517419=2021-06-04+11:07&entry.2133058324=No) so we can improve your experience in the future.

2021-06-04 11:08 UTC, cmltaWt0 commented
@pomegranited 
> cmltaWt0 closed this now

Have no idea how is this happened - reopening...

2021-06-04 12:14 UTC, cmltaWt0 commented
@pomegranited 
Changelog and readme have been updated. Please review.

2021-06-08 01:56 UTC, pomegranited commented
Thank you for updating those docs @cmltaWt0. This is a great addition, thank you so much for contributing!
Merging now. CC @adzuci @natabene

2021-06-08 01:58 UTC, merged

2021-06-08 01:58 UTC, edx-webhook commented
@cmltaWt0 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/6408&entry.1484655318=https://github.com/cmltaWt0&entry.752974735=2021-05-17+14:16&entry.1917517419=2021-06-08+01:58&entry.2133058324=Yes) so we can improve your experience in the future.