[FAL-1792] fix: required jenkins package no longer supported
openedx-unsupported/configuration pull request #6422
Opened 2021-05-26 04:45 UTC by pomegranited

The Jenkins packages available from pkg.jenkins.io no longer support the command-line scripts run by `jenkins_analytics`.
Need to download the old Jenkins package from the mirror site instead.

**Testing instructions**

To do a full test, the `analytics-jenkins.yml` playbook needs to be run on a new VM.

However, this small change can be tested using curl:

```
export JENKINS_VERSION=1.651.3
curl -L http://mirrors.jenkins-ci.org/debian-stable/jenkins_${JENKINS_VERSION}_all.deb -o jenkins_${JENKINS_VERSION}_all.deb
```

**Author Notes & Concerns**

1. This fix should be pulled into Lilac.
2. This old version of Jenkins contains a number of security issues that were fixed in later versions.
   However, attempts to use later versions of Jenkins fail with errors, e.g. [jenkins_analytics: add credentials](https://github.com/edx/configuration/blob/open-release/koa.3/playbooks/roles/jenkins_analytics/tasks/main.yml#L133-L138):
   * `JENKINS_VERSION: '2.235.5'` or `'2.263.4'` :

      ```
      TASK [jenkins_analytics : execute command]    ****************************************************************************************************************
      fatal: [172.31.9.214]: FAILED! => {"changed": true, "cmd": " java -jar /tmp/jenkins-cli/ubuntu/jenkins_cli.jar -s http://localhost:8080  groovy /tmp/credentials/addCredentials.groovy", "delta": "0:00:01.437013", "end": "2021-05-24 06:18:49.108469", "msg": "non-zero return code", "rc": 5, "start": "2021-05-24 06:18:47.671456", "stderr": "\nERROR: This command is requesting the -remoting mode which is no longer supported. See https://jenkins.io/redirect/cli-command-requires-channel", "stderr_lines": ["", "ERROR: This command is requesting the -remoting mode which is no longer supported. See https://jenkins.io/redirect/cli-command-requires-channel"], "stdout": "", "stdout_lines": []}
      ```
   * `JENKINS_VERSION: '2.277.4'` :

      ```
      TASK [jenkins_analytics : execute command] ****************************************************************************************************************
      fatal: [172.31.9.214]: FAILED! => {"changed": true, "cmd": " java -jar /tmp/jenkins-cli/ubuntu/jenkins_cli.jar -s http://localhost:8080  groovy /tmp/credentials/addCredentials.groovy", "delta": "0:00:00.602915", "end": "2021-05-24 07:10:07.900148", "msg": "non-zero return code", "rc": 6, "start": "2021-05-24 07:10:07.297233", "stderr": "\nERROR: anonymous is missing the Overall/Read permission", "stderr_lines": ["", "ERROR: anonymous is missing the Overall/Read permission"], "stdout": "", "stdout_lines": []}
      ```

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [x] Are you adding any new default values that need to be overridden when this change goes live? No.
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [x] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  N/A
  - [x] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release? N/A

2021-05-26 04:45 UTC, edx-webhook commented
Thanks for the pull request, @pomegranited! I've created [OSPR-5807](https://openedx.atlassian.net/browse/OSPR-5807) to keep track of it in JIRA.

As a core committer in this repo, you can merge this once the pull request is approved per the [core committer reviewer requirements](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1529675973/Open+edX+Core+Committers#Reviews-and-Ownership) and according to the agreement with your edX Champion.



<!-- comment:welcome-core-committer -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2021-05-26 14:07 UTC, natabene commented
@pomegranited Thank you for the contribution. Please let me know if this is good to go.

2021-05-27 20:12 UTC, eLRuLL commented
@pomegranited thanks for the explanation. I am ok with this as without this fix, this playbook stops working, but for sure this is something we'll have to fix on future releases.

Approved on my part :+1:

2021-05-27 20:13 UTC, eLRuLL approved these changes

2021-05-28 01:31 UTC, pomegranited commented
@natabene This OSPR is ready for edX or ccore committer review. 

@adzuci @christopappas Since I authored this OSPR, is it still ok for me to merge it with just @eLRuLL 's approval? I can get another OpenCraft team member to have a look too, if you'd rather we had two 👍 's.

2021-05-28 15:37 UTC, natabene commented
@pomegranited According to [](https://openedx.atlassian.net/wiki/spaces/COMM/pages/2718564358/Core%2BCommitters%2BInitial%2BPhases%2Bfor%2BPilot%2BRollout), looks like we need someone else to review, either another Core Committer or an SRE team member. Let me see what we can do.

2021-05-28 18:49 UTC, jdmulloy requested changes
Looks good to me

2021-05-28 18:49 UTC, jdmulloy commented on playbooks/roles/jenkins_master/defaults/main.yml
> +jenkins_deb_url: "http://mirrors.jenkins-ci.org/debian-stable/jenkins_{{ JENKINS_VERSION }}_all.deb"
```suggestion
jenkins_deb_url: "https://archives.jenkins-ci.org/debian-stable/jenkins_{{ JENKINS_VERSION }}_all.deb"
```
It seems mirrors.jenkins-ci.org doesn't have a certificate in that name and we should keep using TLS. The old URL redirects to archices.jenins-ci.org so we should probably use that instead.

2021-05-31 02:28 UTC, pomegranited commented on playbooks/roles/jenkins_master/defaults/main.yml
> +jenkins_deb_url: "http://mirrors.jenkins-ci.org/debian-stable/jenkins_{{ JENKINS_VERSION }}_all.deb"
Oo thank you for that @jdmulloy !

2021-05-31 02:32 UTC, pomegranited commented
Thanks for your assistance here @jdmulloy  -- Can I merge this once you agree that your changes have been addressed?

2021-06-01 13:12 UTC, natabene commented
@pomegranited Yes, feel free to merge.

2021-06-02 03:11 UTC, pomegranited commented
Thank you @natabene  -- @jdmulloy , I can't merge until you approve (it's showing that you've requested changes). Are you ok with my latest changes?

2021-06-02 14:33 UTC, jdmulloy approved these changes

2021-06-02 14:34 UTC, jdmulloy commented
@pomegranited Sorry for the delay. This looks good to me now.

2021-06-02 23:43 UTC, merged

2021-06-02 23:43 UTC, edx-webhook commented
@pomegranited 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/6422&entry.1484655318=https://github.com/pomegranited&entry.752974735=2021-05-26+04:45&entry.1917517419=2021-06-02+23:43&entry.2133058324=Yes) so we can improve your experience in the future.

2021-06-02 23:43 UTC, edx-webhook commented
@nedbat, @feanil: thought you might like to know that pomegranited merged this pull request.

<!-- comment:champion_merge_ping -->

2021-06-02 23:44 UTC, pomegranited commented
Thank you for your help here @jdmulloy !

2021-06-02 23:45 UTC, pomegranited commented
@nedbat  Can you cherry-pick this into the koa and lilac release branches? (Or is there another process for that now?)