fix: run celerybeat only once and on one instance
openedx-unsupported/configuration pull request #6442
Opened 2021-06-09 20:24 UTC by gabor-boros

The current implementation of celerybeat usage works properly if and
only if one concurrent worker process runs per queue using the nested
beat process started by the `--beat` flag. In case the the celerybeat
process is running as a separate process not as part of the workers,
that partially solves the problem. Either in that case, if multiple
instances are running in a cluster, without proper process supervising
across instances will result in (at least) dumplicated scheduling,
meaning that the scheduler will cause more work for the workers and
results will be duplicated.

Taking the above into consideration, to solve this issue, this commit
introduces single-beat package that wraps the celerybeat process and
keeps track of the process that acquired the lock in redis. In case one
of the instances get killed or the locking process crashes, the lock
will be released and another instance or process will take over its place.

**Dependencies**: None

**Related PRs**:

* https://github.com/edx/configuration/pull/6407 (introduced the issue)
* https://github.com/edx/edx-platform/pull/27630 (allow the celerybeat scheduler configuration)

**Sandbox URL**: TBD - under provisioning

**Merge deadline**: ASAP

**Testing instructions**:

1. Proofread the configuration changes

**Author notes and concerns**:

N/A

**Reviewers**
- [ ] TBD
- [ ] edX reviewer[s] TBD

2021-06-09 20:24 UTC, edx-webhook commented
Thanks for the pull request, @gabor-boros! I've created [OSPR-5852](https://openedx.atlassian.net/browse/OSPR-5852) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

<!-- comment:end_of_wip -->




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IHRydWV9 -->

2021-06-10 14:53 UTC, natabene commented
@gabor-boros Thank you for your contribution. Please let me know once it is ready for our review.

2021-06-14 15:17 UTC, pkulkark approved these changes
LGTM :+1: 

- [x] I tested this: verified the changes here work as expected
- [x] I read through the code
- [ ] ~~I checked for accessibility~~ N/A
- [ ] ~~Includes documentation~~ N/A

2021-06-14 15:29 UTC, gabor-boros commented
@natabene Thank you for your patience, now it is ready for edX review.

2021-06-15 16:30 UTC, jdmulloy commented on playbooks/roles/edxapp/tasks/deploy.yml
> +- name: install single-beat to control celerybeat processes
If possible it would be better to use ansible's pip module instead of raw shell commands. See an example here: https://github.com/edx/configuration/blob/d59d8bc70c6a9396d6d40134bdb8a2ef4f4c1c40/playbooks/roles/edxapp/tasks/deploy.yml#L175-L186

2021-06-15 16:31 UTC, jdmulloy commented on playbooks/roles/edxapp/tasks/deploy.yml
> +    - "scheduler.sh"
```suggestion
    - "beat_scheduler.sh"
```
I'd prefer that we rename this so that it's more obvious what it is to someone who's not aware of or thinking about celery beat.

2021-06-15 16:33 UTC, jdmulloy requested changes

2021-06-15 16:33 UTC, jdmulloy commented on playbooks/roles/edxapp/tasks/deploy.yml
> +- name: install single-beat to control celerybeat processes
I'd prefer that we rename this so that it's more obvious what it is to someone who's not aware of or thinking about celery beat.

2021-06-15 16:33 UTC, jdmulloy commented on playbooks/roles/edxapp/tasks/deploy.yml
> +    - "scheduler.sh"
```suggestion
    - "beat_scheduler.sh"
```
I'd prefer that we rename this so that it's more obvious what it is to someone who's not aware of or thinking about celery beat.

2021-06-16 10:39 UTC, gabor-boros commented on playbooks/roles/edxapp/tasks/deploy.yml
> +- name: install single-beat to control celerybeat processes
@jdmulloy The task is renamed, though I don't think it is a lot better. Do you have any suggestions or would this naming be sufficient?

2021-06-16 10:40 UTC, gabor-boros commented
@jdmulloy Thank you for jumping on this and reviewing! 🚀

2021-06-17 17:25 UTC, jdmulloy commented on playbooks/roles/edxapp/tasks/deploy.yml
> +- name: install single-beat to control celerybeat processes
@gabor-boros Looks good now. Either things moved in the diff or I put this comment on the wrong line. It was mostly concerned with ```scheduler.sh``` which you renamed to ```beat_scheduler.sh```. I'm good with this now.

2021-06-17 17:25 UTC, jdmulloy approved these changes

2021-06-17 17:26 UTC, merged

2021-06-17 17:26 UTC, edx-webhook commented
@gabor-boros 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/6442&entry.1484655318=https://github.com/gabor-boros&entry.752974735=2021-06-09+20:24&entry.1917517419=2021-06-17+17:26&entry.2133058324=Yes) so we can improve your experience in the future.

2021-07-04 12:49 UTC, regisb commented
This PR is breaking the open-release/lilac.master branch, as discussed on Slack: https://openedx.slack.com/archives/C01AGTSB1LL/p1625329309139800?thread_ts=1625307781.139400&cid=C01AGTSB1LL

I believe that the following PR should be cherry-picked on top of open-release/lilac.master: https://github.com/edx/configuration/pull/6450/