[SE-4481] Add feature to sync edx services logs
openedx-unsupported/configuration pull request #6465
Opened 2021-07-01 10:39 UTC by pkulkark

This PR reintroduces the feature that was included in #6418 but had to be reverted via #6464, by putting it behind a boolean flag named COMMON_OBJECT_STORE_EDX_LOG_SYNC. The flag is disabled by default so as to not change the existing behaviour.

**JIRA Ticket:** [SE-4481](https://tasks.opencraft.com/browse/SE-4481)

**Sandbox URL:** TBD

**Testing Instructions:**

- Set the COMMON_OBJECT_STORE_EDX_LOG_SYNC to true and the required prefix for COMMON_OBJECT_STORE_EDX_LOG_SYNC_PREFIX.
- Launch new instance and verify that the edx-services logs are uploaded to the configured object storage when the logrotates.

2021-07-01 11:02 UTC, edx-webhook commented
Thanks for the pull request, @pkulkark! I've created [OSPR-5897](https://openedx.atlassian.net/browse/OSPR-5897) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2021-07-01 20:44 UTC, jdmulloy commented
@pkulkark This seems reasonable. I need to think it over to make sure and I will merge during my morning tomorrow so I can watch to make sure our termination process still works once it merges.

2021-07-07 14:48 UTC, jdmulloy requested changes

2021-07-07 14:48 UTC, jdmulloy commented on playbooks/roles/common/templates/etc/logrotate.d/hourly/edx_logrotate.j2
> +    {% if COMMON_OBJECT_STORE_EDX_LOG_SYNC -%}
Can you please move the if and endif out to contian "lastaction" and "endscript"? So that we aren't adding anything that isn't there right now if COMMON_OBJECT_STORE_EDX_LOG_SYNC is false.

2021-07-08 09:56 UTC, pkulkark commented on playbooks/roles/common/templates/etc/logrotate.d/hourly/edx_logrotate.j2
> +    {% if COMMON_OBJECT_STORE_EDX_LOG_SYNC -%}
Good idea @jdmulloy! I've moved it up.

2021-07-08 16:17 UTC, jdmulloy approved these changes

2021-07-08 17:29 UTC, merged

2021-07-08 17:29 UTC, edx-webhook commented
@pkulkark 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/6465&entry.1484655318=https://github.com/pkulkark&entry.752974735=2021-07-01+10:39&entry.1917517419=2021-07-08+17:29&entry.2133058324=Yes) so we can improve your experience in the future.