edX | PSRE-974 | Moving create_data_czar in 'configuration/util' from sysadmin repo
openedx-unsupported/configuration pull request #6516
Opened 2021-08-16 09:38 UTC by arbabkhalil

…min repo

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

2021-08-16 10:34 UTC, syed-awais-ali requested changes

2021-08-16 10:34 UTC, syed-awais-ali commented on util/create_data_czar/assign_czar_org_groups.py
> +for k,v in data['organizations'].items():
NIT: Can we change k,v to more elaborative names?

2021-08-16 10:34 UTC, syed-awais-ali commented on util/create_data_czar/assign_czar_org_groups.py
> +        for i in v['recipients']:
NIT: Similar thing here, can we change `i` to a more meaningful name?

2021-08-16 10:34 UTC, syed-awais-ali commented on util/create_data_czar/assign_czar_org_groups.py
> +        for i in v['recipients']:
NIT: same here

2021-08-16 10:34 UTC, syed-awais-ali commented on util/create_data_czar/assign_czar_org_groups.py
> +    print("Adding {user} to group {group}.".format(user=v['recipients'],group=k))
I know this has been moved from the other repo, but can we change the `.format` to `fstrings`

2021-08-16 10:34 UTC, syed-awais-ali commented on util/create_data_czar/assign_czar_org_groups.py
> +#!/usr/bin/env python
I don't think this is needed here, this can be removed

2021-08-16 10:34 UTC, syed-awais-ali commented on util/create_data_czar/create_org_data_czar_policy.py
> +#!/usr/bin/env python
I don't think this is needed here, this can be removed

2021-08-17 12:12 UTC, syed-awais-ali approved these changes
LGTM. 👍

2021-08-19 15:46 UTC, adzuci approved these changes
This looks good to me & thank you for cleaning up the code during this transition.

2021-08-27 07:54 UTC, merged