chore: Enable ORA Grading MFE for sandboxes
openedx-unsupported/configuration pull request #6641
Opened 2021-12-20 15:39 UTC by jnlapierre

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A SRE team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a SRE ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/spaces/SRE/pages/28967861/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

2021-12-20 22:19 UTC, matthugs requested changes

2021-12-20 22:19 UTC, matthugs commented on playbooks/edx_continuous_integration.yml
> +      MFE_NAME: ora_grading
You'll want the hyphens here: https://github.com/edx/configuration/blob/77a0b37aa6df562087ba6e2f298dad33f46132c4/playbooks/roles/mfe/defaults/main.yml

2021-12-20 22:19 UTC, matthugs commented on playbooks/edx_continuous_integration.yml
> +      MFE_NAME: ora_grading
and elsewhere where you refer to this role

2021-12-20 22:19 UTC, matthugs commented on playbooks/edx_continuous_integration.yml
> +    - role:mfe
```suggestion
    - role: mfe
```

2021-12-20 22:19 UTC, matthugs commented on playbooks/ora_grading.yml
> +    ORA-GRADING_SANDBOX_BUILD: False
missed a spot

2021-12-20 22:35 UTC, matthugs commented on playbooks/edx_continuous_integration.yml
> +    - role:mfe
this is the cause for 
```
yaml.scanner.ScannerError: mapping values are not allowed here
  in "./playbooks/edx_continuous_integration.yml", line 60, column 15
```
in https://github.com/edx/configuration/runs/4588077725?check_suite_focus=true

2021-12-22 20:42 UTC, matthugs commented on playbooks/edx_continuous_integration.yml
> +      MFE_NAME: ora_grading
revisiting https://openedx.atlassian.net/wiki/spaces/FEDX/pages/2124677169/How+To+Add+an+MFE+to+a+Sandbox it looks like we want to update the guidance on that subject as well

2022-01-04 14:05 UTC, jnlapierre commented on playbooks/edx_continuous_integration.yml
> +      MFE_NAME: ora_grading
I have updated the configuration and added a note to the instructions.

2022-01-04 14:07 UTC, jnlapierre commented on playbooks/edx_continuous_integration.yml
> +    - role:mfe
Missing space has been added.

2022-01-04 14:10 UTC, jnlapierre commented on playbooks/ora_grading.yml
> +    ORA-GRADING_SANDBOX_BUILD: False
Oops, face palm, fixed.

2022-01-04 16:10 UTC, matthugs requested changes

2022-01-04 16:10 UTC, matthugs commented on playbooks/ora_grading.yml
> +      MFE_NAME: ora_grading
this is the same situation as https://github.com/openedx/configuration/pull/6641/files#diff-43ed106499a60cebe90128b847e99eed4d09b3720d3ba8231e6e534e3eea0833R60

2022-01-04 16:17 UTC, jnlapierre commented on playbooks/ora_grading.yml
> +      MFE_NAME: ora_grading
Updated, and this is making more sense to me now.  I suspect it will be easier next time for me.

2022-01-04 16:26 UTC, matthugs approved these changes

2022-01-04 17:55 UTC, merged