Add playbook to configure a dbt docs server
openedx-unsupported/configuration pull request #6693
Opened 2022-03-02 19:02 UTC by AbdouSeck

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A SRE team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a SRE ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/spaces/SRE/pages/28967861/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

2022-03-03 13:28 UTC, jazibhumayun commented on playbooks/roles/dbt_docs_nginx/tasks/main.yml
> +    job: /home/server-config/dbt-files-sync.sh
should we add tags on last two tasks as well ? As you have used tags on all the above tasks

2022-03-03 13:32 UTC, jazibhumayun commented on playbooks/roles/dbt_docs_nginx/tasks/main.yml
> +    hour: 23
This job  http://jenkins-new.analytics.edx.org/view/dbt/job/dbt-docs/ runs every 6 hours. I would recommend to update the cron to run every 6 hours. We can use `30 */6 * * *` so it will run “At 30 minute past every 6th hour.”

2022-03-03 13:33 UTC, jazibhumayun commented on playbooks/roles/aws_cloudwatch_agent/templates/amazon-cloudwatch-agent.json
> +		"namespace": "{{ cloudwatch_namespace }}",
great! thanks for making it dynamic namespace

2022-03-03 14:02 UTC, AbdouSeck commented on playbooks/roles/dbt_docs_nginx/tasks/main.yml
> +    hour: 23
The update has been made.

2022-03-03 14:02 UTC, AbdouSeck commented on playbooks/roles/dbt_docs_nginx/tasks/main.yml
> +    job: /home/server-config/dbt-files-sync.sh
The update has been made

2022-03-04 13:16 UTC, jazibhumayun commented on playbooks/roles/aws_cloudwatch_agent/templates/amazon-cloudwatch-agent.json
> +		"namespace": "{{ cloudwatch_namespace }}",
This should be via parameters file. Can you share pull request for https://github.com/edx-ops/analytics-secure ?

2022-03-04 13:16 UTC, jazibhumayun approved these changes

2022-03-04 13:57 UTC, estute commented on playbooks/roles/dbt_docs_nginx/tasks/main.yml
> +- name: Install and start nginx
We already have a role for nginx, which seems to be more complete. It would probably be a good idea to use that instead to get the benefit of the SRE team's experience? See: https://github.com/openedx/configuration/tree/master/playbooks/roles/nginx

2022-03-04 13:59 UTC, estute commented on playbooks/roles/dbt_docs_nginx/tasks/main.yml
> +- name: Copy the nginx configuration file from S3 to the local nginx config directory
What is the benefit of keeping these configs in s3 and separate from this role? Often times we include a template config file

2022-03-04 13:59 UTC, estute commented on playbooks/roles/dbt_docs_nginx/tasks/main.yml
> +- name: Copy dbt docs nginx server configurations from S3
Can you explain the difference between this config file and the one in the next step?

2022-03-04 14:04 UTC, estute commented on playbooks/roles/dbt_docs_nginx/tasks/main.yml
> +    path: /home/server-config/dbt-files-sync.sh
I see. This comes from the s3 bucket. We should either include this script in this role or put it into version control, depending on the nature of it.

2022-03-04 14:08 UTC, estute commented on playbooks/deploy_nginx_for_dbt_docs.yml
> +- name: Deploy dbt docs server
nit: I feel like the name of this file should be `dbt-docs` or something like that, as it represents the whole setup of the server, which can include more than nginx.

2022-03-04 14:08 UTC, estute commented on playbooks/deploy_nginx_for_dbt_docs.yml
> +  roles:
Do we want to include the `aws` role as well?

2022-03-04 14:09 UTC, estute requested changes
See inline comments

2022-03-04 15:22 UTC, AbdouSeck commented on playbooks/roles/dbt_docs_nginx/tasks/main.yml
> +- name: Install and start nginx
That role is doing a bunch more than was needed. I would consider using it once I have an idea how to provide some of the extra args it's templated.

2022-03-04 15:34 UTC, AbdouSeck commented on playbooks/roles/dbt_docs_nginx/tasks/main.yml
> +- name: Copy the nginx configuration file from S3 to the local nginx config directory
I do not know the answer to that. I was working with a shell script that @jazibhumayun had in terraform as `user_data`. In that script, html and config files were copied from S3. I would be open to having them here.

2022-03-04 15:35 UTC, AbdouSeck commented on playbooks/roles/dbt_docs_nginx/tasks/main.yml
> +- name: Copy the nginx configuration file from S3 to the local nginx config directory
@estute  Is that a path we want to take now?

2022-03-04 15:37 UTC, AbdouSeck commented on playbooks/deploy_nginx_for_dbt_docs.yml
> +  roles:
This is also related to what I mentioned about the `nginx` role. There is quite a bit going on there that we may not need here. Happy to look into incorporating tho.

2022-03-17 16:11 UTC, estute commented on playbooks/roles/dbt_docs_nginx/tasks/main.yml
> +- name: Copy the nginx configuration file from S3 to the local nginx config directory
In general, I think it is a good idea to place all of the configs in one place. We don't really have the ability to review and audit the history of an s3 bucket. However, if the configs in question are sensitive, then we store them separately

2022-03-17 16:15 UTC, estute commented on playbooks/deploy_nginx_for_dbt_docs.yml
> +  roles:
I think it would be a good idea to look into it. Part of the benefit of using the `aws` and `nginx` roles is that we can benefit from other teams working on updates, patches and fixes. @jazibhumayun what do you think?

2022-03-22 13:06 UTC, AbdouSeck commented on playbooks/deploy_nginx_for_dbt_docs.yml
> +  roles:
@estute the `aws` and `nginx` are being used now. One thing to note is the `aws` role installs an older version of the CLI tool. It works just fine, though.

2022-03-22 18:45 UTC, AbdouSeck commented on playbooks/roles/dbt_docs_nginx/tasks/main.yml
> +- name: Copy the nginx configuration file from S3 to the local nginx config directory
@estute the latest changes should take care of this.

2022-03-22 19:41 UTC, estute commented on playbooks/roles/dbt_docs_nginx/meta/main.yml
> +dependencies:
nit: In general, we treat the playbook as the top level representation of the system we want to build, and roles represent individual components. In this case, I think `aws`  and `aws_cloudwatch_agent` aren't dependencies of the dbt service we are hosting, so they should probably be moved to the playbook. See: https://github.com/openedx/configuration/blob/master/playbooks/ecomworker.yml

2022-03-22 19:41 UTC, estute commented on playbooks/roles/dbt_docs_nginx/tasks/main.yml
> +- name: Uninstall AWS CLI from the package manager
I'm confused by this. Why are we doing this?

2022-03-22 19:46 UTC, estute commented on playbooks/roles/dbt_docs_nginx/tasks/main.yml
> +- name: Make the dbt-files-sync.sh script executable
I'm not sure this file is present on the system. If it doesn't contain sensitive values, can we include it in this PR as a template or a file (see: https://github.com/openedx/configuration/tree/master/playbooks/roles/jenkins_common/files)

2022-03-22 19:47 UTC, estute commented on playbooks/roles/dbt_docs_nginx/tasks/main.yml
> +- name: Copy dbt-docs html files from S3 to the local machine
How is this different than the script that gets run on the cron job?

2022-03-22 19:48 UTC, estute requested changes
See inline questions

2022-03-22 20:00 UTC, AbdouSeck commented on playbooks/roles/dbt_docs_nginx/tasks/main.yml
> +- name: Copy dbt-docs html files from S3 to the local machine
This copies the files from S3 once. The cron piece is needed to make sure that the files get copied periodically. The cron script uses the same command.

2022-03-22 20:11 UTC, estute commented on playbooks/roles/dbt_docs_nginx/templates/nginx/nginx.conf.j2
> +user www-data;
It might make sense to use https://github.com/openedx/configuration/blob/master/playbooks/roles/nginx/templates/etc/nginx/nginx.conf.j2. You could take the values we use in this and pass it to that template. That way, we get the benefit of a config file that many engineers have had eyes on, but it might not suit this purpose. Just an idea.

2022-03-22 21:10 UTC, AbdouSeck commented on playbooks/roles/dbt_docs_nginx/tasks/main.yml
> +- name: Make the dbt-files-sync.sh script executable
@estute this has been updated with `template`.

2022-03-22 21:10 UTC, AbdouSeck commented on playbooks/roles/dbt_docs_nginx/meta/main.yml
> +dependencies:
Those roles are no longer listed as dependencies.

2022-03-22 21:11 UTC, AbdouSeck commented on playbooks/roles/dbt_docs_nginx/tasks/main.yml
> +- name: Uninstall AWS CLI from the package manager
The name has been updated to reflect the intent for this task.

2022-03-22 21:13 UTC, AbdouSeck commented on playbooks/roles/dbt_docs_nginx/templates/nginx/nginx.conf.j2
> +user www-data;
Our config file is a lot simpler and has a `server_name` attribute that the `nginx` role's config file does not have. I doubt that I should be updating that template file with that attribute.

2022-03-23 13:00 UTC, estute commented on playbooks/roles/dbt_docs_nginx/tasks/main.yml
> +- name: Copy dbt-docs html files from S3 to the local machine
Great, thanks

2022-03-24 20:14 UTC, estute approved these changes

2022-03-24 20:18 UTC, merged