feat: jenkins update Automation
openedx-unsupported/configuration pull request #6696
Opened 2022-03-04 19:00 UTC by oel8man

De[script](https://github.com/edx/edx-internal/pull/6222)ion
As an owner of Jenkins I know that we are able to use an automated script to update it so that we can ensure it is on a recent version.

AC:

ENSURE the  jenkins-upgrade.sh upgrade script PR passes linters and is merged

ENSURE there is a recent snapshot of Jenkins or an AMI backup

[Amazon EC2 backup and recovery with snapshots and AMIs - AWS Prescriptive Guidance](https://docs.aws.amazon.com/prescriptive-guidance/latest/backup-recovery/ec2-backup.html) 

ENSURE the Ansible playbook is run to upgrade Jenkins from jenkins_2.303.3 to jenkins_2.319.3

ENSURE Jenkins is running openJDK-11

ENSURE that the production version of Jenkins matches what is on the master branch

ENSURE docs are up to date to reflect Abdoul’s change: [Jenkins (build.testeng.edx.org)](https://openedx.atlassian.net/wiki/spaces/SRE/pages/1062895636/Jenkins+build.testeng.edx.org) 

Implementation Details:

Get the script via edx-internal/script and run it locally

Please ask any questions you have and update the document.

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A SRE team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a SRE ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/spaces/SRE/pages/28967861/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

2022-03-04 20:47 UTC, adzuci requested changes
Hey Abdoul, I think you copied the edX Jira ticket to the description, but I don't think that's appropriate for a public repo like this.  Could you look at some other PRs for examples and add a concise blurb about what this PR is changing + a link to the docs that explain the is successful syntax?

Also, I think we use the |success syntax a bunch elsewhere, is that something that doesn't work for Ansible 2.8?  Or do you know if we'll need to update other roles?

2022-03-04 20:50 UTC, ohnickmoy approved these changes

2022-03-04 20:50 UTC, ohnickmoy commented on playbooks/roles/aws/tasks/main.yml
> +  until: install_pkgs is succeeded
did flags like these change syntax because of upgrade?

2022-03-04 20:50 UTC, ohnickmoy commented on playbooks/roles/python/tasks/main.yml
> +#- name: Install packages
what was the purpose of commenting this out?

2022-03-04 20:51 UTC, oel8man commented on playbooks/roles/aws/tasks/main.yml
> +  until: install_pkgs is succeeded
yes

2022-03-04 20:58 UTC, oel8man commented on playbooks/roles/python/tasks/main.yml
> +#- name: Install packages
It was failing the python minimal install. I reverted back

2022-03-04 22:54 UTC, adzuci commented on playbooks/roles/aws/tasks/main.yml
> +  until: install_pkgs is succeeded
What got upgraded from what to what to cause this?

2022-03-07 23:33 UTC, adzuci requested changes
@oel8man Could you add a bulleted list of the changes that this PR is making and what roles you touched in your description rather "As an owner of Jenkins I know that we are able to use an automated script to update it so that we can ensure it is on a recent version."

2022-03-07 23:33 UTC, adzuci commented on playbooks/roles/neo4j/meta/main.yml
> +    ORACLEJDK_VERSION: "11.0.13"
@oel8man Does Jenkins install this role?  I think this is used in coursegraph, so we shouldn't changes it without asking TNL for a review, cc @kenclary

2023-12-16 01:53 UTC, closed without merging