feat: add playbooks for enterprise-access and enterprise-subsidy
openedx-unsupported/configuration pull request #7107
Opened 2024-02-15 12:14 UTC by tecoholic

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] Have a Site Reliability Engineer review the PR if you don't own all of the services impacted.
  - [ ] If you are adding any new default values that need to be overridden when this change goes live, update internal repos and add an entry to the top of the CHANGELOG.
  - [ ] Performed the appropriate testing.
  - [ ] Think about how this change will affect Open edX operators and update the wiki page for the next Open edX release if needed

### Description

This PR adds new playbooks and roles for deploying [enterprise-access](https://github.com/openedx/enterprise-access) and [enterprise-subsidy](https://github.com/openedx/enterprise-subsidy) natively. The roles were created using the `enterprise-catalog` role as a reference.

### Testing

The roles were tested following the [Vagrant based testing](https://github.com/openedx/configuration/tree/master/vagrant) instructions using [VirtualBox](https://www.virtualbox.org) as the backend on a Linux machine.

1. Set the role - `export VAGRANT_ANSIBLE_ROLE=enterprise_access` or `export VAGRANT_ANSIBLE_ROLE=enterprise_subsidy`
2. Put the following in a yml file
    ```yaml
    COMMON_CONFIG_NO_LOGGING: false
    GIT_CLONE_NO_LOGGING: false
    COMMON_GIT_PATH: open-craft
    ENTERPRISE_ACCESS_VERSION: 'tecoholic/BB-8440-deployment-fixes'
    ENTERPRISE_SUBSIDY_VERSION: 'tecoholic/BB-8440-deployment-fixes'
    ENTERPRISE_SUBSIDY_MEMCACHE_BACKEND: 'django.core.cache.backends.locmem.LocMemCache'
    ENTERPRISE_SUBSIDY_MEMCACHE: 'enterprise_subsidy'
    ```
3. Set the vars envvar `export VAGRANT_ANSIBLE_VARS_FILE=/path/to/file-with-above-content`
4. Run `vagrant up` and verify that the role completes successfully.

#### Verifying services are running correctly

* For Enterprise Access, running `vagrant ssh -- -NL 8270:localhost:8270` allows us to verify that the service is up. Visit http://localhost:8270/admin/ to get the login form. The static files won't load as they depend on the Nginx from the playbook.
* For Enterprise Subsidy, with running `vagrant ssh -- -NL 8280:localhost:8280` the admin page refuses to render because it tries to load a Waffle Flag from the database which isn't deployed by this role.

2024-02-15 12:14 UTC, openedx-webhooks commented
Thanks for the pull request, @tecoholic! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2024-02-19 16:16 UTC, Agrendalath requested changes
@tecoholic, some of the comments apply to both roles. I didn't duplicate them for readability, though.

Also, we should update the `CHANGELOG.md` file.

2024-02-19 16:16 UTC, Agrendalath commented on playbooks/enterprise_access.yml
> +      when: COMMON_ENABLE_INSIGHTVM_AGENT
Nit: why do we want this here and in the `playbooks/enterprise_subsidy.yml` playbook? Shouldn't it be installed explicitly with the `insightvm_agent` playbook?

2024-02-19 16:16 UTC, Agrendalath commented on playbooks/enterprise_subsidy.yml
> +      when: ENTERPRISE_SUBSIDY_MEMCACHE_ENABLED
This seems to be undefined. Besides, do we need to deploy Memcached here?

2024-02-19 16:16 UTC, Agrendalath commented on playbooks/roles/enterprise_access/defaults/main.yml
> +# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
```suggestion
# code style: https://openedx.atlassian.net/wiki/spaces/OpenOPS/pages/26837527/Ansible+Code+Conventions
```

2024-02-19 16:16 UTC, Agrendalath commented on playbooks/roles/enterprise_access/defaults/main.yml
> +  ENTERPRISE_ACCESS_CFG: '{{ COMMON_CFG_DIR }}/{{ enterprise_access_service_name }}.yml'
This must be overridden to specify more env variables. Why don't we add `ENTERPRISE_ACCESS_ENVIRONMENT_EXTRA: {}` and pass it like `edx_django_service_environment_extra: '{{ enterprise_access_environment | combine(ENTERPRISE_ACCESS_ENVIRONMENT_EXTRA) }}'`

2024-02-19 16:16 UTC, Agrendalath commented on playbooks/roles/enterprise_access/defaults/main.yml
> +# TODO: Let edx_django_service manage ENTERPRISE_ACCESS_STATIC_ROOT in phase 2.
Nit: I know it was copied from the `license_manager`, but I have no idea what "phase 2" is. Instead of adding more TODOs, maybe we could extend the comment in the `license_manager` to indicate that this also applies to two other roles?

2024-02-19 16:16 UTC, Agrendalath commented on playbooks/roles/enterprise_access/defaults/main.yml
> +  ENTERPRISE_ACCESS_SERVICE_USER: '{{ ENTERPRISE_ACCESS_SERVICE_USER }}'
Nit: I don't see the usage of these variables in any of the three repos (`enterprise-access`,  `enterprise-subsidy`,  `license-manager`).

2024-02-19 16:16 UTC, Agrendalath commented on playbooks/roles/enterprise_subsidy/meta/main.yml
> +    edx_django_service_enable_celery_workers: true
`enterprise-subsidy` does not seem to be using Celery:
```bash
enterprise-subsidy on  main via 🐍 v3.11.7 ➜ ag "celery"
docs/decisions/0003-fulfillment-and-corrective-policies.rst
52:as an asynchronous celery task that retries indefinitely (or up to some fairly high maximum).  The fulfillment action

pylintrc
72:load-plugins = edx_lint.pylint,pylint_django,pylint_celery

requirements/dev.txt
16:    #   pylint-celery
435:    #   pylint-celery
438:pylint-celery==0.3
449:    #   pylint-celery

requirements/doc.txt
20:    #   pylint-celery
413:    #   pylint-celery
416:pylint-celery==0.3
427:    #   pylint-celery

requirements/quality.txt
16:    #   pylint-celery
387:    #   pylint-celery
390:pylint-celery==0.3
401:    #   pylint-celery

requirements/test.txt
15:    #   pylint-celery
317:    #   pylint-celery
320:pylint-celery==0.3
326:    #   pylint-celery

requirements/validation.txt
18:    #   pylint-celery
493:    #   pylint-celery
496:pylint-celery==0.3
510:    #   pylint-celery
enterprise-subsidy on  main via 🐍 v3.11.7 ➜ fd tasks
enterprise-subsidy on  main via 🐍 v3.11.7 ➜ 
```

2024-02-19 16:16 UTC, Agrendalath commented on playbooks/roles/enterprise_access/defaults/main.yml
> +enterprise_access_workers: "{{ ENTERPRISE_ACCESS_CELERY_WORKERS }}"
Nit: why don't we pass `ENTERPRISE_ACCESS_CELERY_WORKERS` directly to `edx_django_service_workers`?

2024-02-19 16:16 UTC, Agrendalath commented on playbooks/roles/enterprise_access/defaults/main.yml
> +ENTERPRISE_ACCESS_DISCOVERY_API_URL:  !!null
Shouldn't these variables be used somewhere?

2024-02-19 16:16 UTC, Agrendalath commented on playbooks/roles/enterprise_access/defaults/main.yml
> +ENTERPRISE_ACCESS_SOCIAL_AUTH_REDIRECT_IS_HTTPS: false
This one also seems to be unused.

2024-02-19 16:16 UTC, Agrendalath commented on vagrant/base/test_role/Vagrantfile
> +  config.vm.network :private_network, ip: "192.168.56.20"
Are these changes expected?

2024-02-19 16:23 UTC, tecoholic commented on playbooks/enterprise_access.yml
> +      when: COMMON_ENABLE_INSIGHTVM_AGENT
@Agrendalath Since I created the playbooks and the roles using the `enterprise-catalog` playbook and role as a reference, these were carried over. These can be removed.

2024-02-19 16:30 UTC, tecoholic commented on playbooks/enterprise_subsidy.yml
> +      when: ENTERPRISE_SUBSIDY_MEMCACHE_ENABLED
The [docker-compose.yml](https://github.com/openedx/enterprise-subsidy/blob/main/docker-compose.yml) file of enterprise-subsidy does run memcache as a service. So, I added this flag to make it available as an option. 

You are right, I missed properly mapping the CACHE config to this flag.

2024-02-19 16:34 UTC, tecoholic commented on vagrant/base/test_role/Vagrantfile
> +  config.vm.network :private_network, ip: "192.168.56.20"
@Agrendalath These were added for testing. Probably needed if you are running the Vagrant tests locally as VirtualBox only supports the `192.168.56.0/21` address space by default and Vagrant no longer seems to be using the files.vagrantup.com domain to serve the VM boxes.

2024-02-19 18:37 UTC, tecoholic commented on playbooks/enterprise_access.yml
> +      when: COMMON_ENABLE_INSIGHTVM_AGENT
Removed these.

2024-02-19 18:40 UTC, tecoholic commented on playbooks/enterprise_subsidy.yml
> +      when: ENTERPRISE_SUBSIDY_MEMCACHE_ENABLED
Since both the services use memcache in their setup, I have added it to both the playbooks and used the default `localhost:11211` in the config. Also included a comment that if the flag is turned off, then the other related settings need to be changed as well.

So, this should allow for disabling memcache installation and setting the config to a totally different backend, or pointing to a remote memcahce.

It makes sense to me, but I am not sure if this is the best way to do it. Kindly change it, if I am doing something wrong here.

2024-02-19 18:41 UTC, tecoholic commented on playbooks/roles/enterprise_access/defaults/main.yml
> +  ENTERPRISE_ACCESS_CFG: '{{ COMMON_CFG_DIR }}/{{ enterprise_access_service_name }}.yml'
Done.

2024-02-19 18:41 UTC, tecoholic commented on playbooks/roles/enterprise_access/defaults/main.yml
> +# TODO: Let edx_django_service manage ENTERPRISE_ACCESS_STATIC_ROOT in phase 2.
I copied it from the `enterprise_catalog`. So I have added reference to these 2 services in the enterprise_catalog's comment and removed them here.

2024-02-19 18:42 UTC, tecoholic commented on playbooks/roles/enterprise_access/defaults/main.yml
> +  ENTERPRISE_ACCESS_SERVICE_USER: '{{ ENTERPRISE_ACCESS_SERVICE_USER }}'
Removed.

2024-02-19 18:43 UTC, tecoholic commented on playbooks/roles/enterprise_subsidy/meta/main.yml
> +    edx_django_service_enable_celery_workers: true
Great catch. Removed all celery/worker related config and set the relevant flag `edx_django_service_enable_celery_workers` to `false`.

2024-02-19 18:45 UTC, tecoholic commented on playbooks/roles/enterprise_access/defaults/main.yml
> +enterprise_access_workers: "{{ ENTERPRISE_ACCESS_CELERY_WORKERS }}"
Done. Removed the redundant variable.

2024-02-19 18:45 UTC, tecoholic commented on playbooks/roles/enterprise_access/defaults/main.yml
> +ENTERPRISE_ACCESS_DISCOVERY_API_URL:  !!null
Removed these.

2024-02-19 18:45 UTC, tecoholic commented on playbooks/roles/enterprise_access/defaults/main.yml
> +ENTERPRISE_ACCESS_SOCIAL_AUTH_REDIRECT_IS_HTTPS: false
Removed.

2024-02-19 18:47 UTC, tecoholic commented on vagrant/base/test_role/Vagrantfile
> +  config.vm.network :private_network, ip: "192.168.56.20"
These changes are in a separate commit 5cfa2903c9f3ae17a8b6cf9b6ad5c8fd3ab31d44. If these are not required for testing, we can just rebase and drop that one commit. I needed them for testing, so I am leaving it for now, in case someone else faces issues with the testing instructions, running Vagrant.

2024-04-15 20:54 UTC, Agrendalath approved these changes
@tecoholic, a quick reminder about updating the changelog.

:+1:

* [x] I tested this: we have already used these playbooks on Stage
* [x] I read through the code
* [x] I checked for accessibility issues: n/a
* [ ] Includes documentation: ⚠️ 
* [x] I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository: n/a

2024-04-15 20:54 UTC, Agrendalath commented on playbooks/roles/enterprise_access/defaults/main.yml
> +# The memcache config of edx_django_service is overriden in defaults/main.yml to use PyMemcacheCache
```suggestion
# The memcache config of edx_django_service is overridden in defaults/main.yml to use PyMemcacheCache
```

2024-05-06 17:49 UTC, closed without merging